### ISSUE TITLE
rowserrcheck: panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by powerman** [golangci/golangci-lint#1005]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.24.0 built from 6fd4383 on 2020-03-15T11:25:03Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters:
  enable-all: true
linters-settings:
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
      - github.com/powerman/sqlxx
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.14.1 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build919401820=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint run -v
level=info msg="[config_reader] Config search paths: [./ /home/powerman/tmp/rowserrcheck-bug /home/powerman/tmp /home/powerman /home /]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 41 linters: [bodyclose deadcode depguard dogsled dupl errcheck funlen gochecknoglobals gochecknoinits gocognit goconst gocritic gocyclo godox gofmt goimports golint gomnd goprintffuncname gosec gosimple govet ineffassign interfacer lll maligned misspell nakedret prealloc rowserrcheck scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck whitespace wsl]"
level=info msg="[lintersdb] Active 41 linters: [bodyclose deadcode depguard dogsled dupl errcheck funlen gochecknoglobals gochecknoinits gocognit goconst gocritic gocyclo godox gofmt goimports golint gomnd goprintffuncname gosec gosimple govet ineffassign interfacer lll maligned misspell nakedret prealloc rowserrcheck scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck whitespace wsl]"
level=info msg="[loader] Go packages loading at mode 575 (deps|compiled_files|exports_file|files|imports|name|types_sizes) took 58.062109ms"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 78.633µs"
level=info msg="[runner/goanalysis_metalinter/goanalysis] analyzers took 15.418848ms with top 10 stages: dupl: 1.283183ms, buildssa: 1.042268ms, buildir: 897.041µs, interfacer: 486.111µs, gocritic: 350.864µs, unconvert: 349.42µs, SA5001: 333.612µs, SA3001: 325.567µs, unmarshal: 299.858µs, buildtag: 296.492µs"
level=warning msg="[linters context] Panic: rowserrcheck: package \"bug\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 591 [running]:\nruntime/debug.Stack(0x13488c2, 0x3c, 0xc00007d9b0)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc0017df390)\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:528 +0x1b5\npanic(0x1189b60, 0x1aedf10)\n\t/usr/lib/go/src/runtime/panic.go:967 +0x166\ngolang.org/x/tools/go/ssa.(*Type).Object(...)\n\t/home/powerman/go/pkg/mod/golang.org/x/tools@v0.0.0-20200204192400-7124308813f3/go/ssa/ssa.go:1467\ngithub.com/jingyugao/rowserrcheck/passes/rowserr.runner.run(0xc001c36960, 0x0, 0x0, 0x0, 0x0, 0xc000254740, 0x3, 0x4, 0xc001c36960, 0xc00015f9e0, ...)\n\t/home/powerman/go/pkg/mod/github.com/jingyugao/rowserrcheck@v0.0.0-20191204022205-72ab7603b68a/passes/rowserr/rowserr.go:65 +0x126\ngithub.com/jingyugao/rowserrcheck/passes/rowserr.NewRun.func1(0xc001c36960, 0xc1125d9, 0x1c8ffe0, 0xc0009a8850, 0x2)\n\t/home/powerman/go/pkg/mod/github.com/jingyugao/rowserrcheck@v0.0.0-20191204022205-72ab7603b68a/passes/rowserr/rowserr.go:46 +0x160\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc0017df390)\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:610 +0xa25\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:532 +0x2a\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0016e5540, 0x12faddd, 0xc, 0xc0017f2770)\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x50\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc0017df390)\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:531 +0x91\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func3(0xc0028bacd0, 0xc0017df390)\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:1076 +0x61\ncreated by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze\n\t/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:1071 +0x309\n"
level=info msg="[runner/unused/goanalysis] analyzers took 0s with no stages"
level=info msg="[runner] processing took 2.676µs with stages: max_same_issues: 739ns, diff: 356ns, skip_dirs: 257ns, nolint: 210ns, max_from_linter: 187ns, cgo: 123ns, filename_unadjuster: 89ns, identifier_marker: 87ns, path_prettifier: 87ns, source_code: 86ns, max_per_file_from_linter: 84ns, skip_files: 81ns, exclude: 77ns, uniq_by_line: 55ns, path_shortener: 54ns, exclude-rules: 52ns, autogenerated_exclude: 52ns"
level=info msg="[runner] linters took 79.726185ms with stages: goanalysis_metalinter: 79.511217ms, unused: 174.52µs"
level=info msg="File cache stats: 1 entries of total size 131B"
level=info msg="Memory: 3 samples, avg is 70.8MB, max is 71.1MB"
level=info msg="Execution took 142.893346ms"
```

</details>

This is the code which triggers the panic:
```go
package bug

import (
	"github.com/jmoiron/sqlx"
	"github.com/powerman/sqlxx"
)

func Setup() {
	sqlx.NameMapper = sqlxx.ToSnake
}
```

Panic is:

```
WARN [linters context] Panic: rowserrcheck: package "bug" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 759 [running]:
runtime/debug.Stack(0x13488c2, 0x3c, 0xc0025899b0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc00140f660)
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:528 +0x1b5
panic(0x1189b60, 0x1aedf10)
	/usr/lib/go/src/runtime/panic.go:967 +0x166
golang.org/x/tools/go/ssa.(*Type).Object(...)
	/home/powerman/go/pkg/mod/golang.org/x/tools@v0.0.0-20200204192400-7124308813f3/go/ssa/ssa.go:1467
github.com/jingyugao/rowserrcheck/passes/rowserr.runner.run(0xc0025915e0, 0x0, 0x0, 0x0, 0x0, 0xc00015fdc0, 0x3, 0x4, 0xc0025915e0, 0xc00068a240, ...)
	/home/powerman/go/pkg/mod/github.com/jingyugao/rowserrcheck@v0.0.0-20191204022205-72ab7603b68a/passes/rowserr/rowserr.go:65 +0x126
github.com/jingyugao/rowserrcheck/passes/rowserr.NewRun.func1(0xc0025915e0, 0xbbe3885, 0x1c8ffe0, 0xc000e56e70, 0x2)
	/home/powerman/go/pkg/mod/github.com/jingyugao/rowserrcheck@v0.0.0-20191204022205-72ab7603b68a/passes/rowserr/rowserr.go:46 +0x160
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc00140f660)
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:610 +0xa25
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:532 +0x2a
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0013d34f0, 0x12faddd, 0xc, 0xc0024aef70)
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x50
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc00140f660)
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:531 +0x91
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func3(0xc002ab77e0, 0xc00140f660)
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:1076 +0x61
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/home/powerman/go/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner.go:1071 +0x309 
```

Removing line `- github.com/powerman/sqlxx` from `.golangci.yml` fixes the issue, but to me it looks like this line is valid.

**Comment by ksoichiro** [comment]
It seems that each package in `linters-settings.rowserrcheck.packages` must define a type named `Rows` to suppress this panic.
https://github.com/jingyugao/rowserrcheck/blob/72ab7603b68a2a295b8833da708c757d2c92a803/passes/rowserr/rowserr.go#L65-L65
I think it's better to modify codes in rowserrcheck.

**Comment by bloxer-saurabh** [comment]
**any specific reason why this warning is coming.** I'm also getting this warning 
`level=warning msg="[linters context] 
Panic: gosec: package \"hostrunner\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 10180 
[running]:\nruntime/debug.Stack(0xfec6d6, 0x3c, 0xc00d58c0d0)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/runtime/debug/stack.go:24 
+0x9d\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc002681cf0)                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:508 +0x1b5\npanic(0xe25fc0, 0x1847d10)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/runtime/panic.go:969 +0x166\ngithub.com/securego/gosec/v2/rules.(*implicitAliasing).Match(0xc004731080, 0x11561a0, 0xc00d1c0e60, 0xc002afaa10, 0x198a0a0, 0x0, 0xa)                                    
/home/runner/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/rules/implicit_aliasing.go:36 +0x271\ngithub.com/securego/gosec/v2.(*Analyzer).Visit(0xc004730e40, 0x11561a0, 0xc00d1c0e60, 0xf308ca7a871fcd90, 0xf300000000dd9a60)                                    
/home/runner/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/analyzer.go:353 +0x472\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11561a0, 0xc00d1c0e60)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:52 +0x66\ngo/ast.walkStmtList(0x114c220, 0xc004730e40, 0xc00f2f4680, 0x1, 0x1)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:32 +0x9e\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11557a0, 0xc00caf90b0)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:224 +0x1adf\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11561a0, 0xc00d1c1450)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:285 +0x2946\ngo/ast.walkStmtList(0x114c220, 0xc004730e40, 0xc00f2f4690, 0x1, 0x1)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:32 +0x9e\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11557a0, 0xc00caf90e0)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:224 +0x1adf\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x1155ee0, 0xc006d06b80)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:231 +0x1c7c\ngo/ast.walkStmtList(0x114c220, 0xc004730e40, 0xc00de7b600, 0x6, 0x8)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:32 +0x9e\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11557a0, 0xc00caf9110)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:224 +0x1adf\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x1155ee0, 0xc006d06c00)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:233 +0x1cef\ngo/ast.walkStmtList(0x114c220, 0xc004730e40, 0xc00064d000, 0x34, 0x40)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:32 +0x9e\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x11557a0, 0xc00caf9fb0)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:224 +0x1adf\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x1155d20, 0xc00cdca000)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:344 +0xd98\ngo/ast.walkDeclList(0x114c220, 0xc004730e40, 0xc005860e00, 0x1d, 0x20)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:38 +0x9e\ngo/ast.Walk(0x114c220, 0xc004730e40, 0x1155ca0, 0xc00de7bd80)                                    
/opt/hostedtoolcache/go/1.14.2/x64/src/go/ast/walk.go:353 +0x264e\ngithub.com/securego/gosec/v2.(*Analyzer).Check(0xc004730e40, 0xc00d58dc70)                                    
/home/runner/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/analyzer.go:219 +0x435\ngithub.com/golangci/golangci-lint/pkg/golinters.NewGosec.func1.1(0xc00677f2c0, 0x9b3123c7a, 0x19538a0, 0xc00d697958, 0x2)                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/gosec.go:50 +0x16b\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc002681cf0)\t/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:590 +0xa25\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:512 +0x2a\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc001595680, 0xf3c69a, 0x5, 0xc00174df70)                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x50\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc002681cf0)                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:511 +0x91\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc0081db9d0, 0xc002681cf0)
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:1058 +0x61\ncreated by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze                                    
/home/runner/work/golangci-lint/golangci-lint/pkg/golinters/goanalysis/runner.go:1053 +0x306"`
