### ISSUE TITLE
Freeze default linters list

### ISSUE THREAD

**Issue by casualjim** [golangci/golangci-lint#1007]
It would appear that the list of default linters changes. I think new things are and they get included in the default set of linters. 

This causes churn downstream of your project. All of a sudden one-off contributors are met with issues that are not of their creation. They are editing files that linted properly before and now they are responsible for dealing with a tools issue that just comes out of nowhere. 

So I wonder would it make sense to kind of freeze the default list, unless they are critical. I don't think a stylecheck or whitespace linter qualifies as a critical lint as it won't avoid security issues or panics. It just makes it so that for some arbitrary, subjective standard the code is more "readable".

**Comment by sagikazarmark** [comment]
IMHO these issues can be addressed by proper configuration and usage:

- do not use the latest version of the linter, pin to minor versions
- do not enable all linters by default, only the ones you want to run
- when running the linter locally use the `--new` option by default to only lint unstaged changes
- when running the linter on PRs make sure to use `--new-from-rev` to only raise issues for the changes

Personally I find it a good practice to add new linters to the default list (though I configure golangci to enable all linters by default). When upgrading, you can decide whether you want to enable the new rules or not.

**Comment by ernado** [comment]
Fully agree!

By the way, current best practice is to use `disable-all` and enable linters as needed.
I will pay attention to default linter list during review anway.

Also, PR with explicit test is very welcome.
