### ISSUE TITLE
"too many open files" in macOS High Sierra

### ISSUE THREAD

**Issue by aaronbee** [golangci/golangci-lint#102]
When running `golangci-lint run` on a repository with nearly 4000 .go files on macOS High Sierra, a "too man open files" error is encountered:

```
WARN[0015] running error: can't print 49 issues: can't read file path/to/file.go for printing issued line: open path/to/file.go: too many open files
```

macOS High Sierra defaults to an open file limit of 256, and can be increased for a shell session with `ulimit -n`. 

Perhaps this issue can be documented in README.md. Or `golangcli-lint` can increase its open file limit with [Setrlimit](https://godoc.org/golang.org/x/sys/unix#Setrlimit).

**Comment by jirfag** [comment]
hi, thank you for the issue!
It's a file descriptor leak in errcheck: normal behavior is to get only 1 opened file at a time. I will fix it
