### ISSUE TITLE
Disable stale bot

### ISSUE THREAD

**Issue by rittneje** [golangci/golangci-lint#1024]
Please disable the stale bot. Issues don't stop being issues just because they aren't being actively addressed.

**Comment by ernado** [comment]
Hi, I've eased rules for stale issues, should slightly reduce annoyance.

Currently I'm out of capacity to fully maintain project, and there are no active maintainers, so it is hard to address issues, sorry.

Feel free to add any lables from this list:
```
  - pinned
  - security
  - bug
  - blocked
  - protected
  - triaged
```
Stale bot will ignore such issues.
