### ISSUE TITLE
Add faillint as a linter

### ISSUE THREAD

**Issue by mcristina422** [golangci/golangci-lint#1025]
Add https://github.com/fatih/faillint/ as a linter.

>Faillint is a simple Go linter that fails when a specific set of import paths or exported path's functions, constant, vars or types are used. It's meant to be used in CI/CD environments to catch rules you want to enforce in your projects.

**Comment by jirfag** [comment]
Hi,
we already have `modguard` and `depguard` for blacki/white listing imports. Maybe some of our linters also support func/const/var checking?

**Comment by AugustasV** [comment]
I would like to give it a try!

**Comment by sagar23sj** [comment]
I am first time contributor to golangci-lint and would like to contribute to this issue.
Can anyone help me understand what exactly is needed from this issue?
If someone help me understand, I will start working on it right away.
Thanks

**Comment by Antonboom** [comment]
Covered by:

1. depguard
2. gomodguard
3. forbidigo

@ldez, I think we can close this issue.

**Comment by ldez** [comment]
I agree.
