### ISSUE TITLE
Go Wrapped Error linter

### ISSUE THREAD

**Issue by bclermont** [golangci/golangci-lint#1030]
https://github.com/polyfloyd/go-errorlint

I use it standalone and is quite useful

**Comment by polyfloyd** [comment]
The linters have now been moved to `github.com/polyfloyd/go-errorlint/errorlint` which should make integration possible.

**Comment by FireFart** [comment]
I  vote that the new `go-err113` linter is replaced by this one. `go-err113` reports all calls of `fmt.Errorf('xxx' %s', value)` which is incorrect.

**Comment by jirfag** [comment]
hi,
this linter doesn't use `go/analysis`. We would like to include only `go/analysis`-based linters.
