### ISSUE TITLE
dev: configure renovate or similar bot

### ISSUE THREAD

**Issue by ernado** [golangci/golangci-lint#1033]
We should automate dependency updates.

**Comment by ryancurrah** [comment]
https://dependabot.com/ is now owned by github

**Comment by ernado** [comment]
Yes, or dependabot :)

BTW, if someone knows about a way to auto-update forks to upstream (we have a lot of linter forks), please leave a comment.

**Comment by jirfag** [comment]
We've started using `dependabot`, it's config is [here](https://github.com/golangci/golangci-lint/blob/master/.dependabot/config.yml).
