### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by turkk33** [golangci/golangci-lint#1037]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Can't install package:

```
-> % go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
# github.com/golangci/golangci-lint/pkg/golinters
../../github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
../../github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
```

**Comment by ernado** [comment]
Please try using go modules:
```console
$ GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0
```

**Comment by evzpav** [comment]
Updated to version 1.25.1. For a project it did worked. However for another project I got this error:

 `9 [lint 1/1] RUN golangci-lint run -v -c ./.golangci.yml
#9 0.840 level=info msg="[config_reader] Used config file .golangci.yml"
#9 0.857 level=info msg="[lintersdb] Active 17 linters: [deadcode errcheck goconst gocyclo golint gosec gosimple govet ineffassign interfacer maligned staticcheck structcheck typecheck unconvert unused varcheck]"
#9 0.857 level=info msg="[lintersdb] Active 17 linters: [deadcode errcheck goconst gocyclo golint gosec gosimple govet ineffassign interfacer maligned staticcheck structcheck typecheck unconvert unused varcheck]"
#9 1.362 level=info msg="[loader] Go packages loading at mode 575 (files|compiled_files|deps|name|types_sizes|exports_file|imports) took 504.748582ms"
#9 1.362 level=error msg="Running error: context loading failed: no go files to analyze"
#9 1.362 level=info msg="Memory: 7 samples, avg is 68.7MB, max is 68.7MB"
#9 1.362 level=info msg="Execution took 515.203041ms"
#9 ERROR: executor failed running [/bin/sh -c golangci-lint run -v -c ./.golangci.yml]: exit code: 5`

Could you please advise? I tried commenting linters but did not solve it.

**Comment by ernado** [comment]
Please provide a way to reproduce this issue @evzpav

**Comment by detailyang** [comment]
It works via `GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint`. 

BTW: do not use -u flag to upgrade dep because of https://github.com/tetafro/godot v0.4.2 break changes from v0.3.7
