### ISSUE TITLE
Feature Request: add a "go build" linter mode

### ISSUE THREAD

**Issue by theckman** [golangci/golangci-lint#1043]
Hi there,

I'm running in to a limitation in my editor that I wonder if the `golangci-lint` project would be willing to help with, while acknowledging it may be beyond your scope.

The summary is in my editor right now, I can either get compilation failures or errors from `golangci-lint` not both. Would it be possible to have `golangci-lint` report compilation failures in the same format as it does for other linters, so that my editor can show them?

Thank you for your consideration on this idea!

Cheers!
-Tim

**Comment by ernado** [comment]
Sounds reasonable.

PR's are welcome as always :)

**Comment by pierrre** [comment]
IMO if there is a compilation failure, we should not attempt to "lint" the code, because it's not valid.

**Comment by ernado** [comment]
That's correct, but currently error is pretty cryptic and we can be more user friendly.

**Comment by ryancurrah** [comment]
I've been looking at this to try and raise compile errors as lint errors. I am having some trouble figuring out how to handle this.

So I know `scanner.ErrorList` here https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/goanalysis/runner.go#L1330-L1338 contains the build errors but I am not sure how to convert these errors to a lint issue.

@jirfag or @ernado do you have some guidance for me?
