### ISSUE TITLE
gofmt: got too much paths

### ISSUE THREAD

**Issue by y0ssar1an** [golangci/golangci-lint#105]
```sh
$ golangci-lint run                                                                                                                          0
WARN[0000] Gofmt: got too much paths (5877), analyze first 1000
```
There are only 344 `.go` files in my repo (outside of `vendor/`). So why is `gofmt` receiving so many paths?

**Comment by jirfag** [comment]
hi!
it's fixed in [v1.6](https://github.com/golangci/golangci-lint/releases/tag/v1.6) release in commit [2b587b63d6ae9c86f68fbcf27471a335469adfc5](https://github.com/golangci/golangci-lint/commit/2b587b63d6ae9c86f68fbcf27471a335469adfc5),
check, please

**Comment by y0ssar1an** [comment]
I'm using the latest `master` commit (7f1779d7066dd506ae84bf27a3edf5cec764a6c4).

**Comment by jirfag** [comment]
Are you sure that you are using binary installed from this commit but not another global binary?
We have no such logging in code anymore, it was deleted
