### ISSUE TITLE
Update gosec linter

### ISSUE THREAD

**Issue by nikjain0594** [golangci/golangci-lint#1052]
Hi There,

Gosec has released v2 version and there  are many updates in code, can we please update golangci-lint code to support v2 version of gosec.

Thanks in advance.

Regards,
Nikhil

**Comment by ernado** [comment]
Thank you for report.

Seems like there were breaking changes in API, so it is not a trivial update and PR is welcome.

**Comment by theckman** [comment]
@ernado doesn't seem like they broke any of the APIs we use, but their repo is in a bit of a broken state (https://github.com/securego/gosec/issues/470). I raised #1062 to get `gosec` updated, but because of that issue I linked it's not able to use a tagged release.
