### ISSUE TITLE
Prevent run multiply copies golangci-lint with same params

### ISSUE THREAD

**Issue by rekby** [golangci/golangci-lint#108]
When I edit files Goland can save many files same time (Ctrl+S after rename refactor or after manual changes few files).

If I add golangci-lint [as filewatcher with project dir param](https://github.com/golangci/golangci-lint#editor-integration) - golangci-lint start many times - once for every saved file.

I think it will good for use some lock for prevent do work multiply times. For example - create lock-file/lock-dir flag with hash of current args and env.

If lock file existed - exit with code 0.

Check lock flag for old file (for example - ignore it after a hour) - for prevent forever lock in some mistakes.

**Comment by alecthomas** [comment]
IMO this seems like an issue that is not particular to golangci-lint and should be solved in the general case by Goland.

**Comment by rekby** [comment]
IDE can't know purpose of calls - it only exec command while change file.
May be I want count changes per directory.

I see 3 variants of decision:
1. Some lock schema in linter. May be not use hash, etc. But simple param --lock and use the lock file if parameter exists only.
2. Way to run linter for file, not whole folder - for run from watcher personally for file and doesn't analyse whole dir.
3. Additinal settings in IDE for run only one watcher same time.

**Comment by jirfag** [comment]
Fixed in https://github.com/golangci/golangci-lint/pull/812/files
