### ISSUE TITLE
Zsh (5.8) completions Broken?

### ISSUE THREAD

**Issue by brjadams** [golangci/golangci-lint#1091]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.27.0 built from fb74c2e on 2020-05-13T18:48:26Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
None
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.13.8 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/badams/.cache/go-build"
GOENV="/home/badams/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/badams/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/home/badams/ffmpeg_build/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/badams/ffmpeg_build/lib/ -lavcodec -lavformat -lavutil -lswscale -lswresample -lavdevice -lavfilter"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build980205513=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```console
nothing
```
Using zsh 5.8
</details>
The completions I get appear to be wrong when I use them for zsh.

<code>echo 'source <($HOME/go/bin/golangci-lint completion zsh)' >>~/.zshrc`</code>

All of the auto completions are prefixed with a `_`, such as `_golangci-lint_cache` or `_golangci-lint`. 

Perhaps I misunderstood something but that seems wrong.

**Comment by sayboras** [comment]
seems like the issue got fix in master after upgrade cobra to v1.0.0. @brjadams do you mind to check again ?

```
$ zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

![image](https://user-images.githubusercontent.com/9019229/82743586-b255e500-9db0-11ea-89bd-c257bba19d46.png)

**Comment by bombsimon** [comment]
Not sure if this was ever related, but can confirm this is also working with zsh 5.7.1 which is the latest bundled with macOS.

![image](https://user-images.githubusercontent.com/3248948/82749716-6e141600-9dab-11ea-9523-24f1ba2ae31b.png)

**Comment by lopezator** [comment]
I'm closing this, @brjadams feel free to reopen the issue if the problem persists.
