### ISSUE TITLE
Update go-err113

### ISSUE THREAD

**Issue by jackwhelpton** [golangci/golangci-lint#1093]
I recently resolved a bug in go-err113 that led to false positives for the "do not define dynamic errors" warning: this is in the commit `5174e21577d5ed9c53d9f62d2eecf64c16b86aa0`, merged to master 4 days ago:

https://github.com/Djarvur/go-err113/commit/5174e21577d5ed9c53d9f62d2eecf64c16b86aa0

Unfortunately this doesn't seem to have been picked up in the latest `golangci-lint` release 2 days ago. I'm guessing it's as simple as a go.mod update: I can submit a PR if that's the recommended approach?

**Comment by bombsimon** [comment]
That is correct, updating `go.mod` and vendoringin dependencies in a PR and it will be included in the next release!

**Comment by jackwhelpton** [comment]
Ah, it looks like something runs that raises these PRs automatically?

https://github.com/golangci/golangci-lint/pull/1099

As that's merged, I'm guessing this issue can be closed?

**Comment by bombsimon** [comment]
Yeah, sorry! I didn't know the auto update was running for packages not using semver but it seems like it's running for any dependency. So from now on, all that's needed is a successful build and an approval and then we can merge updates in dependencies.
