### ISSUE TITLE
False positives coming from deadcode

### ISSUE THREAD

**Issue by y0ssar1an** [golangci/golangci-lint#116]
`deadcode` has [a serious bug](https://github.com/remyoudompheng/go-misc/issues/13): It incorrectly flags any test in `package main` as unused. It's causing `golangci-lint` to report a bunch of false positives in my codebase at work. `gometalinter.v2` doesn't have this problem and I'm unsure why.

[This fix was submitted in December 2017](https://github.com/remyoudompheng/go-misc/pull/14), but it hasn't been reviewed or merged, which tells me that @remyoudompheng isn't really maintaining it.

Until the bug is fixed upstream, it would be nice if `golangci-lint` either 1) suppressed the false positive internally, 2) provided guidance about how to suppress the false positive in the README, or 3) forked and fixed `deadcode`.

**Comment by jirfag** [comment]
thank you for reporting

**Comment by jirfag** [comment]
Fixed it
