### ISSUE TITLE
avoid halting, instead check compilation errors

### ISSUE THREAD

**Issue by alvarolm** [golangci/golangci-lint#1172]
**Is your feature request related to a problem? Please describe.**
i dont believe the linter should halt when compilation errors are detected, at least in those cases it could default to report those errors or run **go tool compile**

**Describe the solution you'd like**
run **go tool compile** when the linter halts as last measure

**Describe alternatives you've considered**
using another linter or metalinter

**Comment by iwankgb** [comment]
@alvarolm see #1043 (this issues seems to be a duplicate).
