### ISSUE TITLE
Add nishanths/exhaustive 

### ISSUE THREAD

**Issue by swithek** [golangci/golangci-lint#1187]
**Describe the solution you'd like**
It would be nice to have [nishanths/exhaustive](https://github.com/nishanths/exhaustive) as an official linter. Checking which iota enums are used in switch cases is useful in larger scale applications

**Comment by bombsimon** [comment]
It was implemented 21 days ago in #1166 but has not yet been released. Will be available in next release of `golangci-lint`.

**Comment by swithek** [comment]
Ah, sorry, must have missed that.
