### ISSUE TITLE
make the `-s`, silent output in case of success the default output

### ISSUE THREAD

**Issue by dahankzter** [golangci/golangci-lint#121]
When this was implemented there were several people that noted the Unix principle of silence.
I wanted to add this issue as a discussion for making the `-s` behavior the default.
Possibly also what the rule of silence would mean for Json (and analogously for XML) output where the options discussed so far are basically to return nothing, to return `{}` and to return `{Issues:[]}`. 

The only practical consideration afaik is backwards compatibility. This is less important early in a project because early adopters are usually not too averse to change. As time goes by this gets more and more  important. Backwards compat for the basic text output is also pretty harmless but in the Json case it is easy to see someone parsing the output with [jq](https://stedolan.github.io/jq/) where the three variants above can potentially result in very different outcomes if the user isn't careful.

What do you think?

**Comment by mmatczuk** [comment]
For the record I'm adding my objections as stated in #112 

The `-s` flag:

* does not solve the Rule of Silence - by default say nothing
* adds complexity to the tool, another flag now we have -s and -v
* I do not see a lot of possibilities to reuse it for other things

**Comment by frou** [comment]
From: https://github.com/golangci/golangci-lint/pull/112#issuecomment-397613758

> That would change the current behavior and potentially break someone who for example greps for the congrats message.

Such a grepping person needs to learn sooner or later that the accepted way to check this kind of thing is to examine the process's exit code
