### ISSUE TITLE
Add a `gofumports` as a new linter

### ISSUE THREAD

**Issue by SVilgelm** [golangci/golangci-lint#1241]
`gofumpt` also has `gofumports`. Any way we can sneak that in here?

_Originally posted by @andrewrynhard in https://github.com/golangci/golangci-lint/pull/1239#issuecomment-657578408_

**Comment by dnwe** [comment]
@SVilgelm see https://github.com/mvdan/gofumpt/issues/75

There isn’t really a need for gofumports in golangci-lint

**Comment by SVilgelm** [comment]
@dnwe thank you, so we can close this issue
