### ISSUE TITLE
add new linter to upport repairing import grouping/ordering

### ISSUE THREAD

**Issue by daixiang0** [golangci/golangci-lint#1257]
**Is your feature request related to a problem? Please describe.**

See this [discuss](https://github.com/golang/go/issues/20818#issue-238956416).

**Describe the solution you'd like**

Introduce [gci](https://github.com/daixiang0/gci) as a new linter.

**Additional context**

Golang community has little inseret about imporing it, but it would be useful for both contributors and maintainers.

Now gci implement basic functions，i think add it as new linter would be very cool.

WDYT? @golangci/team

**Comment by SVilgelm** [comment]
Looks like the gci is a very useful linter, but 
1. it should support go/analysis interface
2. the gci implementation contains only `main` package that prevents the other applications to import that tool

**Comment by daixiang0** [comment]
I will refactor it.

**Comment by daixiang0** [comment]
Done.
