### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by odidev** [golangci/golangci-lint#1262]
*Is your feature request related to a problem? Please describe.*
Hi Team,

Are you planning to release golangci/golangci-lint image for arm64?

*Describe the solution you'd like*
I am checking on adding arm64 support in Travis-CI for kube-router package, but I was facing issue in pulling golangci-lint image for arm64 as it is not available in the docker hub. I have observed that golangci-lint has support for arm64 platform. I was successful in building golangci-lint docker image in my local arm64 machine. May I know, Is it possible to make the image also available for arm64?

**Comment by sayboras** [comment]
@odidev I can't think of any reason stopping us from doing this. Are you planning to contribute and send the PR for this ?

**Comment by odidev** [comment]
Thanks for the reply. I didn't update anything in the Dockerfile, it was perfectly building docker image when ran in my arm64 local machine. I was just thinking that if you could release image for arm64 in dockerhub. May I know, how can I contribute in doing that?

**Comment by sayboras** [comment]
can you share the steps that you performed ? I can test it out with my raspi :)

**Comment by odidev** [comment]
I didn't update anything in the Dockerfile. The Steps followed to build the docker image for arm64 are -

1. Install pre-built binary of golangci/golangci-lint using command 
`wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.29.0
`
2. `docker build -t <Image-name>:<tag> -f <path to Dockerfile> .
`

For building image using Dockerfile.alpine
`docker build -t <Image-name>:<tag> -f <path to Dockerfile.alpine> .
`

I am happy to help if any more information is required.

**Comment by SVilgelm** [comment]
The `golancgci-lint` uses `goreleaser` tool to build all binaries and docker files. Unfortunately the `goreleaser` does not support multi-arch builds right now: https://github.com/goreleaser/goreleaser/issues/530

**Comment by SVilgelm** [comment]
you can always download an arm version of binary from the latest release

**Comment by odidev** [comment]
As we don't have multi-arch support in goreleaser, I have added docker release code in tag.yml to release images through github-actions and images got uploaded for both amd64 and arm64 in docker hub successfully. Please check the below links for more details.

Commit Link- https://github.com/odidev/golangci-lint/commit/cf45b6352dda3c884ecf2049e6279a48dd3e4ddf

Github actions Link- https://github.com/odidev/golangci-lint/runs/965764172?check_suite_focus=true

Dockerhub Link- https://hub.docker.com/repository/docker/odidev/golangci-lint/tags?page=1

Please check and let me know if I can raise PR with these changes.

**Comment by SVilgelm** [comment]
it will be great if we can modify goreleaser, so all depended project can re-use this feature

**Comment by odidev** [comment]
As I have mentioned earlier goreleaser does not support multi-arch builds right now. So do you want me to work on supporting goreleaser tool for releasing images?

Are the changes done by me for releasing arm64 images not correct?

**Comment by odidev** [comment]
Can anyone please review my changes and let me know if we can proceed with these changes.

Link - https://github.com/odidev/golangci-lint/commit/cf45b6352dda3c884ecf2049e6279a48dd3e4ddf

**Comment by sayboras** [comment]
@odidev can we use https://github.com/docker/build-push-action instead for building multi-arch docker intead ? Dancing around the script is fine, but make it hard to mantain though.

Additionally, if we want to do this, we need to remove docker step in goreleaser, and build multi-arch docker image using buildx, however, release note will not have docker details.

**Comment by odidev** [comment]
@sayboras  I have done the changes as per your suggestions. Can you please review the changes and suggest if any change is required?

Commit Link - https://github.com/odidev/golangci-lint/commit/6b002d51322ee753c2b537a1c29993cc207d5bae

Dockerhub Link - https://hub.docker.com/repository/registry-1.docker.io/odidev/golangci-lint/tags?page=1

**Comment by sayboras** [comment]
Can you replace `RUN git clone https://github.com/prakriti07/golangci-lint` by multi-stage docker build ? You can send draft PR for early feedback as well.

**Comment by odidev** [comment]
@sayboras I have raised the draft PR as per your suggestion. Can you please review it?

PR Link - https://github.com/golangci/golangci-lint/pull/1383

**Comment by sayboras** [comment]
Fixed as part of #1383
