### ISSUE TITLE
Update to staticcheck 2020.1.4

### ISSUE THREAD

**Issue by flimzy** [golangci/golangci-lint#1264]
**Is your feature request related to a problem? Please describe.**
The new version of staticcheck [solves some noise](https://github.com/dominikh/go-tools/releases/tag/2020.1.4) relating to `github.com/golang/protobuf/proto`

**Describe the solution you'd like**
Update to the latest staticcheck.

**Additional context**
https://github.com/golangci/golangci-lint/pull/1063 erroneously claims to have updated to 2020.1.4 in the PR description, but the actual commit correctly references 2020.1.3 https://github.com/golangci/golangci-lint/pull/987.  Note that this PR happened nearly 2 weeks before 2020.1.4 was released :)

**Comment by ldez** [comment]
Fixed by #1145

The current version is 2020.1.6
