### ISSUE TITLE
Please tweak release changelog format

### ISSUE THREAD

**Issue by AlekSi** [golangci/golangci-lint#1270]
**Is your feature request related to a problem? Please describe.**

Dependabot-generated changelog for golangci-lint is not readable.

![image](https://user-images.githubusercontent.com/11512/88475558-c09fb900-cf39-11ea-8606-0fc799eac2f8.png)

**Describe the solution you'd like**

Using a Markdown syntax for lists should help.

**Describe alternatives you've considered**

https://github.com/dependabot/dependabot-core/issues/2367

**Comment by jeffwidman** [comment]
This is probably something we should fix upstream in Dependabot... because the newlines are present, and it's reasonable to expect Dependabot to preserve those... we're just not handling them correctly... eg something like:
* https://github.com/dependabot/dependabot-core/pull/6358

**Comment by jeffwidman** [comment]
This is already fixed in Dependabot, for example this PR correctly shows the changelog:
* https://github.com/asphaltbuffet/wherehouse/pull/30

Xref: https://github.com/dependabot/dependabot-core/issues/2367#issuecomment-1363336843

So this can be closed as already fixed.
