### ISSUE TITLE
support staticcheck configuration

### ISSUE THREAD

**Issue by benjaminjkraft** [golangci/golangci-lint#1275]
Staticcheck has a bunch of [options](https://staticcheck.io/docs/options).  We'd like to be able to use those via golangci-lint, but it doesn't seem to be supported.

It's not clear to me if staticcheck exposes a proper way to do this, but it looks like setting `DefaultConfig` would be a plenty usable hack.

I think this would subsume #649, #980, perhaps others.

**Comment by csilvers** [comment]
It looks like staticcheck-in-the-context-of-golangci-lint reads the staticcheck.conf file, so another usable hack is to just set that.  It's not great to have two config files but it's better than nothing.
