### ISSUE TITLE
Include go-critic

### ISSUE THREAD

**Issue by mastertinner** [golangci/golangci-lint#132]
It would be awesome to include the [go-critic](https://github.com/go-critic/go-critic) linter which covers cases that aren't covered by other linters.

**Comment by JonKohler** [comment]
I'm curious if it makes sense to reach out to the maintainers / makers over at go-critic and see if it makes sense to just join forces here, with a "better together" strategy.

I've got no skin in the game here, other than loving the high quality analysis that both the golangci-lint and the golangci github webhooks have been giving my project. 

cc @Quasilyte cc @jirfag

**Comment by rgeronimi** [comment]
Joining forces seem even critical. There are a millions "must-have" linters right now. And on top of that 3 meta linters frameworks now. Diversity is needed for innovation, but it just seems some checks are so standard now that they should be declared as "standard" either within or outside the golang project, with all the benefits entailed - more eyeballs to improve them, better integration into all offline and online tools, better deployment over Golang open-source codebases. It is surprising that Golang has standardized so many things which other language communities considered as non-standard (e.g., formatting) and yet has completely missed the linter standardization train.

**Comment by rgeronimi** [comment]
Yes that is what i was pointing to - great then!

**Comment by ewgRa** [comment]
Initial integration done: https://github.com/ewgRa/golangci-lint/commit/694cfa32a68bc445b1b2a2ffa7873e50736d1cb3

There is FIXME left https://github.com/ewgRa/golangci-lint/commit/694cfa32a68bc445b1b2a2ffa7873e50736d1cb3#diff-e8f32f7051f960c9db2c0346f10a8390R26, that will made actual gocritic run, but for this there is changes on go-critic side needed and it will be the next step.

Changes on go-critic side: mostly extract criticize command to be able to reuse it for golangci-lint.

**Comment by AlekSi** [comment]
Would really like to see that issue solved.
