### ISSUE TITLE
Nancy will be moving to 1.0.0 soon and have new usage

### ISSUE THREAD

**Issue by DarthHater** [golangci/golangci-lint#1320]
Hello!

We saw you are using `nancy`, and we are humbled! I thought I'd reach out and let you know that we will have a 1.0.0 release coming soon, and usage is going to change slightly. To avoid disruption to your project, rather than using `latest` on your Docker image tag, I'd suggest using `v0.3` or `v0` for now, and then moving back to `latest` once you've had some time to digest the changes. I'd say we are about a week out from merging those changes, hence the heads up! They aren't gigantic, but we've moved some of the functionality into a `nancy sleuth` command.

CC @zendern @bhamail

**Comment by DarthHater** [comment]
THANK YOU BORING CYBORG!

**Comment by sayboras** [comment]
@DarthHater thanks for the heads up :100:

PS: The bot is funny right :laughing:

**Comment by sayboras** [comment]
Pending task is to make sure nancy v1.0 will not break once it's realease.
