### ISSUE TITLE
nlreturn: support suggested fix

### ISSUE THREAD

**Issue by wreulicke** [golangci/golangci-lint#1322]
**Is your feature request related to a problem? Please describe.**
New version of nlreturn supports suggested fix.

**Describe the solution you'd like**
just update to nlreturn v2.1.0

**Describe alternatives you've considered**
nothing

**Additional context**

**Comment by sayboras** [comment]
@wreulicke thanks for your issue, just want to check if you are planning to send PR as well ?

**Comment by ldez** [comment]
Closed in favor of #1779
