### ISSUE TITLE
docker image doesn't work anymore with time/tzdata package.

### ISSUE THREAD

**Issue by jerome-laforge** [golangci/golangci-lint#1338]
Hello
Is it planned to release whith https://github.com/golangci/golangci-lint/pull/1303?
Because with new `time/tzdata` package. The golangci-lint doesn't work anymore .

Many thx.

**Comment by SVilgelm** [comment]
sure, we a going to make a release soon

**Comment by SVilgelm** [comment]
@jerome-laforge the v1.31.0 is released. Could please check that it works?

**Comment by jerome-laforge** [comment]
Perfect, it works like a charm!
Many thanks
