### ISSUE TITLE
Update gochecknoglobals

### ISSUE THREAD

**Issue by leighmcculloch** [golangci/golangci-lint#1393]
**Is your feature request related to a problem? Please describe.**
It looks like in response to #199 [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals) was ported into golangci-lint, but it's also out-of-date, as the latest gochecknoglobals makes some new exceptions.

**Describe the solution you'd like**
Would it be possible for golandci-lint to call out to gochecknoglobals to make updating easier here, or is there a pattern I can follow to make it possible to hook into so you can simply import and call?

Alternatively the implementation in golangci-lint needs updating to pickup the new changes to maintain consistency.

**Comment by bombsimon** [comment]
`golangci-lint` always vendors it's dependencies but doing so is still easier than copying the linter like this. However, `golangci-lint` relies on the [`analysis.Analyzer`](https://pkg.go.dev/golang.org/x/tools/go/analysis#hdr-Analyzer) so the linter must support that. There are to ways to do that:

1. Make `gochecknoglobals` return both the error message and the `token.Pos` so `golangci-lint` can use this and add it to an internal analyzer like [this] or [this](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/gci.go#L24-L27).
2. Make `gochecknoglobals` implement it's own `analysis.Analyzer` and it could be used as is in `golangci-lint` like [this](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/gomnd.go) (see [source](https://github.com/tommy-muehle/go-mnd/blob/master/analyzer.go#L17-L24)).

I think #2 would be pretty easy to implement to `gochecknoglobals` and would make it super easy to maintain in `golangci-lint` by just bumping the dependency version.

**Comment by leighmcculloch** [comment]
I agree I think 2 would be the best forward looking approach. Thanks @bombsimon for pointing this out.

**Comment by leighmcculloch** [comment]
Thanks to @bombsimon the gochecknoglobals tool is now built on the Go analysis package. I can make the same changes to the [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits) tool too so it can also be upgraded easier.
