### ISSUE TITLE
Normalize path in exclude rules (OS path separator)

### ISSUE THREAD

**Issue by shieldsjared** [golangci/golangci-lint#1398]
**Is your feature request related to a problem? Please describe.**
When specifying path's w/in exclude rules, the path regex requires special attention for cross-platform path separators.  Currently, you have to specify paths using syntax such as `folder[/\\]file.go` in order to gain cross-platform freedom.  Some settings within the configuration appear to support automatic replacement of `/` with the operating system's default (e.g. on windows it becomes `\`).

**Describe the solution you'd like**
Identify all configuration's that involve a path (such as `exclude-rules`), and extend the functionality that currently replaces the path separator when executed on a windows platform while utilizing `skip-files` and `skip-dir`.  Currently, I'm 

**Describe alternatives you've considered**
No other alternatives considered.  Honestly unsure of the implications of this request.  Just throwing it out there for discussion :)

**Comment by frederikhors** [comment]
This is huge!

**Comment by frederikhors** [comment]
Nope
