### ISSUE TITLE
config file json schema

### ISSUE THREAD

**Issue by zepatrik** [golangci/golangci-lint#1453]
**Is your feature request related to a problem? Please describe.**

I have written a JSON Schema for golangci-lint's config file. Maybe someone can check or even improve it? Some of the descriptions could be improved upon also :wink:
https://github.com/SchemaStore/schemastore/pull/1312

This will enable autocompletion, tooltips and validation in IDEs like VSCode or JetBrains.

**Describe the solution you'd like**

A second (or even more) pair of eyes to check the schema. Maybe you have some example config files that the schema can be tested against.

I can also add a PR in this repository to add the schema. In other projects I already utilize documentation generation of pages like your https://golangci-lint.run/usage/configuration/#config-file page from the schema.

**Describe alternatives you've considered**

Just add it as is to the schemastore.

**Additional context**

One of the auto generated docs pages from one of my projects: https://www.ory.sh/kratos/docs/reference/configuration

**Comment by pierrre** [comment]
Hello !
It seems to be used by vscode, and it's reporting an issue for me.

**Comment by pierrre** [comment]
Hello !
It seems to be used by vscode, and it's reporting an issue for me.
The field `linters-settings.depguard.packages-with-error-message` should be an array of objects, not an object.

**Comment by zepatrik** [comment]
Hm right, seems like I missed that. Feel free to fix it in the schema store, they respond quickly

**Comment by SVilgelm** [comment]
one more place to update after any changes in the configurations

**Comment by zepatrik** [comment]
That's why I suggested to take the json schema as the single source of truth and render the documentation from that. In JSONSchemaStore you can also point the schema to a different place, so it would always be fetched from this repo. But if nobody responds whether this is something you would merge I can't do anything about that, sorry.

**Comment by SVilgelm** [comment]
I mean, if we can make all update automatically, then yes, let's do it. Any PRs are welcome. 
But right now the only source of true is go code, so it would be great to keep it and generate the json scheme from go code.

**Comment by zepatrik** [comment]
I don't know of any project that would do that, but  I will have a look. But https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml is manually maintained right? I could auto generate that from the schema, so there are still two places to update. Will draft something in the next days then.
Validation within the config package would be way easier with the schema (it looks like many values are not validated at all?).

**Comment by butuzov** [comment]
I was searching for this issue yesterday but haven't found it. @zepatrik nice job you did, even with depguard bothering :). 

I have updated yesterday a list of govet analyzers, but now its complaining on go-critic checks ;)

What i would suggest is 
1) to fork schema repo to @golangci org
2) see what can be automated while updating it manually ( govet analyzers, go-critic rules, etc)


Thoughts?

**Comment by zepatrik** [comment]
We can just host the schema in this repo and point the schemastore to it, then automate stuff in this repo. That's what I have done with other projects and would propose for this one as well. It worked great so far.

**Comment by butuzov** [comment]
I like this idea more. Can you provide an example or steps I/we/team needs to do in order to host schema in our repository?

**Comment by zepatrik** [comment]
This schema: https://github.com/ory/kratos/blob/master/.schema/version.schema.json (which again maps to the correct schema by version)
was added by: https://github.com/SchemaStore/schemastore/pull/1173
Then we auto-generate this docs page: https://www.ory.sh/kratos/docs/reference/configuration
from that using this script: https://github.com/ory/kratos/blob/master/docs/scripts/config.js
which we can do here in the exact same way to generate this file: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

Sounds good?

**Comment by butuzov** [comment]
it does! 

@SVilgelm  can I assign this to me? 

(I can work on this with slow pace, considering huge amount of work done by @zepatrik)

**Comment by zepatrik** [comment]
Nice, we can definitely work on that together. Feel free to ping me at any point ;).

**Comment by SVilgelm** [comment]
@butuzov @zepatrik sure, do anything you need

**Comment by AlekSi** [comment]
> The field linters-settings.depguard.packages-with-error-message should be an array of objects, not an object.

> The field linters-settings.depguard.packages-with-error-message should be an array of objects, not an object.

The golangci-lint code is not clear about it:
* An array of objects: https://github.com/golangci/golangci-lint/blob/a07b1fa26b5ea8cb4840dcb4db0c5fbe54604308/.golangci.yml#L9
* An array of objects: https://github.com/golangci/golangci-lint/blob/a07b1fa26b5ea8cb4840dcb4db0c5fbe54604308/.golangci.example.yml#L424
* Object: https://github.com/golangci/golangci-lint/blob/a07b1fa26b5ea8cb4840dcb4db0c5fbe54604308/test/testdata/configs/depguard.yml#L7
* Object (?): https://github.com/golangci/golangci-lint/blob/6c295e404247459f9b5e0f50c587f60e2f467ac1/pkg/config/linters_settings.go#L152

And why is that an array of single field objects? What's the point?

**Comment by ldez** [comment]
hello @AlekSi this point is explained here: https://github.com/golangci/golangci-lint/pull/1749#issuecomment-782609234

**Comment by AlekSi** [comment]
@ldez Thank you. Can golangci-lint use https://pkg.go.dev/github.com/spf13/viper#KeyDelimiter (`viper.KeyDelimiter("::")`) as suggested in https://github.com/spf13/viper/issues/324, https://github.com/spf13/viper/issues/977, and other issues?

**Comment by ldez** [comment]
For golangci-lint, the change of the separator produces side effects.
I don't think we have to fix something, because it's a minor problem.

**Comment by butuzov** [comment]
I spend some time pocking around json schema of `golangci-lint` recently. Changes already should be available to everyone.  Please let me know if anything you see in `.golangci.yml` validated correctly.

I have added or updated most of the new linters settings.

**Comment by nsemikov** [comment]
I just got a problem with schema:
![image](https://github.com/golangci/golangci-lint/assets/11590371/0431a7be-a1e4-4128-aefc-f5cbe7cc8bd1)
![image](https://github.com/golangci/golangci-lint/assets/11590371/e1e91a48-5a3d-434e-b710-99c788323b16)

**Comment by bifshteks** [comment]
It would be really nice to have a config schema always up-to-date.
It seems as a good idea to at least validate all the configurations used as examples in documentation against currently published schema in CICD. It becomes frustrating when you setting up your config using examples from docs, but linter says that some parameter does not exist :(

**Comment by trajan0x** [comment]
Would also love to see this

**Comment by ldez** [comment]
Hello,
With PR #4457, the documentation only displays linters and settings related to the current stable version.

The [JSON schema](https://json.schemastore.org/golangci-lint.json) follows this stable version.

Currently, we cannot generate the schema from the code because:
- large and "dynamic" enums (e.g. more than 110 linters, linter rules, etc.)
- some linter configurations are just raw maps
- some elements need to be defined by hand because there is no easy reference.

But, there are again possible improvements that we will try to add.
