### ISSUE TITLE
More configurable goconst

### ISSUE THREAD

**Issue by Antonboom** [golangci/golangci-lint#1495]
Hello!
I have a question :)

I needed the flags in `golangci-lint` that are in the original `goconst`:
https://github.com/jgautheron/goconst/issues/11

I wanted to do a PR and got confused where:
- https://github.com/golangci/goconst (outdated)
- https://github.com/jgautheron/goconst

What is the difference?

What is the best way to proceed? Try to update the `golangci/goconst` fork and then updating `golangci-lint` or update `golangci-lint` so that it no longer links to the fork, but works with the original linter?

Judging by the issues at https://github.com/golangci/goconst, I'm not the only one :)

**Comment by iwankgb** [comment]
@Antonboom judging by this comparison: https://github.com/jgautheron/goconst/compare/master...golangci:master the goal was to enable `goconst` to be used as a library. You may want to consider filing an issue in jgautheron/goconst asking about such a feature. In the meantime I will update our fork.

**Comment by Antonboom** [comment]
@iwankgb 

Сan we now completely switch to the original linter? :)
https://github.com/jgautheron/goconst/issues/11#issuecomment-723576953
