### ISSUE TITLE
Could not find nil pointer

### ISSUE THREAD

**Issue by liuss01** [golangci/golangci-lint#1496]
```go
package main

import (
	"fmt"
	"reflect"
)

type Worker interface {
	String() string
}

type Person struct {
	Age  uint8
	Name string
	Sex  string
}

type Employee struct {
	Person
}

type Employer struct {
	Title string
	Person
}

func (p *Person) String() string {
	return fmt.Sprintf("Name: %s, Sex: %s, Age: %d", p.Name, p.Sex, p.Age)
}

func (er *Employer) String() string {
	return fmt.Sprintf("%s, Title: %s", er.Person.String(), er.Title)
}

func main() {
	test()
}

func test() {
	var (
		w          Worker
		emptyPoint *Employee
	)

	w = &Employer{
		Title: "Title",
		Person: Person{
			Name: "Tom",
			Age:  50,
			Sex:  "male",
		},
	}

	if IsNil(w) {
		fmt.Printf("interface w is nil")
		return
	}

	// **bad**
	e := w.(*Employee)
	fmt.Println(e.String())
	// ok
	if e, ok := w.(*Employee); ok {
		fmt.Printf("It's Employee, %s\n", e.String())
	} else if e, ok := w.(*Employer); ok {
		fmt.Printf("It's Employer, %s\n", e.String())
	}

	// **bad**
	fmt.Println(emptyPoint.String())
}

func IsNil(i interface{}) bool {
	vi := reflect.ValueOf(i)
	if vi.Kind() == reflect.Ptr {
		return vi.IsNil()
	}
	return false
}
```

**Comment by iwankgb** [comment]
@liuss01 can you provide more information, please? Lonely code snippet might be difficult to understand.

**Comment by liuss01** [comment]
golangci-lint.exe version：
golangci-lint has version 1.31.0 built from 3d6d0e7 on 2020-09-07T15:14:41Z

scan via golangci-lint.exe run ./...

the code is above, just in a plain golang project dir

**Comment by liuss01** [comment]
How can we scan the nil pointer bug via golangci-lint?
I try my best to scan the bug, but failed to see the result.

**Comment by liuss01** [comment]
The bad code in my code is above "// **bad**".
Could you scan the two bugs by golangci-lint tool?
Thank you.

**Comment by iwankgb** [comment]
Does any of linters integrated with golanci-lint have such capabilities? I'm not aware of any, to be honest.

**Comment by ldez** [comment]
For the two "bad code":

```
// e := w.(*Employee)
panic: interface conversion: main.Worker is *main.Employer, not *main.Employee
```

```
// fmt.Println(emptyPoint.String())
panic: runtime error: invalid memory address or nil pointer dereference
```

These 2 elements are different:
- one is a type assertion problem
- one is a call of a method on a nil pointer when the method is defined on an embedded structure

---

FYI, it's possible to call a method on a nil pointer:

https://play.golang.org/p/woKTykNQ8TA

So the problem is more related to:
```go
type Employee struct {
	Person
}
```

Because the `String` method is on the struct `Person`

From the point of view of a linter, it's can be difficult to find.

Currently, in golangci-lint, there is no linter that is able to detect this.

**Comment by liuss01** [comment]
Thank you for your reply.

Yes, there are two different elements for the two "bad code".
And I try my best to look for a linter that could detect them, but I failed to find one.
I found that "https://staticcheck.io/docs/checks#SA5011" seems to deduce them. But it failed.
At the same time, the Goland IDE can detect them and notice us they are there.

Nil pointer derenfernce is too dangerous to run, especially for the old project code.

How can I scan thems?

**Comment by ldez** [comment]
> At the same time, the Goland IDE can detect them and notice us they are there.

In fact, if you try my [example](https://play.golang.org/p/woKTykNQ8TA), Goland will display a warning but it's a false-positive.

> I found that "https://staticcheck.io/docs/checks#SA5011" seems to deduce them. But it failed.

The SA5011 rule is able to find a dereferenced pointer, so it does not apply to your cases.

Currently, I think that writing tests on your codebase is the best way to find these issues.

**Comment by liuss01** [comment]
Much aprreciate to you. :-)

The Goland really says the warning.

For those possible nil pointer code, we will try other ways such as code review and test to find them.

**Comment by karlismelderis-outreach** [comment]
I'm new to golang and I'm coming from languages where if type says that variable is string then you definitely get string.
And if variable is string or nil you cannot assign it to variable that is expected to be string only or cannot even call string functions until you wrap code in `if var != nil`

I understand that pointers are good but it shouldn't be hard to add linter that warns that you're reading possibly nil pointer and should wrap code in `if var !=nil`

In my eyes this is fundamental part of type safety.
if type says -> pointer to string then I should get string
if pointer can point to string or is possibly nil -> typing system or lint should tell it

I don't see that tests would help as no matter how hard you try something will slip through eventually.
And strongly types languages should strive to remove need for so trivial tests and let developer to focus more on testing business logic not low level implementation details.

**Comment by karlismelderis-outreach** [comment]
Before closing this ticket please read this from creator of Nil pointers:
https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare/

why nil pointers are Billion dollar mistake
why it's responsibility of language to protect developers
why testing is not enough
