### ISSUE TITLE
Sort structure declaration fields alphabetically

### ISSUE THREAD

**Issue by DONSA** [golangci/golangci-lint#1499]
Before:
```
type Person struct {
    Name string
    Age  int
}
```

After:
```
type Person struct {
    Age  int
    Name string
}
```

**Comment by bombsimon** [comment]
Hello! What is this? Do you want a linter that does this? Do you want our code to use this?

**Comment by DONSA** [comment]
Yes, a linter with the option to automatically order structs alphabetically.

**Comment by sayboras** [comment]
I am sure what the value of this proposal is, except for readability, which is arguable. In my opinion, struct fields are either grouped in particular logical order (e.g. data types, relationship, importance, etc), or in a optimal memory order (e.g. structcheck).

It will be great if you can explain your rationale of having such linter.

**Comment by DONSA** [comment]
We decided to have it like that in our projects to make it easier to find the fields when we are reading the struct.
But you are right, and it surely doesn't apply to every project/team.
