### ISSUE TITLE
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:407:22: ins.Type undefined (type ssa.Instruction has no field or method Type)

### ISSUE THREAD

**Issue by JonKohler** [golangci/golangci-lint#150]
I've upgraded my CI to 1.9.1 yesterday, and am hitting the following error below.

You can see the travis output, here: https://travis-ci.com/nutanix/terraform-provider-nutanix/jobs/132362849

From the looks of it, it might be as a result of https://github.com/golangci/golangci-lint/commit/a6b91ccc7721633a5af2b1f4cccc09efc58fe6c4#diff-2d9c124cc9a48e4c49da657a28d38959

```
12.13s$ go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint/
# github.com/terraform-providers/terraform-provider-nutanix/vendor/honnef.co/go/tools/staticcheck/vrp
vendor/honnef.co/go/tools/staticcheck/vrp/int.go:362:102: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/slice.go:148:76: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/string.go:120:102: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:120:34: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:143:33: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:180:32: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:399:10: undefined: ssa.Sigma
vendor/honnef.co/go/tools/staticcheck/vrp/vrp.go:407:22: ins.Type undefined (type ssa.Instruction has no field or method Type)
```

**Comment by jirfag** [comment]
hi!
Could you use golangci-lint without vendoring?
1. `curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin vX.Y.Z` works very fast.
2. version is fixed, a code never changes

In your case somehow `golang.org/x/tools` got the invalid version, we use `10e39b9b093209d1d6c03acc2252a399ece6b112`.
There can be other problems, I recommend to install it by shell script in CI.

**Comment by JonKohler** [comment]
@jirfag thanks for the response, I'm tuning up our repo right now, will close my related issue when I get a successful build. I think we're good here for now! cheers!
