### ISSUE TITLE
Conflict in GoSec Results

### ISSUE THREAD

**Issue by NishikaDeSilva** [golangci/golangci-lint#1504]
I am trying to gosec in golangci-lint. However, some issues that are reported in gosec do not get reported when using gosec through golangci-lint. 

I've used https://github.com/golang/example project to test this behavior. There were 3 issues reported when runnig gosec however with golangci-lint non were recorded. Please refer to the output below. 

```console
$ golangci-lint run gotypes --disable-all -E gosec
$ gosec gotypes
[gosec] 2020/11/12 13:56:09 Including rules: default
[gosec] 2020/11/12 13:56:09 Excluding rules: default
[gosec] 2020/11/12 13:56:09 Import directory: personal/sec-test-go/example/gotypes
[gosec] 2020/11/12 13:56:09 Checking package: main
[gosec] 2020/11/12 13:56:09 Checking file: personal/sec-test-go/example/gotypes/weave.go
Results:
[personal/sec-test-go/example/gotypes/weave.go:106] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    105: func include(file, tag string) (string, error) {
  > 106: 	f, err := os.Open(file)
    107: 	if err != nil {
[personal/sec-test-go/example/gotypes/weave.go:110] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
    109: 	}
  > 110: 	defer f.Close()
    111:
[personal/sec-test-go/example/gotypes/weave.go:30] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
    29: 	}
  > 30: 	defer f.Close()
    31:
Summary:
   Files: 1
   Lines: 191
   Nosec: 0
  Issues: 3
```
I ran the same commands to another directory in the same project then all the issues were reported with both approaches. 

```console
$ golangci-lint run outyet --disable-all -E gosec
outyet/main.go:98:12: G107: Potential HTTP request made with variable url (gosec)
	r, err := http.Head(url)
$ gosec outyet
[gosec] 2020/11/12 14:07:56 Including rules: default
[gosec] 2020/11/12 14:07:56 Excluding rules: default
[gosec] 2020/11/12 14:07:56 Import directory: personal/sec-test-go/example/outyet
[gosec] 2020/11/12 14:07:56 Checking package: main
[gosec] 2020/11/12 14:07:56 Checking file: sec-test-go/example/outyet/main.go
Results:

[personal/sec-test-go/example/outyet/main.go:98] - G107 (CWE-88): Potential HTTP request made with variable url (Confidence: MEDIUM, Severity: MEDIUM)
    97: 	pollCount.Add(1)
  > 98: 	r, err := http.Head(url)
    99: 	if err != nil {

Summary:
   Files: 1
   Lines: 140
   Nosec: 0
  Issues: 1
```

Do you use any extra steps to exclude these errors?

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# golangci-lint has version 1.32.2 built from 52d26a3
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# go version go1.15.4 darwin/amd64
# GO111MODULE=""
# GOARCH="amd64"
# GOBIN=""
# GOCACHE="<User>/Library/Caches/go-build"
# GOENV="<User>/Library/Application Support/go/env"
# GOEXE=""
# GOFLAGS=""
# GOHOSTARCH="amd64"
# GOHOSTOS="darwin"
# GOINSECURE=""
# GOMODCACHE="<user>/go/pkg/mod"
# GONOPROXY=""
# GONOSUMDB=""
# GOOS="darwin"
# GOPATH="<user>/go"
# GOPRIVATE=""
# GOPROXY="https://proxy.golang.org,direct"
# GOROOT="/usr/local/Cellar/go/1.15.4/libexec"
# GOSUMDB="sum.golang.org"
# GOTMPDIR=""
# GOTOOLDIR="/usr/local/Cellar/go/1.15.4/libexec/pkg/tool/darwin_amd64"
# GCCGO="gccgo"
# AR="ar"
# CC="clang"
# CXX="clang++"
# CGO_ENABLED="1"
# GOMOD=""
# CGO_CFLAGS="-g -O2"
# CGO_CPPFLAGS=""
# CGO_CXXFLAGS="-g -O2"
# CGO_FFLAGS="-g -O2"
# CGO_LDFLAGS="-g -O2"
# PKG_CONFIG="pkg-config"
# GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6y/c2wx50s15bq607l3v_pg42dh0000gn/T/go-build371746232=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

The difference comes because golangci-lint use default excludes: https://golangci-lint.run/usage/configuration/#command-line-options

<details>

>       --exclude-use-default            Use or not use default excludes:
>                                          # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
>                                          - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
>                                        
>                                          # EXC0002 golint: Annoying issue about not having a comment. The rare codebase has such comments
>                                          - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
>                                        
>                                          # EXC0003 golint: False positive when tests are defined in package 'test'
>                                          - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
>                                        
>                                          # EXC0004 govet: Common false positives
>                                          - (possible misuse of unsafe.Pointer|should have signature)
>                                        
>                                          # EXC0005 staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore
>                                          - ineffective break statement. Did you mean to break out of the outer loop
>                                        
>                                          # EXC0006 gosec: Too many false-positives on 'unsafe' usage
>                                          - Use of unsafe calls should be audited
>                                        
>                                          # EXC0007 gosec: Too many false-positives for parametrized shell calls
>                                          - Subprocess launch(ed with variable|ing should be audited)
>                                        
>                                          # EXC0008 gosec: Duplicated errcheck checks
>                                          - (G104|G307)
>                                        
>                                          # EXC0009 gosec: Too many issues in popular repos
>                                          - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
>                                        
>                                          # EXC0010 gosec: False positive is triggered by 'src, err := ioutil.ReadFile(filename)'
>                                          - Potential file inclusion via variable
>                                        
>                                          # EXC0011 stylecheck: Annoying issue about not having a comment. The rare codebase has such comments
>                                          - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
>                                         (default true)

</details>

If you want to achieve the same behavior as gosec, you should disable these default exclusions:

```console
$ golangci-lint run gotypes --exclude-use-default=false --disable-all -E gosec
gotypes/weave.go:30:2: G307: Deferring unsafe method "Close" on type "*os.File" (gosec)
	defer f.Close()
	^
gotypes/weave.go:106:12: G304: Potential file inclusion via variable (gosec)
	f, err := os.Open(file)
	          ^
gotypes/weave.go:110:2: G307: Deferring unsafe method "Close" on type "*os.File" (gosec)
	defer f.Close()
	^
```
