### ISSUE TITLE
go get install failed

### ISSUE THREAD

**Issue by HuberyChang** [golangci/golangci-lint#1518]
Thank you for creating the issue!

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# paste output here
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

Command Run
```
go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
```

Output
```
  ../../pkg/mod/github.com/golangci/golangci-lint@v1.32.0/pkg/golinters/gci.go:50:25: assignment mismatch: 3 variables but gci.Run returns 2 values
  ../../pkg/mod/github.com/golangci/golangci-lint@v1.32.0/pkg/golinters/godot.go:31:30: unknown field 'CheckAll' in struct literal of type godot.Settings
  ../../pkg/mod/github.com/golangci/golangci-lint@v1.32.0/pkg/golinters/godot.go:36:38: multiple-value godot.Run() in single-value context
```

**Comment by sayboras** [comment]
Same as #1506
