### ISSUE TITLE
docker install failed

### ISSUE THREAD

**Issue by HuberyChang** [golangci/golangci-lint#1519]
Thank you for creating the issue!

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# paste output here
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

command
```
golangci-lint run -v
```

Output
```
+ golangci-lint run -v
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="Memory: 601 samples, avg is 72.1MB, max is 72.1MB"
level=info msg="Execution took 1m0.000224665s"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|deps|imports|name|types_sizes|exports_file|files) took 59.991489811s"
level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: context deadline exceeded: stderr: "
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

**Comment by bombsimon** [comment]
Could you clarify this a bit? The title says "docker install failed" but according to your output you're just executing `golangci-lint run -v` and not using Docker. This is how you would run `golangci-lint` inside a Docker container.

```sh
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.32.2 golangci-lint run -v
```

If this is what you're doing, what repository is this? It is possible that `golangci-lint` will take more than 1 minute to execute for large repositories, especially with limited hardware resources. What's the repository you're using? What happens when you do what the output says and set `--timeout` to more than 1m (e.g. `--timeout 10m`)?

**Comment by HuberyChang** [comment]
@bombsimon

this is my jenkins pipeline command
```
                        try {
                            if (previousStageStatus == 'SUCCESS') {
                                stage('Check') {
                                    currentStage = 'Check'
                                    // --任务逻辑-----
                                    container("golangci-lint") {
                                        sh """
                                        pwd
                                        ls -l
                                        go env
                                        golangci-lint --version
                                        golangci-lint run -v
                                    """
                                    }
                                    // ----END------
                                    currentBuild.result = 'SUCCESS'
                                    echo "Stage Check ${currentBuild.result}."
                                }
                            }
                        } catch (e) {
                            currentBuild.result = 'FAILURE'
                            echo "Stage Check ${currentBuild.result}."
                            previousStageStatus = currentBuild.result
                            errMsg = e.toString()
                        }
```
the `golangci-lint` container works in a k8s pod

**Comment by HuberyChang** [comment]
> Could you clarify this a bit? The title says "docker install failed" but according to your output you're just executing `golangci-lint run -v` and not using Docker. This is how you would run `golangci-lint` inside a Docker container.
> 
> ```shell
> docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.32.2 golangci-lint run -v
> ```
> 
> If this is what you're doing, what repository is this? It is possible that `golangci-lint` will take more than 1 minute to execute for large repositories, especially with limited hardware resources. What's the repository you're using? What happens when you do what the output says and set `--timeout` to more than 1m (e.g. `--timeout 10m`)?

---
this is my jenkins pipeline command
```
                        try {
                            if (previousStageStatus == 'SUCCESS') {
                                stage('Check') {
                                    currentStage = 'Check'
                                    // --任务逻辑-----
                                    container("golangci-lint") {
                                        sh """
                                        pwd
                                        ls -l
                                        go env
                                        golangci-lint --version
                                        golangci-lint run -v
                                    """
                                    }
                                    // ----END------
                                    currentBuild.result = 'SUCCESS'
                                    echo "Stage Check ${currentBuild.result}."
                                }
                            }
                        } catch (e) {
                            currentBuild.result = 'FAILURE'
                            echo "Stage Check ${currentBuild.result}."
                            previousStageStatus = currentBuild.result
                            errMsg = e.toString()
                        }
```
the `golangci-lint` container works in a k8s pod

**Comment by iwankgb** [comment]
@HuberyChang I **think** (and I might be wrong) that you set too short timeout in configuration file. Could you share it?

**Comment by bombsimon** [comment]
It's currently set to 1m according to the output (`level=info msg="Execution took 1m0.000224665s"`). I suggested setting it to 10m but never got a response from the author so maybe we should close this for now.
