### ISSUE TITLE
Curious why the nilness analyze was removed in v1.19.0

### ISSUE THREAD

**Issue by 9547** [golangci/golangci-lint#1524]
Thank you for creating the issue!

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# paste output here
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

I'm using v1.18.0,  the code below can check the duplicated nilness

```go
func foo() error {
    err := bar()
    if err != nil {
        return errors.Wrap(err, "some error")
    }
    if err != nil {
        return errors.Wrap(err, "some error")
    }
}
```

outpus:

```bash
foo.go:532:10: nilness: impossible condition: nil != nil (govet)
                if err != nil {
                       ^

```
While using the master's version, this nilness can't checked.

**Comment by sayboras** [comment]
nilness is now part of govet, please find below snapshot of golangci.yaml configuration file.

```
...
linters-settings:
  govet:
    enable:
      - nilness
...
```

**Comment by 9547** [comment]
@sayboras thanks for your advice, it helps me.
