### ISSUE TITLE
New Linters(import aliases, log messages, cli help commands)

### ISSUE THREAD

**Issue by Glyphack** [golangci/golangci-lint#1525]
**Is your feature request related to a problem? Please describe.**
currently there are not linters for: 
- CLI help should be capitalized
- log messages should not be capitalized
- import aliases should be have a consistent pattern

**Describe the solution you'd like**
I would like to suggest Adding three rules to golangci-lint. 

The first two linters are clear, but for the third one there is a rule we use at [projectcontour](https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md#import-aliases).
So the rules for import alias would be:
consider import path: `github.com/projectcontour/x/y/z/v*`
- the alias name should be subset of x[optional]_y[optional]_z[optional]_v* where optional means it can be present or not.
- one of x or y or z must be present in alias name.
- If version exists in path, must be specified.

**Comment by SVilgelm** [comment]
so, the `golangci-lint` is a wrapper for the linters, so could you list the linters, if any, that supports your request?
if no such linters, then they should be implemented and can be integrated with `golangci-lint`

**Comment by Glyphack** [comment]
They are implemented already
https://github.com/projectcontour/lint

**Comment by ldez** [comment]
@Glyphack do not hesitate to open a PR to add them :+1:

**Comment by ldez** [comment]
@Glyphack about the import pattern we already added https://github.com/julz/importas

https://github.com/golangci/golangci-lint/pull/1783
