### ISSUE TITLE
Dockerfile runnable?

### ISSUE THREAD

**Issue by nwillems** [golangci/golangci-lint#153]
Hi

I was trying to run the docker image like below, but was getting an error about go not being on the path. 
```
docker run \
    -v "${PWD}":/go/src/github.com/nwillems/repo \
    -w /go/src/github.com/nwillems/repo \
    golangci/golangci-lint run
```

I suspect I'm holding it wrong - but in case I'm not, I would like to suggest that the images be built from `golang:$version`. Where `$version` is some preferred version.

I can see how this could possibly be a mess with version-a of golangci-lint and version-b of go.

I don't mind making the initial PR for using a golang image as base, just unsure if I was holding it wrong or. :-)

**Comment by jirfag** [comment]
hi!
thank you for reporting,
it's a bug of the Dockerfile: docker image doesn't include go distribution. Golangci-lint can't work without it.

**Comment by jirfag** [comment]
fixed in master
