### ISSUE TITLE
Different behavior of govet && nolinitlint on Windows and Linux 

### ISSUE THREAD

**Issue by wtask** [golangci/golangci-lint#1542]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.33.0 built from b90551c on 2020-11-23T05:15:36Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
run:
  concurrency: 4
  timeout: 15m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs: []
  skip-files: []
  #    - ".*pb\\.go$"
  #    - "bindata.go"
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic: {}
  lll:
    line-length: 120
    tab-width: 4
  misspell:
    locale: US
    ignore-words: []

linters:
  enable:
    - goimports
    - govet
    - golint
    - gocyclo
    - gocognit
    - maligned
    - goconst
    - gocritic
    - staticcheck
    - errcheck
    - lll
    - whitespace
    - nolintlint
    - unused
  disable-all: true
  fast: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocognit
        - gocyclo

    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    - linters:
        - govet
      text: "composite literal uses unkeyed fields$"

    - linters:
        - lll
      source: "^//go:generate "
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.15.6 windows/amd64
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=c:\dev\go\bin
set GOCACHE=C:\Users\webta\AppData\Local\go-build
set GOENV=C:\Users\webta\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\dev\go\pkg\mod
set GONOPROXY=*****.com
set GONOSUMDB=*****.com
set GOOS=windows
set GOPATH=C:\dev\go
set GOPRIVATE=*****.com
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Users\webta\Development\*****\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\webta\AppData\Local\Temp\go-build143508486=/tmp/go-build -gno-record-gcc-switches
mi
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

Under Windows (WSL) if nolint-directive is presented, I'm getting
```
directive `// nolint:govet // func has predefined signature and job passes sync.Mutex by value` is unused for linter govet (nolintlint)
                                // nolint:govet // func has predefined signature and job passes sync.Mutex by value
                                ^
```
So I need drop nolint-comments... And this is true, because I cannot change external implementation.

But when the same golangci-lint version under Linux checks the same code with the same config but without (already dropped) nolint-directive (gitlab pipeline), I/m getting linting error:
```
copylocks: func passes lock by value: github.com/zeebe-io/zeebe/clients/go/pkg/entities.Job contains github.com/zeebe-io/zeebe/clients/go/pkg/pb.ActivatedJob contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
				job entities.Job,
				    ^
```
vicious circle

**Comment by bombsimon** [comment]
Can you provide a minimal reproducible example for this please? It's not clear what code is causing this.

**Comment by ashanbrown** [comment]
It sounds like some linters, such as `govet`, make recommendations based on the implementation of structs.  Given OS-specific implementations (in this case it sounds like we have a lock for one OS but not another), it may be necessary to exclude them from `nolintlint` checks.  One thing not included in `nolintlint` is a way to `nolint` itself, both because this could create the very problem `nolintlint` seeks to avoid (lots of leftover `//nolints`) and because it's not clear what the syntax for this would look like.  Still, we could offer a few options:

1) Add an exclusion list to `nolintlint` for linters it should ignore for `nolintlint` recommendations.  In this case, we'd exclude `govet`.
2) Allow a `//nolint:nolintlint` directive that says that this line should be ignored for `nolintlint` purposes.  We could still require an explanation for this line.

Thoughts?
