### ISSUE TITLE
Golangci-lint breaks Ruleguard's `File().PkgPath` variable

### ISSUE THREAD

**Issue by bmhatfield** [golangci/golangci-lint#1545]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.33.0 built from b90551c on 2020-11-23T05:15:36Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters:
  enable:
    - gocritic

linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "tools/linters/gorules/rules.go"
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.15.5 darwin/amd64
```

</details>

I'm not really sure _how_, but I can confirm that:

- Running my `ruleguard` rules file directly with `ruleguard` works fine.
- Running my `ruleguard` rules file using `gocritic` works fine.
- Running my `ruleguard` rules file using `golangci-lint` breaks rules that depend on `PkgPath` (specifically, they no longer match, as if `PkgPath` was emptystring).
- Removing the `PkgPath` matcher from my ruleguard rule _does_ show errors (but inclusive of places I don't want them from).

I'm not sure what interplay of `golangci-lint` and `ruleguard` leads to this, but `PkgPath` is a critical feature to be able to write rules that only focus on one package or another in my codebase.

**Comment by iwankgb** [comment]
@bmhatfield it will be extremely difficult to determine what's wrong without a snippet of source code allowing to replicate the issues. Can you provide such a snippet?

**Comment by quasilyte** [comment]
I can help to track the issue roots if the example file can be provided.
