### ISSUE TITLE
Update gofumpt to the latest version

### ISSUE THREAD

**Issue by Zamiell** [golangci/golangci-lint#1547]
Hello and thanks for the excellent software.

- The current version of the `gofumpt` linter used by this repository is presumably listed [here](https://github.com/golangci/golangci-lint/blob/master/go.mod#L73).
- This corresponds to the version from [August 2nd, 2020](https://github.com/mvdan/gofumpt/commits/master).
- This version is old, and does not have the latest features.
- [According to the author of gofumpt](https://github.com/mvdan/gofumpt/issues/96#issuecomment-735469284), he is not responsible for updating golangci-lint.

Who is responsible for updating golangci-lint? And can we get this updated to latest?

Thanks for your time.

**Comment by ldez** [comment]
Hello,

> Who is responsible for updating golangci-lint? 

- for the dependencies that use tags and version the [dependabot](https://dependabot.com/) handles the update.
- for the other dependencies, the update must be done manually. golangci-lint is an open-source project, everybody can update a dependency by opening a PR.

I created a PR (#1548) to update the lib but I'm not responsible for the update of this dependency.

**Comment by Zamiell** [comment]
Excellent, thank for the quick reply and PR.
