### ISSUE TITLE
Somehow misleading documentation on golangci-lint run command

### ISSUE THREAD

**Issue by alemoi** [golangci/golangci-lint#1550]
Thank you for creating the issue!

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.32.2 built from 52d26a3 on 2020-11-03T01:15:38Z
```

</details>

<details><summary>Output when running `golangci-lint` locally without parameters</summary>
Smart, fast linters runner. Run it in cloud for every GitHub pull request on https://golangci.com

Usage:
  golangci-lint [flags]
  golangci-lint [command]

Available Commands:
  cache       Cache control and information
  completion  Output completion script
  config      Config
  help        Help
  linters     List current linters configuration
  run         Run this tool in cloud on every github pull request in https://golangci.com for free (public repos)
  version     Version

Flags:
      --color string              Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
  -j, --concurrency int           Concurrency (default NumCPU) (default 8)
      --cpu-profile-path string   Path to CPU profile output file
  -h, --help                      help for golangci-lint
      --mem-profile-path string   Path to memory profile output file
      --trace-path string         Path to trace output file
  -v, --verbose                   verbose output
      --version                   Print version

Use "golangci-lint [command] --help" for more information about a command.
</details>

For the above, I suppose the line about **run** command is somehow misleading:
```
run  Run this tool in cloud on every github pull request in https://golangci.com for free (public repos)
```
it could be partially understood that your are sending local project code to cloud, where its analyzed :smiley: 
You don't do that, right? :smile: 

If not, then you can maybe have it assembled from documentation, e.g.: https://golangci-lint.run/usage/quick-start/

Thanks for the great work you are doing! :smile_cat:

**Comment by iwankgb** [comment]
It used to be a cloud offering https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e.
