### ISSUE TITLE
 nolintlint: too many whitespaces removed after autofix 

### ISSUE THREAD

**Issue by ldez** [golangci/golangci-lint#1580]
Related to https://github.com/golangci/golangci-lint/pull/1573

The fix removes all whitespaces, the choice to remove all the whitespaces, in this case, seems not right.

---

before the fix:
```go
// wantedErrors parses expected errors from comments in a file.
// nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

after the fix:
```go
// wantedErrors parses expected errors from comments in a file.
// nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

OK

---

before the fix:
```go
// wantedErrors parses expected errors from comments in a file.
//    nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

after the fix:
```go
// wantedErrors parses expected errors from comments in a file.
//nolint:nakedret
func wantedErrors(file, short string) (errs []wantedError) {
```

KO

**Comment by ashanbrown** [comment]
I'm not completely sure it is possible to determine the user's intent in this case.  We don't know whether the expected coding style is to use machine-readable directives or not (unless `allow-leading-whitespace` is explicitly disabled in the config for `nolintlint`).  One option might be to have `nolintlint` simply not try to fix this case unless `allow-leading-whitespace` is disabled and simply defer to the user on how to fix it.  Does that sound reasonable?

**Comment by ldez** [comment]
I think that something like that can be possible:

`allow-leading-whitespace`:
- `true`: just keep only one whitespace
- `false`: drop the whitespace
