### ISSUE TITLE
Semantic versioning with v1.33.1

### ISSUE THREAD

**Issue by jerome-laforge** [golangci/golangci-lint#1586]
According to [semantic versioning ](https://semver.org/), on patch version we don't expect that added new linter.
This is not the case with [v1.33.1](https://github.com/golangci/golangci-lint/releases/tag/v1.33.1)

In our CI, we always take the latest from Minor version (here v1.33 with `golangci/golangci-lint:v1.33`) because we want to get all fix on current linter.
By the way, we enable all linter and exclude those we don't want in order to easily test the new added linter and fix the code or exclude the new added linter according our policy.

So the result here was an unexpected break of our CI.

Here, it will be more compliance with semantic versioning to tag this version as `v1.34.0`.

Thanks for your jobs

**Comment by ldez** [comment]
Hello,

there was a communication problem during the creation of the release, we are correcting the problem.

**Comment by ldez** [comment]
We will release a v1.33.2 based on v1.33.0 then we will release a v1.34.0 based on the master branch.

**Comment by jerome-laforge** [comment]
great!
when v1.33.2 is released, I will check and close this issue if all is ok.

**Comment by ldez** [comment]
The v1.33.2 has been published

**Comment by jerome-laforge** [comment]
With v1.33.2, it works like a charm.

Many thx for your support.
