### ISSUE TITLE
Misspell not detecting words

### ISSUE THREAD

**Issue by jpreese** [golangci/golangci-lint#1597]
I have tried using the `misspell` linter in golangci-lint (v1.34.1) as well as just a standalone binary from the [misspell repo](https://github.com/golangci/misspell) and have not been able to get it to detect any misspellings.

Consider this example:

**foo.go**
```golang
package main

import "fmt"

func main() {
	// Prints somethng that says foo
	fmt.Print("foo")
}
```

```console
go get -u github.com/client9/misspell/cmd/misspell
```

```console
$ misspell foo.go
```

Does not return any results. This is the same behavior I'm seeing when adding golangci-lint into the mix as well.

**Comment by ldez** [comment]
Hello,

I tried with:
```go
	// comment with incorrect spelling: occured
	// comment with incorrect spelling: langauge
	// comment with incorrect spelling: something
```

```console
$ golangci-lint run
pkg/golinters/unused.go:20:38: `occured` is a misspelling of `occurred` (misspell)
        // comment with incorrect spelling: occured
                                            ^
pkg/golinters/unused.go:21:38: `langauge` is a misspelling of `language` (misspell)
        // comment with incorrect spelling: langauge
                                            ^
```

misspell seems to use a hard-coded dictionary to detect errors:
- https://github.com/golangci/misspell#where-do-the-word-lists-come-from
- https://github.com/golangci/misspell/blob/master/words.go

**Comment by jpreese** [comment]
Thanks for the response, that makes sense! It'll only find _certain_ misspellings, not a dictionary check.
