### ISSUE TITLE
add default config for forbidigo in .golangci.example.yml

### ISSUE THREAD

**Issue by jerome-laforge** [golangci/golangci-lint#1598]
With v1.34.1, forbidigo searches some forbidden patterns.
It isn't easy to know which patterns are forbidden and the [.golangci.example.yml ](https://github.com/golangci/golangci-lint/blob/b3491fd86a26d71b89df84457a72ddf3e348faca/.golangci.example.yml#L400) doesn't show us the actual used default configuration.
In default configuration the `fmt.Print.*` is forbidden but it seems that `^fmt\.Print(|f|ln)$` pattern is actual used. As when I run v1.34.1, I have this error:
```
use of `fmt.Print` forbidden by pattern `^fmt\.Print(|f|ln)$` (forbidigo)
```

Is it possible to list the default configuration used by golangci-lint (instead of recommended configuration by forbidigo itself)?

**Comment by ldez** [comment]
Hello,

the default values are in the `forbidigo` repository:

https://github.com/ashanbrown/forbidigo/blob/633cfeeae6fdd209d2c84e64ed27db9c99c2770f/forbidigo/forbidigo.go#L44-L46

I recommend opening an issue on this repository

**Comment by ldez** [comment]
Hello,

the default values are in the `forbidigo` repository:

https://github.com/ashanbrown/forbidigo/blob/633cfeeae6fdd209d2c84e64ed27db9c99c2770f/forbidigo/forbidigo.go#L44-L46

**Comment by ldez** [comment]
FYI  .golangci.example.yml doesn't provide the default configuration but just an example.

**Comment by jerome-laforge** [comment]
Thx, it is clear now.
