### ISSUE TITLE
spew.Dump in default configuration for forbidigo

### ISSUE THREAD

**Issue by jerome-laforge** [golangci/golangci-lint#1599]
Could you add [spew.Dump](https://pkg.go.dev/github.com/davecgh/go-spew/spew#Dump) as forbidden pattern in default configuration of golangci-lint. 

From godoc overview, [spew](https://pkg.go.dev/github.com/davecgh/go-spew/spew#pkg-overview) is for debugging:
```
Package spew implements a deep pretty printer for Go data structures to aid in debugging.
```

So from my point of view, it is quite similar to `fmt.Print` (that is already added in the default configuration).

I know that it is possible to add it in configuration of golangci-lint by myself but as this issue #1598 shows it is not easy to know what is the default configuration.

For example, if I set this configuration , I can miss the default configuration (in this example, I miss `^fmt\.Print(|f|ln)$` but I can also miss others unknown configurations)

```yaml
  forbidigo:
    # Forbid the following identifiers
    forbid:
      - ^spew\.Dump$
```

**Comment by ldez** [comment]
Hello,

the default values are in the `forbidigo` repository:

https://github.com/ashanbrown/forbidigo/blob/633cfeeae6fdd209d2c84e64ed27db9c99c2770f/forbidigo/forbidigo.go#L44-L46

I recommend opening an issue on this repository

**Comment by jerome-laforge** [comment]
thx @ldez, this [comment](https://github.com/ashanbrown/forbidigo/issues/2#issuecomment-752698045) misleads me.
I will reopen this issue with this information.

Thx again for your support.
