### ISSUE TITLE
Lint all files regardless of build tags

### ISSUE THREAD

**Issue by silverwind** [golangci/golangci-lint#1646]
**Is your feature request related to a problem? Please describe.**
On projects with many different build tags, it's often necessary to run golangci-lint multiple times to cover all `--build-tags` to get all files linted which leads to very long lint times primarily caused by the same files linted multiple times.

**Describe the solution you'd like**
A option like `--all-tags` which would ignore any tags present in a file and lint it regardless. Maybe used in combination with a explicit list of files and folders given as an argument.

**Describe alternatives you've considered**
Don't think there are any.

**Additional context**
Assuming golangci-lint does only static analysis, it should be possible to just ignore build tags and lint all files.

**Comment by padamstx** [comment]
In some of my Go projects, I'll use various build tags for tests like "fast", "slow", "<feature-name>", "<component-name>", etc., but I typically also add "all" wherever I use one or more of the other tags (e.g. `// +build all fast`).
That way if i want to run all tests, I just use something like `go test -tags=all`. Perhaps this could be useful in your situation as well.
