### ISSUE TITLE
Add default exclude for shadowing of err/ctx

### ISSUE THREAD

**Issue by sudo-suhas** [golangci/golangci-lint#166]
**Version of golangci-lint:** e17b9543

**Go environment:**
<details>
<summary><code>go version && go env</code></summary>

```
go version go1.10.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/suhaskaranth/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/suhaskaranth/installs/go-tools"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692454894=/tmp/go-build   -gno-record-gcc-switches"
```

</details>

<br>

It is considered idiomatic in Go to use the variable name `err` for error which could be returned from function invocations in a block of code which could also have shadowing like this:

```go
err := funcA()
if err != nil {
	// ...
}

val, err := funcB()
if err != nil {
	// ...
}

```

Along the same lines, derived contexts are also named `ctx` and shadowing is common:
```go
ctx, cancel := context.WithCancel(context.Background())
defer cancel()

{
	ctx, cancel := context.WithCancel(ctx)

	db, err := mysql.NewClient(ctx)
	if err != nil {
		// ...
	}

	db.DoSomething()

	cancel() // close the DB conn of our imaginary pkg
}
```

This is not an issue if the default settings are used. It only shows up if `check-shadowing` is enabled for `govet`. So how about adding a default exclusion for this with `declaration of "(err|ctx)" shadows declaration at`?

**Comment by jirfag** [comment]
hi, thank you for the issue!
why do you enable `check-shadowing`? I got some cases where `err` shadowing was a bug, I need to think about it

**Comment by sudo-suhas** [comment]
Not that I have any specific examples now but I have had instances where a bug was hidden behind shadowing.

**Comment by jirfag** [comment]
in my opinion you should choose: fully disable shadowing checking or don't ignore err/ctx shadowing

**Comment by piersy** [comment]
@sudo-suhas You can achieve this with the `--exclude` flag, which exclude certain results based on a regex matching the result text. So for instance to remove notifications about err shadowing you could use.

```
golangci-lint run --config ci.yml --exclude "shadow: declaration of .err. shadows declaration"
```

I used `.err.` here because I had difficulty getting my shell to represent nested double quotes in the exclude declaration.

I'm sure you could do the same for `ctx` variables as well.

**Comment by sudo-suhas** [comment]
Yes @piersy I had used the config file to achieve this:
```toml
[issues]
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude=[
    'declaration of "(err|ctx)" shadows declaration at',
  ]

```

**Comment by piersy** [comment]
@sudo-suhas Thanks for that snippet, its an improvement on using the flag since we can represent the surrounding double quotes easily.

**Comment by Garagator3000** [comment]
```yaml
issues:

  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]
```
relevant in 2022

**Comment by fresonn** [comment]
@Garagator3000 thanks a lot!

**Comment by s3rj1k** [comment]
@jirfag Please reconsider your decision, forcing usage of exclude rule seems sub-optimal solution as types data are lost.

**Comment by ldez** [comment]
The shadowing of errors or context can be a real problem, and it's usually easy to avoid shadowing them.

Quick example:

```go
package main

import (
	"context"
	"fmt"
)

type contextKey string

const (
	importantKey contextKey = "important"
	secretKey    contextKey = "secret"
)

func main() {
	ctx, msg := foo()
	if msg == "a" {
		ctx := context.WithValue(ctx, importantKey, "important")
		noop(ctx)
	}

	fmt.Println(ctx.Value(secretKey)) // got "secret", expected "secret"

	// BUG: importantKey doesn't exist here because of the shadowing
	fmt.Println(ctx.Value(importantKey)) // got <nil>, expected "important"
}

func foo() (context.Context, string) {
	return context.WithValue(context.Background(), secretKey, "secret"), "a"
}

func noop(_ context.Context) {}
```

https://go.dev/play/p/-BA0n1B2Cpn

So enabling `check-shadowing` and excluding the shadowing of errors or context is not a good practice, we can neither add this as default nor recommend it.

FYI, Denis will not answer because he is no longer active on the project.

**Comment by s3rj1k** [comment]
@ldez I fully agree that this can be a problem but for huge codebases it is nearly impossible to fix all the errors, hence a need to somehow configure excludes.

I am fine with this being disabled by default still having the ability to enable this filter in config.

**Comment by ldez** [comment]
I'm also working on large code bases, and if I cannot apply to a rule I exclude it from the project (with a comment to explain why) but we cannot define that as default exclusion inside golangci-lint.
Your constraints and your project history cannot drive the default exclusions inside golangci-lint, I'm sorry.

In the future, I think we will change the current exclusions system to not exclude rules by default.
And it's good news for you because we will be able to add "common exclusions".
Maybe if we think that your problem can be a "common exclusion" you will be able to exclude the problem with a simple code (ex: `EXC12345`)

https://golangci-lint.run/usage/false-positives/#default-exclusions

**Comment by s3rj1k** [comment]
@ldez I fail to follow how adding a configuration `bool` flag that enables skipping `err` shadowing that is disabled by default is forcing "default exclusions inside golangci-lint"

**Comment by ldez** [comment]
Maybe I missed something but skipping `err` shadowing is not a flag, you have to add an exclusion rule.

This issue is about adding this rule inside default exclusions.

https://github.com/golangci/golangci-lint/issues/166#issuecomment-1311642014

**Comment by s3rj1k** [comment]
Yea, this is exactly what I want to avoid if possible, writing text-based exclusion lists.
I was assuming that I was possible to make this configurable via config in `govet` so that linter would check if in fact that `err` is of type error and skip the warning.

**Comment by ldez** [comment]
All the options for govet analyzers are available in the configuration: https://golangci-lint.run/usage/linters/#govet

`check-shadowing` is just a shortcut for the `shadow` analyzer.

The 2 followings snippets do the exact same thing (enabling the `shadow` analyzer):
```yml
linters-settings:
  govet:
    enable:
      - shadow
```

```yml
linters-settings:
  govet:
    check-shadowing: true
```


There is no existing option to exclude `err` or `ctx` shadowing.

The only option is `strict` which is `false` by default.

```
linters-settings:
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true
```

https://github.com/golang/tools/blob/dd1e2f66b2420ea0ea114b7e1f9280612604bb57/go/analysis/passes/shadow/shadow.go#L57

**Comment by s3rj1k** [comment]
So assuming someone forks/extracts `govet` shadow port into separate code-base, add the ability to skip `err` inthere and than donates this code to `golangci-lint` project, is this possible?

**Comment by ldez** [comment]
FYI `govet` is maintained by the Go team.

IMO, one of the main goals of the `shadow` analyzer is to find errors shadowing.
So they will never add an option for skipping errors shadowing.

**Comment by s3rj1k** [comment]
I was thinking of just doing a separate codebase, no Go team interaction, only single rule from `govet`.

`golangci` includes `revive` and it has some similar linters, so I guess that it shouldn't be a problem to add another similar linter.

**Comment by ldez** [comment]
`govet` is a part of the core of golangci-lint, so we will never use a fork especially if it is to have an option with which I do not agree.

**Comment by s3rj1k** [comment]
I fail to see how this would be a fork :)

**Comment by s3rj1k** [comment]
Ok, not related to the issue but how about including some-kind of `Interpreter` into `golangci`, something like `[yaegi](https://github.com/traefik/yaegi)`?

Current requirements for distributing custom private linters are harsh, the need to recompile everything.

**Comment by s3rj1k** [comment]
https://github.com/golangci/golangci-lint/issues/3669

**Comment by ldez** [comment]
I will summarize the discussion for user readers.

The current way to manage your expectation is to write your own exclusion rule.

```yml
issues:

  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]
```

[In the future](https://github.com/golangci/golangci-lint/issues/166#issuecomment-1464642545), some changes will maybe help you with that but for now, it's the only possible thing.
