### ISSUE TITLE
Path for gocritic ruleguard rules depends on the current working directory

### ISSUE THREAD

**Issue by oschwald** [golangci/golangci-lint#1662]
I am using [`ruleguard`](https://github.com/quasilyte/go-ruleguard) via the `gocritic` linter. As part of using this linter, you must set the path to your rules:

https://github.com/golangci/golangci-lint/blob/750309d1574e9a4afc32346364f9e4ae36955692/.golangci.example.yml#L178-L180

Unfortunately, if you currently set a relative path, it will be relative to the directory that you run `golangci-lint` from. This means that you must always run `golangci-lint` from the same directory or use an absolute path, which may not work across different environments.

https://github.com/golangci/golangci-lint/pull/1572 dealt with a similar issue for custom plugins. It fixed the issue by adding an explicit check to see if the path was relative or absolute.

I looked into doing this for the `ruleguard` settings, but it appears that the [settings code](https://github.com/golangci/golangci-lint/blob/750309d1574e9a4afc32346364f9e4ae36955692/pkg/golinters/gocritic.go#L78-L109) is very generic and doesn't know anything in particular. Would a PR that added a special case to that code for `ruleguard` be accepted? I would understand if it would be considered in bad taste.

A more general alternative might be if `golangci-criitc` changed the working directory to the configuration dir directory before running the linters. However, I suspect this would cause other problems.

**Comment by sebastien-rosset** [comment]
I "solved" this by using a mustache template for the golangci.yml file. Before I invoke golangci-lint, I have a `golangci.mustache` file and use mustache to perform variable substitution and generate a golangci.ym.

```yaml
    settings:
      ruleguard:
        rules: "{{MY_ENV}}/gorules/myrules.go"
```

Though it seems it would be possible to support variable substitution directly in golangci
