### ISSUE TITLE
way to identify newly available linters

### ISSUE THREAD

**Issue by wyardley** [golangci/golangci-lint#1686]
**Is your feature request related to a problem? Please describe.**
Just curious - given the deprecation of `enable-all` (e.g., https://github.com/golangci/golangci-lint/issues/542#issuecomment-541889352), is there any way to find out what linters are newly available, shy of comparing the list of enabled ones to the full list on the site?

It would be extremely useful if there were an option to print available (but not enabled) linters. Also, it's great that golangci-lint supports a lot of different types of linters, but sometimes it could be more clear which ones are recommended for typical use cases, so some kind of opinionated preset would also be nice.

IMO, the recommendation it seems is being made (to explicitly list all linters by name one by one in each project's config) is a bit of a hassle / maintenance headache.

**Describe the solution you'd like**
A couple options - one would be a command line flag to print all available, but not enabled linters based on the current version of the tool and the current project's config.

Optionally, some other way to restore the previous behavior of allowing one to move to a more "disable explicit" mode and / or some kind of "recommended" config that would continue to add the most useful of new linters automagically.

**Describe alternatives you've considered**
Some kind of way to define an org-wide preset (similar to tools like, say, `eslint` for node) might be interesting.

**Additional context**

**Comment by ldez** [comment]
Currently, you can find this information in the following pages:
- https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md
- https://github.com/golangci/golangci-lint/releases

**Comment by wyardley** [comment]
@idez Hi -- yes, I know that
in practical terms though, it's not very efficient / simple to go to that page, and try to manually compare it against a yaml file with a list of 30-40+ linters. People also tend to consider these types of configs to be "set it and forget it", so it also makes it very easy for (useful) new linters to come out, but for people to not know about them / enable them.

**Comment by ldez** [comment]
Personally, I like `enable-all`, I'm not convinced by the deprecation proposal.

I think that an enhancement can be made in the linters manager by adding a `Since/IntroducedIn` field in the `Config` structure.

https://github.com/golangci/golangci-lint/blob/60455b502b0b03f83f18c161a6da4f8f4f018df7/pkg/lint/lintersdb/manager.go#L109-L359

https://github.com/golangci/golangci-lint/blob/60455b502b0b03f83f18c161a6da4f8f4f018df7/pkg/lint/lintersdb/manager.go#L109-L359

and add a new flag or subcommand to the `golangci-lint linters` command to display that information.

**Comment by wyardley** [comment]
> Personally, I like enable-all, I'm not convinced by the deprecation proposal.

Me too! I don't have the reference handy, but I believe it's been made pretty official and is documented somewhere on the main site, but let me know if I'm wrong on that!

> I think that an enhancement can be made in the linters manager by adding a Since/IntroducedIn field in the Config structure.
> and add a new flag or subcommand to the golangci-lint linters command to display that information.

Like this idea!

**Comment by Zamiell** [comment]
For what its worth, I also use `enable-all`.
This way, when I upgrade my version of golang-ci, I automatically get the benefits of any new linters.
If the new linters are noise, I can then explicitly add them to the `disable` array my `.golangci.yml` file.
This workflow is very nice, because I notably don't have to do any research on the main page to find what the linters are, as wyardley rightly points out above.

Is there any links to why `enable-all` is being deprecated?

**Comment by wyardley** [comment]
> Is there any links to why enable-all is being deprecated?

https://golangci-lint.run/usage/configuration/
has a comment:
>   # please, do not use `enable-all`: it's deprecated and will be removed soon.
>  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint

which comes from
https://github.com/golangci/golangci-lint/blob/122193999a3f465160814551ec51542d6f8a0f14/.golangci.yml#L66-L67
added in https://github.com/golangci/golangci-lint/pull/803

**Comment by ashanbrown** [comment]
May it would be worth adding an enable-new command that adds any unmentioned linters to the config file.  While I liked using enable-all, I can see why it would be annoying for someone just trying to use a new version of golangci-lint that supports a new go version, for example.

**Comment by bombsimon** [comment]
I also use `enable-all`. If you manually upgrade and know when a new version is installed you could also just check the [release page](https://github.com/golangci/golangci-lint/releases) which will list all added linters in each release.

**Comment by ldez** [comment]
I added a `Since` field on all linters (#1854) so now you can see the version (and also the deprecation) in the documentation:

https://golangci-lint.run/usage/linters/

I have an idea for a command line approach but I need to think more about it.

**Comment by Zamiell** [comment]
Nice work, thanks.

**Comment by ldez** [comment]
I would like to (re)open the debate about the deprecation of `enable-all` so I opened #1888.

So please describe your use-cases in this new issue.
