### ISSUE TITLE
Configurable cache directory

### ISSUE THREAD

**Issue by calvinbui** [golangci/golangci-lint#1690]
**Is your feature request related to a problem? Please describe.**
A configuration option to set the caching directory. By default it goes to `~/.cache/golangci-lint` on Linux and `~/Library/Caches/golangci-lint` on Mac

**Describe the solution you'd like**
The caching directory option via the run command or config file

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlekSi** [comment]
Currently, it is possible to configure the cache directory via `GOLANGCI_LINT_CACHE` environment variable. But it is not documented (https://github.com/golangci/golangci-lint/issues/734), and also not a flag or config file field requested by OP.

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/blob/bcdfb7f6b10b090f66228e263db4ae8c7a7132c9/internal/cache/default.go#L60-L87

Introduced in #699

**Comment by AlekSi** [comment]
Not sure why close it if not a single point from https://github.com/golangci/golangci-lint/issues/1690#issuecomment-807465355 is addressed.

**Comment by ldez** [comment]
Because I reopened #734 and created a PR  #1871

**Comment by AlekSi** [comment]
Sorry, I don't follow.

> Describe the solution you'd like
> The caching directory option via the run command or config file

The environment variable is not a run command flag or config file field.

If you don't think flag/field is a good idea for some reason, explicitly saying so would send a much clear signal than closing an issue with a comment that looks like the issue wasn't really read beyond the title.
