### ISSUE TITLE
not enough arguments in call to govet.Analyze

### ISSUE THREAD

**Issue by KaiserKarel** [golangci/golangci-lint#170]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
1.9.1
2. Go environment: `go version && go env`
```
go version go1.10 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/karel/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/karel/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build464087297=/tmp/go-build -gno-record-gcc-switches"
```

It seems I cannot install golangci-lint run because of revision 5750cffb6440cff7d5aff3382eb525f0a77b9b5c in govet. 

```
vendor/github.com/golangci/golangci-lint/pkg/golinters/govet.go:84:34: not enough arguments in call to govet.Analyze
        have ([]*ast.File, *token.FileSet, nil, bool)
        want ([]*ast.File, *token.FileSet, *loader.PackageInfo, bool, govet.getASTFileContentsFunc)
vendor/github.com/golangci/golangci-lint/pkg/golinters/govet.go:240:34: not enough arguments in call to govet.Analyze
        have ([]*ast.File, *token.FileSet, *loader.PackageInfo, bool)
        want ([]*ast.File, *token.FileSet, *loader.PackageInfo, bool, govet.getASTFileContentsFunc)
 ```

I vendor golangci-lint using dep:

gopkg.toml
```
[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "1.9.1"
```

**Comment by jirfag** [comment]
hi!
1. how do you install `golangci-lint`?
2. do you run `dep ensure` or do something with `vendor` dir in `golangci-lint` repo?

**Comment by jirfag** [comment]
reverted govet code, it should help, but it's interesting how did you use `golangci-lint`: with the proper use it shouldn't be the problem

**Comment by KaiserKarel** [comment]
I install it by using `dep ensure -add github.com/golangci/golangci-lint/cmd/golangci-lint`, adding 
required = ["github.com/golangci/golangci-lint/cmd/golangci-lint"] to my gopkg.toml and pinning it to a specific version.

Might have to do with dep 0.5.0 which came out recently.

**Comment by jirfag** [comment]
oh, don't install `golangci-lint` by this way: it's now recommended and can be easily broken. Recommended way is [this](https://github.com/golangci/golangci-lint#ci-installation).

**Comment by KaiserKarel** [comment]
Thanks for the advice and the quick response!
