### ISSUE TITLE
Generate linter warning for missing pointer deference

### ISSUE THREAD

**Issue by tamalsaha** [golangci/golangci-lint#1724]
**Is your feature request related to a problem? Please describe.**
What linter is available that can generate warning for the following program in Go?

```
package main

import (
	"fmt"
)

func main() {
	i := 5
	p := &i
	fmt.Printf("%d", p) // How to generate linter warning?
}
```

Here my intent is to print the value of `i` not the address of pointer `p`. I want to use this linter to catch all the places pointer dereference is missing. Does https://github.com/golangci/golangci-lint support this? Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ldez** [comment]
golangci-lint is a wrapper for many independent linters. So, you need to find or implement a linter with a feature you requested and then we can integrate that linter
