### ISSUE TITLE
[FEATURE REQUEST] enforce member sorting order

### ISSUE THREAD

**Issue by scrouthtv** [golangci/golangci-lint#1771]
I'd like to see a feature that enforces the sorting of members of a Go file. It's frustrating to read a source file and not being able to understand which type / variable / ... is what.

I'd like to see a solution where a sane, pre-defined member sorting order is applied, something like this:
1. header
2. private constants
3. public constants
4. private variables
5. public variables
6. private static methods
7. public static methods
8. private "constructors" (methods that begin with new)
9. private member methods
10. public "constructors" (methods that begin with New)
11. public member methods

Every group should be sorted alphabetically by their name, member methods should be grouped in their types.
In the end, I'd like the sorting order to be comparable to how pkg.go.dev lists the contents.

I know that most of the time, Go files don't even have five out of these categories, however, a consistent order even makes sense in this case.

Let me know what you think!

**Comment by SVilgelm** [comment]
golangci-lint is a wrapper for may independent linters. So, you need to find or implement a linter with a feature you requested and then we can integrate that linter
