### ISSUE TITLE
MAC M1 Silicon shit doesn't work with this....

### ISSUE THREAD

**Issue by AndreiD** [golangci/golangci-lint#1776]
your shit aint' working with the m1 mac....

it would be amazing if you smart guys fix it...

Tim Cook will be forever grateful

**Comment by theckman** [comment]
Your report isn't super helpful, especially to those without M1 hardware. It may be helpful to indicate what's not working, and to indicate if you've built using the latest Go version.

**Comment by bombsimon** [comment]
Seems to be working fine, using the [pre-built binary](https://github.com/golangci/golangci-lint/releases/tag/v1.37.1)

```sh
% uname -sm
Darwin arm64

% golangci-lint --version
golangci-lint has version 1.37.1 built from b39dbcd6 on 2021-02-20T11:48:06Z
```

**Comment by ldez** [comment]
A small reminder https://github.com/golangci/golangci-lint/blob/master/CODE_OF_CONDUCT.md

**Comment by AndreiD** [comment]
yes man it lives @bombsimon thank you
