### ISSUE TITLE
Add julz/importas linter

### ISSUE THREAD

**Issue by SVilgelm** [golangci/golangci-lint#1782]
Add a new linter https://github.com/julz/importas

**Comment by SVilgelm** [comment]
This PR should be merged before the integration: https://github.com/julz/importas/pull/1

**Comment by ldez** [comment]
FYI with go1.16 and our test system, if you create a test file with external imports (not in the main `go.mod`) you will have an issue.
I meet the same problem during the update to go1.16 and `sqlclosecheck`, I had to remove the imports.
https://github.com/golangci/golangci-lint/pull/1740/commits/4d6aa3ce731a378aa49b3ef0e66dadc56efc85f7

**Comment by SVilgelm** [comment]
we can import system modules, like `import fff "fmt"`
