### ISSUE TITLE
We're not seeing version v1.38 being available to golangci/golangci-lint-action

### ISSUE THREAD

**Issue by magnetikonline** [golangci/golangci-lint#1813]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>GitHub workflow with the following:</summary>

```
 - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
```

</details>

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# golangci-lint has version 1.38.0 built from 507703b4 on 2021-03-03T13:53:01Z
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```console
Error: Failed to run: Error: requested golangci-lint version 'v1.38' doesn't exist, Error: requested golangci-lint version 'v1.38' doesn't exist
    at Object.<anonymous> (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2351:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2230:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: requested golangci-lint version 'v1.38' doesn't exist
```

</details>

<details><summary>Code example or link to a public repository</summary>

```go
// add your code here
```

</details>

**Comment by SVilgelm** [comment]
@magnetikonline We are trying to automate the post release actions and the last run is failed. I want to wait one more day a response from @jirfag . If no response, then I will update the repo manually.

Here is PR: https://github.com/golangci/golangci-lint/pull/1460
Action: https://github.com/golangci/golangci-lint/actions/workflows/post-release.yml

**Comment by magnetikonline** [comment]
Nice one @SVilgelm - seems it failed building the contributors list.

**Comment by SVilgelm** [comment]
yep, the bot's user should be added to the `golangci/team`

**Comment by SVilgelm** [comment]
@jirfag @ernado  please add the @golangci-releaser user to the team, we need it for the post-release automation

**Comment by ernado** [comment]
ACK, will do

**Comment by ernado** [comment]
What permissions we need to provide to @golangci-releaser?

**Comment by ldez** [comment]
just add @golangci-releaser into https://github.com/orgs/golangci/teams/team

**Comment by SVilgelm** [comment]
@ernado @jirfag It's a blocker now. Could you please add the @golangci-releaser user to the team https://github.com/orgs/golangci/teams/team/members ?

**Comment by magnetikonline** [comment]
We're still broken? If there anyone else that can add https://github.com/golangci-releaser into the team so we can kick the build along again?

Thanks!

**Comment by ernado** [comment]
I've PM-ed @jirfag

**Comment by ldez** [comment]
I think it's time to create a PR, we retry the automatic system with the next release if the rights problem is solved.

I created a PR: #1827

**Comment by ernado** [comment]
@golangci-releaser was added to org.

**Comment by ldez** [comment]
Thank you @ernado and @jirfag 

We will test that with the next release :+1:

**Comment by SVilgelm** [comment]
@ldez I re-run the failed action: https://github.com/golangci/golangci-lint/runs/2068816507?check_suite_focus=true
the PR was created successfully: https://github.com/golangci/golangci-lint/pull/1828

so we can assume that it works

**Comment by magnetikonline** [comment]
Thanks @SVilgelm and @ernado - we're back in action! 🎉 

Appreciate all your help on this one 👍
