### ISSUE TITLE
Support identypo

### ISSUE THREAD

**Issue by sagikazarmark** [golangci/golangci-lint#182]
Currently the misspell spell checker only checks go code (using [ReplaceGo](https://github.com/client9/misspell/blob/f10ccd0965008e8b712f379c2e4068a24748172e/replace.go#L142))

Unfortunately it doesn't provide feature parity with simply using misspell.

I suggest either adding a config option to use `Replace` instead, or just use `Replace` so that it provides the same features as just using `misspell`.

Happy to provide a PR once a solution is decided.

Please include the following information:
1. Version of golangci-lint: 1.9.3
2. Go environment: go version go1.10.3 darwin/amd64

**Comment by sagikazarmark** [comment]
Ping

**Comment by sagikazarmark** [comment]
Ping :)

**Comment by alexkohler** [comment]
@sagikazarmark if you are looking for a workaround, I've wrote a [tool](https://github.com/alexkohler/identypo) that parses the Go AST and looks for typos in constants, variables, functions, etc. It calls misspell's `Replace`: https://github.com/alexkohler/identypo/blob/master/identifier_typo.go#L97

**Comment by jirfag** [comment]
@sagikazarmark would you like to search typos in constants and func names or to search types in txt,md and other types of files?

**Comment by sagikazarmark** [comment]
As the comment says: 

```
// ReplaceGo is a specialized routine for correcting Golang source
// files.  Currently only checks comments, not identifiers for
// spelling.
```

So yeah, I'd like to search typos in identifiers and I think it'd be nice if golangci supported it.

**Comment by sagikazarmark** [comment]
Bump

**Comment by SVilgelm** [comment]
hmmmm, as I can see, the behavior was changed in the release `v1.17.0`, it uses `r.Replace(string(fileContent))` and was added in the 3d78f64b commit. 
So I'm closing it as fixed
