### ISSUE TITLE
--new doesn't ignore gitignored files

### ISSUE THREAD

**Issue by rski** [golangci/golangci-lint#183]
This is an issue with revgrep, but since golangci-lint uses its own fork of revgrep that has no issue tracker and this shows up in golangci-lint, I thought I'd open an issue here.

revgrep does

`git ls-files -o`

which doesn't ignore untracked files.

This means that if any gitignored files exist, --new runs against them instead of HEAD~1, even if git status comes up clean. This completely took me by surprise.

Here is a small repro of the issue: https://github.com/rski/gcl-new-gitignore-issue

I'll submit a PR for revgrep later today to fix this.

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
1f3d5b2e42aa185800eb22d4ae0a179cb7e86886
2. Go environment: `go version && go env`
$ go version && go env
go version go1.10.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rski/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rski/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build684912009=/tmp/go-build -gno-record-gcc-switches"

3. Verbose output of running: `golangci-lint run -v`

**Comment by jirfag** [comment]
hi!
we would like to not use forked revtrep, but our [pull request](https://github.com/bradleyfalzon/revgrep/pull/13) isn't merged yet.

Please, make a fix in revgrep (with tests) and I will merge it
