### ISSUE TITLE
Consider making -v print which files --new and friends decided to lint

### ISSUE THREAD

**Issue by rski** [golangci/golangci-lint#184]
That would have helped me a lot with debugging, it will probably be useful to have for the future as well.

**Comment by jirfag** [comment]
Hi!
We lint all files (otherwise compilation error), but show only issues from git diff. Can't you do just `git diff --stat REV`?

**Comment by rski** [comment]
My point is that any git commands are not necessarily what revgrep sees,  eg `git diff --stat rev` would have given no hints as to what the original issue I was seen was, because revgrep was looking at gitignored files. That is why logging verbosely which files revgrep sees is helpful.
