### ISSUE TITLE
JSON Schema on json.schemastore.org is outdated 

### ISSUE THREAD

**Issue by kavu** [golangci/golangci-lint#1846]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).
- [ ] ~Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)~

<details><summary>Description of the problem</summary>

As golangci-lint now support `fieldalignment` in `govet` linter, the only way to disable this specific (while enabling all others) check is just to disable is a specific `govet` setting, e.g.:

```
linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
```

But this value is not present in schema https://json.schemastore.org/golangci-lint. So, we can get an error (my VS Code setup is somehow aware of schema):

![image](https://user-images.githubusercontent.com/1994/111201381-c125b680-85d3-11eb-810b-c6a535203e18.png)

So, I think schema should be updated, but I can't find any mentions of it.

</details>

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version v1.38.0 built from (unknown, mod sum: "h1:hgZsLRzZrjhpp44Ak+fhXNzgrbDF39ETf22a+Jd3fJQ=") on (unknown)
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.16 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/maxim.riveiro/Library/Caches/go-build"
GOENV="/Users/maxim.riveiro/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/maxim.riveiro/GOPATH/pkg/mod"
GOOS="darwin"
GOPATH="/Users/maxim.riveiro/GOPATH"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/maxim.riveiro/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zw/2lmf1b256tq26hj0nhdw7b0m0000gp/T/go-build644894838=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

**Comment by ldez** [comment]
Hello,

currently, we don't maintain the JSON Schema on json.schemastore.org

You can follow https://github.com/golangci/golangci-lint/issues/1453
