### ISSUE TITLE
add jq to dockerfile

### ISSUE THREAD

**Issue by justinrush** [golangci/golangci-lint#1858]
**Is your feature request related to a problem? Please describe.**
When running the tool to generate code quality reports its helpful to be able to tee the output to a file and to some human readable output using jq.

**Describe the solution you'd like**
`RUN apk update && apk add --no-cache jq=1.6-r1`

**Describe alternatives you've considered**
maintain a local fork :(

**Comment by sayboras** [comment]
In my opinion, golangci-lint docker image should be just bare minimum (e.g. base image + golangci-lint binary). So while adding _one more tool_ (like jq) is trivial, it will lead to few implications:

- request to add one more tool
- more responsibilities to maintain versions
- security vulnerabilities

**Comment by justinrush** [comment]
> In my opinion, golangci-lint docker image should be just bare minimum (e.g. base image + golangci-lint binary). So while adding _one more tool_ (like jq) is trivial, it will lead to few implications:
> 
> * request to add one more tool
> * more responsibilities to maintain versions
> * security vulnerabilities

I don't disagree with the sentiment but at the same time using code quality as an output either requires that you run two jobs, one with non-human and output to file, and another to screen... Or create a private image based on the latest, and then keep maintaining that.

If there is some sed/awk magic people are using instead, I'm game, please share. I just don't want to maintain a private image for a pubic tool for something so basic.

**Comment by ldez** [comment]
I agree with @sayboras.

I guess that you are using the json output format, instead of adding `jq` to pipe the output, we can just add another output format like "json for human"

**Comment by ldez** [comment]
could you provide more information about your use case?

**Comment by justinrush** [comment]
this is closed by https://github.com/golangci/golangci-lint/pull/2386
