### ISSUE TITLE
Running golangci-lint --enable-all prints warnings about deprecated linters

### ISSUE THREAD

**Issue by davidnewhall** [golangci/golangci-lint#1878]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>Description of the problem</summary>

Running `golangci-lint run --enable-all` generates warnings for deprecated linters.
This behavior seems to be new in the past few months. 
**Can we make the app not run deprecated linters with `--enable-all`?**
or: **Can we add another flag to run all linters except deprecated linters?**
also: **Can we add these flags to `run --help` output?**

```
GOOS=linux golangci-lint run --enable-all -D nlreturn,exhaustivestruct
235WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
236WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
237WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
```
</details>

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version v1.38.0 built from (unknown, mod sum: "h1:hgZsLRzZrjhpp44Ak+fhXNzgrbDF39ETf22a+Jd3fJQ=") on (unknown)
```

This also happens on `latest` in a CI pipeline.

</details>

<details><summary>Config file</summary>

I've never made a config file for golangci-lint. TIL.

```console
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```

</details>

<details><summary>Go environment</summary>

This is my mac, but again, this happens on a fresh CI build on any OS with Go > 1.14.

```console
$ go version && go env
go version go1.16.2 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/newhalld/Library/Caches/go-build"
GOENV="/Users/newhalld/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/newhalld/Documents/Twitch/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/newhalld/Documents/Twitch/go"
GOPRIVATE="*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cm/7fsxbrdx75vb7_qnjs0tpd7dkhxv7n/T/go-build2935844840=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

<details><summary>Verbose output of running</summary>

Nothing changes. The warnings emit regardless.

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

<details><summary>Code example or link to a public repository</summary>

This happens with any and all code I run it against.

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

It's the expected behavior: all the people that use `enable-all` must disable those linters.

Also `enable-all` is deprecated:

>  please, do not use `enable-all`: it's deprecated and will be removed soon.
>  inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint

https://golangci-lint.run/usage/configuration/

**Comment by davidnewhall** [comment]
That's all very unfortunate. Thank you for your reply.
