### ISSUE TITLE
golint will be deprecated

### ISSUE THREAD

**Issue by sanposhiho** [golangci/golangci-lint#1892]
Sorry if this issue is duplicated

golint is(will be) deprecated.
> This proposal - to freeze and deprecate x/lint - is accepted.
https://github.com/golang/go/issues/38968

**Describe the solution you'd like**

deprecate golint like `interfacer`.
https://github.com/golangci/golangci-lint/pull/1755

**Comment by sanposhiho** [comment]
Can I pick this issue?

**Comment by ldez** [comment]
Please don't deprecate golint for now.

We have to think more about it.

**Comment by ldez** [comment]
The proposal [has been accepted](https://github.com/golang/go/issues/38968#issuecomment-638331245) but no action has been taken on this subject, at least there is nothing on the [golint repository](https://github.com/golang/lint).

I think it can be a good idea before the deprecation to wait for the actions of the Go team.

**Comment by sanposhiho** [comment]
okey 👍

**Comment by sanposhiho** [comment]
Hello
Sorry, I have one thing to discuss, so let me reopen it for a while.

The Golint README uses staticcheck and `go vet` as an example of an alternative tool.
Shouldn't we recommend staticcheck or govet as an alternative instead of revive?


> NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as Staticcheck and go vet should be used instead.

https://github.com/golang/lint

**Comment by ldez** [comment]
The most important information is "There's no drop-in replacement for it".

`go vet` and `staticcheck` are currently not the closest linters to replace `golint`.

`go vet` doesn't contain passes that are comparable to golint, I think they mean that you can implement new passes for `go vet`.

I think that the Go team doesn't really know the Go linters world.

The closest linter to golint is `revive`.

We are not alone with this approach:
- https://github.com/open-telemetry/opentelemetry-collector/pull/3182
- https://github.com/DataDog/datadog-agent/pull/8160/files
