### ISSUE TITLE
Add 'goreduce' Linter

### ISSUE THREAD

**Issue by Dentrax** [golangci/golangci-lint#1902]
https://github.com/mvdan/goreduce

> Reduce a program to its simplest form as long as it produces a compiler error or any output (such as a panic) matching a regular expression.

```golang
func main() {
        a := []int{1, 2, 3}
        if true {
                a = append(a, 4)
        }
        a[1] = -2
        println(a[10])
}
```

```bash
$ goreduce -match 'index out of range' .
```

```golang
func main() {
        a := []int{}
        println(a[0])
}
```

**Comment by ldez** [comment]
Hello,

`goreduce` is not a linter it's a program to simplify code.

I think it's out of the scope of golangci-lint.
