### ISSUE TITLE
unparam linter does not respect `--issues-exit-code=0`

### ISSUE THREAD

**Issue by colinking** [golangci/golangci-lint#1903]
- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>Description of the problem</summary>

I was trying out the `unparam` linter with `golangci-lint` and noticed that [it would `os.Exit(1)`](https://github.com/mvdan/unparam/blob/aac4ce9116a7d389fb9d16019cfbfa13a34be227/main.go#L23) if it encounters any errors. That seems reasonable when used on its own, but when used as a linter in `golangci-lint` inside of VSCode, it's not great since you get an error like this:

![image](https://user-images.githubusercontent.com/2907397/114240490-35424880-994d-11eb-8c1a-df177c5b7ace.png)

Which is normally suppressed by `golangci-lint`'s `--issues-exit-code=0` flag. All other non-default linters that I have tried so far properly respect that flag. 

I considered opening this issue on `unparam`'s GitHub, but this specific behavior seemed more relevant to how golangci-lint embeds unparam, so I opened it here instead.

</details>

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version v1.39.0 built from (unknown, mod sum: "h1:aAUjdBxARwkGLd5PU0vKuym281f2rFOyqh3GB4nXcq8=") on (unknown)
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters:
  enable:
    - unparam
```

</details>

<details><summary>Go environment</summary>

```console
$ go version
go version go1.16.3 darwin/arm64
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# (not relevant -- happy to provide if wrong?)
```

</details>

<details><summary>Code example or link to a public repository</summary>

```go
// happy to create some if useful, but just a repo with an unused param will cause an unparam error
```

</details>

**Comment by ldez** [comment]
Hello,

could you provide the "Verbose output of running" and a code example?

Thank you.

**Comment by ldez** [comment]
Everything works as expected:

```go
// main.go
package main

func unused(a, b uint) uint {
	a++
	return a
}
```

```yml
# .golangci.yml
linters:
  disable-all: true
  enable:
    - unparam
```

```console
$ golangci-lint run --issues-exit-code=0
main.go:3:16: `unused` - `b` is unused (unparam)
func unused(a, b uint) uint {
               ^
$ echo $?
0
```
