### ISSUE TITLE
'Windows_NT' got converted to 'windows_nt' which is not a GOOS value.

### ISSUE THREAD

**Issue by mayocream** [golangci/golangci-lint#1944]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>Go environment</summary>

```console
❯ go version && go env
go version go1.16 windows/amd64
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Mayo\AppData\Local\go-build
set GOENV=C:\Users\Mayo\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Mayo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Mayo\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\ProgramData\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\ProgramData\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Mayo\AppData\Local\Temp\go-build434575085=/tmp/go-build -gno-record-gcc-switches
```

</details>

```bash
❯ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
golangci/golangci-lint crit uname_os_check 'Windows_NT' got converted to 'windows_nt' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
```

Runs on Win10.

**Comment by ldez** [comment]
@mayocream could you edit your issue to follow the issue template? https://raw.githubusercontent.com/golangci/golangci-lint/master/.github/ISSUE_TEMPLATE/bug_report.md

Have you tried to open an issue on https://github.com/client9/shlib as suggested by the log?

> golangci/golangci-lint crit uname_os_check 'Windows_NT' got converted to 'windows_nt' which is not a GOOS value. Please file bug at https://github.com/client9/shlib

**Comment by mayocream** [comment]
https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/install.sh#L194
```bash
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}
```

Output from Windows Terminal.
```bash
❯ uname -s
Windows_NT
```

**Comment by ldez** [comment]
@mayocream can you follow my comment https://github.com/golangci/golangci-lint/issues/1944#issuecomment-829438055 ?
