### ISSUE TITLE
Feature request: fix

### ISSUE THREAD

**Issue by ewgRa** [golangci/golangci-lint#195]
What about introduce "fix" flag, if linter support fixing (like gofmt for example), than fix will be run.

Probably it needs to be done not in parallel, to avoid problems, but it is technical question I think.

**Comment by jirfag** [comment]
Hi!
I know only 2 linters with fixing support: gofmt and goimports. I'm not sure it makes sense to support `--fix` just for these "linters"

**Comment by ewgRa** [comment]
@jirfag even if there is now not so many of them, such option can give additional motivation to start implement such feature for linters, without such option linters that rely on usage through golangci-lint and want implement "fix" will be limited by golangci-lint.

**Comment by matoous** [comment]
`--fix` currently works for linters the support it. Closing.
