### ISSUE TITLE
Intro page: Integrations guide list is so short for front page

### ISSUE THREAD

**Issue by MrWormHole** [golangci/golangci-lint#1961]
**Is your feature request related to a problem? Please describe.**
I am disappointed by not seeing all integration options on the introduction page because emacs, vscode and sublime are the only listed ones. It could save me a lot of time if I checked it out integrations page(which is quite extensive and super great) first instead of going over intro and quick start

**Describe the solution you'd like**
Could you go ahead and list all the options there on the front page? (6 IDEs and 1 CI/CD platform)

**Describe alternatives you've considered**
Ignore my PR

**Additional context**
Windows context:
I have just wasted straight 2 hours battling with golangci-lint for windows and ubuntu WSL. I observed diffutil is not included on windows platform so I gave a quick approach by installing GNU diff util 32 bit (.exe) file then adding into PATH `https://sourceforge.net/projects/gnuwin32/files/diffutils/2.8.7-1/diffutils-2.8.7-1.exe/download?use_mirror=deac-riga&download=` it did work but it was a pain to find

```
level=warning msg="[runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. "
level=warning msg="[runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref."
level=warning msg="[runner] Can't run linter goanalysis_metalinter: gofmt: error computing diff: exit status 3221225781"
level=error msg="Running error: gofmt: error computing diff: exit status 3221225781"
```

```
golangci-lint has version v1.39.0 built from (unknown, mod sum: "h1:aAUjdBxARwkGLd5PU0vKuym281f2rFOyqh3GB4nXcq8=") on (unknown)
```

WSL context:
I tried WSL to find out if it can only work with golangci-lint go module, it didn't work I got fatal errors like this even though everything is properly installed on WSL environment(every command of golangci-lint and go works except linting)

```
WARN Failed to discover go env: failed to run 'go env': exec: "go": executable file not found in $PATH
ERRO Running error: context loading failed: failed to load packages: failed to load with go/packages: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:
```

```
golangci-lint has version 1.39.0 built from 9aea4aee on 2021-03-26T08:02:53Z
```

**Comment by JacekDuszenko** [comment]
Hey, I implemented the requested docs change in #2040, feel free to review it! Thanks
