### ISSUE TITLE
Enable configuration of govet -printfuncs

### ISSUE THREAD

**Issue by jsm** [golangci/golangci-lint#204]
Would it be possible to be able to configure govet printfuncs?

**Comment by ncw** [comment]
This would be very useful.  I'm having to run `go vet -printfuncs Debugf,Infof,Logf,Errorf ` in addition to golangci-lint - it would be nice to include that too :-)

**Comment by jirfag** [comment]
Thank you! It would be useful feature

**Comment by jirfag** [comment]
I've merged #443 with the newest go vet. It supports:
1. automatic detection of printing functions
2. if the function wasn't classified automatically you have two choices:
  - add `if false { _ = fmt.Sprintf(format, args...) }` as described in `go tool vet help printf`
  - configure it in `.golangci.yml` via `linters-settings.govet.settings.printf.funcs`, see example in [.golangci.yml](https://github.com/golangci/golangci-lint/blob/master/.golangci.yml)

**Comment by ncw** [comment]
Thank you @jirfag - I've tested that with my codebase and it works perfectly :-)

When are you planning a release? My CI will only use a release build of golangci-lint!

**Comment by jirfag** [comment]
I think in 1-2 days
