### ISSUE TITLE
Typecheck runs even though it is not an enabled linter

### ISSUE THREAD

**Issue by ewrenn8** [golangci/golangci-lint#2063]
- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>Description of the problem</summary>

When running with `golangci-lint` version `1.40.0`, we are seeing that, although we have explicitly disabled all linters in our config and only enabled a few, not including `typecheck`, the `typecheck` linter is still running. 

</details>

<details><summary>Version of golangci-lint</summary>

v0.40.0

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
run:
  timeout: 5m
linters:
  enable:
    - goheader
    - golint
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.16.5 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/runner/.cache/go-build"
GOENV="/home/runner/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/runner/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/runner/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/hostedtoolcache/go/1.16.5/x64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/hostedtoolcache/go/1.16.5/x64/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/runner/work/carvel-kapp-controller/carvel-kapp-controller/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3653466737=/tmp/go-build -gno-record-gcc-switches"
```

</details>

For context, this is not running with the bare binary, it is running in a github action. I opened the issue here, because the binary is reporting conflicting info and I figured that is not due to the action itself. Here are some potentially helpful links:

1. [Binary reporting it is only using 4 linters](https://github.com/vmware-tanzu/carvel-kapp-controller/pull/238/checks?check_run_id=2843973090#step:5:101)
1. [Typecheck errors](https://github.com/vmware-tanzu/carvel-kapp-controller/pull/238/checks?check_run_id=2843973090#step:5:33) even though `typecheck` isn't an enabled linter

If I am mistaken and this issue should be opened some place else, please let me know.

Thank you!

**Comment by ldez** [comment]
Hello,

typecheck is not a real linter, it's a way to display compilation errors reported by the other linters.

**Comment by ewrenn8** [comment]
I'm a bit confused, there are no compilation errors when compiling with the plain go compiler, so why is typecheck reporting that there are? Also, after investigating the errors, typecheck is reporting errors that don't actually exist, such as a named import not being used by its name, when it clearly is (potentially related issue #1921). Is there anything I can do to further investigate why these errors are being reported?

**Comment by ldez** [comment]
@ewrenn8 your problem is related to your `vendor` folder: there are some missing files.

You have to do a `go mod vendor`

```console
$ go mod vendor 
$ git st
## go-version-bump...origin/go-version-bump
 D vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
 D vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
 D vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.proto
 D vendor/github.com/googleapis/gnostic/OpenAPIv2/README.md
 D vendor/github.com/googleapis/gnostic/OpenAPIv2/openapi-2.0.json
?? vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.go
?? vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.pb.go
?? vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.proto
?? vendor/github.com/googleapis/gnostic/openapiv2/README.md
?? vendor/github.com/googleapis/gnostic/openapiv2/openapi-2.0.json
```

**Comment by aaahrens** [comment]
I would really appreciate this being fixed as it's seriously blocking bazel integration.

**Comment by ldez** [comment]
There is nothing to fix: typecheck is not real linter, it's a way to display "compilation" errors throw by linters.
