### ISSUE TITLE
install golangci-line failed

### ISSUE THREAD

**Issue by romberli** [golangci/golangci-lint#2068]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

<details><summary>Description of the problem</summary>

I tried to install golangci-lint with homebrew, but it failed, I've uploaded the screenshot, please someone help me

![image](https://user-images.githubusercontent.com/6140181/122701716-6b227800-d280-11eb-893a-a91493c70050.png)

</details>

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
# paste output here
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version

go version go1.16.4 darwin/amd64
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

<details><summary>Code example or link to a public repository</summary>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

sound like a problem with Brew and Go, it's not related to golangci-lint itself.
