### ISSUE TITLE
lll: support the exclude option

### ISSUE THREAD

**Issue by benma** [golangci/golangci-lint#207]
I'd like to exclude comments from the `lll` output. `lll` has the `--exclude` flag I could use for that (https://github.com/walle/lll), but it doesn't seem to be supported by golangcli-lint.

**Comment by jirfag** [comment]
1. do you want to exclude only comments?
2. why do you like to make comments an exception to the line length rule?

**Comment by benma** [comment]
1. For now, yes.
2. I ran the `lll` linter on our codebase and found that only comments are affected. Many of them are long for a good reason, ie. a long url that can't be broken up, etc. 

In any case, it would be useful to transparently allow the configuration of the underlying linters in the way they support it (i.e. not invent new config rules in `golangci-lint` and translate them to the underlying linter). Other people might be using `lll` with another custom exclude rule, for example.

**Comment by henrahmagix** [comment]
> 2\. Many of them are long for a good reason, ie. a long url that can't be broken up

Exactly the problem I have: it's impossible to make the comment line shorter.

I feel a tiny stab or irony that I have to make the comment _longer_ to ignore it with a `nolint[:lll]` command, e.g.
```
// nolint[:lll] See https://longurl.org/path/to/thing/with/commit/has/1232u4t98u98fdugdsgeawefe/now/a/file.txt
```

**Comment by nerder** [comment]
Same issue here, trying `exclude: ^\/\/.+` but without result

**Comment by matoous** [comment]
Currently there's example in readme for excluding certain patterns from linting.

From README:

```
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
```

In case of long comments it would be:

```
    - linters:
        - lll
      source: "^// "
```

Closing.

**Comment by henrahmagix** [comment]
Thanks @matoous, that works perfectly!

This is my config, so you can see what to add directly to `.golangci.yml`:
```yaml
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^// "
```

**Comment by alvaroaleman** [comment]
https://github.com/golangci/golangci-lint/issues/207#issuecomment-534771981

This only works for comments on top-level objects, as otherwise there is preceeding whitespace. And for some reason `\s` isn't supported, so `^\s*// ` results in a `While parsing config: yaml: line 103: found unknown escape character`?

**Comment by ktong** [comment]
> \s*



> [#207 (comment)](https://github.com/golangci/golangci-lint/issues/207#issuecomment-534771981)
> 
> This only works for comments on top-level objects, as otherwise there is preceeding whitespace. And for some reason `\s` isn't supported, so `^\s*// ` results in a `While parsing config: yaml: line 103: found unknown escape character`?

it should be `^\t*// `
