### ISSUE TITLE
Add linter `github.com/nishanths/dedupimport`

### ISSUE THREAD

**Issue by zx8** [golangci/golangci-lint#2070]
It would be great to include https://github.com/nishanths/dedupimport in `golangci-lint`, with an option to `golangci-lint run --fix` any issues raised.

I've also created an upstream issue to (hopefully) get the author onboard: https://github.com/nishanths/dedupimport/issues/4

**Comment by ldez** [comment]
Hello,

`dedupimport` is not linter, it's a simplify/format code.

I think it's out of the scope of golangci-lint.

We already have dupl to handle duplication
