### ISSUE TITLE
Provide list of .go files to scan via stdin or file

### ISSUE THREAD

**Issue by huornlmj** [golangci/golangci-lint#2076]
Provide list of .go files to scan via stdin or file, instead of just running **golangci-lint run** on the current directory.

**Comment by ldez** [comment]
Hello,

could you explain what is the use case behind this issue?

**Comment by huornlmj** [comment]
Sorry I've since found the feature that I was looking for.  The ability to only scan new files in a git repo.  Although I'm having difficulty passing all new or modified files within one branch to golangci-lint.  It only appears that it will scan whatever is in the specific revision I supply with --new-from-rev=<commit hash>.  Not a cumulative scan of all commits within the branch.

**Comment by ldez** [comment]
ok, so I will close this issue.

For the rest, you can open a discussion: https://github.com/golangci/golangci-lint/discussions
