### ISSUE TITLE
Support RISV64

### ISSUE THREAD

**Issue by qdm12** [golangci/golangci-lint#2079]
### your feature request related to a problem? Please describe.

```sh
GOARCH=riscv64 go build ./cmd/golangci-lint
```

fails with:

```
/go/pkg/mod/github.com/prometheus/procfs@v0.1.3/cpuinfo.go:71:9: undefined: parseCPUInfo
```

### Describe the solution you'd like.

I expect golangci-lint to be buildable for riscv64 as it is for all other platforms.

There is the dependency `github.com/prometheus/procfs` which added support for riscv64 in `v0.6.0` (https://github.com/prometheus/procfs/commit/910e68572b35da779e4f84cfa5261b0a67532d05)

golangci-lint probably depends on many dependencies using versions pre-v0.6.0 of procfs so it's more of a long shot than something that can be fixed in a single PR I believe.

### Describe alternatives you've considered.

```sh
go mod edit -replace=github.com/prometheus/procfs=github.com/prometheus/procfs@v0.6.0
go mod tidy
```

Fixes the build, but probably in a risky-ish way I guess. Not a priority issue at all, but I thought it would be useful to track it.

**Comment by ldez** [comment]
Hello,

The `replace` directives are a major issue because they are not transitive.
As some people use golangci-lint with the "tools pattern", the replace directives are a problem.

In all cases, the `replace` directive is not the good solution to force the version of a lib, the right way is to use `// indirect`.

**Comment by qdm12** [comment]
@ldez thanks for the heads up! Using `go get github.com/prometheus/procfs@v0.6.0 && go mod tidy` also fixes the build. Although I'm not sure it's that safe still compared to upgrading dependencies one by one 🤔

**Comment by ldez** [comment]
If that build and run it's safe :wink: 

The best way to handle that is to fix the root cause:
```console
$ go mod why -m github.com/prometheus/procfs
# github.com/prometheus/procfs
github.com/golangci/golangci-lint/pkg/golinters
github.com/yeya24/promlinter
github.com/prometheus/client_golang/prometheus
github.com/prometheus/procfs
```

But the  `prometheus` library is like the `grpc` or `kubernetes` libraries: the root of a major dependency hell in Go, each patch or minor version can break your project.

The "indirect" approach follows semver and the Minimal Version Selection (MVS), then it a safe way.

**Comment by qdm12** [comment]
> go mod why

TIL about this command thanks!

> each patch or minor version can break your project.

Oh really? Don't they carefully follow semver?

> The "indirect" approach follows semver

Are we sure it's safe though? I guess it still replaces older versions with 0.6.0 for all dependencies right? As in it does compile so that's good, but I can't guarantee it behaves the same as before right? Especially since these are 0.x.x releases (unstable).

Ill dig through their release notes and get back.

**Comment by qdm12** [comment]
Actually I was wrong, the RISCV64 fix came with release v0.3.0, not v0.6.0.

- [Commits from v0.1.3 to v0.3.0](https://github.com/prometheus/procfs/compare/v0.1.3...v0.3.0): I don't think there is any breaking changes but can't be 100% sure yet
- [Commits from v0.3.0 to v0.6.0](https://github.com/prometheus/procfs/compare/v0.3.0...v0.6.0): mostly bug fixes and new features, no breaking changes really

So we could use v0.3.0 to stay on the safe side, although v0.6.0 might be safer with the several bug fixes it comes with 🤔

**Comment by ldez** [comment]
>  I guess it still replaces older versions with 0.6.0 for all dependencies right? 

It's not really a replacement, by using `indirect` we feed the MVS with new information, and MVS chooses the right version.

In all the cases, MVS chooses only **one version** of a dependency, then currently we use `v0.1.3`.

In golang-ci lint, we don't really use `prometheus` or `procfs`, the dependency is only used by `promlinter` to parse metric's names.

Also golang-ci is not designed to be used as a library, then we don't have to care about use in another context.

**Comment by ldez** [comment]
If you want to be 100% sure:

- clone https://github.com/prometheus/client_golang
- checkout `v1.7.1`
  - https://github.com/prometheus/client_golang/tree/v1.7.1
  - https://github.com/prometheus/client_golang/blob/v1.7.1/go.mod#L11
- procfs is only used here:
  - https://github.com/prometheus/client_golang/blob/v1.7.1/prometheus/process_collector_other.go
  - https://github.com/prometheus/client_golang/blob/v1.7.1/prometheus/process_collector_other_test.go
- update `procfs` to `v0.6.0`
- then check the compilation and run the tests

=> everything works as expected

**Comment by ldez** [comment]
Still not confident? Check the diff between v0.1.3 and v0.6.0.

https://github.com/prometheus/procfs/compare/v0.1.3...v0.6.0

There are no breaking changes :wink:

**Comment by ldez** [comment]
So don't be afraid:
1. we don't use `procfs`
2. `github.com/prometheus/client_golang` is compatible with v0.6.0
3. there are no breaking changes of the API between v0.1.3 and v0.6.0
4. we don't use `procfs` :smile_cat: 
5. golangci-lint is not designed to be used as a library

Yes it's safe :smile:

**Comment by qdm12** [comment]
Thanks so much for all the clarifications!

Sorry for being way too paranoid. Anyway, in the worst case promlinter may behave strangely in some corner cases, but as you mentioned golangcilint isn't meant to be used as a lib or a productiom program so that's fine.

A tiny few notes:

> then check the compilation and run the tests

Assuming the tests cover the code and are deep enough to detect  behavioral changes. Probably the case, but not always.

> Check the diff between v0.1.3 and v0.6.0.

I did and also asked on their repo if they can think of any breaking change: https://github.com/prometheus/procfs/issues/389

We can merge that 0.6.0 PR you made then, nice 👍 I'll come back here if I find anything. I'm also onto the helm and buildx repositories asking them to upgrade their procfs, although this might be more risky so we will definitely find any breaking change I think.

> Edit: I close the issue by mistake 😄

Tell me about it, this close button is way too close to the comment button 😄

**Comment by ldez** [comment]
another element: between v1.7.1 and v1.11.0 of `github.com/prometheus/client_golang`, the `procfs` library has been updated.

As you can see there no changes, except `go.mod` and `go.sum`, related to `procfs`.

https://github.com/prometheus/client_golang/compare/v1.7.1...v1.11.0
