### ISSUE TITLE
Revive is not merging configs

### ISSUE THREAD

**Issue by arxeiss** [golangci/golangci-lint#2087]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

If I use a config like mentioned below, I don't see any **revive** errors. But when I remove completelly `revive` part from `linters-settings` then I start getting errors.

It seems like setting `revive` override the config completely, instead of merging.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.41.0 built from (unknown, mod sum: "h1:1kfytWKEn2EPjniwD5xCwWtHAHR57q+vmDX3+VBoJac=") on (unknown)
```

</details>

### Configuration file

<details>

```yaml
---
linters:
    enable:
        - revive

linters-settings:
    revive:
        severity: error
        
issues:
    exclude-use-default: false 
    max-issues-per-linter: 0
    max-same-issues: 0
    
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.16 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pavel/.cache/go-build"
GOENV="/home/pavel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pavel/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pavel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pavel/Projects/IndyKite/jarvis-proto/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2591285065=/tmp/go-build -gno-record-gcc-switches"

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
package revivesample

func Abc() {
	fmt.Println("a")
}
```

</details>

**Comment by ldez** [comment]
Hello,

golangci-lint follows the same approach than revive for the revive configuration.

Then this behavior is expected.

**Comment by arxeiss** [comment]
OK, thanks
