### ISSUE TITLE
Add simplify option for gofumpt similar to gofmt

### ISSUE THREAD

**Issue by leighmcculloch** [golangci/golangci-lint#2090]
### your feature request related to a problem? Please describe.

gofumpt has a simplify option like gofmt, but it can't be triggered with a param like `simplify: true`.

### Describe the solution you'd like.

The ability to enable simplification with `simplify: true` in the yaml config.

### Describe alternatives you've considered.

Using gofumpt directly with the `-s` option.

**Comment by SVilgelm** [comment]
unfortunately this is not possible, since the gofumpt's formatter has no simplify option: https://github.com/mvdan/gofumpt/blob/master/format/format.go#L30

**Comment by leighmcculloch** [comment]
Ahh so it appears that the simplify code lives outside the formatter that gets imported here. It lives here in gofumpt instead: https://github.com/mvdan/gofumpt/blob/master/simplify.go. It looks like gofumpt is adding the simplify option to its formatter and there's already an open PR for it in https://github.com/mvdan/gofumpt/pull/131.

Could this issue stay open for implementing once https://github.com/mvdan/gofumpt/pull/115 is closed?

**Comment by SVilgelm** [comment]
sure
