### ISSUE TITLE
linter goconst not working as intended

### ISSUE THREAD

**Issue by mkungla** [golangci/golangci-lint#2127]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

1. `golangci-lint run --no-config --disable-all --enable goconst` outputs nothing
2. `goconst -min-length 3 -min-occurrences 3 .` outputs all the occurrences correctly

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.41.1 built from a2074809 on 2021-06-19T16:01:50Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# irrelevant --no-config
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.16.5 linux/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [lintersdb] Active 1 linters: [goconst]      
INFO [loader] Go packages loading at mode 7 (files|compiled_files|name) took 164.628839ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 5.715079ms 
INFO [linters context/goanalysis] analyzers took 1.955345ms with top 10 stages: goconst: 1.955345ms 
INFO [runner] processing took 3.859µs with stages: max_same_issues: 716ns, max_from_linter: 440ns, skip_dirs: 352ns, nolint: 298ns, exclude-rules: 272ns, cgo: 222ns, filename_unadjuster: 179ns, exclude: 170ns, skip_files: 162ns, path_prettifier: 115ns, severity-rules: 113ns, uniq_by_line: 111ns, max_per_file_from_linter: 109ns, path_prefixer: 103ns, diff: 103ns, source_code: 102ns, autogenerated_exclude: 94ns, identifier_marker: 89ns, path_shortener: 59ns, sort_results: 50ns 
INFO [runner] linters took 18.027252ms with stages: goconst: 17.986046ms 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 3 samples, avg is 71.8MB, max is 72.3MB 
INFO Execution took 193.656626ms 
```

</details>

### Code example or link to a public repository

<details>

```go
package main

import "fmt"

func main() {
  fmt.Println("goconst")
  fmt.Println("goconst")
  fmt.Println("goconst")
  fmt.Println("goconst")
}

```

</details>

**Comment by ldez** [comment]
Hello,

it's expected because `ignore-calls` is `true` by default.

I will improve the documentation.

**Comment by mkungla** [comment]
aight, was expecting `golangci-lint` not do make own rules of rules set by linter defaults.... And linter with default config to work exactly as original one.

**Comment by ldez** [comment]
I don't have the full history behind this settings but maybe goconst change their default values.
golangci-lint, in some minor cases, doesn't follow the linter's default values.
