### ISSUE TITLE
Update go vet to go1.11

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#213]

**Comment by AlekSi** [comment]
Note that `go vet` will change significantly in 1.12: https://tip.golang.org/doc/go1.12#vet
https://godoc.org/golang.org/x/tools/go/analysis looks interesting in general.

**Comment by jirfag** [comment]
@AlekSi thank you

**Comment by jirfag** [comment]
was merged in https://github.com/golangci/golangci-lint/pull/443
