### ISSUE TITLE
If config file specifies a linters section, the cli ignores `--fast`

### ISSUE THREAD

**Issue by calind** [golangci/golangci-lint#215]
If config file specifies a `linters.enable` section, the cli ignores `--fast`

```yaml
linters:
  disable-all: true
  enable:
    - golint
    - govet
```
When runnning `golangci-lint run --fast ./pkg/...` I'm expecting that only `golint` runs, but it also runs `govet`.

The use case for this is that I want to declare my desired list of linters to run in `.golangci.yml` but on IDE run only _"fast"_ ones.

__Environment__:
1. `golangci-lint --version`:
```
golangci-lint has version 1.10.2 built from dbfcf63 on 2018-09-02T12:28:26Z
```
2. `go version && go env`
```
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/calin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/calin/work"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n4/1c4lyyfn1296bkwn6scp_j980000gn/T/go-build426123229=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
3. `golangci-lint run -v --fast ./pkg/...`
```
INFO [config_reader] Config search paths: [./ /Users/calin/work/src/github.com/presslabs/wordpress-operator/pkg /Users/calin/work/src/github.com/presslabs/wordpress-operator /Users/calin/work/src/github.com/presslabs /Users/calin/work/src/github.com /Users/calin/work/src /Users/calin/work /Users/calin /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 2 linters: [golint govet]
INFO [load/path_resolver] Paths resolving took 3.9778ms: [pkg/apis pkg/apis/wordpress pkg/apis/wordpress/v1alpha1 pkg/apis/wordpress/v1alpha1 pkg/controller pkg/controller/wordpress pkg/controller/wordpress/sync]
INFO [load] Program loading took 5.787409736s
INFO [runner] worker.1 took 7.568µs
INFO [runner] worker.2 took 5.816µs
INFO [runner] worker.4 took 7.254132ms with stages: govet: 7.234308ms
INFO [runner] worker.3 took 496.894636ms with stages: golint: 496.868981ms
INFO [runner] Workers idle times: #1: 496.72485ms, #2: 496.690854ms, #4: 489.550011ms
INFO [runner] processing took 4.499µs with stages: max_same_issues: 779ns, path_prettifier: 517ns, nolint: 505ns, max_from_linter: 362ns, exclude: 319ns, skip_files: 311ns, uniq_by_line: 307ns, diff: 300ns, autogenerated_exclude: 289ns, cgo: 275ns, source_code: 270ns, max_per_file_from_linter: 265ns
INFO Memory: 35 samples, avg is 498.9MB, max is 1141.9MB
INFO Execution took 6.342989896s
```

**Comment by diegs** [comment]
So I hit this too, and I think it's counterintuitive. It's actually intended behavior, though:

https://github.com/golangci/golangci-lint/blob/55a18ae18a3c49cb7151da117c0ca0a566f58ce5/pkg/lint/lintersdb/enabled_set.go#L50

Effectively the yaml config is treated the same way as specifying linters through `--enable` on the command line. The idea is to support disabling slow linters but then manually re-enabling any linter.

I get the logic behind this, but I also feel that any flag specified via command line should override anything in config (possibly with a warning). I might try to fix this...

**Comment by jirfag** [comment]
hi, sorry for the slow response, I've lost this issue.

The problem is we don't know where the parameter comes: from the config or from the cli. If we could save this information we can properly fix this issue.

Also, we've already made govet and almost all linters "fast" (thanks to go/packages and go cache)

**Comment by jirfag** [comment]
now all linters are fast except `unused`
