### ISSUE TITLE
Global configured lang version

### ISSUE THREAD

**Issue by SVilgelm** [golangci/golangci-lint#2158]
### your feature request related to a problem? Please describe.

Some of the linters have the configuration option to configure the lang's version, like `gofumpt`, `staticcheck`, `unused`, etc...

So it would be great to configure the version in one place and use it as default value or 

### Describe the solution you'd like.

probably the `run` section should be extended to have the `go` parameter to store the default lang version 
then all the linters that have this parameter can use it as default

or the lang version can be read from go.mod directly

### Describe alternatives you've considered.

https://www.google.com/search?client=safari&rls=en&q=yaml+anchors&ie=UTF-8&oe=UTF-8
but it looks like a dirty hack

**Comment by scop** [comment]
The suggestion of using a special sentinel value in #2680 for triggering the inheritance could be made in a minor release, no need to wait for 2.0.0 for that. It isn't too pretty, but the advantage it would have over the anchor approach:

```
run:
  go: &run_go "1.17"
linters-settings:
  gofumpt:
    lang-version: *run_go
```

...would be that there would be no need to configure run.go at all now that we have autodetection, and linters could still use it. Dunno if not worth it, though, but if we're going to have inheritance in 2.0.0, perhaps support for the sentinel could be dropped at that time so the ugliness wouldn't be there forever.
