### ISSUE TITLE
Add support for custom initialisms to tagliatelle linter

### ISSUE THREAD

**Issue by AlekSi** [golangci/golangci-lint#2167]
### Your feature request related to a problem? Please describe.

tagliatelle linter tells me that my `fooCLIBar` tag should be `fooCliBar`, but CLI is a common initialism.

### Describe the solution you'd like.

`strcase` supports custom initialisms, so it would be nice if tagliatelle and golangci-lint allowed them to be configured.

### Describe alternatives you've considered.

Fixing 100+ tags and break the world, or disable this linter (that looks useful otherwise).

**Comment by ldez** [comment]
Hello,

It's a feature of tagliatelle not of golangci-lint, then I will close this issue.

You can follow this issue https://github.com/ldez/tagliatelle/issues/2

**Comment by AlekSi** [comment]
Sure, but once it is implemented in tagliatelle, golangci-lint surely should be modified to accept configuration, no?

Anyway, I'm all for it if that's easier for you this way :)
