### ISSUE TITLE
use-installed-packages flag

### ISSUE THREAD

**Issue by jsm** [golangci/golangci-lint#217]
Can we get a flag for use-installed-packages?

See issue: https://github.com/golangci/golangci-lint/issues/208

I don't want to have it on the CI build, but it makes sense to enable for editors like VSCode to speed things up in the use case of running it many times on single files.

I'd rather not have to have a separate configuration file for this one case.

**Comment by jirfag** [comment]
hi! the flag isn't needed anymore: we use go/packages. Check it please
