### ISSUE TITLE
Chronos static race detector 

### ISSUE THREAD

**Issue by jerome-laforge** [golangci/golangci-lint#2171]
### Your feature request related to a problem? Please describe.

Is it possible to add https://github.com/amit-davidson/Chronos in linters? 

### Describe the solution you'd like.

Add new linter

### Describe alternatives you've considered.

Run Chronos as standalone

**Comment by bombsimon** [comment]
`golangci-lint` requires linters to use `go/analysis` which Chronos does not seem to do so based on that it's currently not possible to integrate it in `golangci-lint`. You can read more about integrating linters [here](https://golangci-lint.run/contributing/new-linters/).

**Comment by jerome-laforge** [comment]
OK thanks for your reply. I have just opened this https://github.com/amit-davidson/Chronos/issues/45
