### ISSUE TITLE
`1.10.2` release was rewritten!

### ISSUE THREAD

**Issue by 31z4** [golangci/golangci-lint#219]
Hey guys, I think the latest `1.10.2` release was rewritten.

I got checksum mismatch on the `golangci-lint-1.10.2-linux-amd64.tar.gz` distro. It was `853407c3ccd7c2e3496206fe9b5a4a47cce71655e88099600f0fe8021f7a99e8` and now it's `9c90232309a6f1bca319b3bf93b4105a7f348b6cd97c197b1269f949599ac650`.

I'm really worried that the build could be compromised.

**Comment by jirfag** [comment]
hi!
sorry, yes it was. It was an empty release for the first time to test work of go modules with tags. Users shouldn't use empty releases if they choose release to install from [releases](https://github.com/golangci/golangci-lint/releases) page. Do you always install the latest release?

**Comment by 31z4** [comment]
Ah perhaps I didn't notice that it was an empty release then, sorry. No, I don't always install the latest release, I specify the version instead. Like this (doing it within Docker)

```Dockerfile
# Download and install GolangCI-Lint
RUN set -ex; \
    wget -q https://github.com/golangci/golangci-lint/releases/download/v1.10.2/golangci-lint-1.10.2-linux-amd64.tar.gz; \
    echo '9c90232309a6f1bca319b3bf93b4105a7f348b6cd97c197b1269f949599ac650 golangci-lint-1.10.2-linux-amd64.tar.gz' | sha256sum -c -; \
    tar -xzf golangci-lint-1.10.2-linux-amd64.tar.gz; \
    mv golangci-lint-1.10.2-linux-amd64/golangci-lint /usr/local/bin/golangci-lint; \
    chmod +x /usr/local/bin/golangci-lint; \
    rm -rf golangci-lint-1.10.2-linux-amd64*
```

Thanks for the swift reply 👍
