### ISSUE TITLE
Sublime Plugin

### ISSUE THREAD

**Issue by alecthomas** [golangci/golangci-lint#22]
I adapted my gometalinter plugin for golangci-lint:

https://github.com/alecthomas/SublimeLinter-contrib-golang-cilint

(just opening an issue because there seems to be no other means of contacting the authors)

**Comment by golangci** [comment]
@alecthomas thank you very much for reporting bugs and making this integration, you are awesome :)
I added information about it into README.

**Comment by golangci** [comment]
You can contact me by [denis@golangci.com](mailto:denis@golangci.com).
