### ISSUE TITLE
Feature request: make --new/new-from-rev configurable per linter

### ISSUE THREAD

**Issue by rski** [golangci/golangci-lint#221]
--new is a good way to introduce new linters to prevent new issues without being blocked by existing issues. However, if linter1 is happy without new and linter2 is not happy without it, the lowest common denominator is using --new, unless you want to have two passes of running golangci-lint. Unfortunately, --new has proven to be flaky and as it is there is no  way to guarrantee no issues for linter1 slip in, unless golangci-lint is run both with and without new. 

The big selling point of gcil is parallelism, so it would be nice if it were possible to run the --new and non--new linters in the same pass.

**Comment by jirfag** [comment]
thank you for the idea!
I think it makes sense and it's not difficult to implement.
Pull requests are welcome

**Comment by jirfag** [comment]
also, you can run golangci-lint multiple times with different --new options
