### ISSUE TITLE
Apply default arguments for some checks related to revive

### ISSUE THREAD

**Issue by jawnsy** [golangci/golangci-lint#2258]
### Your feature request related to a problem? Please describe.

Some linters for revive will cause a panic if users do not supply arguments. This behavior is as-designed according to the maintainers (see https://github.com/mgechev/revive/issues/579) and they suggested we could apply defaults in golangci-lint instead.

### Describe the solution you'd like.

As a user, I'd like to be able to run revive's linters without any additional configuration, if it is possible to select reasonable defaults, or otherwise get an error message that is friendlier than a panic stack dump. Ideally, the defaults would be applied in revive itself so that anyone using it would have the same behavior, but since I specifically use golangci-lint, fixing it there would be suitable too.

### Describe alternatives you've considered.

* Getting the change upstreamed into revive, but this was rejected
* Catching the panic and emitting a nicer message, but I'm not sure if this is done with other linters that golangci-lint integrates or if there's a clean way to do it (we don't want to eat all panics, just ones specifically related to missing arguments)
* Changing the code to invoke some validation method in revive (I'm not sure if one exists) that would return an error if the linter is not valid?

### Additional context.

@chavacava provided a reference to some golangci-lint code that sets the default: https://github.com/golangci/golangci-lint/blob/c6c55d2502b052e2e5925389ee40b6bde887e3db/pkg/golinters/revive.go#L152

**Comment by ldez** [comment]
Hello,

we prefer to follow the revive behavior for the revive configuration.

I will try to improve the error output.

Can you provide a reproducible example?

**Comment by ldez** [comment]
It's not possible to catch the panic because it comes from a go routine inside revive.

**Comment by jawnsy** [comment]
> we prefer to follow the revive behavior for the revive configuration: the rule constraints are inside the rules themself it will be difficult to maintain.

Yeah, I understand that, seems like a very sensible design choice. I was really just forwarding this idea upstream as it was proposed by one of the revive contributors.

>It's not possible to catch the panic because it comes from a go routine inside revive.

Well, that's too bad :frowning: 

>The problem is that revive uses a panic instead of error (it's not a problem with CLI, but it's a problem with a lib) and doesn't provide something to handle this.

Yeah, that makes sense to me. Maybe that's something we can propose to the revive maintainers to add, a function that will validate options and return an error instead of panicing?

**Comment by ldez** [comment]
You can try to do that but I can understand if the revive maintainers don't want to add that.
