### ISSUE TITLE
Provide integration with Sonar

### ISSUE THREAD

**Issue by SergiiOliinyk** [golangci/golangci-lint#228]
It would be good to have an integration with Sonar, the same as gometalinter has. 

Please see https://github.com/uartois/sonar-golang
Thanks for really the great tool golangci-lint

**Comment by alecthomas** [comment]
Just FYI, that project was not implemented by the gometalinter team, it's entirely third party.

**Comment by 88SergiiOliinyk** [comment]
@alecthomas Is this implementation on the roadmap or no one will do it ?

**Comment by alecthomas** [comment]
In this project? I have no idea, you'll need to  ask @jirfag .

**Comment by jirfag** [comment]
hi!
Sorry, it's not on a roadmap. You can implement it yourself, I will make a link in README.

**Comment by kenjones-cisco** [comment]
Actually it would be the other way around, SonarGo would need to support golangci-lint (ie by consuming the output and mapping to the rules/categories within Sonar). I created an issue with SonarGo for the same, https://github.com/SonarSource/sonar-go/issues/346.
Currently it supports GoVet, GoLint, and Gometalinter. But with a new analyzer that understands the output from golangci-lint, it should be do able.

**Comment by evlacan** [comment]
@kenjones-cisco Gometalinter has `--checkstyle` flag which is required to send data to SonarQube in [checkstyle](http://checkstyle.sourceforge.net/) compatible XML format.

**Comment by tpounds** [comment]
Resolving as there are now several output formats available that should work with various CI and reporting tools.

* Checkstyle (#95)
* JUnit (#557)
* Code Climate (#386)
