### ISSUE TITLE
enable runtime error

### ISSUE THREAD

**Issue by mohammadne** [golangci/golangci-lint#2291]
### Your feature request related to a problem? Please describe.

I want it to continuely shows linting in my editor ( here it's vscode )

### Describe the solution you'd like.

adding a linting file to the root of project

### Describe alternatives you've considered.

None

**Comment by bombsimon** [comment]
More information about integrations in VS Code and other editors can be found [here](https://golangci-lint.run/usage/integrations/). Please refer to each specific implementation for details on usage such as those suggested by @natefinch.
