### ISSUE TITLE
Consider licensing with BSD or GPL license

### ISSUE THREAD

**Issue by cflewis** [golangci/golangci-lint#232]
Hi there,
`golangci-lint` is a very cool tool. Sadly I can't use it because [AGPL is banned at Google](https://opensource.google.com/docs/using/agpl-policy/). This means other Alphabet companies, and Google open-source efforts, like the Go project and Kubernetes teams, can't use it. This makes us sad as `golangci-lint` is awesome.

Is it possible to license using a BSD or GPL license?

Thank you!

**Comment by jirfag** [comment]
Hi!
Thank you for the explanation. I've changed the license to GPL.
