### ISSUE TITLE
Add NebulousLabs/glyphcheck as linter

### ISSUE THREAD

**Issue by adamdecaf** [golangci/golangci-lint#2329]
### Your feature request related to a problem? Please describe.

Homoglyph attacks are an increasing concern for source code and currently hard to detect. There are some tools available for detecting suspect UTF-8 runes. 

### Describe the solution you'd like.

Including support for running a homoglyph linter would be a good first step. 

### Describe alternatives you've considered.

There are few if any good homoglyph linters available for the Go language. Perhaps a new linter should be written.

https://github.com/search?l=Go&q=homoglyph&type=Repositories 

### Additional context.

https://github.com/NebulousLabs/glyphcheck

**Comment by bombsimon** [comment]
A liter needs to be written using the [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis) package to be merged to `golangci-lint`. It doesn't look like any of the ones in the search result does this so someone would need to write a new linter for `golangci-lint` to pick it up.

**Comment by ldez** [comment]
Hello,

`asciicheck` already check that cases

**Comment by ldez** [comment]
@adamdecaf you can follow the PR #2330
