### ISSUE TITLE
Broken links in the Contributing FAQ section

### ISSUE THREAD

**Issue by neha-viswanathan** [golangci/golangci-lint#2365]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

The following sections in the FAQ page in the Contributing docs has broken links:

https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/docs/src/docs/contributing/faq.mdx#how-to-write-a-custom-linter

https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/docs/src/docs/contributing/faq.mdx#how-to-add-a-new-open-source-linter-to-golangci-lint

https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/docs/src/docs/contributing/faq.mdx#how-to-add-a-new-private-linter-to-golangci-lint

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.43.0 built from 861262b on 2021-11-02T20:54:42Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17.2 darwin/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
```

</details>

### Code example or link to a public repository

https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/docs/src/docs/contributing/faq.mdx#how-to-add-a-new-private-linter-to-golangci-lint

**Comment by ldez** [comment]
Hello,

The links work as expected: https://golangci-lint.run/contributing/faq/

**Comment by neha-viswanathan** [comment]
oops my bad! thanks for clarifying
