### ISSUE TITLE
Support revive

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#238]
https://github.com/mgechev/revive

**Comment by jirfag** [comment]
I've tested revive a bit, looks like all warnings are the same as in golint. Why do we need revive in golangci-lint if we already have golint?

**Comment by s3rj1k** [comment]
Revive provides more rules compared to golint.

**Comment by jirfag** [comment]
ok, I will look at it, maybe it's rules are already implemented by other linters

**Comment by AlekSi** [comment]
In my project I would really like to use this check: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines I don't think it is implemented anywhere else.

**Comment by jirfag** [comment]
@AlekSi thank you. A similar check is in [`gofumpt`](https://github.com/mvdan/gofumpt), which is not included into golangci-lint too

**Comment by akyoto** [comment]
According to their README, revive is `2x faster running the same rules as golint`.
So it could replace `golint` for a performance improvement?

I've used revive as a default linter so far without any problems.

**Comment by jirfag** [comment]
As I understand It's faster just because of parallel execution. golangci-lint does the same parallel execution between linters (not inside `golint` only -  but if anyone wants to run only `golint` in `golangci-lint` he can use `revive`/`golint` instead)

**Comment by johnrichardrinehart** [comment]
Will a PR be accepted which integrates `revive` into `golangci`?

**Comment by jirfag** [comment]
@johnrichardrinehart yep, it will be accepted

**Comment by Dentrax** [comment]
@jirfag any updates? :)

**Comment by jirfag** [comment]
@Dentrax contributions [are welcome](https://golangci-lint.run/contributing/new-linters/). But, I hope `revive` uses `go/analysis`: we would like to include only `go/analysis`-based linters.

**Comment by johnrichardrinehart** [comment]
@jirfag You mean [this](https://godoc.org/golang.org/x/tools/go/analysis)?

**Comment by gonzaloserrano** [comment]
I think this is relevant to the discussion: https://github.com/golang/go/issues/38968

**Comment by johnrichardrinehart** [comment]
@gonzaloserrano Thanks for referencing this.

@jirfag In light of the planned deprecation of `x/lint`, will you consider PRs for non-`x/lint` linters?

**Comment by wburningham** [comment]
Ignoring the speed differences, the biggest reason I use revive over golint is the support for "disabling a specific rule or the entire linter for a file or a range of lines". I currently have to run revive and golangci-lint (with golint disabled). Please add support for revive so I can just run one lint command.

**Comment by s3rj1k** [comment]
@wburningham And actually still feels that revive catches more errors than some of the similar linters in golangci-lint.

It was the case in 2018, now is probably difference of catching errors is lesser.

This all comes from my experience only :)
