### ISSUE TITLE
Using the installation instructions downgrades your Go installation on macos with brew

### ISSUE THREAD

**Issue by brackendawson** [golangci/golangci-lint#2381]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Installing golangci-lint "on my machine" following the instructions actually downgrades your Go install.

1. I started with go 1.17.3 installed and wanted to install golangci-lint.
2. I saw in the [instructions](https://github.com/golangci/golangci-lint/issues/1657) that using `go install` is not recommended, so I went with `brew install` as shown in the documentation.
3. However this first installed Go 1.17.2 via brew.

Is the brew install actually from source or is it just misconfigured? This was just a very slow and irritating waste of my time as I now had to fix my development environment.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.43.0 built from 861262b on 2021-11-02T20:54:42Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17.2 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alan/Library/Caches/go-build"
GOENV="/Users/alan/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alan/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alan"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8x/rpf58y2d68z45w0b5_mg47b00000gn/T/go-build3369227732=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# This is an installation issue
```

</details>

### Code example or link to a public repository

<details>

```go
// This is an installation issue
```

</details>

**Comment by brackendawson** [comment]
I think for mac uses the `go install` approach actually would be better than `brew install`, they're more likely to have Go than they are to have brew.

Or possibly #1657 would be better.

Lets look at the reasons stated for not using `go install`:
> 1. some users use -u flag for go get, which upgrades our dependencies. Resulting configuration wasn't tested and isn't guaranteed to work.

This does not apply to the code snippets provided.

> 2. go.mod replacement directive doesn't apply. It means a user will be using patched version of golangci-lint if we use such replacements.

You don't use any replace directives.

> 3. it's stability depends on a user's Go version (e.g. on this compiler Go <= 1.12 bug).

golangci-lint doesn't compile at all on Go 1.11.

> 4. we've encountered a lot of issues with Go modules hashes.

This is a valid reason to favour a binary release.

> 5. it allows installation from master branch which can't be considered stable.

This does not apply to the code snippets provided.

> 6. it's slower than binary installation

Not true for brew.

Is that all just old information?

**Comment by ldez** [comment]
It was a problem related to `brew`, we (golangci-lint maintainers) don't maintain `brew`.
