### ISSUE TITLE
importas supports checking different aliases for the same package

### ISSUE THREAD

**Issue by Rodge0** [golangci/golangci-lint#2404]
### Your feature request related to a problem? Please describe.

Importas uses rules to standardize package aliases. But as the project gets bigger, there will be more and more rules and it is difficult to maintain.  There may be cases where the same package has different aliases because this package is not covered by the rules. importas cannot handle this situation because it does not support checking whether there are different aliases for the same package in different go files or in same go file without rules.

### Describe the solution you'd like.

Checking whether there are different aliases for the same package before checking the aliases according to the importas rules. 
Like this :
![屏幕截图 2021-12-06 230754](https://user-images.githubusercontent.com/27199364/144870293-cd6b29dd-4be0-4be6-b26c-ed62983921dc.png)
![屏幕截图 2021-12-06 230827](https://user-images.githubusercontent.com/27199364/144870344-a8bae3a3-d739-4743-b188-8db0dfb8b4d7.png)

This is a little implement, https://github.com/Rodge0/samealias, maybe useful. 

### Describe alternatives you've considered.

Don't let same pakcage have different aliases in different go file or same go files if there are no rules.  Add support in importas linter (suggested) or add samealias linter.

### Additional context.

Appreciate!

**Comment by Rodge0** [comment]
OK, thanks, I will close this issue

**Comment by butuzov** [comment]
Also supported by revive

**Comment by Rodge0** [comment]
> Also supported by revive

yeah, revive have a rule named duplicated-imports, but it only checks for duplicated imports in a single go file, this also supported by gci. But revive cannot check whether a package uses the different aliases in different files in project.
