### ISSUE TITLE
Add Semgrep linter support

### ISSUE THREAD

**Issue by rc-mattschwager** [golangci/golangci-lint#2408]
### Your feature request related to a problem? Please describe.

[Semgrep](https://github.com/returntocorp/semgrep) is a relatively new linter / static analysis tool. Using both `golangci-lint` and Semgrep is currently a challenge - it would be very helpful if `golangci-lint` directly supported Semgrep as a linter.

### Describe the solution you'd like.

Direct Semgrep support as a [`golangci-lint` linter](https://golangci-lint.run/usage/linters/).

### Describe alternatives you've considered.

Running both tools as separate jobs in CI. While this is certainly possible, it's not as convenient as a direct integration.

### Additional context.

Semgrep has a number of [extensions](https://semgrep.dev/docs/extensions/) listed. Those may provide additional context on an integration here.

**Comment by ldez** [comment]
Hello,

Semgrep is a meta-linter written in Python, there are several points that don't fit with our requirements:
- we integrate only linter written is Go
- a linter must implement a new linter using `go/analysis` API (which is a Go interface)
- a meta-linter inside a meta-linter is something that can be complex to handle.

https://golangci-lint.run/contributing/new-linters/#how-to-add-a-public-linter-to-golangci-lint
