### ISSUE TITLE
--build-tags from command line should override the build-tags from yaml

### ISSUE THREAD

**Issue by jaakkotuosa** [golangci/golangci-lint#2411]
### Your feature request related to a problem? Please describe.

I added the build tags to the yaml so that they could be shared by all our developers, but in CI I would also lint against production config. I was expecting --build-tags from command line (account_prod) would override the build-tags from yaml (account_test test), but instead all the tags were appended, which is was not a sensible combination in my case. I think it would common logic to have the command line switches to override values from config files.

### Describe the solution you'd like.

The command line option should override the values from yaml. 

### Describe alternatives you've considered.

Not using a yaml with build tags. Or maybe scripts for sharing the different tag combinations.

**Comment by ldez** [comment]
Hello,

The current behavior is the expected behavior:

> Slice options (e.g. list of enabled/disabled linters) are combined from the command-line and config file.

https://golangci-lint.run/usage/configuration/#config-file

It's not possible to handle the merge and the override at the same time.
The 2 possibilities are real use-cases it's difficult to say that one is better than the other.
