### ISSUE TITLE
maintidx Support

### ISSUE THREAD

**Issue by yagipy** [golangci/golangci-lint#2434]
### Your feature request related to a problem? Please describe.

I would like to measure the maintainability index.

### Describe the solution you'd like.

Add support for [maintidx](https://github.com/yagipy/maintidx).

### Describe alternatives you've considered.

Run maintidx separately to golangci-lint.

### Additional context.

I will be responsible for implementing it myself.

**Comment by hyagihashi-cq** [comment]
maintidx is [here](https://github.com/yagipy/maintidx)

**Comment by butuzov** [comment]
How this information can be useful? We already have complexity checks in place, which is simpler abstraction of "code complexity" then one from microsoft.

**Comment by yagipy** [comment]
@butuzov 
Thanks for your opinion.

> How this information can be useful?

IMO, "code complexity" is difficult to decide based on a single indicator and should be decided by referring to multiple indicators.
I recognize that there is already support for indicators such as cyclomatic complexity, cognitive complexity, etc., but I think no problem in having a maintainability index among them.
