### ISSUE TITLE
Rename gas to gosec in default exclude patterns

### ISSUE THREAD

**Issue by sgleizes** [golangci/golangci-lint#247]
From version `1.10.2`, it seems that gosec errors previously ignored by `exclude-use-default` are no longer excluded.

This seems to be because the default exclude patterns have not been updated after the rename (gas->gosec):
https://github.com/golangci/golangci-lint/blob/master/pkg/config/config.go#L67

**Comment by sgleizes** [comment]
I see this has been fixed in 6ecea1cdd :+1:

**Comment by jirfag** [comment]
thank you for reporting,
yes, it was already fixed. Please, try the latest release.
