### ISSUE TITLE
Install script fails on CircleCI

### ISSUE THREAD

**Issue by 13rac1** [golangci/golangci-lint#250]
**Problem**
```
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.10.2
golangci/golangci-lint info checking GitHub for tag 'v1.10.2'
golangci/golangci-lint info found version: 1.10.2 for v1.10.2/linux/amd64
install: cannot change permissions of ‘/go/bin’: Operation not permitted
Exited with code 1
```

Adding `sudo` it works, but changes the permissions of `/go/bin` so later `go get` installs fail.

**Cause**

The cause is `/go/bin` is owned by root with 777 perms. You can check the official Docker image: `circleci/golang:1.10`

**Workaround**
```
sudo chown circleci:circleci /go/bin
```

**Solution**

There are multiple ways this could be fixed. Here? CircleCI images? What do you think?

**Comment by jirfag** [comment]
hi!
the proper solution is to fix goreleaser script.
The workaround is to copy binary file manually:
```sh
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.10.2
sudo cp ./bin/golangci-lint $GOPATH/bin/
```

does it work ok?

**Comment by garagatyi** [comment]
@jirfag it helped me in the same situation, thanks!
