### ISSUE TITLE
feat: multiple output files-formats for different analyze tools

### ISSUE THREAD

**Issue by 090809** [golangci/golangci-lint#2504]
### Your feature request related to a problem? Please describe.

We are using different linter tools to visualize and control code quality, and we need to run linter multiple times for different linter output formats.

### Describe the solution you'd like.

Some flag, like `--output format:/path/to/file` which can be used multiple times.

### Describe alternatives you've considered.

Idk alternative ways how to realize this feature.

**Comment by 090809** [comment]
UPD: Find that it already done. Maybe need to update documentation for it?
https://github.com/golangci/golangci-lint/blob/ffb3fde4ef6d479bd29a19d18f57eec4d9ae2b10/pkg/commands/run.go#L405

**Comment by ldez** [comment]
The doc is already updated.
I will be available in the next version (v1.44.0)
