### ISSUE TITLE
Unused private fields check ignoring tests

### ISSUE THREAD

**Issue by ggarnier** [golangci/golangci-lint#265]
I just updated golangci-lint to master and I started getting a couple of `... is unused` errors for private functions and fields that are used only in tests.

Here's a simple code that illustrates the issue:

main.go
```
package test

type User struct {
	name string
}
```

main_test.go
```
package test

import "testing"

func TestSomething(t *testing.T) {
	u := User{}
	if u.name == "me" {
		t.Fail()
	}
}
```

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
Latest commit: https://github.com/golangci/golangci-lint/commit/f5f7701

2. Go environment: `go version && go env`
```
go version go1.11.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/home/linuxbrew/.linuxbrew/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/home/linuxbrew/.linuxbrew/Cellar/go/1.11.1/libexec/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc-5"
CXX="g++-5"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build366441268=/tmp/go-build -gno-record-gcc-switches"
```

3. Verbose output of running: `golangci-lint run -v`
```
INFO [config_reader] Config search paths: [./ /home/user/go/src/test /home/user/go/src /home/user/go /home/user /home /]
INFO [lintersdb] Active 8 linters: [deadcode errcheck govet ineffassign megacheck structcheck typecheck varcheck]
INFO [loader] Go packages loading at mode load deps types and syntax took 580.6528ms
INFO [loader] SSA repr building took 254.37378ms
INFO [runner/skip dirs] sorted abs args: [/home/user/go/src/test]
INFO [runner] worker.3 took 178.757µs with stages: ineffassign: 149.782µs, structcheck: 17.864µs, typecheck: 1.563µs
INFO [runner] worker.1 took 159.867µs with stages: errcheck: 70.112µs, varcheck: 61.678µs, deadcode: 20.883µs
main.go:4:2: `name` is unused (structcheck)
        name string
        ^
INFO [runner] worker.4 took 909.665µs with stages: govet: 897.036µs
INFO [runner] worker.2 took 66.545228ms with stages: megacheck: 66.525576ms
INFO [runner] Workers idle times: #1: 66.349623ms, #3: 66.362904ms, #4: 65.642119ms
INFO [runner] processing took 239.508µs with stages: exclude: 78.983µs, skip_dirs: 60.587µs, cgo: 32.485µs, source_code: 25.569µs, path_prettifier: 12.389µs, autogenerated_exclude: 10.755µs, nolint: 8.138µs, max_same_issues: 2.463µs, uniq_by_line: 2.354µs, max_from_linter: 2.233µs, path_shortener: 1.19µs, max_per_file_from_linter: 1.118µs, diff: 881ns, skip_files: 363ns
INFO Memory: 10 samples, avg is 136.3MB, max is 204.3MB
INFO Execution took 924.017002ms
```

**Comment by diegs** [comment]
I hit this too, and though it may come down to personal preference, you can also just move those private methods to the tests. That's technically correct, since it's unexported and not used in non-test code (and therefore doesn't need to be shipped as part of a binary, for example). But I would say it's not 100% unambiguous whether that is strictly better though.

**Comment by AlekSi** [comment]
I'm getting those errors in other cases. First, a non-exported method is used in a non-test file with a specific build tag (which is passed to `--build-tags`). Second, a non-exported function which is used _in the same file_ with the same build tag. So it is not something specific to tests.

**Comment by jirfag** [comment]
hi!
@ggarnier thank you for reporting, after switching to go/packages we have 2 packages for each loaded package with tests: one without tests and one with tests. It's a feature of go/packages. I've excluded package without tests if we have a package with tests from an analysis in the linked commit.

Please, check it in the master branch.

**Comment by jirfag** [comment]
@AlekSi please create an issue with code examples, looks like no connection with the current case

**Comment by AlekSi** [comment]
Created #272.

**Comment by ggarnier** [comment]
@jirfag now it's working, thanks!

**Comment by ilya-hontarau** [comment]
I had the same issue but discovered the problem with the configuration: linting in the test files was disabled.
```
run:
    test: false
```
