### ISSUE TITLE
Detects Go 1.18 Fuzz methods as unused code

### ISSUE THREAD

**Issue by Hades32** [golangci/golangci-lint#2650]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

```console
$ golangci-lint run                                                          
grid_test.go:128:6: `FuzzRectVsGrid` is unused (deadcode)
func FuzzRectVsGrid(f *testing.F) {
```

### Version of golangci-lint

```
golangci-lint has version v1.44.2 built from (unknown, mod sum: "h1:MzvkDt1j1OHkv42/feNJVNNXRFACPp7aAWBWDo5aYQw=") on (unknown)
```

### Configuration file

none

### Go environment

go version go1.18 linux/amd64

### Verbose output of running

-

### Code example or link to a public repository

<details>

```go
func FuzzRectVsGrid(f *testing.F) {
}
```

</details>

**Comment by ldez** [comment]
Hello,

Currently golangci-lint doesn't support go1.18, you can follow #2649


https://github.com/golangci/go-misc/deadcode

**Comment by ldez** [comment]
With a compiled version of golangci-lint with Go1.18, I don't reproduce the problem.

**Comment by ldez** [comment]
Thank you, I'm able to reproduce the problem, I will fix that quickly.
