### ISSUE TITLE
Plan for June 2018 - linters already added

### ISSUE THREAD

**Issue by JensRantil** [golangci/golangci-lint#266]
June 2018 plans can be updated; some of the linters listed in https://github.com/golangci/golangci-lint/blob/master/README.md#june-2018 are now updated.

Creating this issue since I saw the list and thought "oh, how sad some of those aren't implemented". Then I saw they were!! 🙌 🎉

**Comment by jirfag** [comment]
hi!
but it's a changelog, not plans. Maybe english is incorrect there?

**Comment by jirfag** [comment]
Got it, need to move it before "Future Plans"
