### ISSUE TITLE
typecheck: no matching files found when removing non-Go files on CI

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint#2690]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

After removing a git-ignored `json` file from Git, CI fails:

    Error: pattern samples/status.json: no matching files found (typecheck)

https://github.com/evcc-io/evcc/runs/5706205666?check_suite_focus=true

It feels wrong that the linter cares about `.json` at all?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
1.45.2
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  go: 1.18
issues:
  exclude:
  - .regActualCurrent. is unused
  - "`routeLogger` is unused"
linters-settings:
  staticcheck:
    checks:
      - '-SA1019'
```

</details>

### Go environment

Not possible on CI, running Go 1.18

### Verbose output of running

Not possible on CI

### Code example or link to a public repository

https://github.com/evcc-io/evcc/runs/5706205666?check_suite_focus=true

**Comment by ldez** [comment]
Hello,

are you using `//go:embed` to link a file called `samples/status.json` but you removed this file?

**Comment by ldez** [comment]
So it's the same behavior as Go: the [embed directive](https://pkg.go.dev/embed) requires that the file exists.
You have to provide this file. 

`typecheck` is not a real linter it's just a way to parse/display "compilation" and linters errors (linter reports are not errors)

**Comment by andig** [comment]
Arrrgh. Never came that far since the tests only run after the linter. Much appreciated!
