### ISSUE TITLE
Add a lint for `struct` constructors

### ISSUE THREAD

**Issue by elauffenburger** [golangci/golangci-lint#2708]
### Your feature request related to a problem? Please describe.

I've run into runtime bugs when adding a new field to a "service-like" `struct` (a `FooService` or something like that), but then I find out someone's instantiating the `struct` without a constructor so some code _somewhere_ breaks at runtime because of a `nil` pointer!

### Describe the solution you'd like.

I'd love to see two linters created: 
  - `struct`s that _should_ have a ctor, which _don't_ have a ctor
  - `struct`s that _do_ have a ctor, but which are instantiated without using the ctor

These linters would definitely want to take regexes that specify the types of `structs` that we consider to be lintable -- _most_ `struct`s don't have this problem since they're just data and we really don't even _want_ a ctor for them.

### Describe alternatives you've considered.

Pray our tests catch this stuff! 🙏 

### Additional context.

I've written these linters already (and they're useful for me), but I didn't want to create a PR without gauging interest first.

I'm new to this project, so thanks for your patience!

**Comment by ldez** [comment]
Hello,

your linters seem really specific to your use case, I'm not sure there is a big demand for this type of linter.

My recommendations: 
- open source your projects
- create 1 linter instead 2
- allow your linter to run as a [plugin](https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint)
- allow your linter to run as a binary

**Comment by elauffenburger** [comment]
Okay! Yep, make sense -- could I elaborate on this a bit more? Just to make it a bit more clear (because I _do_ think this is a somewhat general pattern and tl;dr is for DI)!

This is totally contrived, but:

```go
package metrics

struct Service {
  cfg     Config
  client Client
}

func NewService(cfg Config, client Client) Service {
  return Service {  cfg, client }
}

func SomethingSilly() {
  // All good here; this is just some data, so no need to use a ctor or anything.
  cfg := Config{}

  // Wait! I bypassed the ctor, so now I don't have the client set!
  svc := Service { cfg: cfg }
}

// ...

package foo

func DoTheThing() {
  // Wait! This definitely won't work!
  metricsSvc := metrics.Service{}
}
```

Does that illustrate this any better?

**Comment by ldez** [comment]
I understand your use case, but your linter will only be useful if all the structs follow the same name pattern.
If the structs don't follow a strict pattern, the configuration will be complex or will create a lot of false-positive/false-negative.

So I'm still thinking that is a specific use case.

But I'm not the community, so we will see, with this issue, if there is some interest for this linter.

**Comment by elauffenburger** [comment]
Okay! Nope, that makes sense -- thanks for taking a look. Feel free to close this if you feel that makes sense!

**Comment by alingse** [comment]
why not use `exhaustivestruct` https://github.com/mbilski/exhaustivestruct

it can also check miss field in struct
