### ISSUE TITLE
`go get` downgrades gci and golangci-lint

### ISSUE THREAD

**Issue by joshua** [golangci/golangci-lint#2764]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Running `go get` for any package results in downgrading gci and golangci-lint versions. We just updated to golangci-lint v1.45.2 and Go 1.18.

```
go: downgraded github.com/daixiang0/gci v0.3.3 => v0.2.9
go: downgraded github.com/golangci/golangci-lint v1.45.2 => v1.43.0
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.45.2 built from (unknown, mod sum: "h1:9I3PzkvscJkFAQpTQi5Ga0V4qWdJERajX1UZ7QqkW+I=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  timeout: 5m
  tests: false
  build-tags:
    - integration
    - unit
  skip-dirs:
    - <omitted>
  skip-files:
    - <omitted>

linters-settings:
  govet:
    check-shadowing: true
  depguard:
    list-type: allowlist
    packages:
      - <omitted>

linters:
  enable:
    - unused
    - goconst
    - gocyclo
    - revive
    - ineffassign
    - structcheck
    - varcheck
    - govet
    - depguard
    - goimports
    - misspell
    - staticcheck
  disable-all: true

issues:
  exclude-use-default: false
  exclude:
    - SA1019 # depricated check
```
</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.18 darwin/amd64
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/josh/Library/Caches/go-build"
GOENV="/Users/josh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/josh/src/go/pkg/mod"
GONOPROXY="github.com/acst"
GONOSUMDB="github.com/acst"
GOOS="darwin"
GOPATH="/Users/josh/src/go"
GOPRIVATE="github.com/acst"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="<omitted>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cf/ldfj9cts70q7b2kwgmtkz9wm0000gp/T/go-build2548637220=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by bosix** [comment]
Hi @joshua,

am I assuming right that you have added golanglint-ci via `go get` to your project?

**Comment by joshua** [comment]
Hey @bosix,

Yes, and the desired version of golangci-lint is in our go.mod before it's downgraded:

```
	github.com/golangci/golangci-lint v1.45.2
```

**Comment by ldez** [comment]
Go uses the [MVS algorithm](https://research.swtch.com/vgo-mvs) to choose the version.

So in the dependency graph, you have an older version of golangci-lint.

It's not a bug, it's just how Go modules work.

I recommend not using golangci-lint as a lib.
If you are using the tools.go pattern, I recommend adding a dedicated go.mod for your tools.

**Comment by bosix** [comment]
@joshua I recommend either download the pre-compiled binary from github in your desired version or use `go install` instead of `go get` to get golangci-lint.
