### ISSUE TITLE
struct alignment linter (e.g. structslop)

### ISSUE THREAD

**Issue by jzelinskie** [golangci/golangci-lint#2773]
### Your feature request related to a problem? Please describe.

There isn't any linter in golangci-lint that warms about wasted space from struct alignment.

### Describe the solution you'd like.

I found https://github.com/orijtech/structslop and wondered if it would be a good edition.

### Describe alternatives you've considered.

I've found some older tools used for this purpose, but I think structslop is most recently maintained.

**Comment by ldez** [comment]
Hello,

you can already use the govet analyzer called `fieldalignment`


https://golangci-lint.run/usage/linters/#govet
