### ISSUE TITLE
Add Linter: modcons

### ISSUE THREAD

**Issue by ghostsquad** [golangci/golangci-lint#2786]
### Your feature request related to a problem? Please describe.

Looking for a way to lint on deprecated modules:

https://medium.com/@mcdonnell.myles/managing-go-module-deprecation-3f7065c44e5c

https://github.com/go-tooling/modcons

### Describe the solution you'd like.

adding an integration with https://github.com/go-tooling/modcons

### Describe alternatives you've considered.

installing/calling modcons manually

**Comment by ldez** [comment]
Hello,

You can already handle constraints on modules with `gomodguard`

https://golangci-lint.run/usage/linters/#gomodguard

**Comment by ghostsquad** [comment]
@ldez it looks like modguard requires you to know what versions are ok/not ok. The point of this modcon is that you don't know what something may become deprecated, and thus want to be warned what it occurs.

**Comment by ghostsquad** [comment]
@ldez it looks like modguard requires you to know what versions are ok/not ok. The point of this modcon is that you don't know what something may become deprecated, and thus want to be warned what it occurs.

Please reopen?
