### ISSUE TITLE
ifshort is extreamly slow for larger builder patters

### ISSUE THREAD

**Issue by ThomasObenaus** [golangci/golangci-lint#2787]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

## Context
I like to use the build pattern approach where function calls are 'just' concatenated without storing intermediate results to configure something and then generate the result.

## Problem
In case enough calls are concatenated (~30) then the ifshort linter performance degrades drastically with each added call.

## Example Code 
```
package main

func main() {
	t := thing{}
	t.add().add().add().add().add().add().add().add().add().add().add().add().add().
		add().add().add().add().add().add().add().add().add().add().add().add().add()
}

type thing struct {
}

func (t thing) add() thing {
	return t
}
```

When I then call the linter
```
golangci-lint cache clean &&   golangci-lint -v  run --disable-all --timeout 10m --no-config -E ifshort
```

The run takes ~ 900ms but when I add more calls the performance degrades drastically:
- 1 more add: 1.7s
- 2 more add: 3.4s
- 3 more add: 6.8s
- 4 more add: 13.8s
- 5 more add: 27.3s
- 6 more add: 54.5s
- 7 more add: 1.48m

We had a builder with enough calls that lead to a execution of ifshort time of > 20m resulting in our pipeline to timeout.
And it took a while to figure out what is the actual problem.

### Version of golangci-lint

<details>

```console
golangci-lint has version 1.45.2 built from 8bdc4d3f on 2022-03-24T11:51:26Z
```

</details>

### Configuration file

<details>
None used
</details>

### Go environment

<details>

```console
go version go1.17.7 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/m/.cache/go-build"
GOENV="/home/m/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/m/work/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/m/work/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/m/work/n/ifshort-bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1585209923=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
golangci-lint cache clean &&   golangci-lint -v  run --disable-all --timeout 10m --no-config -E ifshort
INFO [lintersdb] Active 1 linters: [ifshort]      
INFO [loader] Go packages loading at mode 7 (files|name|compiled_files) took 47.698225ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 240.116µs 
INFO [linters context/goanalysis] analyzers took 1m48.592520426s with top 10 stages: ifshort: 1m48.59232851s, inspect: 191.916µs 
INFO [runner] processing took 3.897µs with stages: max_same_issues: 682ns, skip_dirs: 481ns, nolint: 481ns, max_from_linter: 301ns, cgo: 180ns, exclude-rules: 180ns, exclude: 180ns, autogenerated_exclude: 170ns, skip_files: 170ns, filename_unadjuster: 170ns, path_prettifier: 160ns, sort_results: 91ns, source_code: 90ns, diff: 90ns, path_shortener: 81ns, uniq_by_line: 80ns, identifier_marker: 80ns, severity-rules: 80ns, max_per_file_from_linter: 80ns, path_prefixer: 70ns 
INFO [runner] linters took 1m48.596960867s with stages: ifshort: 1m48.596896959s 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 1088 samples, avg is 50.6MB, max is 50.6MB 
INFO Execution took 1m48.651453525s 
```

</details>

### Code example or link to a public repository

<details>

```go
package main

func main() {
	t := thing{}
	t.add().add().add().add().add().add().add().add().add().add().add().add().add().
		add().add().add().add().add().add().add().add().add().add().add().add().add()
}

type thing struct {
}

func (t thing) add() thing {
	return t
}
```

</details>

**Comment by ldez** [comment]
Hello,

have you tried to use ifshort as a standalone command?

https://github.com/esimonov/ifshort

**Comment by ThomasObenaus** [comment]
Hi @ldez,

I get the same result, when I use the standalone command.

I used ifshort v1.0.4 (==master)

```
./ifshort  -debug vfpst  .
10:12:40.122061 load [.]
10:12:40.193156 building graph of analysis passes
1m43.554850346s ifshort@ifshort-bug
```

**Comment by ldez** [comment]
So it's an issue with this linter, golangci-lint is a wrapper around linters, then I recommend opening an issue on ifshort repository https://github.com/esimonov/ifshort

**Comment by ThomasObenaus** [comment]
@ldez ok I did so.

This is the issue on the ifshort repo: https://github.com/esimonov/ifshort/issues/29
