### ISSUE TITLE
Add binaries to releases

### ISSUE THREAD

**Issue by posener** [golangci/golangci-lint#28]
It would nice to have binaries in the release pages.
Currently the proposed way to install is to `go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`.
There are official releases though :clap: .
It would be nice to have binaries attached to the releases so one can use a specific version.

Cheers!

**Comment by golangci** [comment]
@posener thank you for suggestion, we will do it

**Comment by golangci** [comment]
@caarlos0 thank you
Now we have binaries in the [releases page](https://github.com/golangci/golangci-lint/releases). `| sh` scripts are waiting for [pr](https://github.com/goreleaser/godownloader/pull/74).

**Comment by caarlos0** [comment]
PR is merged :D should be live in a few minutes :)
