### ISSUE TITLE
Support rangerdanger

### ISSUE THREAD

**Issue by rgeronimi** [golangci/golangci-lint#280]
rangerdanger (https://github.com/mdempsky/rangerdanger) has proven useful in many projects.

To the best of my knowledge (I may be wrong), its control is not equivalently supported by golangci-lint existing linters.

**Comment by s3rj1k** [comment]
https://github.com/mdempsky/rangerdanger/pull/1/commits/4400fb56a47f99719c53bef33b5dfdb5d24c5041

**Comment by rgeronimi** [comment]
Is there any reason for rangerdanger not being used? I looked for duplicate linters within golangci-lint, but couldn't find (maybe there is one?). Thx

**Comment by jirfag** [comment]
Hi!
Pull requests are welcome, [this wiki](https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter) can help

**Comment by dertseha** [comment]
If I read the readme of the [open pull-request](https://github.com/mdempsky/rangerdanger/pull/1/files) properly, then this small linter does what go-critic (part of golang-ci) already provides: https://go-critic.github.io/overview#rangeexprcopy 

rangerdanger seems to me rather unmaintained.

**Comment by matoous** [comment]
The same functionality is now in `gofmt` which is part of `golangci-lint` so there's no longer need for this linter.

Closing.
