### ISSUE TITLE
linters-settings.thelper.test.name not working

### ISSUE THREAD

**Issue by powerman** [golangci/golangci-lint#2848]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

It's impossible to disable thelper's "t_name" check using `.golangci.yml`.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.46.0 built from 7c1d8b75 on 2022-05-09T11:16:24Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters-settings:
  thelper:
    test:
      name: false

linters:
  disable-all: true
  enable:
    - thelper
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.18.2 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/tmp/go/bug-golangci-lint-thelper/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3888433916=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
bug_test.go:5:6: parameter *testing.T should have name t (thelper)                               
func helper(tt *testing.T) {
     ^
```

</details>

### Code example or link to a public repository

<details>

```go
package bug_test

import "testing"

func helper(tt *testing.T) {
	tt.Helper()
}

func Test(tt *testing.T) {
	tt.Parallel()
	helper(tt)
}
```

</details>

**Comment by ldez** [comment]
Hello,
Have you tried to run the linter as a standalone command?
https://github.com/kulti/thelper

**Comment by powerman** [comment]
> Hello, Have you tried to run the linter as a standalone command? https://github.com/kulti/thelper

Yes - as you see I've checked this item.

**Comment by powerman** [comment]
```
$ thelper -checks=b_begin,b_first,b_name,t_begin,t_first,tb_begin,tb_first,tb_name .
$ thelper -checks=b_begin,b_first,b_name,t_begin,t_first,t_name,tb_begin,tb_first,tb_name .                                                                         
/home/powerman/tmp/go/bug-golangci-lint-thelper/bug_test.go:5:6: parameter *testing.T should have name t
```

**Comment by ldez** [comment]
https://github.com/kulti/thelper/issues/28#issuecomment-1125474834

**Comment by cbandy** [comment]
I think `.golangci.example.yml` needs to change to resolve this. It shows values set to `false`, but the [author says](https://github.com/kulti/thelper/issues/28#issuecomment-1125684723):

> You cannot configure golangci-lint using `false`.

https://github.com/golangci/golangci-lint/blob/e889b405dff8a71038c49d0a77f30782a8ae4804/.golangci.example.yml#L1447-L1461

**Comment by ldez** [comment]
The problem is the default behavior of the linter itself.

**Comment by ldez** [comment]
I will try to override the behavior in golangci-lint but it's not the right place IMHO.

**Comment by ldez** [comment]
In fact, since v1.46.0, thelper doesn't work inside golangci-lint.
I'm working on a fix.
I think I will also open an issue.
