### ISSUE TITLE
idea: add sarif output format

### ISSUE THREAD

**Issue by ZyanKLee** [golangci/golangci-lint#2866]
### Your feature request related to a problem? Please describe.

[SARIF](http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html) is becoming the de-facto industry standard for SAST scanning results. Several tools already support it, like for example gitlab, github and more.

When adding the golangci-lint action on github I was missing an option to choose SARIF as output format to allow github to import any findings into the security tab or as a check result set in pullrequests.

Using the action in its current form does not seem to satisfyingly link findings to their actual locations in the code.

### Describe the solution you'd like.

I'd like to see a SARIF output format (`output.format: sarif`) and ideally an option to define an output file name. 

### Describe alternatives you've considered.

* Using the action in its current form and live with the shortcomings. 
* Search for an alternative tool.

**Comment by nvuillam** [comment]
This would make much powerful the [integration of golangci-lint within MegaLinter](https://oxsecurity.github.io/megalinter/latest/descriptors/go_golangci_lint/) :)
