### ISSUE TITLE
support safesql

### ISSUE THREAD

**Issue by s3rj1k** [golangci/golangci-lint#287]
add support for https://github.com/stripe/safesql
to be feature comparable with gometalinter

**Comment by unmultimedio** [comment]
Hi all, any progress on this?

**Comment by SVilgelm** [comment]
This linter didn't seems to implement go analysis

**Comment by Dentrax** [comment]
cc: @zenazn Wdyt? How much does it cost to implement go analysis?

**Comment by zenazn** [comment]
I haven't contributed to `safesql` for over five years, and left Stripe nearly a year ago. Maybe worth reaching out to someone more closely involved with the project!
