### ISSUE TITLE
duplicate exhaustivestruct linters

### ISSUE THREAD

**Issue by switchupcb** [golangci/golangci-lint#2923]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

v1.46.2
```yml
disable:
  - exhaustivestruct # results in exhaustruct issues
  - exhaustruct # ignores all exhaustivestruct complaints
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

it's 2 different linters: one is deprecated (exhaustivestruct) and replaced by the second (exhaustruct)

**Comment by switchupcb** [comment]
Related: https://github.com/golangci/golangci-lint/issues/1987
