### ISSUE TITLE
Exit > 0 if we are failing to run a check

### ISSUE THREAD

**Issue by chmouel** [golangci/golangci-lint#294]
Currently when we run golangci and there is an issue with one of the checker :

<tt>
>>--- RESULTS: GOLANGCI CODE ANALYSIS ---<<
[33mWARN[0m [runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/fabric8-services/fabric8-build/app [github.com/fabric8-services/fabric8-build/app.test] github.com/fabric8-services/fabric8-build/app/test github.com/fabric8-services/fabric8-build/auth/client github.com/fabric8-services/fabric8-build/gormapp github.com/fabric8-services/fabric8-build github.com/fabric8-services/fabric8-build/controller [github.com/fabric8-services/fabric8-build/controller.test] github.com/fabric8-services/fabric8-build/controller_test [github.com/fabric8-services/fabric8-build/controller.test] github.com/fabric8-services/fabric8-build/build [github.com/fabric8-services/fabric8-build/build.test] github.com/fabric8-services/fabric8-build/build_test [github.com/fabric8-services/fabric8-build/build.test] github.com/fabric8-services/fabric8-build/configuration [github.com/fabric8-services/fabric8-build/configuration.test] github.com/fabric8-services/fabric8-build/configuration_test [github.com/fabric8-services/fabric8-build/configuration.test] github.com/fabric8-services/fabric8-build/design github.com/fabric8-services/fabric8-build/test github.com/fabric8-services/fabric8-build/application github.com/fabric8-services/fabric8-build/auth [github.com/fabric8-services/fabric8-build/auth.test] github.com/fabric8-services/fabric8-build/auth_test [github.com/fabric8-services/fabric8-build/auth.test] github.com/fabric8-services/fabric8-build/migration [github.com/fabric8-services/fabric8-build/migration.test] github.com/fabric8-services/fabric8-build/migration_test [github.com/fabric8-services/fabric8-build/migration.test] github.com/fabric8-services/fabric8-build/test/doubles github.com/fabric8-services/fabric8-build/test/recorder]: app/contexts.go:1: /tmp/gopackages429210980/go-build/net/cgo_linux.cgo1.go:1: no such file or directory and 167 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors
</tt>

<p>

golangci exit with a 0 exit code, which don't make the CI failing although there is obviously an error.

An exit code of greater than 0 would be good so we can catch this as an failure in CI

**Comment by matoous** [comment]
Use `--issues-exit-code int        Exit code when issues were found (default 1)` to make the golangci lint exit with non-zero status code of you liking. Otherwise, non-zero exit status is default, not sure since when.

Closing.
