### ISSUE TITLE
[Info only] Dependency upgrade introduces compilation error when running from source

### ISSUE THREAD

**Issue by jamietanna** [golangci/golangci-lint#2977]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

When performing an update of one of the background dependencies for `golangci-lint`, we receive a compilation error:

```
# github.com/golangci/golangci-lint/pkg/golinters
vendor/github.com/golangci/golangci-lint/pkg/golinters/paralleltest.go:12:16: undefined: paralleltest.NewAnalyzer
```

This appears to be due to https://github.com/kunwardeep/paralleltest/issues/22.

### Version of golangci-lint

<details>

(As it no longer runs, I'm sharing from the `go.mod`)

```go.mod
	github.com/golangci/golangci-lint v1.46.2
```

</details>

### Configuration file

N/A

### Go environment

<details>

```console
$ go version && go env
go version go1.18.1 darwin/arm64

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jamietanna/Library/Caches/go-build"
GOENV="/Users/jamietanna/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jamietanna/go/pkg/mod"
GONOPROXY="github.com/deliveroo/*"
GONOSUMDB="github.com/deliveroo/*"
GOOS="darwin"
GOPATH="/Users/jamietanna/go"
GOPRIVATE="github.com/deliveroo/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.1/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jamietanna/workspaces/.../go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/66/k5kpxzwn0cv5cmhkcx5ljl940000gq/T/go-build2824728241=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

Not possible, as compile fails.

### Code example or link to a public repository

N/A

**Comment by ldez** [comment]
Hello,

we build golangci-lint in our CI for each PR, and we don't have this behavior.

**Comment by jamietanna** [comment]
It looks like as part of the changes in https://github.com/golangci/golangci-lint/commit/97eea6ea4921f4594b917b38fae52506a46ea018 we'd resolved this as part of the upgrade 👍 

As we're still pinning to v1.46.2, that doesn't include this change, so we'll avoid updating the paralleltest dependency until golangci-lint is updated, too 👍

**Comment by ldez** [comment]
Yes, it's recommended to use the exact same dependencies as the golangci-lint version that you are using.

I will close this issue.
