### ISSUE TITLE
cannot find package "./run"

### ISSUE THREAD

**Issue by floatice** [golangci/golangci-lint#299]
![image](https://user-images.githubusercontent.com/18067441/48757546-14272180-ecd8-11e8-8615-2499e9fb9af9.png)

version: 1.12.2
golangci-lint run run -j 8 --issues-exit-code=0 --out-format=checkstyle src/... >gocheck.xml
go version go1.10.2 linux/amd64

[root@test212vm22 sched_calculator]# golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/jenkins/workspace/live_scheduler/LiveScheduler_AP_Build_Pack_10.10.50.122/live_scheduler/sched_calculator /home/jenkins/workspace/live_scheduler/LiveScheduler_AP_Build_Pack_10.10.50.122/live_scheduler /home/jenkins/workspace/live_scheduler/LiveScheduler_AP_Build_Pack_10.10.50.122 /home/jenkins/workspace/live_scheduler /home/jenkins/workspace /home/jenkins /home /] 
INFO Gocritic enabled checks: [appendAssign assignOp caseOrder dupArg dupBranchBody dupCase flagDeref ifElseChain regexpMust singleCaseSwitch sloppyLen switchTrue typeSwitchVar underef unlambda unslice defaultCaseOrder] 
INFO [lintersdb] Active 8 linters: [deadcode errcheck govet ineffassign megacheck structcheck typecheck varcheck] 
INFO [loader] Go packages loading at mode load deps types and syntax took 2.786872991s 
INFO [loader] SSA repr building timing: packages building 27.84877ms, total 791.92311ms 
INFO [loader] SSA for megacheck repr building timing: packages building 24.188808ms, total 731.778445ms 
INFO [runner] worker.2 took 11.52µs               
INFO [runner] worker.5 took 7.066049ms with stages: structcheck: 7.029044ms 
INFO [runner] worker.4 took 12.335031ms with stages: errcheck: 12.30734ms 
INFO [runner] worker.3 took 12.945906ms with stages: deadcode: 12.897068ms, typecheck: 12.483µs 
INFO [runner] worker.8 took 14.990861ms with stages: varcheck: 14.951411ms

**Comment by jirfag** [comment]
hi!
`golangci-lint run run` - the proper command is `golangci-lint run -j 8 --issues-exit-code=0 --out-format=checkstyle src/... >gocheck.xml`
