### ISSUE TITLE
Do not store the binary in GOPATH/bin in the Docker image 

### ISSUE THREAD

**Issue by Dirbaio** [golangci/golangci-lint#304]
Docker image version: golangci/golangci-lint:v1.12.2

For CI builds using Go 1.11 modules, it's common to cache the GOPATH between builds, so that dependencies are downloaded only once. This is usually done by mounting an external dir from the build host on top of `/go`. 

The issue is that `golangci-lint` binary is in `/go/bin/golangci-lint`. If GOPATH is mounted from outside, the binary stops being visible in the filesystem, and is thus not possible to run it.

IMO it would be better if `golangci-lint` was stored in `/usr/local/bin`, so it's always accessible.

**Comment by tpounds** [comment]
@Dirbaio Closing as it appears this was also reported in #393 and fixed by #396.
