### ISSUE TITLE
bug: couldn't distinguish 32-bit or 64-bit under arch x86_x64 when execute install.sh

### ISSUE THREAD

**Issue by jnan806** [golangci/golangci-lint#3081]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

in the function uname_arch() of the install.sh file, it couldn't distinguish 32-bit or 64-bit under arch x86_x64 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/43714056/183460137-32e12c04-c85e-4f29-a200-a602fa9a7a55.png">

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/43714056/183463098-9e1d68a2-889a-4ecf-9dab-6db80efea0c9.png">

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```
<img width="476" alt="image" src="https://user-images.githubusercontent.com/43714056/183463203-d9e723b3-16ca-4cfa-9809-b5c8276d63f6.png">

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

as far I know `x86_64` is 64bits, it's the meaning of 64, so seems more a problem with your OS than with our script.

**Comment by jnan806** [comment]
i has tried several ways to get the platform of OS, use docker image i386/ubuntu:latest

**Comment by jnan806** [comment]
> Hello,
> 
> as far as I know, `x86_64` is 64bits, it's the meaning of 64, so it seems more a problem with your OS than with our script.
> 
> https://en.wikipedia.org/wiki/X86-64

Yes , i know too. 😄  :) 

But i has tried several commands to get the platform of OS, and get different results:

use docker image ` i386/ubuntu:latest`
<img width="432" alt="image" src="https://user-images.githubusercontent.com/43714056/183541257-34a5bbbf-f312-477c-874d-05385526eba3.png">

different results of several commands
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/43714056/183541585-e3cb3472-dc57-488b-85a2-941cd251986f.png">

**Comment by jnan806** [comment]
> @jnan806 You are deployed a 32bits Docker image from a 64bits host

Yeah! But i think we should also get a correct arch even in this case. 😄  :)

**Comment by jnan806** [comment]
> @jnan806 You are deployed a 32bits Docker image from a 64bits host



> @jnan806 You are deployed a 32bits Docker image from a 64bits host



> @jnan806 You are deployed a 32bits Docker image from a 64bits host

@lbcjbb 

Yeah! But i think we should also get a correct arch even in this scenario. 😄  :)

**Comment by ldez** [comment]
> But i think we should also get a correct arch even in this scenario.

We will not agree on that: x86_64 is 64 bits and if you want to use a 32 bits image on a 64 bits system it's your choice but we will promote that because, for me, it's bad practice.
