### ISSUE TITLE
Upgrade go-critic

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint#3096]
### Your feature request related to a problem? Please describe.

go-critic has just released https://github.com/go-critic/go-critic/releases/tag/v0.6.4, containing upgraded ruleguard and x/tools. This might help solving some of the panics experienced on Go 1.19

### Describe the solution you'd like.

Upgrade and release

### Describe alternatives you've considered.

None available that I could eventually use on ci

**Comment by ldez** [comment]
I'm working on it #3089
