### ISSUE TITLE
docs: missing image version for the Docker installation

### ISSUE THREAD

**Issue by robel-yemane** [golangci/golangci-lint#3103]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

The docker installation method specified in the website and/or `README` is inaccurate

The command as specified here https://golangci-lint.run/usage/install/#docker i.e. 
```
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint: golangci-lint run -v
```
is not executable and results in a docker error
```
docker: invalid reference format.
See 'docker run --help'.
```
suggested fix:
```
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint golangci-lint run -v
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.48.0 built from 2d8fea81 on 2022-08-04T19:06:48Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
N/A
```

</details>

### Go environment

<details>

```console
$ go version && go env
N/A
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
N/A
```

</details>

### Code example or link to a public repository

<details>

```go
N/A
```

</details>

**Comment by ldez** [comment]
hello,

the problem is fixed, it was just a bug during the generation of the doc.
