### ISSUE TITLE
make `decorder` usable

### ISSUE THREAD

**Issue by jabielecki** [golangci/golangci-lint#3138]
### Your feature request related to a problem? Please describe.

Currently, when a user adds the [`decorder`](https://gitlab.com/bosi/decorder) linter the [default](https://github.com/golangci/golangci-lint/blob/58809c3bf5d4e94500f7880978b6eb5e204f0f96/pkg/config/linters_settings.go#L15-L17) configuration makes the linter silently ignore all its findings.

Consider cognitive load. For a vaguely interested user, it's already a hop to find a relevant linter in the list. Enabling that linter is another hop. Frustratingly, nothing happens. Learning about per-linter configs would be the 3rd hop and configuring this specific linter is the 4th hop.

Let's skip hops 3 and 4.

### Describe the solution you'd like.

Change [the above defaults](https://github.com/golangci/golangci-lint/blob/58809c3bf5d4e94500f7880978b6eb5e204f0f96/pkg/config/linters_settings.go#L15-L17) for `decorder` in a major release (v2) to:

```
		DisableDecNumCheck:        true,
		DisableDecOrderCheck:      false,
		DisableInitFuncFirstCheck: false,
```
(Leaving the first one `true` as it was, but it's only a subjective suggestion.)

### Describe alternatives you've considered.

Change the defaults for `decorder` in a minor v1.x release. This doesn't impact users who run the default set of linters, because `decorder` isn't one. There are however users who enable `decorder` and such a minor version upgrade would very likely get them new findings.

### Additional context.

Example of the findings under the new settings:

```go
type A struct{}

var my A
var yours A

type X int  # finding: type must not be placed after var

func NewA() A {
     return A{}
}

func (a A) Println() {
    fmt.Println(a)
}

func init() { # finding: init func must be the first function in file
}

```

**Comment by ldez** [comment]
Hello,

> Currently, when a user adds the [decorder](https://gitlab.com/bosi/decorder) linter the [default](https://github.com/golangci/golangci-lint/blob/58809c3bf5d4e94500f7880978b6eb5e204f0f96/pkg/config/linters_settings.go#L15-L17) configuration makes the linter silently ignore all its finding

Yes, it's the expected behavior.

https://github.com/golangci/golangci-lint/pull/2453#issuecomment-1005025914

> Change the defaults for decorder in a minor v1.x release. This doesn't impact users who run the default set of linters, 

A lot of users use `enable-all` option, so there is an impact.

**Comment by jabielecki** [comment]
> Yes, it's the expected behavior.

Sorry, no. As is it's unexpected behavior. I would expect that an (arguably very very opinionated) linter requires 2 mental hops:
  - to find a relevant linter in the list
  - to enable that linter and deal with the findings
 
It is unexpected and frustrating that in fact obtaining any findings requires two more mental hops:
  - learning about per-linter configs
  - configuring this specific linter


> A lot of users use `enable-all` option, so there is an impact.

Alas, my proposition was intended towards a `v2` milestone...

**Comment by ldez** [comment]
Sorry, but it's the behavior that I expect for this opinionated linter.

We can change a linter configuration without creating a v2.

**Comment by jabielecki** [comment]
I'm not saying it's unexpected to the maintainer. I'm saying it's unexpected to a user.

As a user, I install a meta-linter. I take a look at a list of *disabled* linters. Say a line catches my eye:

```
decorder: check declaration order and count of types, constants, variables and functions [fast: true, auto-fix: false]
```

Now I enable this linter. I expect it to **check declaration order**. It's not out of this earth, it literally promises me that, right there. As of now, it does absolutely nothing.

**Comment by ldez** [comment]
I just want to explain a bit more why, for me, this linter is way too much opinionated and in some way wrong.
And so this explains why I choose to disable all the options by default.

---

Case 1: Methods and types

```yaml
linters-settings:
  decorder:
    disable-dec-num-check: true
    disable-dec-order-check: false
    disable-init-func-first-check: true
```

<details>
<summary>Before</summary>

```go
package cli

type Yo struct {
	Foo string `description:"Foo description"`
	Fii string `description:"Fii description"`
	Fuu string `description:"Fuu description"`
	Yi  *Yi    `label:"allowEmpty" file:"allowEmpty"`
	Yu  *Yi
}

func (y *Yo) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}

type Yi struct {
	Foo string
	Fii string
	Fuu string
}

func (y *Yi) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}
```

```console
cli/fixtures_test.go:16:1: type must not be placed after func (decorder)
type Yi struct {
^
```

</details>


<details>
<summary>After</summary>

```go
package cli

type Yo struct {
	Foo string `description:"Foo description"`
	Fii string `description:"Fii description"`
	Fuu string `description:"Fuu description"`
	Yi  *Yi    `label:"allowEmpty" file:"allowEmpty"`
	Yu  *Yi
}

type Yi struct {
	Foo string
	Fii string
	Fuu string
}

func (y *Yo) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}

func (y *Yi) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}
```

</details>


Splitting Struct types and methods is not a good practice: this decrease the readability and maintainability.

---

Case 2: Grouping types

```yaml
linters-settings:
  decorder:
    disable-dec-num-check: false
    disable-dec-order-check: true
    disable-init-func-first-check: true
```

<details>
<summary>Before</summary>

```go
package cli

type Yo struct {
	Foo string `description:"Foo description"`
	Fii string `description:"Fii description"`
	Fuu string `description:"Fuu description"`
	Yi  *Yi    `label:"allowEmpty" file:"allowEmpty"`
	Yu  *Yi
}

func (y *Yo) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}

type Yi struct {
	Foo string
	Fii string
	Fuu string
}

func (y *Yi) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}
```

```console
cli/fixtures_test.go:11:1: multiple "type" declarations are not allowed; use parentheses instead (decorder)
type Yi struct {
^
```

</details>


<details>
<summary>After</summary>

```go
package cli

type (
	Yo struct {
		Foo string `description:"Foo description"`
		Fii string `description:"Fii description"`
		Fuu string `description:"Fuu description"`
		Yi  *Yi    `label:"allowEmpty" file:"allowEmpty"`
		Yu  *Yi
	}

	Yi struct {
		Foo string
		Fii string
		Fuu string
	}
)

func (y *Yo) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}

func (y *Yi) SetDefaults() {
	y.Foo = "foo"
	y.Fii = "fii"
}
```

</details>


Grouping Struct types without their methods is not a good practice: this decrease the readability and maintainability.

---

Case 3: grouping constants

```yaml
linters-settings:
  decorder:
    disable-dec-num-check: false
    disable-dec-order-check: true
    disable-init-func-first-check: true
```

<details>
<summary>Before</summary>

```go
package cli

// Code of Bar.
const (
	CodeBarA = 100
	CodeBarB = 101
)

// Status of Foo.
const (
	StatusFooA = "A"
	StatusFooB = "B"
)
```

```console
cli/foo.go:10:1: multiple "const" declarations are not allowed; use parentheses instead (decorder)
const (
^
```

</details>

<details>
<summary>After</summary>

```go
package cli

const (
	CodeBarA = 100
	CodeBarB = 101

	StatusFooA = "A"
	StatusFooB = "B"
)
```

</details>


Even with an empty line we have lost the meaning of the const groups.
Also, the "global" comments must be removed because a comment inside the group is linked to one element instead of a group.

Once again this is bad practice.

---

I will not list all the problems related to this strongly opinionated linter.

**Comment by jabielecki** [comment]
Thank you for illustrating this so well!

For the cases 2 and 3 I can only agree. This is why I began with `DisableDecNumCheck: true`, to specifically avoid case 2 and 3.

My intended usage was a variant of your case 1 but with added enforcement of max one `type` declaration per source file. After playing with it for a while, I'd say I was wrong, and the strongest reason against it is that it tends to discourage adding small private types with methods when coding a big function. ("The complexity needs to go somewhere" and in my experience it tends to go into more complex functions passing more arguments around.)
