### ISSUE TITLE
New linter: punused for finding exported but unused symbols

### ISSUE THREAD

**Issue by Southclaws** [golangci/golangci-lint#3143]
### Your feature request related to a problem? Please describe.

https://github.com/bep/punused

Sometimes, non-Go engineers or inexperienced Go engineers inadvertently export symbols by accident simply by naming them with uppercase. The unused/deadcode linters don't capture this as an exported symbol is considered part of the public API and thus not considered "unused".

But in applications (not libraries) this is problematic as deprecated functions can accumulate and it's unclear whether or not they are used in other parts of the code. punused solves this quite nicely and it would be great to see it added as part of the linters.

### Describe the solution you'd like.

https://github.com/bep/punused be added and part of the deadcode linter group (though it's quite slow especially on large projects so probably best not to include it as a default or part of the "fast" category)

### Describe alternatives you've considered.

I can't find any other projects that actually do dead code analysis on exported functions and symbols.

### Additional context.

If I find the time and people are cool with this, I could draft a PR and implement it myself. As long as there are no issues, give me the green light here and I'll find some time to integrate it!

**Comment by ldez** [comment]
Hello,

https://github.com/bep/punused#readme
> For all other similar use cases, use https://github.com/dominikh/go-tools

https://github.com/dominikh/go-tools is staticcheck, staticcheck (unused) is already inside golangci-lint.

**Comment by bombsimon** [comment]
`punused` does not use [`go/analysis`](https://pkg.go.dev/golang.org/x/tools/go/analysis) which is a requirement ([docs](https://golangci-lint.run/contributing/new-linters/)).

**Comment by ldez** [comment]
@bombsimon is right.

> I can't find any other projects that actually do dead code analysis on exported functions and symbols.

It's expected to didn't find this kind of tool because it will produce a ton of false positives.

I can see a use case for some applications but in the majority of cases, unused exported functions are expected.

**Comment by Southclaws** [comment]
In a library, yes but in an application, no it's still considered dead code if it's unused.

I'll continue using the command line tool for now and see if I can make it use the go/analysis library.
