### ISSUE TITLE
rebuild the documentation (please)

### ISSUE THREAD

**Issue by lookfirst** [golangci/golangci-lint#3191]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

The docs mention an oldvers version of golangci-lint

![2022-09-05 at 03 04 58](https://user-images.githubusercontent.com/85355/188352951-0c8956b4-6330-4bb5-98ec-2d9283907d17.png)

 which fails in my go 1.19 build:

![2022-09-05 at 03 04 10](https://user-images.githubusercontent.com/85355/188352924-bf81d598-e833-425c-a46d-bdbb5ba033b7.png)

upgrading to 1.49.0 succeeds:

![2022-09-05 at 03 07 09](https://user-images.githubusercontent.com/85355/188353144-3ad46572-99ff-4930-86a2-7a1ff88b26e3.png)

### Version of golangci-lint

1.49.0

### Configuration file

no needed

### Go environment

go 1.19

### Verbose output of running

see screenshots

### Code example or link to a public repository

see screenshots

**Comment by bombsimon** [comment]
The docs are rebuilt on every new release with [this GitHub action](https://github.com/golangci/golangci-lint/actions/workflows/post-release.yml). As you can see last time this happened was 12 days ago when we released v1.49.0. I don't know when you took this screenshot but if recent it might be some caching issues, this is what it looks like for me:

![image](https://user-images.githubusercontent.com/3248948/188373675-254e3472-60bd-4467-a47c-2137e1a60eeb.png)

**Comment by lookfirst** [comment]
@bombsimon Sorry about that, looks like it was a caching issue!
