### ISSUE TITLE
broken all paths in subprojects

### ISSUE THREAD

**Issue by Vany** [golangci/golangci-lint#3213]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

i'm not sure, but #2654 may be related

***there is no `go.mod` in the root folder***

```console
$ cd libclient
$ head go.mod -n3
module github.com/binarly-io/client/libclient

go 1.18

$ GO111MODULE=on  golangci-lint run -v ./...
INFO [config_reader] Config search paths: [./ /home/vany/w/b/client/libclient /home/vany/w/b/client /home/vany/w/b /home/vany/w /home/vany /home /] 
INFO [lintersdb] Active 7 linters: [errcheck gosimple govet ineffassign staticcheck typecheck unused] 
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|imports|exports_file|files|name|types_sizes) took 176.768616ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 5.49µs 
ERRO [linters context] typechecking error: # github.com/binarly-io/client/libclient [github.com/binarly-io/client/libclient.test]
./cmd_root.go:4:2: could not import reflect (open : no such file or directory)
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.49.0 built from (unknown, mod sum: "h1:I8WHOavragDttlLHtSraHn/h39C+R60bEQ5NoGcHQr8=") on (unknown)
```

</details>

### Configuration file

.golangci.yml is not used yet

### Go environment

<details>

```console
$ go version && go env
go version go1.18.5 linux/amd64
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vany/.cache/go-build"
GOENV="/home/vany/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vany/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vany/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9952"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9952/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vany/w/b/client/libclient/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2674431381=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v

story the same

```

</details>

### Code example or link to a public repository

<details>

all imports

</details>

**Comment by ldez** [comment]
Hello,

without a concrete reproducible context, it's impossible to diagnose the problem.

**Comment by Vany** [comment]
@ldez
there is very simple context  GO111MODULE=on  +  go.mod in folder

**Comment by Vany** [comment]
and sorry, i can't provide the code.

**Comment by ldez** [comment]
so no concrete reproducible context.

golangci-lint has mainly the same constraints as Go.
go.mod is required.
you cannot use golangci-lint to check several projects at the same time.
That's all that I say based on your information.

**Comment by dmitrytrager** [comment]
I've got this kind of error after switching from 1.46

**Comment by foamzou** [comment]
May cause by import cycles in test file?

ref:  https://github.com/golang/go/issues/51180

I occurred the issue as well, I found there are import cycles in my test file. When I fixed the problem, the error was dismissed.

**Comment by Vany** [comment]
@foamzou Yes =) It is. Thankyou =)
