### ISSUE TITLE
can't use an "easy install" way, on 64bit RISC-V port of Ubuntu

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golangci/golangci-lint#3219]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Cross-referencing [here](https://github.com/client9/shlib/issues/40)

```
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
golangci/golangci-lint crit uname_arch_check 'riscv64' got converted to 'riscv64' which is not a GOARCH value. Please file bug report at https://github.com/client9/shlib
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
golangci/golangci-lint crit uname_arch_check 'riscv64' got converted to 'riscv64' which is not a GOARCH value. Please file bug report at https://github.com/client9/shlib
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
golangci/golangci-lint crit uname_arch_check 'riscv64' got converted to 'riscv64' which is not a GOARCH value. Please file bug report at https://github.com/client9/shlib
```

I shall clone the git repo of the project and install it locally.
I shall report whether it would success or fail.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version (devel) built from (unknown, mod sum: "") on (unknown)

```

</details>

### Configuration file

Not using

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by advancedwebdeveloper** [comment]
All the above checkboxes are untrue

**Comment by ldez** [comment]
Hello,

you can close this issue https://github.com/client9/shlib/issues/40 because it's not related to shlib.
