### ISSUE TITLE
Override `fix: true` via command line arguments

### ISSUE THREAD

**Issue by davidhsingyuchen** [golangci/golangci-lint#3231]
### Your feature request related to a problem? Please describe.

We woud like to specify `fix: true` in our `.golangci.yml` so that issues can be fixed when `golangci-lint` is invoked in terminal, IDE, etc. However, there's a single place we want to set `fix: false`, and that's when `golangci-lint` is run in CI build; if there is an issue, we want the CI to fail instead of fixing it.

### Describe the solution you'd like.

Enable us to override `fix: true` via command line arguments, which can then be passed as [`args`](https://github.com/golangci/golangci-lint-action/blob/9305be5e9f16995e5ce5b96adb87810383511507/action.yml#L8).

### Describe alternatives you've considered.

Set `fix: false` in config file and override that via passing `--fix` when `golangci-lint` is invoked by things other than CI build. The downside of this is that we need to configure multiple places.

**Comment by ldez** [comment]
Hello,

The default value for `fix` is `false`, so you just have to not define `fix: false` in the config.

**Comment by davidhsingyuchen** [comment]
Hi @ldez , I've mentioned that:

> Describe alternatives you've considered.
Set `fix: false` in config file and override that via passing `--fix` when `golangci-lint` is invoked by things other than CI build. The downside of this is that we need to configure multiple places.

**Comment by davidhsingyuchen** [comment]
Hi @ldez,

> The default value for fix is false, so you just have to not define fix: false in the config.

Yeah, that holds when you _want_ the default value to be `false`. We want the default value to be `true`, so we want to set it to be `true` in the config file to avoid the need of setting it to be `true` in multiple places (e.g., Makefile, IDE, all the other places except for CI).

**Comment by ldez** [comment]
the behavior is the same for all args, we will not create a different behavior only for one arg.

**Comment by davidhsingyuchen** [comment]
Thank you for your time. I just realized that I can simply write `--fix=false` to achieve my goal. Leaving this comment in case anyone is unaware of that obvious fact like I was.
