### ISSUE TITLE
paralleltest config does not work

### ISSUE THREAD

**Issue by yonderblue** [golangci/golangci-lint#3232]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Using
```
paralleltest:
    ignore-missing: true
```
does not work, however using `-i` on the paralleltest command directly does.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml

linters-settings:
  paralleltest:
    ignore-missing: true

linters:
  disable-all: true
  enable:
    - paralleltest
```

</details>

### Go environment

<details>

```console
$ go version && go env

go1.18.2 darwin/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v

Same result..
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

can you fill in the required information (version, output, etc.) in the issue description?

**Comment by ldez** [comment]
`ignore-missing` works well, I think you are not using the right version of golangci-lint.
