### ISSUE TITLE
Support gocritic tags

### ISSUE THREAD

**Issue by lopezator** [golangci/golangci-lint#324]
Instead of having to add each specific enabled check inside gocritic (which could be painful for newcomers), isn't a way to add groups of checks (called tags) like #performance, #style...? 

If this isn't implemented yet I think it would be very interesting.

Reference:

https://github.com/go-critic/go-critic#usage -> section "Tags"

**Comment by jirfag** [comment]
I've supported gocritic tags in the linked pull request.
/cc @Quasilyte
