### ISSUE TITLE
Please upgrade go-revive to a latest version and release new patch version

### ISSUE THREAD

**Issue by jan-dubsky** [golangci/golangci-lint#3250]
### Your feature request related to a problem? Please describe.

We'd love to upgrade to the latest version of `golangci-lint` because of Go 1.19 support. Unfortunately this version uses `go-revive` with a bug that lint single-line functions as errors [1]. Because our codebase uses many single-line functions, this issue blocks us from upgrading. go-revive just released a new patch version where this bug is fixed [2].

[1]: https://github.com/mgechev/revive/issues/739
[2]: https://github.com/mgechev/revive/issues/747#issuecomment-1259795903

### Describe the solution you'd like.

Please upgrade `go-revive` to a latest version (v1.2.4) and then release new patch version of `golangci-lint`.

### Describe alternatives you've considered.

Technically it is possible to wait for a new release. This is undesirable because this bug is blocking us from upgrading to Go 1.19 in general.

**Comment by ldez** [comment]
Hello, we use dependabot, the bot will update the linter at the end of the week.

**Comment by jan-dubsky** [comment]
> Hello, we use dependabot, the bot will update the linter at the end of the week.

OK, but according to git history, the bot won't release new patch version, will it?

**Comment by ldez** [comment]
I don't talk about the release of golangci-lint but about the update of the dependencies.

We will not create a patch release because we already merged other changes.

**Comment by jan-dubsky** [comment]
Ok, so if I read your comment correctly we just have to wait for release of a new version even though the latest official version contains a bug that block us? That doesn't sound right.

> We will not create a patch release because we already merged other changes.
Why is it an issue to create a "bugfix" branch based on `v1.49.0` with just this dependency updated? Why is the fact that other changes were merged considered blocking at all?

**Comment by ldez** [comment]
> Why is it an issue to create a "bugfix" branch based on v1.49.0 with just this dependency updated? 

Because we don't branch release branch, it's too much maintenance.

> Why is the fact that other changes were merged considered blocking at all?

Because we follow semver

**Comment by bombsimon** [comment]
>  the latest official version contains a bug that block us

If you're blocked I suggest either downgrading to a version that does not block you or build from source while waiting for a new release.
