### ISSUE TITLE
Documentation issue with loggercheck linter

### ISSUE THREAD

**Issue by sebastien-rosset** [golangci/golangci-lint#3270]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I am reporting a documentation issue. The list of linters is documented at https://golangci-lint.run/usage/linters/. The list includes "loggercheck":

loggercheck ⚙️ | Checks key valur pairs for common logger libraries (kitlog,klog,logr,zap). | style, bugs |   | v1.49.0
-- | -- | -- | -- | --

There are two problems:
1. There is a small typo: "value", not "valur".
2. The loggercheck linter is not listed when typing the `golangci-lint linters` version 1.49. Instead, the command lists a `logr` linter which is not documented at https://golangci-lint.run/usage/linters/.

This seems to be a side effect of https://github.com/golangci/golangci-lint/pull/3144, which was merged on Aug 31. Initially I thought that PR was merged before 1.49, but 1.49 was released before on Aug 24. The documentation refers to the new linter name.

### Version of golangci-lint

<details>

```console
$ golangci-lint version
golangci-lint has version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z
```

</details>

### Configuration file

Not applicable, this is a documentation issue.
<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment
Not applicable, this is a documentation issue.

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running
Not applicable, this is a documentation issue.

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository
Not applicable, this is a documentation issue.

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,

it's because logrlint has been renamed to loggercheck.

In the next release (v1.50.0), the name logrlint will be an alias on loggercheck.

The version at the end of the line is the version when the linter (logrlint) has been introduced.

We publish the documentation automatically, when required, without any "link" with a version of golangci-lint.

The typo `valur` is inside the linter itself:
https://github.com/timonwong/loggercheck/blob/216be45f6bb8195e278d2c16608f9b0f3e2f0198/loggercheck.go#L21
