### ISSUE TITLE
Support configurable file extensions for `misspell` linter

### ISSUE THREAD

**Issue by sebastien-rosset** [golangci/golangci-lint#3272]
### Your feature request related to a problem? Please describe.

When the [misspell](https://github.com/client9/misspell) linter is integrated with `golangci-lint`, the linter analyzes files that have the `*.go` extension. The `misspell` linter is useful for `.go` files, but it's also useful for files with other extensions. For example, a go code generator may use a `.template` file to generate go code. It's valuable to scan the template file since it is the file that contains the source of truth.

Furthermore:
1. The `misspell` integration is not consistent with the [bidichk](https://github.com/breml/bidichk) linter integration, which scans all the files. IMHO, `misspell` and `bidichk` are in the same category, they are useful for files with various extensions.
2. The [misspell](https://github.com/client9/misspell) documentation clearly states it can be used for any type of file, but when used under `golangci-lint`, only `.go` files are scanned, and I don't think this behavior is documented. Maybe I missed the documentation.

The misspell integration scans the files with `.go` extensions:
https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/misspell.go#L64

### Describe the solution you'd like.

Either scan all files by default, or expose settings to allow users to customize which files should be scanned.
For example, there could be a new `include-files` config parameter under the `misspell` settings. The default value would be `.*\\.go$` for backwards-compatibility.

### Describe alternatives you've considered.

Run `misspell` independently of `golangci-lint`.

### Additional context.

The following parameters need to be taken into consideration: `skip-dirs-use-default`, `skip-files` and `skip-dirs`.
https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml#L29-L51

**Comment by ldez** [comment]
I think you misinterpreted this line https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/misspell.go#L64: this is not a filter on go files (because only go files are in the pass) it's a trick related to CGo.


bidichk follows the same constraints.

**Comment by sebastien-rosset** [comment]
Thanks for the quick feedback. Would it make sense to allow these two linters to scan more than just files with `.go` extensions?

**Comment by ldez** [comment]
> Would it make sense to allow these two linters to scan more than just files with .go extensions?

The `pass` is linked to the cache, and the cache is the "secret" of the golangci-lint performances. The `pass` is filled in by the Go code analysis system from Go itself.

Golangci-lint handles Go code, so it's off-topic to handle other file types.

**Comment by sebastien-rosset** [comment]
ok, thanks. We will run bidicheck and misspell separately then.
