### ISSUE TITLE
Change not to use linter with AGPL lisence

### ISSUE THREAD

**Issue by momom-i** [golangci/golangci-lint#3337]
### Your feature request related to a problem? Please describe.

Hi, I've used golangci-lint but after upgrading its version to latest one, I found the linter with AGPL lisence was added([github.com/leonklingele/grouper](https://github.com/leonklingele/grouper), PR: https://github.com/golangci/golangci-lint/pull/2497).
I can't find discussion around it, but I don't think it's a good idea to use that because user might have to disclose their source codes.

### Describe the solution you'd like.

Changing its license or not to use it

### Describe alternatives you've considered.

If there is a special reason, we might not have to change it.

**Comment by ldez** [comment]
Hello,

our license is GPL, you already have to disclose your code.

https://github.com/golangci/golangci-lint/blob/master/LICENSE

> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there. 

THE AGPL variant is about network use, in the case of golangci-lint it doesn't make a real difference.

**Comment by bombsimon** [comment]
According to #232, Google does not allow AGPL licenses. The issue references [this page](https://opensource.google/documentation/reference/using/agpl-policy) which explains why it's not allowed at Google.

**Comment by ldez** [comment]
I don't agree with the fact to be forced by Google to follow Google.
But we will follow the initial direction, I asked to @leonklingele to change the license of grouper https://github.com/leonklingele/grouper/issues/1.

If the license is not changed we will just drop the linter.

**Comment by momom-i** [comment]
Thank you for listening to my opinion. I'm waiting for that.

**Comment by momom-i** [comment]
@ldez How is it going?

**Comment by ldez** [comment]
Just be clear: our license is GPL, you already have to disclose any changes that you do in golangci-lint, the grouper license doesn't change that.

As you can see, we are still waiting for an answer of @leonklingele

**Comment by leonklingele** [comment]
I'm a bit busy these days but will get back to this asap.

**Comment by momom-i** [comment]
@ldez In my understanding, the difference between GPL and AGPL is disclosure range. As you said, GPL has surely obligation to disclose codes if developer provides binary using a module with that license in public, but when they provides web service using that in server side, they don't have to disclose their codes.
And AGPL don't allow that case.
Anyway,  personally, our company doesn't allow us to use AGPL module. So I'd appreciate if you'd decide whether change it or not soon because we need to consider whether to continue using golangci-lint in some cases.

**Comment by leonklingele** [comment]
Just to better understand the problem here. It’s because AGPL is not allowed at Google and we want the project to be usable there?

**Comment by ldez** [comment]
It’s because AGPL is not allowed at Google and other companies.

**Comment by leonklingele** [comment]
https://github.com/golangci/golangci-lint/pull/3372
