### ISSUE TITLE
Update README.md information about default enabled linters

### ISSUE THREAD

**Issue by vpakhuchyi** [golangci/golangci-lint#334]
Hi, 

In my version of golangci-lint following linters are enabled by default: 

- gochecknoglobals
- gocritic
- scopelint
- gochecknoinits

Please update information about default enabled linters in README.md. Currently in README.md pointed that these linters are disabled by default - it's not correct. 
Thanks!

1. Version of golangci-lint:  golangci-lint has version 1.12.3 built from 014a924 on 2018-11-24T08:54:08Z
2. Config file: `cat .golangci.yml`: N/A
3. Go environment: `go version && go env`:

> go version go1.11.2 darwin/amd64
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/vpakh/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/vpakh/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zs/g36kxyq96vb1d12dd4gslm2c0000gp/T/go-build739705085=/tmp/go-build -gno-record-gcc-switches -fno-common"

4. Verbose output of running: `golangci-lint run -v`: N/A

**Comment by jirfag** [comment]
Hi!
How did you find out that these linters are enabled by default?

I can't reproduce:
```bash
$ git checkout v1.12.3
$ go run ./cmd/golangci-lint/main.go linters --no-config
Enabled by your configuration linters:
govet: Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string [fast: true]
errcheck: Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: true]
megacheck: 3 sub-linters in one: unused, gosimple and staticcheck [fast: false]
structcheck: Finds an unused struct fields [fast: true]
varcheck: Finds unused global variables and constants [fast: true]
typecheck: Like the front-end of a Go compiler, parses and type-checks Go code [fast: true]
ineffassign: Detects when assignments to existing variables are not used [fast: true]
deadcode: Finds unused code [fast: true]

Disabled by your configuration linters:
golint: Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: true]
staticcheck: Staticcheck is a go vet on steroids, applying a ton of static analysis checks [fast: false]
unused: Checks Go code for unused constants, variables, functions and types [fast: false]
gosimple: Linter for Go source code that specializes in simplifying a code [fast: false]
gosec (gas): Inspects source code for security problems [fast: true]
interfacer: Linter that suggests narrower interface types [fast: false]
unconvert: Remove unnecessary type conversions [fast: true]
dupl: Tool for code clone detection [fast: true]
goconst: Finds repeated strings that could be replaced by a constant [fast: true]
gocyclo: Computes and checks the cyclomatic complexity of functions [fast: true]
gofmt: Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true]
goimports: Goimports does everything that gofmt does. Additionally it checks unused imports [fast: true]
maligned: Tool to detect Go structs that would take less memory if their fields were sorted [fast: true]
depguard: Go linter that checks if package imports are in a list of acceptable packages [fast: true]
misspell: Finds commonly misspelled English words in comments [fast: true]
lll: Reports long lines [fast: true]
unparam: Reports unused function parameters [fast: false]
nakedret: Finds naked returns in functions greater than a specified function length [fast: true]
prealloc: Finds slice declarations that could potentially be preallocated [fast: true]
scopelint: Scopelint checks for unpinned variables in go programs [fast: true]
gocritic: The most opinionated Go source code linter [fast: true]
gochecknoinits: Checks that no init functions are present in Go code [fast: true]
gochecknoglobals: Checks that no globals are present in Go code [fast: true]
```

Maybe you use config file where these linters are enabled? You didn't paste `golangci-lint run -v` in the description, therefore I can't say more. Closing it, reopen with `run -v` output if you are sure that linters are enabled.
