### ISSUE TITLE
The "unused" linting rule has misleading behaviour when interacting with generated code

### ISSUE THREAD

**Issue by adamroyjones** [golangci/golangci-lint#3354]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

One of the default linters, unused, is described on [the golangci-lint site](https://golangci-lint.run/usage/linters/) as something that

> [c]hecks Go code for unused constants, variables, functions and types

but if a constant, variable, function, or type is only referred to in a generated file, then golangci-lint will act in a misleading way.

I _think_ this should be categorised as a bug, but it may be that I've missed a piece of configuration that I can set.

### Version of golangci-lint

```console
$ golangci-lint --version
golangci-lint has version 1.50.1 built from 8926a95f on 2022-10-22T10:50:47Z
```

### Configuration file

```console
$ cat .golangci.yml
---
run:
  timeout: 20m

linters:
  disable-all: true
  enable:
    - unused
```

### Go environment

The reproducing example at the end uses a Dockerfile.

### Verbose output of running

The reproducing example at the end uses a Dockerfile.

### Code example or link to a public repository

The "details" block below describes the following directory structure (which I've also attached as a tarball [here](https://github.com/golangci/golangci-lint/files/9982882/golangci-lint-reprex.tar.gz)):

```
.
├── bar.go
├── Dockerfile
├── foo.go
├── .golangci.yml
├── go.mod
└── rc.sh
```

First, recreate this directory structure and set `rc.sh` to be executable.

1. If you run `./rc.sh`, then golangci-lint will report that the function `foo` is unused.

2. If you remove the first line from foo/bar.go (that says the file is generated) and then run `./rc.sh`, then golangci-lint will now report that both `foo` and `bar` are unused.

3. If you replace `bar` with `Bar`, then, irrespective of the line at the top about the file being generated being present, everything is (correctly) declared as being used.

In my view, the messages in 1 and 2 are misleading. In both cases, the issue is that `bar` isn't public (and therefore isn't used); `foo` is only unused as a consequence of `bar` not being used. This is especially awkward in 1, because there's no way to resolve the problem from the error message alone.

<details>

```go
// bar.go
// Code generated by hand. DO NOT EDIT.
package foo

func bar() {
	foo()
}
```

```Dockerfile
# Dockerfile
FROM golang:1.19-bullseye

RUN apt-get update && \
  apt-get install curl && \
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1

RUN mkdir /reprex
WORKDIR /reprex
```

```go
// foo.go
package foo

func foo() {}
```

```yaml
# .golangci.yml
---
run:
  timeout: 20m

linters:
  disable-all: true
  enable:
    - unused
```

```go
// go.mod
module golangci-lint-reprex

go 1.19
```

```sh
# rc.sh
#! /usr/bin/env sh

docker build --tag golangci-lint-reprex .

docker container run \
  --mount type=bind,source=$(pwd),destination=/reprex \
  -it \
  golangci-lint-reprex \
  golangci-lint run ./...
```

**Comment by adamroyjones** [comment]
I'll see if I can put together a reproduction of what I mentioned above as the "dual" behaviour, since that type of problem is a bigger concern.

**Comment by adamroyjones** [comment]
(Closing for now, as I need to clean up the examples and should produce the dual example. Everything's a bit mangled. I'll try to reopen things later today.)

**Comment by adamroyjones** [comment]
Right—apologies for the noise above. I've replaced the example with someone that should be clearer.

**Comment by ldez** [comment]
Hello,

`unused` comes from [staticcheck](https://github.com/dominikh/go-tools), have you tried this linter as suggested by the checkbox "Yes, I've tried with the standalone linter if available"?
