### ISSUE TITLE
Upgrade broken version of GCI.

### ISSUE THREAD

**Issue by benmathews** [golangci/golangci-lint#3365]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Golangci-lint includes GCI 0.8.2. It has a bug that is fixed in the [latest release](https://github.com/daixiang0/gci/releases/tag/v0.8.4). Upgrade please.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

**Comment by ldez** [comment]
Hello,

We have a bot that update automatically the linter.
