### ISSUE TITLE
Update README.txt with instructions for how to install on Windows

### ISSUE THREAD

**Issue by Zamiell** [golangci/golangci-lint#338]
For local installations, the README.txt says the following:

```
go get -u github.com/golangci/golangci-lint
cd $(go env GOPATH)/src/github.com/golangci/golangci-lint/cmd/golangci-lint
go install -ldflags "-X 'main.version=$(git describe --tags)' -X 'main.commit=$(git rev-parse --short HEAD)' -X 'main.date=$(date)'"
```

However, this fails on Windows because of the command substitution (`$(date)`). How are other people installing this on Windows?

**Comment by jirfag** [comment]
@AlekSi it looks like the issue without GoReleaser script.

@Zamiell - we have the line `(On Windows, you can run the above commands with Git Bash, which comes with [Git for Windows](https://git-scm.com/download/win).)` in our README. Did you try it, does it help?

**Comment by Zamiell** [comment]
I wrote that line lol

**Comment by Zamiell** [comment]
https://github.com/golangci/golangci-lint/pull/346

Can probably close this unless you want to add to the README a native-Windows way to install the linter.

**Comment by jirfag** [comment]
:) sorry
