### ISSUE TITLE
`--mod` flag is missing

### ISSUE THREAD

**Issue by lorencio1** [golangci/golangci-lint#339]
Why has `--mod` flag been removed in https://github.com/golangci/golangci-lint/commit/09c65fcf425a96380621813c8b1eda1f69618901?

It would be really convenient to have the same configuration during development and CI, but using different modules download modes.

**Comment by lorencio1** [comment]
We don't use vendoring locally, we use dependencies directly from `${GOPATH}/pkg/mod` since Go 1.11.

In CI (self-hosted Gitlab-CI), I use some stages:

1. `go mod download` then `go mod vendor`. We save the repo with the `vendor/` folder as an artifact  and pass it to all the next stages.
2. Unit testing - Run tests with vendored dependencies downloaded on the stage 1
3. **running linters - Run linters with vendored dependencies downloaded on the stage 1**
4. Build Docker images
  - I can't add any files outside the build context to the Docker image
  - I don't want to do `go mod download` again because I have already downloaded my dependencies
  - So I just copy the entire directory with vendored dependencies from the stage 1 and use `go build` with the mod flag
5. [...]
I download dependencies only once, on the stage 1.

The only workaround I found is using two configuration files, which is far from perfect.

**Comment by rfay** [comment]
We use -mod=vendor in our builds, as we're using checked-in vendor.  Is there any way to make golangci-lint behave like golang 1.11 does in this case?

**Comment by rfay** [comment]
I changed to use `golangci-lint run` with a golangci.yml with these contents in order to get around the multiple problems of golangci-lint not respecting use of vendor directory:
```
run:
  modules-download-mode: vendor
```

**Comment by lorencio1** [comment]
@jirfag Yes you did. 

Multiple files are okay, it will be inconvenient but at least it will work.

If you want to keep this only with multiple config files, I would like to see the extends/override feature from docker-compose (https://docs.docker.com/compose/extends/).

**Comment by ydkn** [comment]
@jirfag @lorencio1 I hand the same problem when using <tt>golangci-lint</tt> with a Gitlab-CI pipeline.

But instead of having multiple config files I simply update the config when running the linters stage.
I set the <tt>modules-download-mode: readonly</tt> because the linter should never change the mod files and then use <tt>sed</tt> to change it to <tt>vendor</tt> before running <tt>golangci-lint run</tt>

Snippet from linters stage:
```yaml
before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /usr/local/bin v1.17.1
    - sed -i -E 's/(modules-download-mode:) (.*)/\1 vendor/' .golangci.yml
  script:
    - golangci-lint run
```

Maybe this helps to optimize your setup.

**Comment by jirfag** [comment]
We’be added  modules download mode command line flag recently
