### ISSUE TITLE
Go <= 1.8 support

### ISSUE THREAD

**Issue by henson** [golangci/golangci-lint#34]
I run the command to install the tool:

`
go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
`

but something wrong occur:

> go get github.com/golangci/golangci-lint/cmd/golangci-lint
> \# github.com/golangci/golangci-lint/vendor/github.com/golangci/govet
> D:\Gworks\src\github.com\golangci\golangci-lint\vendor\github.com\golangci\govet\asmdecl.go:99: undefined: types.SizesFor
> D:\Gworks\src\github.com\golangci\golangci-lint\vendor\github.com\golangci\govet\types.go:313: undefined: types.SizesFor
> \# github.com/golangci/golangci-lint/vendor/github.com/golangci/go-tools/lint
> D:\Gworks\src\github.com\golangci\golangci-lint\vendor\github.com\golangci\go-tools\lint\lint.go:421: undefined: sync.Map

I need help, thanks!

**Comment by henson** [comment]
> go version go1.8.3 windows/amd64

**Comment by henson** [comment]
OK, I get it. Thank you for your reply.

**Comment by jirfag** [comment]
@henson try to install `golangci-lint` binary: from [releases](https://github.com/golangci/golangci-lint/releases) or by `curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh`, it's documented [here](https://github.com/golangci/golangci-lint#install). It doesn't require go at all
