### ISSUE TITLE
misspell ignore-words doesn't seem to be working

### ISSUE THREAD

**Issue by source-transformer** [golangci/golangci-lint#3406]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I've tried using this:

```
  misspell:
    locale: US
    ignore-words:
      - Dialogue

```

and if I have the following in my golang code:

```
type Test struct {
	Dialogue string
}
```

Dialogue is replaced wth Dialog

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.46.2 built from (unknown, mod sum: "h1:o90t/Xa6dhJbvy8Bz2RpzUXqrkigp19DLStMolTZbyo=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - Dialogue
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19.2 linux/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN="/go/bin"
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/my-project/go.mod"
GOWORK="/workspaces/my-project/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3362665096=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
`Dialogue` is a misspelling of `Dialog` (misspell)
        // Dialogue
```

</details>

### Code example or link to a public repository

<details>

```go
type Test struct {
	Dialogue string
}
```

Dialogue gets replaced with Dialog

</details>

**Comment by ldez** [comment]
Hello,

it's because `ignore-words` values must be in lowercase.

```yml
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - dialogue
```

**Comment by source-transformer** [comment]
ah - thanks!

**Comment by ldez** [comment]
I created a PR to put all the `ignore-words` to lowercase :wink: https://github.com/golangci/golangci-lint/pull/3918
