### ISSUE TITLE
golangci/go-misc: checksum mismatch

### ISSUE THREAD

**Issue by ml-** [golangci/golangci-lint#344]
When trying to build the project, there is a checksum mismatch when dependencies are retrieved.
I tried this on my own system, as well as on the golang:1.11.4 docker image.

**$** `go build -o golangci-lint ./cmd/golangci-lint/main.go`

**Error:**
```
go: verifying github.com/golangci/go-misc@v0.0.0-20180628070357-927a3d87b613: checksum mismatch
	downloaded: h1:9kfjN3AdxcbsZBf8NjltjWihK2QfBBBZuv91cMFfDHw=
	go.sum:     h1:WadunOE/TeHR8U7f0TXiJACHeU3cuFOXuKafw4rozqU=
```

**Info:**
System: Arch Linux
`go version go1.11.4 linux/amd64`

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ml/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ml/.local/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ml/code/golangci-lint/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build893572642=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by mbana** [comment]
I am getting the **_same_** error but in a different context; I am trying to place all the tools that I use in `tools/tools.go` file.

**Sample Repo:**
https://github.com/banaio/go_samples/tree/master/how_can_i_track_tool_dependencies_for_a_module
```sh
git clone git@github.com:banaio/go_samples.git
cd go_samples/how_can_i_track_tool_dependencies_for_a_module
make
```

**Error Log:**
https://circleci.com/gh/banaio/go_samples/10, look at the step `find * -maxdepth 1 -mindepth 1 -type d -execdir make \;`.

```sh
  ---> Initialising ... 
go mod download
go: verifying github.com/golangci/go-misc@v0.0.0-20180628070357-927a3d87b613: checksum mismatch
	downloaded: h1:9kfjN3AdxcbsZBf8NjltjWihK2QfBBBZuv91cMFfDHw=
	go.sum:     h1:WadunOE/TeHR8U7f0TXiJACHeU3cuFOXuKafw4rozqU=
Makefile:11: recipe for target 'init' failed
make: *** [init] Error 1
```

**Cause:**
For someone reason this only happens when I run it on the CI, it never happens locally.

**Comment by ml-** [comment]
Hi @mbana,
is it possible that the Go versions of your local machine and CI differ?

I can safely reproduce this with 1.11.4.

**Comment by jirfag** [comment]
@ml- @mbana thank you! I've fixed it in the master

**Comment by mbana** [comment]
Thanks, are you going to make a new release?

**Comment by jirfag** [comment]
Yes, I already did - v1.13

**Comment by y0ssar1an** [comment]
I ran into this. I fixed it by updating my `go` compiler to the latest version and running `go clean -modcache`, which clears out the cache of downloaded modules.
