### ISSUE TITLE
Update all dependencies & linters

### ISSUE THREAD

**Issue by leonklingele** [golangci/golangci-lint#3475]
### Your feature request related to a problem? Please describe.

Quite a few linters have updates available which are not going to be reported by dependabot (as they have started using tags instead of referring to a commit hash).

Found by removing the `go.mod` and `go.sum` file and initializing them again using `go mod init github.com/golangci/golangci-lint` and `go mod tidy`

### Describe the solution you'd like.

—

### Describe alternatives you've considered.

—

**Comment by ldez** [comment]
We already do that periodically

**Comment by leonklingele** [comment]
Just randomly picked two of the non-tagged dependencies in `go.mod` and both haven't been updated for ages:

- The `github.com/gordonklaus/ineffassign` linter has not been updated for at least 4 months
- `github.com/go-xmlfmt/xmlfmt` has not been updated for over a year
- etc.

**Comment by ldez** [comment]
I upddated go-xmlfmt/xmlfmt here #3414.

We don't need to update everything.
