### ISSUE TITLE
add param for gofmt linter to disable comment formatting

### ISSUE THREAD

**Issue by jnan806** [golangci/golangci-lint#3484]
### Your feature request related to a problem? Please describe.

Now, if format error occurs in the comment, will make the result of `gofmt check` fail, But sometimes I do not want to change my commet. So I want to add a param to control enable or disable to check the comment formatting when do `gofmt`.

### Describe the solution you'd like.

I want to add a param to control enable or disable to check the comment formatting when do `gofmt`.

### Describe alternatives you've considered.

I want to add a param to control enable or disable to check the comment formatting when do `gofmt`.

**Comment by ldez** [comment]
Hello,

it's not possible to do that, the format is not an option of gofmt.

**Comment by jnan806** [comment]
:) 

@ldez    em......do you have any suggestions to deal with it ?

**Comment by ldez** [comment]
you have to follow gofmt, it's not a choice.
