### ISSUE TITLE
golangci-lint allocates gigabites of memory on compilation errors

### ISSUE THREAD

**Issue by rski** [golangci/golangci-lint#349]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
v1.2.3 & current master
2. Config file: `cat .golangci.yml`
 golangci-lint run --disable-all --enable gosimple max-issues-per-linter 0 --max-same-issues 0
3. Go environment: `go version && go env`
go 1.12, +e3eb2ff827

gopackage fails to load some packages correctly with the latest go, e.g. 
runtime/internal/atomic:/home/rski/tmp/memoryissues/goroot/src/runtime/internal/atomic/asm_amd64.s:8:1: illegal character U+0023 '#'

This is because some package that is checked by golangci-lint imports atomic. That's fine - it's not golangci-lint's problem.

The issue comes in that in this case golangi-lint starts continuously going through the checked package's dependencies in extractErrorsImpl, ballooning in memory use. 
I  don't have a specific reproduction case at hand, but in our repo, it got to 70Gigs of ram processing a   package before I killed it. yikes. 
I have a fix for this, I'll push a pr in a bit

**Comment by jirfag** [comment]
thank you,
was fixed in the linked pull request and in the https://github.com/golangci/golangci-lint/pull/363
