### ISSUE TITLE
Golangci-lint downloader fails to download binary

### ISSUE THREAD

**Issue by ssko1** [golangci/golangci-lint#3509]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

The downloader decscribed in the installation guide https://golangci-lint.run/usage/install/#other-ci returns with an error. It does not install the golangci-lint binary into my go path.

Perhaps the Github API changed?

### Version of golangci-lint

N/A

### Configuration file

N/A

### Go environment

N/A

### Verbose output of running
```
computer@computer directory % curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

golangci/golangci-lint info checking GitHub for tag 'v1.50.1'
golangci/golangci-lint info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/darwin/amd64
computer@computer directory %
```
### Code example or link to a public repository

N/A

**Comment by mdestagnol** [comment]
Same problem here, since this morning. The script mentioned in the [install](https://golangci-lint.run/usage/install/) page is broken. It seems that it's fetching from a URL which is not returning what it used to

**Comment by ssko1** [comment]
The script performs a check against github to obtain a tag... something like:
```
curl https://github.com/golangci/golangci-lint/releases/v1.49.0 -H "Accept: application/json"
```

This now returns a webpage instead of JSON like it was before?

**Comment by mdestagnol** [comment]
could that be that the github download format has changed ? 
from https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-v1.50.1-darwin-arm64.tar.gz
to https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-darwin-arm64.tar.gz

(note the v in the file name)

**Comment by mfine** [comment]
Maybe they turned off that access path in favor of using the [API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name)?

```sh
➜  ~ curl --silent -H 'Accept: application/json'  https://api.github.com/repos/golangci/golangci-lint/releases/tags/v1.35.2 | head
{
  "url": "https://api.github.com/repos/golangci/golangci-lint/releases/36207082",
  "assets_url": "https://api.github.com/repos/golangci/golangci-lint/releases/36207082/assets",
  "upload_url": "https://uploads.github.com/repos/golangci/golangci-lint/releases/36207082/assets{?name,label}",
  "html_url": "https://github.com/golangci/golangci-lint/releases/tag/v1.35.2",
  "id": 36207082,
  "author": {
    "login": "golangci-releaser",
    "id": 65486276,
    "node_id": "MDQ6VXNlcjY1NDg2Mjc2",
```

**Comment by mfine** [comment]
This works for me:

```diff
321c321
<   giturl="https://api.github.com/repos/${owner_repo}/releases/tags/${version}"
---
>   giturl="https://github.com/${owner_repo}/releases/${version}"
324c324
<   version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name": "//' | sed 's/".*//')
---
>   version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
```

**Comment by ben-tbotlabs** [comment]
Hopefully this can get merged fairly quickly. The devcontainers install for Go (https://github.com/devcontainers/features/tree/main/src/go) is currently broken as it has been dependant on the golangci install since Oct

**Comment by mfine** [comment]
And added support for handling without a specified version https://github.com/golangci/golangci-lint/pull/3510.

**Comment by ldez** [comment]
Seems to be a GitHub bug: https://github.com/orgs/community/discussions/45590

**Comment by cyprianbergoniatmo** [comment]
I'm getting rate limits so our pipelines are still failing on the api calls

**Comment by ldez** [comment]
I have no solution for your rate limits problem, it's a GitHub constraint.
You have to stop calling the API for 1 hour.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

**Comment by ldez** [comment]
https://github.com/orgs/community/discussions/45590#discussioncomment-4802887

**Comment by ldez** [comment]
@cyprianbergoniatmo as GitHub engineers reverted their change, and due to the rate limit problem I will revert the previous fix.
