### ISSUE TITLE
install.sh script broken in main

### ISSUE THREAD

**Issue by armsnyder** [golangci/golangci-lint#3511]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

To reproduce, run:

```shell
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- v1.50.1
```

Result:

```
golangci/golangci-lint info checking GitHub for tag 'v1.50.1'
golangci/golangci-lint info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/darwin/arm64
```

(exits with code 3)

### Version of golangci-lint

n/a

### Configuration file

n/a

### Go environment

n/a

### Verbose output of running

n/a

### Code example or link to a public repository

n/a

**Comment by armsnyder** [comment]
And it's back to working again. Maybe https://github.com/golangci/golangci-lint/commit/d57156ec228b712ccd429367482771179e3fa050 resolved it? I'll close the issue.

**Comment by ldez** [comment]
duplicate of #3509
