### ISSUE TITLE
docs: unused configuration broken link

### ISSUE THREAD

**Issue by oscr** [golangci/golangci-lint#3555]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

On the page https://golangci-lint.run/usage/linters

In the "Enabled by default" section in the end there is: "unused ⚙️" 

If you click on the ⚙️ for configuration it's a broken link: https://golangci-lint.run/usage/linters/#unused

### Version of golangci-lint

N/A

### Configuration file

N/A

### Go environment

N/A

### Verbose output of running

N/A

### Code example or link to a public repository

N/A

**Comment by ldez** [comment]
Hello,

there is no configuration for `unused`, so the gear must be removed.

I will fix that.

**Comment by oscr** [comment]
Awesome! Thank you **l**dez! :grin:
