### ISSUE TITLE
Generating bash completions with --no-descriptions does not work

### ISSUE THREAD

**Issue by scop** [golangci/golangci-lint#3567]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

golangci-lint seems to be doing something with flags that makes cobra's built in bash completion generator `--no-descriptions` to break.

```console
$ golangci-lint completion bash --help | grep -- --no-descriptions
      --no-descriptions   disable completion descriptions
$ golangci-lint completion bash --no-descriptions
ERRO Can't get config for command line: can't parse args: unknown flag: --no-descriptions 
```

### Version of golangci-lint

<details>

```console
$ golangci-lint version
golangci-lint has version 1.51.1 built from b87d2c19 on 2023-02-05T13:06:33Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# not relevant
```

</details>

### Go environment

<details>

```console
$ go version && go env
# not relevant
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# not relevant
```

</details>

### Code example or link to a public repository

<details>

```go
// N/A
```

</details>

**Comment by ldez** [comment]
Fixed by #4412
