### ISSUE TITLE
False positive in "unused" linter since upgrade to go-tools 0.4.0

### ISSUE THREAD

**Issue by vitaly-eureka-security** [golangci/golangci-lint#3569]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

The release of go-tools Staticcheck 2023.1 (v.0.4.0) introduced regression: https://github.com/dominikh/go-tools/issues/1360.
This regression propagated to golangci-lint 1.51.1.
According to https://github.com/dominikh/go-tools/issues/1360#issuecomment-1415151084 the fix for go-tools should be released on Feb 6th.

### Version of golangci-lint

golangci-lint has version 1.51.1 built from b87d2c19 on 2023-02-05T13:06:33Z

### Configuration file

<details>
</details>

### Go environment

<details>
</details>

### Verbose output of running

<details>
</details>

### Code example or link to a public repository

<details>
</details>

**Comment by ldez** [comment]
Hello,

Can you fill in the template and add a reproducible example?

**Comment by ldez** [comment]
when staticcheck will create a release we will update.

**Comment by ldez** [comment]
Fixed by #3591
