### ISSUE TITLE
Lint tests by default

### ISSUE THREAD

**Issue by mastertinner** [golangci/golangci-lint#36]
I think we shouldn't treat testing code as a second class citizen. In my opinion this sends a wrong message that somehow its not as important for test code to be clean as for non-test code. I think we should set `--tests` to `true` by default.

**Comment by jirfag** [comment]
Hello, thank you for the issue! I've enabled tests linting by default in https://github.com/golangci/golangci-lint/pull/59

**Comment by mastertinner** [comment]
Nice. Thanks, @jirfag!
