### ISSUE TITLE
Mirror docker image on ghcr.io

### ISSUE THREAD

**Issue by tarampampam** [golangci/golangci-lint#3621]
### Your feature request related to a problem? Please describe.

The problem is very simple - the docker hub has a limitation for image pulling. And to solve this problem, could you mirror the docker image on `ghcr.io`?

### Describe the solution you'd like.

A CI step to push the docker image with `golangci-lint` on `ghcr.io`

### Describe alternatives you've considered.

---

**Comment by ldez** [comment]
duplicate of #3105
