### ISSUE TITLE
tparallel: checksum mismatch

### ISSUE THREAD

**Issue by etkecc** [golangci/golangci-lint#3716]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

```
#10 134.9 pkg/mod/github.com/golangci/golangci-lint@v1.52.1/pkg/golinters/tparallel.go:4:2: github.com/moricho/tparallel@v0.3.0: verifying module: checksum mismatch
#10 134.9 	downloaded: h1:EthKzLoZA6C11YB1vMPWLYmF2nnPCUX712TjDgsP31A=
#10 134.9 	sum.golang.org: h1:8dDx3S3e+jA+xiQXC7O3dvfRTe/J+FYlTDDW01Y7z/Q=
#10 134.9 
#10 134.9 SECURITY ERROR
#10 134.9 This download does NOT match the one reported by the checksum server.
#10 134.9 The bits may have been replaced on the origin server, or an attacker may
#10 134.9 have intercepted the download attempt.
#10 134.9 
#10 134.9 For more information, see 'go help module-auth'.
```

### Version of golangci-lint

<details>

v1.52.1 - cannot provide the requested output, because cannot install that version

</details>

### Configuration file

Not applicable

### Go environment

Not applicable

### Verbose output of running

Not applicable

### Code example or link to a public repository

<details>

Line in dockerfile: https://gitlab.com/etke.cc/base/-/blob/main/Dockerfile.build#L15

Failed job: https://gitlab.com/etke.cc/base/-/jobs/3986968517
</details>

**Comment by ldez** [comment]
https://github.com/moricho/tparallel/issues/22
