### ISSUE TITLE
Tab output format without a color

### ISSUE THREAD

**Issue by cristaloleg** [golangci/golangci-lint#3728]
### Your feature request related to a problem? Please describe.

I started writing a blog post regarding my `golangci-lint` setup and decided to try the `tab` format, which looks cool and I like it.

I tried the following config and was upset because my `lint.txt` is full of cryptic symbols related to the colouring (see screenshot)

```yaml
output:
  format: tab:lint.txt
```

<img width="241" alt="image" src="https://user-images.githubusercontent.com/366002/227712744-4bb918da-e60c-4348-9b14-6374ba0f39a9.png">

### Describe the solution you'd like.

Add a new format which outputs results in the `tab` format but without colours, so no cryptic symbols appear in the output file.

### Describe alternatives you've considered.

Keep using `line-number` or using a personal fork without colours. This can be also `sed`-ed but I don't like this fix.

### Additional context.

I'm happy to make a PR, I'm just not sure which fix would be better: add a new `tab-no-colour` format or add a separate config field `no-color: <boolean>` or just join https://no-color.org/ movement.

**Comment by ldez** [comment]
Hello,

I created PR #3729.

I don't introduce a `no-color` option because I prefer to have a consistent and homogenous option.
Today we already have `colored-line-number` and `line-number`.

**Comment by ldez** [comment]
I missed one existing option because this option was not documented:
```yaml
output:
  color: never
```

I will document that.

And I think we will have to review this global approach to color and output.

**Comment by ldez** [comment]
In fact, the option `color` only works as a CLI flag: `--color never`

The YAML version doesn't work, and I don't know why, probably a historical reason.

**Comment by ldez** [comment]
I think I know why: the option has been probably introduced to handle colors inside logs but as this option is modifying the global var `color.NoColor` it also impacts the report outputs which use the same library.
As the setup of the log is handled before the configuration file parsing, this explains why the config file option doesn't work.

**Comment by cristaloleg** [comment]
Well, my feature is completely done in #3729. A global `no-color` parameter was just 1 way to achieve my goal.
