### ISSUE TITLE
Support JUnit output format

### ISSUE THREAD

**Issue by iwata** [golangci/golangci-lint#373]
I'm using CircleCI.
It can show `Test Summary` section.
But in order to display the summary, it is necessary to output in JUnit format.
Ref. [Configuring CircleCI \- CircleCI](https://circleci.com/docs/2.0/configuration-reference/#store_test_results)

**Comment by jirfag** [comment]
hi!
pull requests are welcome but I suggest using code climate or golangci.com or hound ci or similar: they allow to see linters warnings inline like a code review

**Comment by sagikazarmark** [comment]
@iwata what exactly would you like golangci to output in a JUnit file? golangci does not execute tests. You could use gotestsum for that: https://github.com/gotestyourself/gotestsum

**Comment by iwata** [comment]
> golangci does not execute tests. 

I know.
I want to output the result of thin linter in JUnit format looks like ESLint.
https://circleci.com/docs/2.0/collect-test-data/#eslint
https://eslint.org/docs/user-guide/formatters/#junit

**Comment by howardjohn** [comment]
I think this is added in 1.17?

**Comment by vovapi** [comment]
@howardjohn yeah, seems to be true. It seems that Unit format support was added in #557 and fixed in #632

**Comment by matoous** [comment]
True. Closing ✅

**Comment by ced42** [comment]
Hello,
It seems that the generated output is not valid, according to the Jenkins Junit XSD (https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd).
For example, the attributes tests, failures and errors are missing.
