### ISSUE TITLE
Error must be checked before other code run

### ISSUE THREAD

**Issue by lx-world** [golangci/golangci-lint#3743]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

this code can't check the err not return, so it panic.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.52.2 built with go1.20 from (unknown, mod sum: "h1:FrPElUUI5rrHXg1mQ7KxI1MXPAw5lBVskiz7U7a8a1A=") on (unknown)
```

</details>

### Configuration file

<details>

```console

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.20 linux/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
```

</details>

### Code example or link to a public repository

<details>

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

type Stu struct {
	Age int
}

func AAA() (*Stu, error) {
	return nil, errors.New("error here")
}

func BBB() (v int, err error) {
	stu, err := AAA() //lint must return if err != nil
	stu.Age = 1
	return
}

func main() {
	res, err := BBB()
	fmt.Fprintln(os.Stdout, res, err)
}
```
</details>

**Comment by ldez** [comment]
Hello,

golangci-lint is a wrapper around the linter.
So I don't understand what is your problem.

if a linter does not behave as you want it to, give the name of this linter and ask the author of the linter to correct the problem.

**Comment by lx-world** [comment]
> Hello,
> 
> golangci-lint is a wrapper around the linter. So I don't understand what is your problem.
> 
> if a linter does not behave as you want it to, give the name of this linter and ask the author of the linter to correct the problem.

I hope `errcheck` will detect this situation

**Comment by ldez** [comment]
In your example `err` is used, so the linter cannot detect that your use of the `err` is wrong.
There is no difference between your case and a case where a function is used to check the error.
If the linter reported that as a problem it would be a false-positive.

**Comment by hesining** [comment]
> In your example `err` is used, so the linter cannot detect that your use of the `err` is wrong. There is no difference between your case and a case where a function is used to check the error. If the linter reported that as a problem it would be a false-positive.

I think in this case, an error occurs, and the program is still executing, which may lead to unexpected results, such as a panic of null pointer access. So maybe it's better to detect 'err' and return if it's not empty.
