### ISSUE TITLE
README Question about Local Installation

### ISSUE THREAD

**Issue by Zamiell** [golangci/golangci-lint#377]
Greetings golangci-lint maintainers. Thanks again for the excellent (and free!) software.  I recently submitted a pull request to update the README file, but since then it has changed again and I had a question.

In this commit:
https://github.com/golangci/golangci-lint/commit/2192097e7f56c84fa793b6f933056cd18773fae2

@jirfag changed:

```
(On Windows, you can run the above commands with Git Bash, which comes with [Git for Windows](https://git-scm.com/download/win).
```

to:

```
(On Windows, you can run the above commands with Git Bash, which comes with [Git for Windows](https://git-scm.com/download/win). Or you can run just `go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`.)
```

As a nooby non-technical end-user, this is confusing. Are the lines:

```
cd $(go env GOPATH)/src/github.com/golangci/golangci-lint/cmd/golangci-lint
go install -ldflags "-X 'main.version=$(git describe --tags)' -X 'main.commit=$(git rev-parse --short HEAD)' -X 'main.date=$(date)'"
```

necessary? Or are they not necessary? What do they even do? If they are not necessary, can they be removed from the README entirely to simplify it? If they are necessary, can this please be added to the README file to document exactly what they do? Perhaps with an inline comment? If they are necessary, why exactly can Windows users skip it? If Windows users do skip it, what are the implications? And so on.

Thanks.

**Comment by jirfag** [comment]
hi, thank you!

I've tried to simplify docs. Check it please in [README](https://github.com/golangci/golangci-lint#local-installation)

**Comment by Zamiell** [comment]
Thank you, that explains it!
