### ISSUE TITLE
Double-comment `nolint` not recognized

### ISSUE THREAD

**Issue by silverwind** [golangci/golangci-lint#3788]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

A `nolint` comment that is "part" of another comment is not recognized. It's useful to preserve original comments at the line where `nolint` is added, so I suggest this to be supported.

```go
a := 1 // comment //nolint:unused
```

### Version of golangci-lint

v1.51.2

### Configuration file

https://github.com/go-gitea/gitea/blob/main/.golangci.yml

### Go environment

go1.20.3

### Verbose output of running

https://drone.gitea.io/go-gitea/gitea/72802/1/5

```go
models/migrations/v1_13/v140.go:26:3: const `RepoIndexerTypeCode` is unused (unused)
		RepoIndexerTypeCode RepoIndexerType = iota // 0 //nolint:unused
		^
````

### Code example or link to a public repository

https://github.com/go-gitea/gitea/pull/24214/files#diff-cf1b69f4f0a1f4b830cfd2aef9d86f90d1bde357abc19448fa3a30df9bf3be82R26

**Comment by ldez** [comment]
Hello,

the nolint directive is not a comment: it's a directive.
if you define a directive inside a comment, the directive is ignored because it's commented.

You can move your comment before the line:

```go
// comment
a := 1 //nolint:unused
```

Note: Your example is just a kind of illustration because it cannot compile.

Also, you can remove the directive in [your code](https://github.com/go-gitea/gitea/pull/24214/files#diff-cf1b69f4f0a1f4b830cfd2aef9d86f90d1bde357abc19448fa3a30df9bf3be82R26) because currently unused will not report your exported constants as unused.

I recommend updating your golangci-lint to the [latest version](https://github.com/golangci/golangci-lint/releases).

**Comment by silverwind** [comment]
It compiles just fine with the usual boilerplate around, but here's a acutal compiling example:

```go
package main
const a = 1 // foo //nolint
func main() {}
```

As per [go spec](https://go.dev/ref/spec#Comments) `//` is a comment:

>  Line comments start with the character sequence // and stop at the end of the line. 

So you just need to be more lenient in your comment parsing. Want a new issue with above example?

**Comment by ldez** [comment]
Your example was:
```go
a := 1
```

not:
```
const a = 1
```

So it doesn't compile.

**Comment by silverwind** [comment]
Yes, sorry, the example was bad. I've edited OP now to the proper example. A actual complete example can be found in [this link](https://github.com/go-gitea/gitea/pull/24214/files#diff-cf1b69f4f0a1f4b830cfd2aef9d86f90d1bde357abc19448fa3a30df9bf3be82R26),  also from OP.

**Comment by ldez** [comment]
> As per [go spec](https://go.dev/ref/spec#Comments) `//` is a comment. Go does not know "directives":
> 
> >  Line comments start with the character sequence // and stop at the end of the line. 
> 
> So golangci just needs to be more lenient in the comment parsing. Want a new issue with this updated example?

Go has a notion of directives or if you prefer specific comment syntax:
- https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives
- https://groups.google.com/g/golang-dev/c/r4rdPdsH1Fg/m/tNZazPenX5cJ

example:

This works:
```go
//go:generate echo test
```

```console
$ go generate
test
```

This doesn't work:
```go
// foo //go:generate echo test
```
```console
$ go generate
```

The problem with your issue was not the compilation problem of your example.

**Comment by silverwind** [comment]
Hmm, interesting:

> directives require no space between the comment opening and the name of the directive.

`nolint` works as `// nolint` with an actual space, which would make it a comment, in a sense, except go AST parsers would probably not recognize it as such because

> A comment cannot start inside a [rune](https://go.dev/ref/spec#Rune_literals) or [string literal](https://go.dev/ref/spec#String_literals), or inside a comment

So maybe it could be supported if the `nolint` is an actual comment and the golangci parser extracts the substring from `//` to the end, if the comment contains `//`.

**Comment by ldez** [comment]
nolint used to work with a space but now it's not allowed.

```
directive `// nolint:unused` should be written without leading space as `//nolint:unused` (nolintlint)
```

**Comment by silverwind** [comment]
So it tested it with `// nolint` style. New minimal reproduction:

```go
package main
const a = 1 // comment // nolint:unused
func main() {}
```
```
main.go:2:7: const `a` is unused (unused)
const a = 1 // comment // nolint:unused
```

I think it would definitely be in the realm of being supportable if the comment parser is just a bit more smart to split in last `//` when string contains `//`.

**Comment by ldez** [comment]
We follow the directives convention so we will not allow that.
The leading space is not allowed by this convention.

Directives inside a comment must be ignored because without that it's impossible to create an example inside a go doc.

**Comment by silverwind** [comment]
I recently discovered the eslint allows such nested comments via this a syntax:

```
// directive -- comment why the rule is disabled
```

I think it's nice that the user can give justification why a rule was disabled on the same line as the rule. There is even a [meta-linter](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) that requires such comments on every directive.

**Comment by ldez** [comment]
`nolint` already has that.

```go
//nolint:gocyclo // This legacy function is complex but the team too busy to simplify it
func someLegacyFunction() *string {
  // ...
}
```

https://golangci-lint.run/usage/false-positives/#nolint-directive
