### ISSUE TITLE
Main README.md should contain only usefull information

### ISSUE THREAD

**Issue by jirihnidek** [golangci/golangci-lint#3840]
### Your feature request related to a problem? Please describe.

I aware that main `README.md` contains links to documentation, how to contribute, etc. It is possible to have such information in other files or hosted on other web pages.

I really do not understand why this file contains images of contributors like this one:

![obrazek](https://github.com/golangci/golangci-lint/assets/2057012/4a886ef1-0ce1-4954-bacf-901ec8884229)

This image is bigger than necessary and it requires to download about 3MB in total to view this page. 3MB is lot of, but it does not contain anything useful. And displaying graph of number of stargezers over time is useless too.

The `README.md` looks really unprofessional.

### Describe the solution you'd like.

Delete all useless images from `README.md` except logo of this project.

### Describe alternatives you've considered.

If you are scared from empty space in your `README.md` file, then you can add e.g. instruction how to build this project.

**Comment by ldez** [comment]
Hello,

Our readme is not our documentation and it will not become a "how-to build".

We prefer to have just a link to the documentation and promote contributors.

Maybe it feels "unprofessional" for you but it's not, your point of view is not ours.

**Comment by jirihnidek** [comment]
Hello,
I really tried to be constructive, but if you thing that I'm "condescending, arrogant, and aggressive", then I really wasted my time filling this issue. And no, I will never contribute to this project.

Have a nice day

Jiri

**Comment by karelbilek** [comment]
@ldez thank you for maintaining this repo even with horrible issues like this. This is the reason why I never want to be a maintainer of a popular repo.
