### ISSUE TITLE
files were modified by this hook

### ISSUE THREAD

**Issue by louisliu2048** [golangci/golangci-lint#3848]
### Your feature request related to a problem? Please describe.

#13 0.173 pre-commit run -a
#13 0.573 check yaml...............................................................Passed
#13 0.711 fix end of files.........................................................Passed
#13 1.544 trim trailing whitespace.................................................Passed
#13 1.685 go fmt...................................................................Passed
#13 2.238 go-mod-tidy..............................................................Passed
#13 2.729 go-build.................................................................Passed
#13 34.43 golangci-lint............................................................Failed
#13 135.3 - hook id: golangci-lint
#13 135.3 - files were modified by this hook
#13 135.4 make: *** [Makefile:328: test] Error 1

### Describe the solution you'd like.

`files were modified by this hook`
give the files that has been modified!

### Describe alternatives you've considered.

give the files that has been modified!

**Comment by bombsimon** [comment]
This message comes from [pre-commit](https://github.com/pre-commit/pre-commit/blob/80344305393e8ccbb60b0ec3b5a9464e2e67bcb6/pre_commit/commands/run.py#L228), not `golangci-lint`. I would suggest checking the [docs](https://pre-commit.com/) or asking in that repo on how to show files.
