### ISSUE TITLE
goimports no longer requires explicit package names for mismatched ones

### ISSUE THREAD

**Issue by kyessenov** [golangci/golangci-lint#389]
I noticed that golangci-lint is using older goimports.
```sh
go get -u golang.org/x/tools/cmd/goimports
goimports -d < some file with mismatched imports >
<nothing>
```

This no longer complains about the following import:
```go
       "github.com/opentracing/opentracing-go"
```

which in golangci-lint 1.12.4 would be required to be explicit:

```go
      opentracing  "github.com/opentracing/opentracing-go"
```

/cc @louiscryan

**Comment by kyessenov** [comment]
Checked that the latest version 1.13.2 also uses older goimports. I think either a clarification on goimports expectations, or a new release of golangci-lint would be helpful.

**Comment by jirfag** [comment]
hi!
I've updated `goimports` in master

**Comment by sashayakovtseva** [comment]
Having the same issue with v1.14 and v1.15

**Comment by jirfag** [comment]
Already released, assuming it's ok
