### ISSUE TITLE
Misspell not detecting strings inside single quotes

### ISSUE THREAD

**Issue by perfectcw** [golangci/golangci-lint#3893]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

**Issue: Misspell not detecting strings inside single quotes**
In this case, misspell not detecting 'Unkonwn'

Input test.go:
```go
// comment with incorrect spelling: occured
// comment with incorrect spelling: langauge
// comment with incorrect spelling: somethng
// comment with incorrect spelling: Unkown
// comment with incorrect spelling: 'Unkonwn'
// comment with incorrect spelling: Unkonwn
```

Output:
```
query/mkpl_inventory_bidding_entity_builder.go:66:38: `occured` is a misspelling of `occurred` (misspell)
   // comment with incorrect spelling: occured

query/mkpl_inventory_bidding_entity_builder.go:67:38: `langauge` is a misspelling of `language` (misspell)
   // comment with incorrect spelling: langauge

query/mkpl_inventory_bidding_entity_builder.go:69:38: `Unkown` is a misspelling of `Unknown` (misspell)
   // comment with incorrect spelling: Unkown

query/mkpl_inventory_bidding_entity_builder.go:71:38: `Unkonwn` is a misspelling of `Unknown` (misspell)
   // comment with incorrect spelling: Unkonwn
```
	

### Version of golangci-lint

V1.53.2

### Configuration file

not exist

### Go environment

go version go1.20.5 darwin/amd64

### Verbose output of running

```
query/test.go:66:38: `occured` is a misspelling of `occurred` (misspell)
	// comment with incorrect spelling: occured
	
query/test.go:67:38: `langauge` is a misspelling of `language` (misspell)
	// comment with incorrect spelling: langauge

query/test.go:69:38: `Unkown` is a misspelling of `Unknown` (misspell)
	// comment with incorrect spelling: Unkown
	
query/test.go:71:38: `Unkonwn` is a misspelling of `Unknown` (misspell)
	// comment with incorrect spelling: Unkonwn
```

### Code example or link to a public repository

```go
// comment with incorrect spelling: occured
// comment with incorrect spelling: langauge
// comment with incorrect spelling: somethng
// comment with incorrect spelling: Unkown
// comment with incorrect spelling: 'Unkonwn'
// comment with incorrect spelling: Unkonwn
```

**Comment by ldez** [comment]
Hello,

I think this is expected because misspell uses `var wordRegexp = regexp.MustCompile(`[a-zA-Z0-9']+`)` to split word.
Maybe it's a way to ignore a word.

**Comment by perfectcw** [comment]
Thanks for your response! So it actually checks for **_'Unkown'_** rather than **_Unkown_**.

**Comment by Antonboom** [comment]
Related to https://github.com/client9/misspell/issues/195

I think we should close this issue (as unrelated to `golangci-lint`) and open another one (or do contribution) in `misspell`.
