### ISSUE TITLE
tagalign should skip generated .pb.go files

### ISSUE THREAD

**Issue by DoubleDi** [golangci/golangci-lint#3915]
### Your feature request related to a problem? Please describe.

After enabling tagalign all of the generated pb.go files were marked 

```
.../accountinvalidate.pb.go:180:18: tag is not aligned, should be: protobuf:"bytes,1,opt,name=id,proto3"                      json:"id,omitempty"
```

### Describe the solution you'd like.

As pb.go files are generated, there should be no changes there

### Describe alternatives you've considered.

Alternatives are to skip .pb.go files from analysis, but here it is stated, that those files should be handled "under the hood" by golangci-lint 
https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml#L50

**Comment by ldez** [comment]
Hello,

golangci-lint is a runner/wrapper of linters.

You can open an issue on the [tagalign](https://github.com/4meepo/tagalign) repo.

FYI, you can use `issues.exclude-rules` to handle the exclusion: https://golangci-lint.run/usage/configuration/#issues-configuration
