### ISSUE TITLE
Cyclop no longer working

### ISSUE THREAD

**Issue by huornlmj** [golangci/golangci-lint#3928]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

When I run

```console
$ golangci-lint run ./... --disable-all -E cyclop --no-config
```
I only get (typecheck) results, not (cyclop) results.

### Version of golangci-lint

(1.53.3)

### Configuration file

None

### Go environment

<details>

```console
$ go version && go env
go version go1.18.1 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/source/REDACTED/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build763151559=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

None

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello,


`typecheck` is not a real linter it's just a way to parse/display "compilation" and linters errors (linter reports are not errors).
So if you have `typecheck` reports, you will not have other reports.

**Comment by huornlmj** [comment]
Sorry but that's not actually what the issue is.  The problem is that even though I'm only enabling the cyclop checker, cyclop doesn't appear to be running.  Instead, the typecheck checker is running, **_even though I've disabled all checkers and only enabled cyclop._**

**Comment by ldez** [comment]
Can you provide a reproducible example (code and configuration) asked in the issue template?

FYI, `typecheck` is not a real linter, it cannot be disabled because of that.
