### ISSUE TITLE
Release v1.18.0-darwin-arm64 unavailable for download 

### ISSUE THREAD

**Issue by lukerees** [golangci/golangci-lint#3955]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Attempting to install version 1.18.0 of the package and receiving output:
```
golangci/golangci-lint info checking GitHub for tag 'v1.18.0'
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/v1.18.0
golangci/golangci-lint info found version: 1.18.0 for v1.18.0/darwin/arm64
golangci/golangci-lint debug downloading files into /var/folders/ks/65jhzgln1hl0mqv_0wlk5mdw0000gq/T/tmp.Z5N69QFA
golangci/golangci-lint debug http_download https://github.com/golangci/golangci-lint/releases/download/v1.18.0/golangci-lint-1.18.0-darwin-arm64.tar.gz
golangci/golangci-lint debug http_download_curl received HTTP status 404
```
Verified that other OS have v1.18.0 available but darwin/arm64 does not

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration

<details>

```console
# paste configuration file or CLI flags here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here

go version go1.20.1 darwin/arm64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

v1.18.0 has been released 4 years ago and supports go1.11.

we support only the current version (v1.53.3) of golangci-lint.

**Comment by lukerees** [comment]
> Hello,
> 
> [v1.18.0](https://github.com/golangci/golangci-lint/releases/tag/v1.18.0) has been released 4 years ago and supports go1.11.
> 
> 4 years ago, darwin/arm64 was not a topic, the first M1 appears in 2020.
> 
> we support only the current version (v1.53.3) of golangci-lint.

I was afraid that would be the case, okay thank you!
