### ISSUE TITLE
Travis-CI: Context loading failed: could not determine GOARCH and Go compiler

### ISSUE THREAD

**Issue by llorllale** [golangci/golangci-lint#397]
1. Version of golangci-lint: v1.14.0
2. `.golangci.yml`
See [here](https://github.com/llorllale/go-gitlint/blob/master/.golangci.yml)

3. Go environment:
```$ go version
go version go1.11.5 linux/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.11.5.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.11.5.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build698695726=/tmp/go-build -gno-record-gcc-switches"
```
4. Verbose output of running: `golangci-lint run -v`
See this [Travis build](https://travis-ci.org/llorllale/go-gitlint/builds/494057948)

**Comment by llorllale** [comment]
I can reproduce the issue locally if I run the [docker image](https://github.com/golangci/golangci/wiki/Configuration#how-to-test), but not if I run the binary directly.

**Comment by llorllale** [comment]
I've narrowed the issue down to one configuration in my `.golangci.yml`: `modules-download-mode: readonly`. I just commented it out and it works.

**Comment by jirfag** [comment]
hi, thank you!
you don't see a proper error because of poor error handling of `go list` in `go/packages`. Will be fixed in https://github.com/golangci/golangci-lint/issues/401

**Comment by kf6nux** [comment]
Same error, possibly different issue:
I found if we failed to configure git to use ssh instead of https, golangci-lint would fail at the `go list` stage when attempting to get a private repo.

**Comment by martinsirbe** [comment]
Seeing the same issue as @kf6nux because of this, it's not possible to use https with a github token.

**Comment by jirfag** [comment]
#401 was fixed, now we have normal errors, closing
