### ISSUE TITLE
Error during installation on macOS Sonoma

### ISSUE THREAD

**Issue by PSalant726** [golangci/golangci-lint#3984]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

When installing via `go install` on macOS Sonoma public beta 2, the installation fails with an error.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.51.0 built from (unknown, mod sum: "h1:M1bpDymgdaPKNzPwQdebCGki/nzvVkr2f/eUfk9C9oU=") on (unknown)
```

</details>

### Configuration

<details>

N/A

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.20.7 darwin/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/{{REDACTED}}/go/bin"
GOCACHE="/Users/{{REDACTED}}/Library/Caches/go-build"
GOENV="/Users/{{REDACTED}}/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/{{REDACTED}}/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/{{REDACTED}}/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.7/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bj/g9s4csxn0133kb42jm0kn7jh0000gn/T/go-build3463871108=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

N/A

</details>

### Code example or link to a public repository

<details>

```console
$ go install -v github.com/golangci/golangci-lint/cmd/golangci-lint@latest
# github.com/golangci/golangci-lint/cmd/golangci-lint
/opt/homebrew/Cellar/go/1.20.7/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: warning: -bind_at_load is deprecated on macOS
ld: warning: search path '/usr/local/lib' not found
ld: warning: '/private/var/folders/bj/g9s4csxn0133kb42jm0kn7jh0000gn/T/go-link-302694370/go.o' has malformed LC_DYSYMTAB, expected 138 undefined symbols to start at index 81717, found 150 undefined symbols starting at index 112
0  0x104228130  __assert_rtn + 72
1  0x1041e14f4  ___ZN2ld16LayoutExecutable27writeContentWithoutLinkEditENSt3__14spanIhLm18446744073709551615EEEy_block_invoke + 9772
2  0x180411950  _dispatch_client_callout2 + 20
3  0x180424ba0  _dispatch_apply_invoke + 176
4  0x180411910  _dispatch_client_callout + 20
5  0x1804233cc  _dispatch_root_queue_drain + 864
6  0x180423a04  _dispatch_worker_thread2 + 156
7  0x1805bb0d8  _pthread_wqthread + 228
ld: Assertion failed: (addr + content.size() <= sectionEndAddr), function writeContentWithoutLinkEdit_block_invoke, file Layout.cpp, line 5690.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by dkegel-fastly** [comment]
See https://github.com/golang/go/issues/61229, maybe?

**Comment by PSalant726** [comment]
> See [golang/go#61229](https://github.com/golang/go/issues/61229), maybe?

This is definitely the source of the current issue(s) with `gopls` on macOS Sonoma (see: https://github.com/golang/go/issues/61190), but it's unclear to me if this particular issue with `golangci-lint` is also related 🤷‍♂️

**Comment by ldez** [comment]
Hello,

> This is definitely the source of the current issue(s) with gopls on macOS Sonoma (see: https://github.com/golang/go/issues/61190), but it's unclear to me if this particular issue with golangci-lint is also related !man_shrugging!

It's not an issue with gopls but with the linker and some symbols, so this impact the compilation.
