### ISSUE TITLE
Move docs/ to a different repository

### ISSUE THREAD

**Issue by sethvargo** [golangci/golangci-lint#4013]
### Your feature request related to a problem? Please describe.

Our security team is flagging issues with our use of golangci-lint, and the issues are always related to vulnerabilities in the Node dependencies for the `docs/` folder.

### Describe the solution you'd like.

Move the `docs/` folder to a dedicated repository.

### Describe alternatives you've considered.

Publish a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) and a committed SLA for responding to security issues.

**Comment by ldez** [comment]
Hello,

the documentation will stay in the repository because maintenance and contribution are easier like that.

Your security team should change their practices.
