### ISSUE TITLE
Add go-sumtype

### ISSUE THREAD

**Issue by AlekSi** [golangci/golangci-lint#402]
https://github.com/haya14busa/gosum
I found it very useful to ensure that a new enum value is handled everywhere.

**Comment by AlekSi** [comment]
Another alternative: https://github.com/BurntSushi/go-sumtype

**Comment by jirfag** [comment]
thank you for suggestion

**Comment by matoous** [comment]
The first proposed linter is unmaintained, if we decide to add this linter I suggest going with the second one.

**Comment by SVilgelm** [comment]
it is not possible to use go-sumtype as a library

**Comment by cristaloleg** [comment]
Sounds like https://github.com/nishanths/exhaustive which is already supported.

**Comment by AlekSi** [comment]
I wasn't able to make `exhaustive` linter work with types like go-sumtype there: https://github.com/percona/pmm/blob/PMM-2.0/api/agentpb/agent.go

**Comment by leonklingele** [comment]
Implemented with https://github.com/nishanths/exhaustive linter.
