### ISSUE TITLE
Can we get non-zero error code even if all issues get fixed

### ISSUE THREAD

**Issue by rayjlinden** [golangci/golangci-lint#4041]
### Your feature request related to a problem? Please describe.

We generally run the linter with the "fix" option set in the config.  However, when fix's get applied the tool returns a 0 error code.

This is fine when running locally - but when running in the CI environment we would rather it return an error so we can stop the build.  (Turns out having modified code then breaks other shit later in the pipeline.)

Is there a way to have the --fix option se but still have it return an error code?

### Describe the solution you'd like.

An option to allow the linter to return a non-zero error code on found issues even if the "fix" option could fix all issues.

### Describe alternatives you've considered.

Have different configs for local use versus ci use?  Less than ideal...

**Comment by ldez** [comment]
Hello,

if all reports are fixed, there are no reports and so the exit code is zero, it's expected.

the `--fix` flags should not be used on a CI because it alters the content of the repository so it will ignore the reports.

**Comment by rayjlinden** [comment]
Your response is both completely logical and yet so not useful.

So like many people we call the linter from a Makefile AND we use a config file.  So both developers and the CI system just call "make lint".

Now when developers call it we want it to do the fix.
Now when CI calls it - I want it to FAIL.  (I actually don't care if it does the fix or not - I just need it to fail.)

Now if the developer calls it by had do they care if the return code is non-zero?  No.  Hell, they will not even notice.
But in the CI case - I need  it too return.

Ok - can I work around this.  Sure.  I can extra plumbing  in the Makefile to determine if I'm running in CI or not and adjust the config file accordingly.   Not too hard - just a pain.  If I had the option to cause the linter to return a non-zero error code it would be a one-line fix.  Now that would be useful...
