### ISSUE TITLE
Allow spaces inside "nolint" directive

### ISSUE THREAD

**Issue by leonklingele** [golangci/golangci-lint#405]
I'm migrating from gometalinter which will probably be [discontinued](https://github.com/alecthomas/gometalinter/issues/590) soon.

The syntax used by gometalinter to disable specific / all linters is as follows (see their [README](https://github.com/alecthomas/gometalinter/blob/f64e0e4b6a4bbabe18b0c66400fd164e2521cb01/README.md), GitHub doesn't allow linking to lines in Markdown files):

`// nolint[: <linter>[, <linter>, ...]]`

whereas this project uses the following syntax:

`//nolint[:linter1,linter2,...]`

Both currently seem to be supported by `golangci-lint` but that might not be intentional.

Which of the following forms are _officially_ supported?

- `// nolint[: <linter>[, <linter>, ...]]`
- `// nolint[:<linter>[,<linter>,...]]`
- `//nolint[: <linter>[, <linter>, ...]]`
- `//nolint[:<linter>[,<linter>,...]]`

**Comment by jirfag** [comment]
Hi!
All of these forms are supported for compatibility with the `gometalinter`. But the only one mentioned in the README is `//nolint[:linter1,linter2,...]` because it's the recommended one.

**Comment by leonklingele** [comment]
Thanks!
