### ISSUE TITLE
nolint sub linter

### ISSUE THREAD

**Issue by yonderblue** [golangci/golangci-lint#4050]
### Your feature request related to a problem? Please describe.

Cannot do nolint:revive:cyclomatic or something like that

### Describe the solution you'd like.

see above

### Describe alternatives you've considered.

ignoring too much

**Comment by ldez** [comment]
Duplicate of #1658

**Comment by yonderblue** [comment]
Does not seem to be a duplicate? I'm referring to something like https://github.com/mgechev/revive/issues/885#issuecomment-1699432511.
