### ISSUE TITLE
Add `go-safer` linter

### ISSUE THREAD

**Issue by cristaloleg** [golangci/golangci-lint#4061]
### Your feature request related to a problem? Please describe.

Go Vet-style linter to find incorrect uses of reflect.SliceHeader and reflect.StringHeader, and unsafe casts between structs with architecture-sized fields. https://github.com/jlauinger/go-safer

### Describe the solution you'd like.

This linter is based on `go/analysis` so adding it should be a big deal.

### Describe alternatives you've considered.

Not adding

### Additional context.

Probably I can take it if this feature will be accepted.

**Comment by ldez** [comment]
> The [SliceHeader](https://go.dev/pkg/reflect/#SliceHeader) and [StringHeader](https://go.dev/pkg/reflect/#StringHeader) types are now deprecated. In new code prefer [unsafe.Slice](https://go.dev/pkg/unsafe/#Slice), [unsafe.SliceData](https://go.dev/pkg/unsafe/#SliceData), [unsafe.String](https://go.dev/pkg/unsafe/#String), or [unsafe.StringData](https://go.dev/pkg/unsafe/#StringData).

https://go.dev/doc/go1.21

As those elements are not deprecated, a dedicated linter seems not required.
