### ISSUE TITLE
Typecheck errors with packages that don't match the import name

### ISSUE THREAD

**Issue by Tonkpils** [golangci/golangci-lint#4073]
### Welcome

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Similar to https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/736

Running 

```
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.54.2 golangci-lint run -v
```

complains on files where there are packages defined that don't match the name of the package.

```go
package main

import "github.com/vaughan0/go-ini"

type Foo struct { 
  File ini.File // undefined: ini (typecheck)
}
```

Even though the project builds and runs without issues.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.54.2 built with go1.21.0 from 411e0bbb on 2023-08-21T12:26:30Z
```

</details>

### Configuration

<details>

```console
golangci-lint run -v
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.21.0 linux/amd64
```

</details>

### Verbose output of running

<details>

Output of sample file is mentioned above

```
undefined: ini (typecheck)
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
package main

import "github.com/vaughan0/go-ini"

type Foo struct { 
  File ini.File // undefined: ini (typecheck)
}
```

</details>

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

I am not able to reproduce your error.

Please read https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors

**Comment by chaoyifei** [comment]
@Tonkpils How to solve this problem
