### ISSUE TITLE
unused: support options

### ISSUE THREAD

**Issue by fatanugraha** [golangci/golangci-lint#4085]
### Your feature request related to a problem? Please describe.

unused (U1000) has its own configuration to tune its aggressiveness on determining whether an object is unused or not.
ref: https://github.com/dominikh/go-tools/blob/master/unused/unused.go#L231C6-L231C13

Currently we used `config.StaticCheckSettings` to configure this linter which doesn't allow us to tune its behaviour. If you think this is acceptable I can come up with an MR to support this.

### Describe the solution you'd like.

A new configuration to configure `unused`'s [options](https://github.com/dominikh/go-tools/blob/master/unused/unused.go#L231C6-L231C13)

### Describe alternatives you've considered.

N/A

**Comment by ldez** [comment]
Hello,

you can try to create a PR but unused options are accessible only via a global variable, so concurrency issues can occur.
