### ISSUE TITLE
rpm package: adds dependencies

### ISSUE THREAD

**Issue by gucio321** [golangci/golangci-lint#4089]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Hi, I've just updated to latest release (I'm lazy so I'm using rpm package for fedora)
When installing via dnf, it wants to add some extra packages:
```console

===============================================================================
 Package             Architecture Version             Repository          Size
===============================================================================
Installing:
 golangci-lint       x86_64       1.54.2-1            @commandline       9.9 M
Installing dependencies:
 libgo               x86_64       13.2.1-1.fc38       updates            7.5 M
 libgo-devel         x86_64       13.2.1-1.fc38       updates            490 k
Installing weak dependencies:
 gcc-go              x86_64       13.2.1-1.fc38       updates             13 M
```
(it tries to install dnf's version of golang)
Its a problem, because I'm not using fedora's go (its 3 minor rleases behind upstream).

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

### Configuration

_not applicable_

### Go environment

_not applicable_

### Verbose output of running

_not applicable_

### A minimal reproducible example or link to a public repository

_not applicable_

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

We don't maintain rpm repositories, you can contact the maintainer of this package (I don't know who is it).

**Comment by gucio321** [comment]
@ldez so how this golangci-lint.rpm gets to yoUr releases?

**Comment by ldez** [comment]
We create a RPM package but we don't provide it through an RPM repository.

**Comment by gucio321** [comment]
> We create a RPM package but we don't provide it through an RPM repository.
I don't know how dnf handles that.

so yes, I mean this package.
I download it and install using `sudo dnf install ./golangci-lint.rpm` and it installs golang as dependency for some reason (and it ditn't do that in previous releases)

**Comment by gucio321** [comment]
@ldez so there is no repository

**Comment by ldez** [comment]
outside of RPM, Go is a requirement (`diff` too).
Inside the definition of the RPM:
https://github.com/golangci/golangci-lint/blob/41bfce91a56541224bc1e7b334a8d03674149679/.goreleaser.yml#L131-L132

It's just a recommendation, and not related to another package, so I don't understand how this become a requirement inside the RPM.

**Comment by denisvmedia** [comment]
Just to avoid creating a new ticket for such a simple question: when do you think we can have a new release @ldez ? There was a bunch of various improvements and new features in several linters, and it'd be nice be be able to use them.
