### ISSUE TITLE
doc: check default lists configuration reference

### ISSUE THREAD

**Issue by Antonboom** [golangci/golangci-lint#4134]
### Your feature request related to a problem? Please describe.

```
$ grep ': \[\]' .golangci.reference.yml
  # Default: [].
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
      # Default: []
      # Default: []
      # Default: []
      # Default: []
    # Default: [] - means include all rules
    # Default: []
    # Default: []
        # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
    # Default: []
  # Default: []
  # Default: []
```

### Describe the solution you'd like.

1. Review configuration.
2. If `default` is really empty – no changes.
3. If `default` is not empty – add value and context in the comment.
4. Change rule about this field in the new-linter-checklist

### Describe alternatives you've considered.

Let it be as it is.

### Additional context.

https://github.com/golangci/golangci-lint/pull/4127#issuecomment-1760904555

**Comment by ldez** [comment]
The majority of those empty defaults are real.
