### ISSUE TITLE
Add "urlcheck" linter

### ISSUE THREAD

**Issue by 500poundbear** [golangci/golangci-lint#4147]
### Your feature request related to a problem? Please describe.

Some URLs embedded within comments get stale and invalid over time, i.e. they stop returning HTTP 200. 

A secondary problem is that some contributors are unaware about the [Go Doc comment links](https://go.dev/doc/comment#links) recommendation to leave the actual URLs at the bottom of the comment block.

### Describe the solution you'd like.

I will like to contribute a linter that can check that:

* All urls are still returning HTTP 200
* URLs should be formatted as per Go Doc recommendation

### Describe alternatives you've considered.

Perhaps a whitelist/blacklist should be configurable to limit the URLs to test

**Comment by Antonboom** [comment]
> All urls are still returning HTTP 200

IMHO, the static analyzer making network calls is not a good idea, especially for isolated CI environments.

**Comment by ldez** [comment]
I agree with you, network calls are a bad idea.

The element about doc formatting can be integrated in another linter, so I will close this issue.

**Comment by 500poundbear** [comment]
@Antonboom do you have a recommendation on the suitable linter to add the URL formatting & comment structure check?

**Comment by Antonboom** [comment]
@500poundbear also, related tool

https://github.com/butuzov/deadlinks

**Comment by 500poundbear** [comment]
thanks for the followup @Antonboom yep that is the essence of the 'urlcheck' linter :)
