### ISSUE TITLE
Allow lint of `examples` directory

### ISSUE THREAD

**Issue by Sean-Der** [golangci/golangci-lint#416]
Hey @jirfag 

golangci-lint is amazing, switching to it has made such a huge difference for my project. It is so nice to not manage all these linters on my own (and wasn't aware of how bad my code was before)

My repo [pions/webrtc](https://github.com/pions/webrtc) has an examples directory, and I would like to lint it. It is ignored by default [here](https://github.com/golangci/golangci-lint/blob/master/pkg/packages/skip.go#L22) and I haven't found a way to override it.

Are there any hacks I can do to make this happen though? I noticed the quality of my examples slipping without this. For now I can exec twice, but that puts a bigger burden on contributors. 

thanks!

**Comment by Sean-Der** [comment]
@jirfag I would love to make the PR for this as well (if you have a suggestion on how you would like to see this implemented) 

Can I expose `excluded-directories` as an argument, and make the default match the current behavior?

**Comment by jirfag** [comment]
Hi!
I suggest making an analog of `--exclude-use-default`: `--skip-dirs-use-default=true|false` with enumerating all default skipped dirs

**Comment by Sean-Der** [comment]
Hey @jirfag anything I can do to help get this merged? It would be really nice to be able to lint Pion using the hosted golang-ci

thanks!
