### ISSUE TITLE
Errors "can't run linter goanalysis_metalinter: musttag: running `go list all`"

### ISSUE THREAD

**Issue by nawa** [golangci/golangci-lint#4165]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I run `golangci-lint` on GH actions using `golangci/golangci-lint:v1.54.1`

```yaml
  lint:
    container:
      image: golangci/golangci-lint:v1.54.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: golangci-lint run -v
```

 and receive next errors

```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1\n\n"
```

This issue isn't reproduced locally neither with `golangci-lint` locally installed nor with the same docker image. `go list all` is executed without errors as well

Such issue wasn't observed with `v1.50.1`

### Version of golangci-lint

<details>

```console
$ golangci-lint --version

golangci-lint has version v1.54.1 built with go1.21.0 from a9378d9b on 2023-08-11T13:17:35Z
```

</details>

### Configuration

<details>

```console
golangci-lint run -v
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

> - [X] Yes, I've included all the information above (version, config, etc.).

can you add the missing information?
