### ISSUE TITLE
Directory prefix src does not contain main module or its selected dependencies

### ISSUE THREAD

**Issue by stephanwesten** [golangci/golangci-lint#4189]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I searched for similar issues, but it is pretty subtle so I can't tell for sure. Feel free to close as duplicate.

To reproduce, create a new folder 'testgolint', with a 'src' folder and two files: go.main and go.mod:

```
➜  testgolint ls -R
src

./src:
go.mod  main.go
```

Run the linter:
```
➜  testgolint golangci-lint run src/...
ERRO [linters_context] typechecking error: pattern ./src/...: directory prefix src does not contain main module or its selected dependencies

➜  testgolint golangci-lint run src    
ERRO Running error: context loading failed: no go files to analyze

```

env:

```
➜  testgolint go env GOPATH
/Users/xyz/go

➜  testgolint go version 
go version go1.20.4 darwin/arm64
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version

➜  testgolint golangci-lint --version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z
```

</details>

### Configuration

<details>

```console
# paste configuration file or CLI flags here

n/a
```

</details>

### Go environment

see description, don't want to paste all info unless it is really needed

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/stephan.westen/projects/testgolint /Users/stephan.westen/projects /Users/stephan.westen /Users /] 
INFO [lintersdb] Active 6 linters: [errcheck gosimple govet ineffassign staticcheck unused] 
INFO [loader] Go packages loading at mode 575 (imports|name|compiled_files|deps|exports_file|files|types_sizes) took 17.879708ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 24.125µs 
ERRO [linters_context] typechecking error: pattern ./...: directory prefix . does not contain main module or its selected dependencies 
INFO [linters_context/goanalysis] analyzers took 2.299212ms with top 10 stages: fact_deprecated: 511.167µs, buildir: 408.584µs, typecheck: 113.875µs, ineffassign: 103.208µs, httpresponse: 87.834µs, S1003: 80.333µs, framepointer: 71.917µs, S1016: 71.458µs, unmarshal: 65.834µs, SA4000: 62.584µs 
INFO [runner] processing took 1.288µs with stages: max_same_issues: 208ns, skip_files: 166ns, skip_dirs: 166ns, path_prettifier: 83ns, nolint: 83ns, path_prefixer: 42ns, filename_unadjuster: 42ns, fixer: 42ns, sort_results: 42ns, severity-rules: 42ns, diff: 42ns, cgo: 42ns, exclude-rules: 42ns, uniq_by_line: 41ns, max_per_file_from_linter: 41ns, max_from_linter: 41ns, autogenerated_exclude: 41ns, identifier_marker: 41ns, source_code: 41ns, exclude: 0s, path_shortener: 0s 
INFO [runner] linters took 12.61375ms with stages: goanalysis_metalinter: 12.575917ms 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 2 samples, avg is 27.4MB, max is 27.7MB 
INFO Execution took 43.000541ms
```

</details>

### A minimal reproducible example or link to a public repository

see describes

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by stephanwesten** [comment]
also tried Go 1.21:

```
➜  testgolint go version
go version go1.21.4 darwin/arm64

```
same results

**Comment by bombsimon** [comment]
I cannot reproduce this on macOS 14 with go1.21.3 darwin/amd64

```sh
› mkdir -p testgolint/src
› cd testgolint/src
› go mod init x
go: creating new go.mod: module x
› echo "package main\n\nvar i = 1" > main.go
› cd ..
› golangci-lint run --no-config --disable-all --enable gochecknoglobals ./src/...
src/main.go:3:5: i is a global variable (gochecknoglobals)
var i = 1
    ^
```

What's in your `main.go`?

**Comment by stephanwesten** [comment]
main is close to empty:

```
package main

func main() {

}

```

My real project - with the same problem - has a realistic impl - that how ran into this.

Note that if I navigate into src, there is no error:
```
➜  src golangci-lint run 
➜  src 

```

(I tried adding a dummy assignment into main and indeed get a linter error)

Somehow locating the src folder gives issues.

**Comment by stephanwesten** [comment]
So it seems something specific to my setup, perhaps this gives a clue:


```
➜  src go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/stephan.westen/Library/Caches/go-build'
GOENV='/Users/stephan.westen/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/stephan.westen/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/stephan.westen/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/stephan.westen/projects/testgolint/src/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/nq/d7q3r9d96dx4f07_ttn4_38w0000gn/T/go-build3511727781=/tmp/go-build -gno-record-gcc-switches -fno-common'

```

**Comment by stephanwesten** [comment]
module is different:

```
➜  src cat go.mod
module testgolint
```

**Comment by ldez** [comment]
If your project follows this:
```
.
└── src
    ├── go.mod
    └── main.go
```

and you try to run golangci-lint at the root of this structure, the behavior is expected because you are outside the module.

**Comment by ldez** [comment]
The error message comes from Go itself:
https://github.com/golang/go/blob/1cc19e5ba0a008df7baeb78e076e43f9d8e0abf2/src/cmd/go/internal/modload/load.go#L497-L505

**Comment by officialasishkumar** [comment]
Hey @ldez , How to solve this problem? 

https://github.com/keploy/samples-go/actions/runs/7538153673/job/20518222700

**Comment by officialasishkumar** [comment]
@ldez thanks for the reply. I was trying to fix it but the [pipeline](https://github.com/keploy/samples-go/actions/runs/7545047650/job/20539807383) always ignore the [unused variable in a specific module](https://github.com/keploy/samples-go/pull/93/files#diff-f843f4b4e93c1f20dcc848778e668242bf7ef7e1aa2ff505ea452916a3d9fa16) even after including it in the [working-directory](https://github.com/keploy/samples-go/pull/93/files#diff-d9a956120ac84289d2650137f64bd8f0893331de05e44cc41899dd984c9e0d48) .
