### ISSUE TITLE
goconst: add ignore-strings support

### ISSUE THREAD

**Issue by tarasmadan** [golangci/golangci-lint#4198]
### Your feature request related to a problem? Please describe.

Some string literals may generate false positives. https://github.com/google/syzkaller/pull/4323 is an example.

### Describe the solution you'd like.

goconst sinve v1.7.0 supports the ignore-strings regexp.
It allows to opt-out some literals.
This new parameter is not yet supported by golangci-lint.

### Describe alternatives you've considered.

1. To opt-out specific lines by "// nolint: goconst".
2. To add special literal.

**Comment by ldez** [comment]
Hello,

When we update goconst to v1.7.0, we will add the option.
currently, we use v1.6.0

https://github.com/golangci/golangci-lint/blob/b3146552ac168eba7e658bb2cad99996bf79e7d6/go.mod#L58C38-L58C38
