### ISSUE TITLE
Would you be open to an `--include` option?

### ISSUE THREAD

**Issue by svanharmelen** [golangci/golangci-lint#420]
Please have a look at this PR I made a while ago for `gometalinter`: https://github.com/alecthomas/gometalinter/pull/71

Would you be open to adding such a feature to `golangci-lint`? The main reasoning is that some linters need to run on the whole package and don't work when you run them on a single file (like `typecheck` for example).

So when running this in an editor (in my case using ALE with neovim) you need to run this on the whole package in order for all linters to work. But that means that _all_ issues are getting loaded in your (in my case) location list, instead of only the issues related to the file you are working on.

The `gometalinter` PR was created for exactly that is the feature is used in both `vim-go` and `ALE`, so I would love to have this functionality when switching to `golangci-lint`.

Thanks!

**Comment by jirfag** [comment]
Hi, thank you for suggestion!

1. Golangci-lint exclude mechanism differs from the gometalinter's one: we don't handle file path excluding by `--exclude`: this option excludes only by a message text. But golangci-lint can exclude by file path by `skip-files`.
2. As I understand the goal is to analyze an only one file. If we run golangci-lint on one file we can get compilation errors. I think a more convenient way is to fix this behavior: if a user requested an analysis of one file we need to load a full package but report errors only from this file. The simplest way to implement it is:
1. replace single files by their packages
2. make a Include processor and filter messages for such packages

**Comment by svanharmelen** [comment]
Sounds good to me! I think that will improve the usability of `golangci-lint` when used `on-save` from within an editor 👍
