### ISSUE TITLE
Enable all except deprecated option

### ISSUE THREAD

**Issue by antonsacred** [golangci/golangci-lint#4204]
### Your feature request related to a problem? Please describe.

I would like to run all linters, but exclude deprecated, to not consider linters that will be removed somewhere in the future.

### Describe the solution you'd like.

2 options:

* Combine of 2 options: `--enable-all` and `--disable-deprecated` at the same time
* `--enable-all-except-deprecated`

### Describe alternatives you've considered.

-

**Comment by ldez** [comment]
Hello,

the deprecation flow is discussed here #1987.
Your issue can be considered as a part of this discussion.
