### ISSUE TITLE
errcheck check-blank not worked well

### ISSUE THREAD

**Issue by jinleileiking** [golangci/golangci-lint#4205]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

errcheck check-blank not worked well
```
a, _ := func()
```
should be checked, but enable `check-blank` not work.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.54.2 built with go1.21.0 from 411e0bbb on 2023-08-21T12:04:32Z
```

</details>

### Go environment

<details>

```

go version go1.21.0 linux/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jinlei/.cache/go-build'
GOENV='/home/jinlei/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jinlei/gocodes/pkg/mod'
GONOPROXY='git.visionular.com'
GONOSUMDB='git.visionular.com'
GOOS='linux'
GOPATH='/home/jinlei/gocodes'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/home/jinlei/os/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/jinlei/os/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/jinlei/gocodes/src/cloudlive/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build770989326=/tmp/go-build -gno-record-gcc-switches'
```

</details>

### Verbose output of running

nil

### A minimal reproducible example or link to a public repository

nil

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by jinleileiking** [comment]
use errcheck cmdline worked.

**Comment by jinleileiking** [comment]
or vim-go pluglin

**Comment by jinleileiking** [comment]
strange. 

enable type assertion check will make blank check worked well....

<img width="356" alt="image" src="https://github.com/golangci/golangci-lint/assets/93968/e465a9a7-ab84-40a4-9d4e-66720769b48e">

**Comment by jinleileiking** [comment]
<img width="1026" alt="image" src="https://github.com/golangci/golangci-lint/assets/93968/b86f1f86-800c-4aaf-847b-3866977b9ec3">

**Comment by jinleileiking** [comment]
<img width="1512" alt="image" src="https://github.com/golangci/golangci-lint/assets/93968/92e6deb6-c7b9-46f7-af00-aa3c3fe54c0f">

**Comment by jinleileiking** [comment]
<img width="712" alt="image" src="https://github.com/golangci/golangci-lint/assets/93968/5e9c9890-85dd-4976-804f-51cb72fed73b">

**Comment by jinleileiking** [comment]
```
❯ cat .golangci.yml
linters-settings:
  errcheck:
    check-blank: true
  forbidigo:
    forbid:
      - ^fmt.Print(f|ln)?$
      # - ^log.(Panic|Fatal|Print)(f|ln)?$
      - ^os.Exit$
      - ^spew.*Dump$
      # - ^panic$
      - ^print(ln)?$
  staticcheck:
    checks:
      - '-SA1029'
```

**Comment by jinleileiking** [comment]
latest version, same:
<img width="881" alt="image" src="https://github.com/golangci/golangci-lint/assets/93968/8e084a0b-0124-484f-bd31-e82cd2f5b623">

**Comment by jinleileiking** [comment]
errcheck cmd use latest

**Comment by ldez** [comment]
Hello,

> [x] Yes, I've included all the information above (version, config, etc.).

1. you haven't provided all the information.
2. you have spam this issue with 10 comments instead of just editing the issue description.

Conclusion: you should follow the issue template and its requirements and never spam an issue.

**Comment by ldez** [comment]
```go
package main

import "fmt"

func main() {
	a, _ := func() (string, error) { return "", nil }()

	fmt.Println(a)
}
```

```yml
linters:
  disable-all: true
  enable:
    - errcheck

linters-settings:
  errcheck:
    check-blank: true
```

```console
$ golangci-lint version 
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z

$ golangci-lint run 
main.go:6:5: Error return value is not checked (errcheck)
        a, _ := func() (string, error) { return "", nil }()
           ^
```

**Comment by jinleileiking** [comment]
sorry, It was cause by     `disable-default-exclusions: true` deault is false, will suppress   a lot of warnings
