### ISSUE TITLE
golangci-lint is slow for projects with many files.

### ISSUE THREAD

**Issue by sbadame** [golangci/golangci-lint#4217]
### Your feature request related to a problem? Please describe.

I'm working on a project that includes vendored dependencies. This alone appears to be taking ~5 minutes.

I was hoping that configuration like skip-dirs or "issues: new" would help reduce the search space, but instead it looks like it only affects which findings are _reported_. I was also hoping for a way to say: "only lint these files or directories", but that also doesn't appear to be a feature.

Thank you!

### Describe the solution you'd like.

Is there a way to either:
1. Get more profiling information from golanglint-ci? Using -v doesn't give me any output beyond the initial loading of configuration. 
2. Configure golanglint-ci to only run on a sub directory?
3. Configure golanglint-ci to ignore any files that were not changed between git revisions?

### Describe alternatives you've considered.

It seems that regardless of my configuration for golangci-lint it will always at the very least try to "stat" every file in my directory (by checking with strace).

**Comment by ldez** [comment]
1. https://golangci-lint.run/contributing/debug/
2. golangci-lint acts as a Go compiler, so partial analyze are globally not possible
3. the option `new-from-rev` https://golangci-lint.run/usage/configuration/#issues-configuration
