### ISSUE TITLE
Add deadcode linter

### ISSUE THREAD

**Issue by alexandear** [golangci/golangci-lint#4254]
### Your feature request related to a problem? Please describe.

Add [`deadcode`](golang.org/x/tools/cmd/deadcode) linter to find unreachable functions that will replace deprecated [`deadcode`](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/deadcode.go).

### Describe the solution you'd like.

Integrate into golangci-lint `deadcode` tool which is described here https://go.dev/blog/deadcode. 

### Describe alternatives you've considered.

`golangci-lint` already has [`unused`](https://golangci-lint.run/usage/linters/#unused) linter.

**Comment by ldez** [comment]
deadcode is a command line, not a lib, so we cannot use it.

**Comment by KasonBraley** [comment]
> And `unused` is more accurate.

There are some differences, some in favor of `deadcode`. It looks like the difference is in they way they both handle interfaces. The `deadcode` tool correctly identifies unreachable methods that `unused` does not report. I'm not saying `deadcode` should be in golangci-lint or not, just wanted to point out my findings.

**Comment by ldez** [comment]
Finding unused elements is complex, requiring a subtle balance between relevance and false positives.
`deadcode` has more false positives.
an example of false positives: when you create a lib, some exposed functions will be unused, but it's expected as it's a lib.

`deadcode` is oriented for analyzing the code of Go itself, so it's optimized for applications but not libs.

**Comment by theyoprst** [comment]
> an example of false positives: when you create a lib, some exposed functions will be unused, but it's expected as it's a lib.

On the other hand if those functions are not used, it means that they are not tested. Which shows some problem, isn't it?

**Comment by ldez** [comment]
> On the other hand, if those functions are not used, it means that they are not tested. 

no, because by default `deacode` doesn't analyze tests, you have to add `-test`.

In all cases `deadcode` is not usable as a lib.

**Comment by ikari-pl** [comment]
> no, because by default `deacode` doesn't analyze tests, you have to add `-test`.

nice, that's the linter I've been looking for
