### ISSUE TITLE
golangci-lint version format in macOS is different than other platforms

### ISSUE THREAD

**Issue by jsolana** [golangci/golangci-lint#4263]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

In macOS, `golangci-lint version` returns its  version in different format.

```console
golangci-lint version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265 on 2023-11-02T21:40:02Z
```

Instead of `vMajor.minor.patch`. Eg using docker alternative:

```console
docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.55.2 golangci-lint version

golangci-lint has version v1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T13:27:54Z
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265 on 2023-11-02T21:40:02Z
```

</details>

### Configuration

Running `sw_vers`

ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

### Go environment

<details>

```console
$ go version && go env
go version go1.21.3 darwin/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/javier.solana/Library/Caches/go-build'
GOENV='/Users/javier.solana/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/javier.solana/go/pkg/mod'
GONOPROXY='gopkg.cabify.tools,gitlab.otters.xyz,secondary.gitlab.otters.xyz,gitlab.com/cabify,github.com/cabify'
GONOSUMDB='gopkg.cabify.tools,gitlab.otters.xyz,secondary.gitlab.otters.xyz,gitlab.com/cabify,github.com/cabify'
GOOS='darwin'
GOPATH='/Users/javier.solana/go'
GOPRIVATE='gopkg.cabify.tools,gitlab.otters.xyz,secondary.gitlab.otters.xyz,gitlab.com/cabify,github.com/cabify'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.21.3/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.3/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/zm/4j_1k_j979sffbtvh_jm2wyr0000gr/T/go-build2602725925=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

</details>

### Verbose output of running

NA

### A minimal reproducible example or link to a public repository

Install `golangci-lint` following [the instructions to install `golangci-lint` locally in MacOs](https://golangci-lint.run/usage/install/#macos)
Run `golanci-lint --version`

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

it's not a problem with golangci-lint itself but a problem with [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/g/golangci-lint.rb).

We (the golangci-lint maintainers) are maintainers of the homebrew solution.

**Comment by ldez** [comment]
If you use our [binaries](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2) you will see that the version has the same format on all OS.

Homebrew builds the binary from sources, so the version is defined by Homebrew.

https://github.com/Homebrew/homebrew-core/blob/56b593d11f0fadf7f63b0b437a5cb520c83489e1/Formula/g/golangci-lint.rb#L25

It's better to follow the original golangci-lint format but Homebrew can use a different version format, there is no rule.

**Comment by jsolana** [comment]
Nice thanks a lot!

**Comment by ldez** [comment]
There is a typo in my previous message: We (the golangci-lint maintainers) are **not** maintainers of the homebrew formula.

**Comment by ldez** [comment]
In fact there is a problem with the build of the Docker image: https://github.com/golangci/golangci-lint/discussions/4268
