### ISSUE TITLE
godiff return no output to goimports

### ISSUE THREAD

**Issue by sohailmd1-lhat** [golangci/golangci-lint#4276]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Issue is  similar to #307 

https://github.com/golangci/golangci-lint/issues/1169

I am seeing this error in windows.

level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: goimports: can't extract issues from gofmt diff output \"\": got no diffs from patch parser: \n\n"

First I got the error that "diff" was not present in the PATH value. I installed it and added it to the PATH. Then it gave the above error where diff parser did not return any output to goimports.
### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration

<details>

```console
# paste configuration file or CLI flags here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

you provided 0 elements of the required section, your issue will be closed.
Also, the answer to your problem is inside the issues you have linked.

**Comment by sohailmd1-lhat** [comment]
Hello,

Apologies for not providing the required details due to constraint of time. 

The issue still seems to persists. I will open another issue with all the required details. 

Also if you can please point me to workarounf/fix for the issues. I have added in the mentioned issues as well. 

Link : https://github.com/golangci/golangci-lint/issues/307#issuecomment-1864244234
