### ISSUE TITLE
revive: Missing rule enforce-slice-style

### ISSUE THREAD

**Issue by orestisfl** [golangci/golangci-lint#4278]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

The [enforce-slice-type](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-slice-style) rule is missing from golangci-lint.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z
```

</details>

### Configuration

<details>

```console
linters:
  disable-all: true
  enable:
    - revive

linters-settings:
  revive:
    enable-all-rules: false
    rules:
      - name: enforce-slice-style
        arguments:
          - "literal"
```

</details>

### Go environment

<details>

```console
$ go version && go env
Can provide upon request
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Used config file .golangci.yaml 
INFO [lintersdb] Active 1 linters: [revive]       
INFO [loader] Go packages loading at mode 575 (types_sizes|files|imports|name|compiled_files|deps|exports_file) took 1.043404014s 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 14.608104ms 
INFO [linters_context/goanalysis] analyzers took 74.764074ms with top 10 stages: the_only_name: 73.680205ms, typecheck: 1.083869ms 
WARN [runner] Can't run linter goanalysis_metalinter: the_only_name: cannot find rule: enforce-slice-style 
INFO [runner] processing took 3.339µs with stages: max_same_issues: 459ns, source_code: 446ns, skip_dirs: 350ns, nolint: 289ns, cgo: 166ns, identifier_marker: 163ns, skip_files: 160ns, autogenerated_exclude: 157ns, exclude-rules: 151ns, filename_unadjuster: 149ns, fixer: 148ns, path_prettifier: 143ns, max_from_linter: 95ns, exclude: 64ns, sort_results: 62ns, path_shortener: 62ns, severity-rules: 57ns, uniq_by_line: 55ns, max_per_file_from_linter: 55ns, path_prefixer: 54ns, diff: 54ns 
INFO [runner] linters took 1.294847234s with stages: goanalysis_metalinter: 1.294809637s 
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: the_only_name: cannot find rule: enforce-slice-style
 
INFO Memory: 26 samples, avg is 211.5MB, max is 845.0MB 
INFO Execution took 2.437671107s 
```

</details>

### A minimal reproducible example or link to a public repository

Unrelated to any specific repo

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

`enforce-slice-style` is not in a release:
- the latest release of revive is [v1.3.4](https://github.com/mgechev/revive/releases/tag/v1.3.4): 2023-09-17
- The [PR](https://github.com/mgechev/revive/pull/900) with `enforce-slice-style` has been merged the 2023-09-23
- we use [v1.3.4](https://github.com/golangci/golangci-lint/blob/d131daf184e272288ec16246980522e4e8ac5ebe/go.mod#L77)
- 
so as it's not in a release of revive, it's not in golangci-lint.

**Comment by orestisfl** [comment]
Oops :facepalm: sorry for the noise
