### ISSUE TITLE
Add s390x binaries to goreleaser config?

### ISSUE THREAD

**Issue by dnwe** [golangci/golangci-lint#430]
For CI-purposes, it is convenient to fetch pre-built binaries from the releases.

Currently these are just linux, mac, windows, i386 and amd64:
https://github.com/golangci/golangci-lint/blob/7514bf823931b8c777a68ba7a7af8e5217fff191/.goreleaser.yml#L11-L17

Please could I request adding `s390x` to the arch set?

**Comment by jirfag** [comment]
Hi, I am ok with that. Could you please add it yourself, run goreleaser locally and test resulted binary? I have no s390x platform to test.

**Comment by jirfag** [comment]
already added

**Comment by dnwe** [comment]
Thanks 😊 fixed by https://github.com/golangci/golangci-lint/pull/797
