### ISSUE TITLE
gosimple suggests to remove comments from if()s that are specifically written to make a comment stand out

### ISSUE THREAD

**Issue by alexander-hirth** [golangci/golangci-lint#4300]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Sometimes it makes sense to have code organised this way:
```
if cond {
    // explain a rather non-obvious condition checked by this if()
    return true
}
// I expect more cases to appear where I need to return true,
// but for now the above case is the only one.
return false
```

gosimple suggests to replace this with a plain `return cond`.

If a conditional `if smth { return true }` has comments inside, then do not suggest to fold it with the code that follows.

### Version of golangci-lint

golangci-lint has version v1.55.2 built with go1.21.4 from (unknown, mod sum: "h1:yllEIsSJ7MtlDBwDJ9IMBkyEUz2fYE0b5B8IUgO1oP8=") on (unknown)

### Configuration

```
linters:
  disable-all: true
  enable:
    - gosimple
```

### Go environment

```
% go version
go version go1.21.4 linux/amd64
```

`go env` is irrelevant and contains some data that can't be shared.

### Verbose output of running

```
INFO [config_reader] Config search paths: [./ /home/alex/testing/lint /home/alex/testing /home/alex /home /]
INFO [config_reader] Used config file .golangci.yaml
INFO [lintersdb] Active 1 linters: [gosimple]
INFO [loader] Go packages loading at mode 575 (deps|files|types_sizes|compiled_files|exports_file|imports|name) took 33.232431ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 145.091µs
INFO [linters_context/goanalysis] analyzers took 0s with no stages
INFO [runner] Processors filtering stat (out/in): max_same_issues: 1/1, skip_dirs: 1/1, path_prettifier: 1/1, exclude: 1/1, max_from_linter: 1/1, path_prefixer: 1/1, filename_unadjuster: 1/\
1, identifier_marker: 1/1, exclude-rules: 1/1, skip_files: 1/1, autogenerated_exclude: 1/1, nolint: 1/1, uniq_by_line: 1/1, diff: 1/1, max_per_file_from_linter: 1/1, source_code: 1/1, path_\
shortener: 1/1, cgo: 1/1, fixer: 1/1, sort_results: 1/1, severity-rules: 1/1
INFO [runner] processing took 267.583µs with stages: exclude-rules: 70.901µs, identifier_marker: 67.261µs, nolint: 49.391µs, source_code: 23.31µs, autogenerated_exclude: 21.73µs, path_prett\
ifier: 20.03µs, skip_dirs: 5.91µs, max_same_issues: 1.8µs, cgo: 1.39µs, uniq_by_line: 1.16µs, path_shortener: 1.06µs, max_from_linter: 1.01µs, filename_unadjuster: 500ns, max_per_file_from_\
linter: 380ns, fixer: 350ns, severity-rules: 290ns, exclude: 290ns, skip_files: 260ns, diff: 210ns, sort_results: 190ns, path_prefixer: 160ns
INFO [runner] linters took 896.172µs with stages: goanalysis_metalinter: 524.957µs
l.go:4:2: S1008: should use 'return x > 0' instead of 'if x > 0 { return true }; return false' (gosimple)
        if x > 0 {
        ^
INFO File cache stats: 1 entries of total size 119B
INFO Memory: 2 samples, avg is 26.1MB, max is 28.1MB
INFO Execution took 38.982958ms
```

### A minimal reproducible example or link to a public repository

```
package main

func F(x int) bool {
        if x > 0 {
                // a comment
                return true
        }
        return false
}
```

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

you can use the `nolint` directive: https://golangci-lint.run/usage/false-positives/#nolint-directive

FYI, golangci-lint is a wrapper around linters.

**Comment by bombsimon** [comment]
To elaborate, this in the upstream repository: https://github.com/dominikh/go-tools. The rule is [S1008](https://staticcheck.dev/docs/checks/#S1008) and is implemented [here](https://github.com/dominikh/go-tools/tree/master/simple/s1008).
