### ISSUE TITLE
Improve description of spancheck linter

### ISSUE THREAD

**Issue by alexandear** [golangci/golangci-lint#4310]
### Your feature request related to a problem? Please describe.

The description for the [spancheck linter](https://golangci-lint.run/usage/linters/#spancheck) on the website seems excessively lengthy and weirdly formatted (see screenshots). This decreases readability.

<img width="1296" alt="image" src="https://github.com/golangci/golangci-lint/assets/3228886/d7be1d78-3004-4ba9-9891-0eff33fe0a77">

<img width="889" alt="image" src="https://github.com/golangci/golangci-lint/assets/3228886/ca0d4efc-4932-483f-9eb6-5fa309a6a91f">

### Describe the solution you'd like.

Drop examples from the description:

```
Check for mistakes with OpenTelemetry trace spans.

Common mistakes with OTEL trace spans include forgetting to call End, forgetting to set an Error status, forgetting to record the Error
```

### Describe alternatives you've considered.

N/A

**Comment by ldez** [comment]
I think we will just keep `"Check for mistakes with OpenTelemetry trace spans."`

**Comment by jjti** [comment]
whoops! I got that approach from `go/tools/analysis` packages, eg: https://github.com/golang/tools/blob/6a0605d4e3d20a2ffb313ef9106199551317973d/go/analysis/passes/lostcancel/lostcancel.go#L26

Did not realize we'd display the whole thing in these docs, though
