### ISSUE TITLE
remove nilness from go vet linter configuration settings on the website

### ISSUE THREAD

**Issue by hueuebi** [golangci/golangci-lint#4336]
remove nilness from go vet linter configuration settings on the website (nilness got removed from go vet for memory reasons)

Configuration setting should be removed here:
https://golangci-lint.run/usage/linters/#govet

context:
https://github.com/golang/go/issues/59714

I stumbled upon it by trying to enable nilness as part of go vet inside golangci-lint.

**Comment by ldez** [comment]
hello,

nilness got **not removed from go vet for memory reasons.

nilness is just not enabled by default.

**Comment by hueuebi** [comment]
@ldez My bad. Somehow, I was not able to enable it in golangci-lint.
