### ISSUE TITLE
Generate html report 

### ISSUE THREAD

**Issue by dharmjit** [golangci/golangci-lint#436]
Hi, Is there a way to generate html report after running golangci-lint. I am trying to make it work with gitlab and show the output on gitlab pages. 

Thanks in advance.

**Comment by jirfag** [comment]
Hi!
Sorry, It's not planned. Can you use [goreportcard](https://goreportcard.com)?

**Comment by dharmjit** [comment]
Hi, Its an internal project and hosted on gitlab. goreportcard can't be used as of now. I was thinking of some html formats supported by golangci-lint. Any other options available.
Thanks

**Comment by Jackmrzhou** [comment]
Same here! Our group would be willing use this project if generating html is supported, but we have to use another linter which supports generating html currently.

**Comment by jirfag** [comment]
pull requests are welcome :)

**Comment by schaudhary111** [comment]
Hi, any update on this enhancement. We need to publish lint results as html report and it will be great if this project provides formatting option for html. 
Thanks

**Comment by SVilgelm** [comment]
As a workaround, you can use `junit-xml` output: `golangci-lint run --out-format junit-xml ./...`
and then convert it to html

or feel free to create a pull request with necessary changes
