### ISSUE TITLE
Add official go deadcode linter

### ISSUE THREAD

**Issue by sonatard** [golangci/golangci-lint#4383]
### Your feature request related to a problem? Please describe.

I want to use nolint for official go deadcode llinter.

### Describe the solution you'd like.

Is it possible to add a deadcode linter?

https://pkg.go.dev/golang.org/x/tools/cmd/deadcode

### Describe alternatives you've considered.

nothing

**Comment by ldez** [comment]
duplicate of #4254, #4270
