### ISSUE TITLE
Checking usages of deprecated symbols

### ISSUE THREAD

**Issue by vearutop** [golangci/golangci-lint#439]
Hello, is it possible to find usages of deprecated symbols in code with `golangci-lint`?

**Comment by jirfag** [comment]
Hi!
Yep, e.g. go-critic can [find deprecated functions](https://github.com/go-critic/go-critic/blob/master/checkers/testdata/deprecatedComment/positive_tests.go). Also, I think staticcheck can do it too.

**Comment by nvx** [comment]
It looks like go-critic's `deprecatedComment` check doesn't find usage of deprecated symbols, rather `Detects malformed 'deprecated' doc-comments`.

Hopefully this saves some time for the next person who stumbles across this and wonders why it's not working. I couldn't see anything in `staticcheck` (nor any other linter in golangci-lint for that matter) that checks for this either.

**Comment by black-06** [comment]
> It looks like go-critic's `deprecatedComment` check doesn't find usage of deprecated symbols, rather `Detects malformed 'deprecated' doc-comments`.
> 
> Hopefully this saves some time for the next person who stumbles across this and wonders why it's not working. I couldn't see anything in `staticcheck` (nor any other linter in golangci-lint for that matter) that checks for this either.
> 
> Edit: Actually it looks like staticcheck does have an appropriate check (SA1019) but for whatever reason it doesn't seem to work. Might open a separate issue to discuss that.

I made a linter, I hope you like it 
https://github.com/black-06/check-deprecated
