### ISSUE TITLE
// indirect dependency causes golanci-lint to error

### ISSUE THREAD

**Issue by bbatha** [golangci/golangci-lint#440]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
golangci-lint has version 1.15.0 built from 901cf25 on 2019-02-18T08:22:26Z
2. Config file: `cat .golangci.yml`
```
[run]
"modules-download-mode" = "readonly" # don't implicitly download modules

[linters]
disable-all = true
enable = [
    "govet",
    "typecheck",
]
```

3. Go environment: `go version && go env`

```
go version && go env
go version go1.11.4 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bbatha/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bbatha/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bbatha/projects/reproducer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jg/k4grw5yj71qgpftq4wr0wsz40000gp/T/go-build326271166=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
4. Verbose output of running: `golangci-lint run -v`

```
INFO [config_reader] Used config file .golangci-lint.toml
INFO [lintersdb] Active 2 linters: [govet typecheck]
INFO [loader] Go packages loading at mode load types and syntax took 187.022946ms
ERRO Running error: context loading failed: no go files to analyze
INFO Memory: 4 samples, avg is 69.2MB, max is 69.2MB
INFO Execution took 339.363952ms
```

Here are the files required for reproducing:

#### main.go
```go
package main

import (
	"github.com/montanaflynn/stats"
)

func main() {
	median, _ := stats.Median([]float64{1.0, 2.0, 3.0})
	println("Median: ", median)
}
```

#### go.mod
```go
module reproducer

require github.com/montanaflynn/stats v0.5.0 // indirect
```

#### go.sum

```go
github.com/montanaflynn/stats v0.5.0 h1:2EkzeTSqBB4V4bJwWrt5gIIrZmpJBcoIRGS2kWLgzmk=
github.com/montanaflynn/stats v0.5.0/go.mod h1:wL8QJuTMNUDYhXwkmfOly8iTdp5TEcJFWZD2D7SIkUc=
```

**Comment by jirfag** [comment]
Hi! The problem is in the bad error message, am I right? Looks like related to https://github.com/golangci/golangci-lint/issues/401

**Comment by bbatha** [comment]
I do not believe the issue is a bad error message. If I remove the `// indirect` part of the line all of my lints pass. Since `// indirect` is a comment (that is auto generate by `go mod`) I would expect it to have no effect on the result of the lint.

**Comment by jirfag** [comment]
sorry, can't understand. Please, attach how do you run `golangci-lint` and more information

**Comment by hanzei** [comment]
I strongly suppose this will be fixed if the build-runner get updated to use at least go 1.13.1.

**Comment by joshprzybyszewski-wf** [comment]
@bbatha I've run into the issue where specifying `"modules-download-mode" = "readonly"` in your yml breaks in CI, where it works locally. While indirectly related to this `// indirect` issue, have you given that a shot?
