### ISSUE TITLE
unknown failing in ci

### ISSUE THREAD

**Issue by Bysmyyr** [golangci/golangci-lint#4426]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Sorry, this is a bit hard to reproduce thing but just a note about our problem we had.

So, this morning golangci-lint github action started failing without reason. The code it pointed was months old. Error was this:
```
[golangci-lint: xxx/xxx/xx_test.go#L1370]
SA5011: possible nil pointer dereference (staticcheck)
[golangci-lint: xxx/xxx/xx_test.go#L1366]
SA5011(related information): this check suggests that the pointer can be nil (staticcheck)
```

Cache clearing fixed the issue. I understand that this is not enough to fix issue but I like to anyway write this as a note. Always possible that github is doing something wonky too. Feel free to close it. Thanks for the great tool.

### Version of golangci-lint

<details>
v1.55.2 
golangci/golangci-lint-action@v3

</details>

### Configuration

<details>
staticcheck without any confiquration 

Action config
  golangci-lint:
    runs-on: gcp-default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  golang-unittest:

</details>

### Go environment

<details>
1.21.5

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [ ] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

as it's not reproducible, I will close the issue, but the issue will still be here if the problem happens again.

**Comment by jlewi** [comment]
I ran into the same problem today. 
Cleaning the cache fixed the problem. @Bysmyyr thank you for reporting the fix.
