### ISSUE TITLE
Error Shadowing in StartTransfer Function and Handling Multiple Errors

### ISSUE THREAD

**Issue by cubxxw** [golangci/golangci-lint#4433]
#### Description:
In the `StartTransfer` function within `internal/msgtransfer/init.go`, there is an issue of error shadowing where the `err` variable declared at the beginning of the function is re-declared multiple times, which can lead to confusion and potential bugs in error handling. This was specifically flagged by the linter in the GitHub Actions workflow as a shadowing issue at line 73.

#### Error Shadowing Issue:

The function `StartTransfer` re-declares `err` when handling errors from different operations (e.g., initializing Redis, Mongo, creating RPC root nodes). This pattern can potentially lead to oversight in error handling, making the code less maintainable and more prone to bugs.

#### Suggested Fix:

To avoid error shadowing and improve error handling, consider using unique variable names for errors from different operations or handling the error immediately without reassigning it to the `err` variable used in a scope outside the current block. This approach ensures that each error is handled in its own context and does not overshadow any previous error variables.

For example, instead of re-declaring `err`:

```go
client, err := kdisc.NewDiscoveryRegister(config.Config.Envs.Discovery)
if err != nil {
    return err
}
// This redeclaration shadows the previous one
if err := client.CreateRpcRootNodes(config.Config.GetServiceNames()); err != nil {
    return err
}
```

Consider handling the error immediately or using a different variable name:

```go
client, err := kdisc.NewDiscoveryRegister(config.Config.Envs.Discovery)
if err != nil {
    return err
}
// Handle the error immediately or use a different variable
if err2 := client.CreateRpcRootNodes(config.Config.GetServiceNames()); err2 != nil {
    return err2
}
```

### Describe alternatives you've considered.

For scenarios where multiple functions return errors that need to be managed, as shown in the additional code snippet provided, a structured approach to handling errors can improve readability and error management. Using `defer` for resource cleanup and logging errors before terminating the program or returning an error is a good practice. It ensures that resources are released properly and errors are logged for debugging. Always ensure that `defer` statements are placed correctly to avoid resource leaks, especially after successful resource acquisition.

#### Conclusion:

Improving error handling by addressing error shadowing and adopting a consistent strategy for managing multiple errors can significantly enhance code quality and maintainability.

**Comment by bombsimon** [comment]
Did you intend to file this issue in https://github.com/openimsdk/open-im-server and got the wrong repo?
