### ISSUE TITLE
Support autofixing of `perfsprint`

### ISSUE THREAD

**Issue by G-Rath** [golangci/golangci-lint#4453]
### Your feature request related to a problem? Please describe.

It seems that `perfsprint` supports some autofixing, but using `--fix` does not trigger it.

### Describe the solution you'd like.

The ability to have volitions reported by `perfsprint` automatically fixed

### Describe alternatives you've considered.

Manually running `perfsprint --fix`

**Comment by ldez** [comment]
Hello,

perfprint as a binary supports fix but not inside golangci-lint.

Related to #1779

**Comment by G-Rath** [comment]
Is there something that `perfsprint` could do differently to enable that? I based my PR off `dupword` which supports `-fix`, [is marked as autofixable](https://github.com/golangci/golangci-lint/blob/master/pkg/lint/lintersdb/builder_linter.go#L105), and also looks like to be using [`SuggestedFixes`](https://github.com/Abirdcfly/dupword/blob/main/dupword.go#L136).
