### ISSUE TITLE
Update the JSON schema

### ISSUE THREAD

**Issue by firelizzard18** [golangci/golangci-lint#4486]
### Your feature request related to a problem? Please describe.

#4437 adds a new kind of plugin. The [published JSON schema](https://json.schemastore.org/golangci-lint.json) needs to be updated. Specifically the current schema does not allow `linters-settings.custom.{name}.path` to be unset. It also doesn't have any of the new properties, but I don't care about that as much as the angry red squiggles from the supposedly missing property.

### Describe the solution you'd like.

The schema to be updated.

### Describe alternatives you've considered.

N/A

**Comment by bombsimon** [comment]
The schema comes from #1453 and is not written by us. I don't really know the process of updating it, I assume PRs to https://github.com/SchemaStore/schemastore?

We might also want to consider a schema file for [`.custom-gcl.reference.yml`](https://github.com/ldez/golangci-lint/blob/d18acc5b51ed0db3fc94a71f89758bebd9da5d18/.custom-gcl.reference.yml) which is a separate file.

**Comment by ldez** [comment]
I updated the JSON schema after each release https://github.com/SchemaStore/schemastore/pulls?q=is%3Apr+author%3Aldez+is%3Aclosed

As I said some other issues related to this topic, I'm working on several things about JSON schema.

One of them is to move the schema from the schemastore to our repo like goreleaser:
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L2108-L2123

If the schema is inside our repo we will be able to do the same thing as `.golangci.next.reference.yml`/`.golangci.reference.yml`.

I think we will not ask contributors to update this schema because the syntax is not simple.

I need more time to think about a better solution.

**Comment by ldez** [comment]
About the `.custom-gcl.yml` JSON schema, I already created one, but I want to "resolve" the move and the management of the golangci-lint schema first.

**Comment by ldez** [comment]
@bombsimon what do you think about my idea to move the JSON schema inside our repo?

**Comment by bombsimon** [comment]
> @bombsimon what do you think about my idea to move the JSON schema inside our repo?

Yes, I absolutely think we should do that and I thought that was part of the goal with #1453 as well since it was offered. Even better if it's a solution to reference the schema in our repository to not have to update upstream!

**Comment by firelizzard18** [comment]
I had assumed it was in this repo, it makes sense that you'd only update it for releases. I was eager to update golangci-lint and remove my plugin workaround hacks.

I assume there is a Go type that corresponds to the schema? It might be feasible to automatically generate that via introspection (e.g. reflection or reading the source and go/types). Besides [all of these JSON schema packages](https://pkg.go.dev/search?q=json+schema) I wrote a [JSON-schema code generator](https://github.com/traefik-contrib/yaegi-debug-adapter/tree/main/internal/jsonx) for Yaegi though I'm honestly not sure how usable that is. It was very purpose-specific.

**Comment by ldez** [comment]
> I assume there is a Go type that corresponds to the schema? It might be feasible to automatically generate that via introspection (e.g. reflection or reading the source and go/types).

I answered to this question here: https://github.com/golangci/golangci-lint/issues/1453#issuecomment-1989261467

**Comment by ldez** [comment]
So I will move the schema :tada:
