### ISSUE TITLE
Alpine images

### ISSUE THREAD

**Issue by amenzhinsky** [golangci/golangci-lint#453]
Hi there.

I would be nice if we had golang-alpine based images, since it has some advantages over debian based ones in terms of CI/CD, like total image size and apk is way faster than apt when it's needed to install something within a pipeline. Besides many people use alpine to build their code.

**Comment by jirfag** [comment]
Hi! It's a good idea, pull requests are welcome.

**Comment by tpounds** [comment]
Relates to https://github.com/golangci/golangci-lint/issues/528.
