### ISSUE TITLE
Update demo video and demo.svg on website

### ISSUE THREAD

**Issue by alexandear** [golangci/golangci-lint#4582]
### Your feature request related to a problem? Please describe

The [golangci-lint demo video](https://golangci-lint.run/#demo) was filmed [5 years ago](https://asciinema.org/a/183662) using golangci-lint v1.16.0 and is now mostly outdated for golangci-lint v1.57.0.

Firstly, the official repository for **beego** is [beego/beego](https://github.com/beego/beego), not [astaxie/beego](https://github.com/astaxie/beego).
<img width="447" alt="image" src="https://github.com/golangci/golangci-lint/assets/3228886/c57c6538-e5de-42a1-b1b8-d84d392570c4">

Secondly, the video displays issues from linters that have since been renamed or deprecated: `gas` is now `gosec`, `megacheck` is `gosimple` + `staticcheck` + `unused`.
<img width="876" alt="image" src="https://github.com/golangci/golangci-lint/assets/3228886/dc4d6b11-479c-4333-bc18-4ffa38f0378f">

Lastly, the `golangci-lint linters` command outputs many more linters in v1.57.0 compared to v1.67.0.
<img width="1010" alt="image" src="https://github.com/golangci/golangci-lint/assets/3228886/09566a1d-5a46-49cc-8620-f9c2e86b3060">

### Describe the solution you'd like

Re-film the demo video on https://asciinema.org/ and re-generate `demo.svg` using the latest golangci-lint version.

### Describe alternatives you've considered

N/A

**Comment by ldez** [comment]
The asciinema video (the second video on the page) should be removed, it's not useful now.

The first one (the SVG animation) should be updated.

---

Offtopic:

@alexandear If you have a bit of time, I'm working around linters, and I see 2 topics that can help me:

Add missing auto-fix tests:
- protogetter
- tagalign
- mirror

Add missing tests:
- grouper
