### ISSUE TITLE
json-schema: missing some properties

### ISSUE THREAD

**Issue by nikpivkin** [golangci/golangci-lint#4593]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

VSCode issues the following warnings:
- Property check-shadowing is not allowed.
- Property skip-files is not allowed.
- Property skip-dirs is not allowed.

Scheme source: https://golangci-lint.run/jsonschema/golangci.jsonschema.json

<img width="680" alt="image" src="https://github.com/golangci/golangci-lint/assets/100182843/debb1f22-218e-4c67-9c71-8298f427fa10">

### Version of golangci-lint

-

### Configuration

https://github.com/aquasecurity/trivy/blob/main/.golangci.yaml

### Go environment

-

### Verbose output of running

-

### A minimal reproducible example or link to a public repository

-

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

it's the expected behavior, those properties have been deprecated.

https://golangci-lint.run/product/changelog/#v1570

**Comment by nikpivkin** [comment]
@ldez Thank you! Why doesn't `golangci` warn about deprecated fields?

**Comment by akutz** [comment]
> Hello,
> 
> it's the expected behavior, those properties have been deprecated, then they are considered as removed.
> 
> https://golangci-lint.run/product/changelog/#v1570

I do not see `skip-files` as deprecated in the linked changelog page.

**Comment by ldez** [comment]
> ⚠️ Replace `run.skip-xxx` options by `issues.exclude-xxx` options
