### ISSUE TITLE
gci: Add trailing slash to local module

### ISSUE THREAD

**Issue by StephenBrown2** [golangci/golangci-lint#4608]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

In my company's package, there are a few repositories that are named similarly, because they are related, and one is imported in the other (for example, a separate proto repository).

e.g.:
Main program: github.com/Company/main-program
Dependency: github.com/Company/main-program-dependency

This unfortunately confuses `gci` when trying to use the `localmodule` section, as imports from both repos get grouped as one.

e.g:
```go
import (
  "fmt"
  "errors"

  "github.com/Company/main-program/package"
  "github.com/Company/main-program-dependency/other"
)
```

When they should be separate, e.g:
```go
import (
  "fmt"
  "errors"

  "github.com/Company/main-program-dependency/other"

  "github.com/Company/main-program/package"
)
```

Adding the local module as it's own custom section with the trailing slash gets around this (i.e. `prefix("github.com/Company/main-program/")`), but I would prefer to rely in the linter's detection so I can use the same config across multiple repos in our org.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.57.3-0.20240402181201-2dd62d125014 built with go1.21.8 from (unknown, modified: ?, mod sum: "h1:jmz5tBAul6h97PilGm8Sd+n9wWfIWduO67xL9AAOF0k=") on (unknown)
```

</details>

### Configuration

<details>

```yaml
---
linters:
  enable:
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - "prefix(github.com/Company/)"
      - localmodule # Package name being "github.com/Company/main-program"
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.21.8 linux/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/user/.cache/go-build'
GOENV='/home/user/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/user/go/pkg/mod'
GONOPROXY='github.com/Company'
GONOSUMDB='github.com/Company'
GOOS='linux'
GOPATH='/home/user/go'
GOPRIVATE='github.com/Company'
GOPROXY='direct'
GOROOT='/usr/lib/golang'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.8'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2947470614=/tmp/go-build -gno-record-gcc-switches'

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

An example, non-functioning, code sample.

```go
package main

import (
	"fmt"

	"github.com/Company/main-program-dependency/other"
	"github.com/Company/main-program/pkg"
)

func main() {
	fmt.Println("Hello, World!")
	pkg.Package(other.Name)
}

```
Expected:
```go
package main

import (
	"fmt"

	"github.com/Company/main-program-dependency/other"

	"github.com/Company/main-program/pkg"
)

func main() {
	fmt.Println("Hello, World!")
	pkg.Package(other.Name)
}

```
</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

I recommend opening an issue to the linter repo: https://github.com/daixiang0/gci

golangci-lint is a wrapper around linter.

**Comment by StephenBrown2** [comment]
Agreed that golangci-lint is a wrapper around linters. However, your hack https://github.com/golangci/golangci-lint/pull/4522#issuecomment-2023274019 is what I'm proposing to be modified.

**Comment by ldez** [comment]
In some way, my hack is just what the linter does, the problem is not my hack but how localModule is handled inside the linter.

**Comment by StephenBrown2** [comment]
> In some way, my hack is just what the linter does

Then the hack should be removed, no?

**Comment by ldez** [comment]
> Then the hack should be removed, no?

No, because the linter doesn't work inside golangci-lint without this hack.

The problem is here: https://github.com/daixiang0/gci/blob/4f7ff3c79e25e9076af03eab88e658d7448ae7de/pkg/section/local_module.go#L21

**Comment by ldez** [comment]
The fix:
```go
if spec.Path == m.Path || strings.HasPrefix(spec.Path, m.Path+"/") {
```
instead of:
```go
if strings.HasPrefix(spec.Path, m.Path) {
```

**Comment by StephenBrown2** [comment]
Thanks for that, I was about to make a different PR: https://github.com/daixiang0/gci/pull/203

**Comment by ldez** [comment]
I think your PR will create a side effect with a module without packages.

My PR fixes the problem at the root without any side effects.

**Comment by StephenBrown2** [comment]
Thanks. Your understanding is better than mine. I hope it can be merged to `gci` soon.

**Comment by ldez** [comment]
I added tests into the PR to illustrate the problem with your PR: https://github.com/daixiang0/gci/pull/202/commits/005b33c1988a4ac85aa7502e7caef71a2eb43563

You can close your PR because it will create a regression.
