### ISSUE TITLE
A support for duration check linter

### ISSUE THREAD

**Issue by purpleidea** [golangci/golangci-lint#461]
This seems like an easy and very helpful linter to add:

https://github.com/charithe/durationcheck

Related issue: 
https://github.com/purpleidea/mgmt/issues/494

Thanks!

**Comment by purpleidea** [comment]
hi bot

**Comment by SVilgelm** [comment]
I really tried to add it, but it requires some changes in the durationcheck.

**Comment by SVilgelm** [comment]
I created a ticket in main repo: https://github.com/charithe/durationcheck/issues/6
