### ISSUE TITLE
Add "govulncheck" to golangci-lint

### ISSUE THREAD

**Issue by daabr** [golangci/golangci-lint#4623]
### Your feature request related to a problem? Please describe

Govulncheck was released by the Go security team last year: https://go.dev/blog/govulncheck

### Describe the solution you'd like

Add Govulncheck as an option (maybe enabled by default?) to golangci-lint.

### Describe alternatives you've considered

Govulncheck can run as a standalone tool, and it also has a GitHub action for CI: https://github.com/golang/govulncheck-action

This works fine, but it would be great to keep using only golangci-lint as an meta-tool umbrella for all linters.

**Comment by ccoVeille** [comment]
I found back the old discussion and its status https://github.com/golangci/golangci-lint/issues/3094#issuecomment-1636093709

But I'm curious to see if govulncheck could be considered again
