### ISSUE TITLE
Offline config validation

### ISSUE THREAD

**Issue by tmzane** [golangci/golangci-lint#4646]
### Your feature request related to a problem? Please describe

While working offline, I noticed that `golangci-lint config verify` attempts to download the json schema from the internet. I'm not really familiar with the workflow around it, so maybe I don't see something. But can't it be embedded into the `golangci-lint` binary instead, since the schema is located in the same repository? AFAIK, no other commands require internet connection, so it would be nice to be able to use all `golangci-lint` features offline.

### Describe the solution you'd like

Being able to validate a `.golangci.yml` config offline. Could be implemented by embedding the json schema via `//go:embed`.

### Describe alternatives you've considered

Don't bother about it 😅

**Comment by ldez** [comment]
Hello,

I already answered this inside the PR about this new command: https://github.com/golangci/golangci-lint/pull/4527
