### ISSUE TITLE
--out-format no longer overrides output->format in config file

### ISSUE THREAD

**Issue by andrewradamis-paay** [golangci/golangci-lint#4677]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Previous to golangci-lint `v1.57.2` (presumably `v1.57.0`, but I haven't tested), providing `--out-format json` as part of the run command overrode the config file. This behavior has changed.

Given the output section of the config file is:
```yaml
output:
  format: colored-line-number
  print-linter-name: true
  sort-results: true
```

Running `golangci-lint run -c ./golangci.yml --out-format json` in v1.57.2 returns results in `colored-line-number` format. In `v1.56.2` this returned results in `json`.

I know in 1.52.0, `format:` was depreciated in favor of `formats`, but we haven't updated our config files yet.

If we exclude `format: colored-line-number` from the config file _OR_ replace it with:
```yaml
output:
  formats:
    - format: colored-line-number
       path: stdout
  print-linter-name: true
  sort-results: true
```
`golangci-lint run -c ./golangci.yml --out-format json` works as expected.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.57.2 built with go1.22.1 from 77a8601 on 2024-03-28T18:39:06Z
```
```console
$ golangci-lint --version
golangci-lint has version 1.57.2 built with go1.22.1 from 77a8601a on 2024-03-28T19:01:11Z
```
(Linux Arm64 and MacOS Arm64)
</details>

### Configuration

<details>

```yaml
output:
  format: colored-line-number
```

```console
golangci-lint run -c ./golangci.yml --out-format json
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# This does not change behavior
```

</details>

### A minimal reproducible example or link to a public repository

<details>
N/A

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

There are no differences between the default format and an explicit configuration of this format (`colored-line-number`).
Then we cannot have a smart detection of when to override or not.

It's a side-effect that we cannot fix: to keep the compatibility with the old field we have to override the values with the old field value (if defined).

As you notice in your issue description, the solution is to migrate to the new configuration `formats:`.
