### ISSUE TITLE
golangci-lint.sh obliterates entire Mac OS X session specific $TMPDIR

### ISSUE THREAD

**Issue by ahilananantha** [golangci/golangci-lint#470]
This is an issue with the installer script here:

https://install.goreleaser.com/github.com/golangci/golangci-lint.sh

There is a shell function in there:

mktmpdir() {
  test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
  mkdir -p "${TMPDIR}"
  echo "${TMPDIR}"
}

that assumes that $TMPDIR isn't an exported variable and so appears to unintentionally reuse an exported one. This is super bad because later the script attempts to remove the directory. On Mac OS X, $TMPDIR is the location of per user session "/tmp" equivalent. It's where mktemp actually creates things. I think we must instead do all of.

1) Pick a different variable name like MYTMPDIR to be really clear this is a script specific variable.

2) Unset or clear the value of the variable at the top of the script so we know we are only just reusing the value of TMPDIR="$(mktemp -d)" from the first time mktmpdir() is called.

**Comment by jirfag** [comment]
Hi, thank you! please make an issue to https://github.com/goreleaser/goreleaser

**Comment by tpounds** [comment]
@ahilananantha This was fixed in https://github.com/goreleaser/godownloader/pull/105 and should no longer be an issue.
