### ISSUE TITLE
Integrate Bodyclose checker

### ISSUE THREAD

**Issue by alexdor** [golangci/golangci-lint#471]
It would be nice to integrate [this](https://github.com/timakin/bodyclose) linter as well. I could try to create a pr if you are interested :)

**Comment by jirfag** [comment]
Hi, thank you for the idea!
I'm interested and it would be great if you can make a pull request. [Wiki](https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter) can help you

**Comment by phamdt** [comment]
#533 :)

**Comment by jirfag** [comment]
released in [v1.17.0](https://github.com/golangci/golangci-lint/releases/tag/v1.17.0)
