### ISSUE TITLE
golangci-lint.sh: crit uname_os_check 'MINGW64_NT-10.0' got converted to 'mingw64_nt-10.0' which is not a GOOS value

### ISSUE THREAD

**Issue by mholt** [golangci/golangci-lint#472]
Running the install script on Azure Pipelines (Windows) returns this error:

```
golangci/golangci-lint crit uname_os_check 'MINGW64_NT-10.0' got converted to 'mingw64_nt-10.0' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
```

I know it says to file a bug over in shlib, but [similar issues are unresolved](https://github.com/client9/shlib/issues/13), and this code lives in this repo anyway, not shlib.

Would be nice to have this work, as writing more platform-specific code to install a go program doesn't sound awesome. I'll probably just fall back to using `go get` for now.

Update: Fortunately the `go get` works! Any idea why it is not recommended? Seems much simpler...

**Comment by jirfag** [comment]
Hi!
Sorry, I have no Windows for testing. It would be ok if you locally fix it in the golangci-lint repo. Pull requests are welcome

**Comment by mholt** [comment]
I don't have Windows either 😅

**Comment by AlekSi** [comment]
> Any idea why it is not recommended?

Because (without modules) `go get -u` installs the version from `master` branch, not the latest tagged release.
