### ISSUE TITLE
Run custom linter without changing the source code of golangci-lint

### ISSUE THREAD

**Issue by HaraldNordgren** [golangci/golangci-lint#473]
For our project, we are using `gometalinter` with a config to allow running our own linter called "go-corp-linter" like this:

**.gometalinter.json:**
```json
{
  "Deadline": "2m",
  "Vendor": true,
  "Test": true,

  "Enable": [
    "deadcode",
    "errcheck",
    "goconst",
    "golint",
    "gotype",
    "gotypex",
    "ineffassign",
    "interfacer",
    "nakedret",
    "staticcheck",
    "structcheck",
    "unconvert",

    "go-corp-linter"
  ],

  "linters": {
    "go-corp-linter": "go-corp-linter:PATH:LINE:COL:MESSAGE"
  },

  "exclude": [
    ".+_mock(_test)?\\.go:"
  ]
}
```

We run the linter through `gometalinter --config=scripts/.gometalinter.json ./...`

I would like the same option with `golangci-lint` without having to clone the repo and change the source code.

**Comment by jirfag** [comment]
Hi!
The idea to run any linter contradicts golangci-lint's architecture: we reuse parsed/analyzed code. We don't analyze code repeatedly as gometalinter does.

But I'm planning to add support for any go/analysis` based linter without changing source code

**Comment by benjaminjkraft** [comment]
> But I'm planning to add support for any go/analysis` based linter without changing source code

@jirfag Do you have any guess at a timeframe for this?  Is it something where you'd welcome a PR?  We're keen to start writing our own `go/analysis`-based linters specific to our codebase.

**Comment by jirfag** [comment]
No timeframe, pull requests are welcome

**Comment by dbraley** [comment]
https://github.com/golangci/golangci-lint/pull/841

**Comment by jirfag** [comment]
thank you,
now you can use plugins for that, see [docs](https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint).
