### ISSUE TITLE
docs: broken link on contribution page

### ISSUE THREAD

**Issue by ccoVeille** [golangci/golangci-lint#4765]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

contribution refers to https://github.com/golangci/golangci-lint/blob/master/CODE_OF_CONDUCT.md but it's a 404

### Version of golangci-lint

NA

### Configuration

NA

### Go environment

NA

### Verbose output of running

NA

### A minimal reproducible example or link to a public repository

open https://golangci-lint.run/contributing/workflow/ click on code of conduct

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
The link should be replaced by https://github.com/golangci/golangci-lint?tab=coc-ov-file

**Comment by ccoVeille** [comment]
I will open a PR then if you are OK @ldez
