### ISSUE TITLE
Show project test coverage for a PR

### ISSUE THREAD

**Issue by alexandear** [golangci/golangci-lint#4769]
### Your feature request related to a problem? Please describe

In order to ensure the quality of our code, it would be beneficial to display the test coverage for each pull request. This will allow us to easily identify any areas of the code that are not adequately covered by tests and need attention.

### Describe the solution you'd like

Add a `make` target that run all tests with coverage. Generate coverage Markdown report and add a comment with this report to every PR. See https://josh-ops.com/posts/github-code-coverage/

### Describe alternatives you've considered

Use https://coveralls.io/, it's free for Open Source projects.

**Comment by ldez** [comment]
This is mainly useless and noise on PR:
- the coverage is not something representative because our tests are not mainly not unit tests
- the coverage is an indicator that is globally misused and misunderstood.
- it drives to write tests only for coverage instead of useful tests
