### ISSUE TITLE
intrange lacks a preset

### ISSUE THREAD

**Issue by Inuart** [golangci/golangci-lint#4795]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

`intrange` is the only linter that's not a part of a preset.

I'm using presets to be able to enable all linters and automatically deal with new and deprecated linters, but after adding all the available presets, the `intrage` linter is still disabled.

### Describe the solution you'd like

intrange is added to one or more presets

### Describe alternatives you've considered

enabling it specifically, but since it's the only one, that's weird.

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

A preset can be added here: https://github.com/golangci/golangci-lint/blob/4e53f51c4ec2752844ba45bd75efcb57f9f4ba4d/pkg/lint/lintersdb/builder_linter.go#L508-L511

The `file assets/linters-info.json` will be modified, this file will be updated automatically when we create a new release.

The preset can be "style" as you suggested.

Note: your hack is a bit obsolete with the new deprecation cycle of the linters.
https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle

**Comment by Inuart** [comment]
> Note: your hack is a bit obsolete with the new deprecation cycle of the linters.
> https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle

But I still have to manually disable it / see a warning right?

> A preset can be added here:
> 
> [golangci-lint/pkg/lint/lintersdb/builder_linter.go](https://github.com/golangci/golangci-lint/blob/4e53f51c4ec2752844ba45bd75efcb57f9f4ba4d/pkg/lint/lintersdb/builder_linter.go#L508-L511)

I can create another PR modifying this then. Thanks!
