### ISSUE TITLE
Add goimports-reviser as a linter option

### ISSUE THREAD

**Issue by thelooter** [golangci/golangci-lint#4824]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

We currently use [goimports-reviser](https://github.com/incu6us/goimports-reviser) as our import Linter in our Projects. Due to its slight difference to goimports, golangci-lint always complains about the file not being goimport-ed.

### Describe the solution you'd like

Add goimports-reviser to the list of supported linters

### Describe alternatives you've considered

Switch to goimports: Not really a desired way to go, as in my opinion the imports of goimports-reviser are more readable and organized

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

we already have linters that do the same things:
- [gci](https://golangci-lint.run/usage/linters/#gci) to manage imports.
- [importas](https://golangci-lint.run/usage/linters/#gci) to handle import aliases.

I recommend using `gci` instead of `goimports` inside your configuration.
