### ISSUE TITLE
detects whether declarations of exported variables, constants, functions, etc. have comments. 

### ISSUE THREAD

**Issue by cold-bin** [golangci/golangci-lint#4828]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

When a new person takes over a large project, it will be painful if there are no comments. This is how I feel that necessary comments need to be provided for public types, variables, functions or methods to facilitate the new person to quickly familiarize themselves with the project.

### Describe the solution you'd like

use go/analyze package to recursive traversal ast comment or documention node. if empty the comment and documention node, then  call `reportf`. the link of https://github.com/cold-bin/declaration-comment is my implement

### Describe alternatives you've considered

nothing, this way can solve no comments of many complex type

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

this already exists inside golangci-lint: revive, stylecheck, etc.

**Comment by ccoVeille** [comment]
The  only existing linter I know that looks like what is requested would be revive:comment-density

https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#comments-density

**Comment by cold-bin** [comment]
thank for your reply

**Comment by ldez** [comment]
> The only existing linter I know that looks like what is requested would be revive:comment-density

This issue is about comments, so there several rules inside revive and stylecheck.

But remember that by default, golangci-lint skips those reports.

https://golangci-lint.run/usage/false-positives/#default-exclusions

To disable those exclusions:

```yml
issues:
  exclude-use-default: false
```

**Comment by ccoVeille** [comment]
Thanks for providing this information. I totally missed that parameter even I'm using golangci-lint for a while.

I'll have a look, thanks
