### ISSUE TITLE
docs: add a way to link linter without settings on the linter page

### ISSUE THREAD

**Issue by ccoVeille** [golangci/golangci-lint#4841]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

Sometimes I want to share documentation about a specific linter to someone, but for some of them I cannot

Right now, there are anchors on linters with settings, but none on the others.

Be able to link https://golangci-lint.run/usage/linters/#bodyclose

the same we link https://golangci-lint.run/usage/linters/#gosimple

right now this link point to the settings (it might change after my PR and discussion), maybe it's something that need to be changed, but it's out of the scope of what I'm reporting.

I'm sure that we will iterate if my suggestion is accepted.

### Describe the solution you'd like

So it's about adding a `<span id="bodyclose">bodyclose</span` instead of using bodyclose text

### Describe alternatives you've considered

Ask people to use CTRL+F :rofl: 

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by Antonboom** [comment]
+1

faced with this issue a lot of times

**Comment by ccoVeille** [comment]
Thanks 🎉
