### ISSUE TITLE
Double parsing having unwanted side effects.

### ISSUE THREAD

**Issue by dixonwille** [golangci/golangci-lint#49]
I noticed your comment here https://github.com/golangci/golangci-lint/blob/master/pkg/commands/run.go#L404 about double parsing that way you can get Viper setup with the config values. But this causes some of the flags to act as if they were passed in twice by the user. StringSlice for example will duplicate the result. Not sure if there are any other flags that are doing this.

I think a possible solution may be to call `e.parseConfig` inside the `executeRun` command. But maybe there is something I am not seeing?

**Comment by jirfag** [comment]
Thank you! My fix is in https://github.com/golangci/golangci-lint/pull/58, check it, please. Maybe you see ways to fix it better?

**Comment by dixonwille** [comment]
I don't have time to check it where I was seeing the issue, right now. I may be able to get to it later today.

**Comment by jirfag** [comment]
ok, thank you
