### ISSUE TITLE
Add gofumpt

### ISSUE THREAD

**Issue by andrewrynhard** [golangci/golangci-lint#490]
Include https://github.com/mvdan/gofumpt in set of linters.

**Comment by jirfag** [comment]
Hi, nice tool, thank you!
Pull requests [are welcome](https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter)

**Comment by dackroyd** [comment]
Given `gofumpt`/`gofumports` does everything that `gofmt` / `goimports` would do, what is the preference for applying this?

> Enforce a stricter format than `gofmt`, while being backwards compatible. That is, `gofumpt` is happy with a subset of the formats that `gofmt` is happy with.
> The tool is a modified fork of `gofmt`, so it can be used as a drop-in replacement. Running `gofmt` after `gofumpt` should be a no-op.

Would `gofumpt` (and `gofumports`) be added as an entirely new linter, or options for `gofmt`/`goimports` ?

**Comment by gonzaloserrano** [comment]
Hey there, I'm also interested in adding gofumpt/goimports.

> Would gofumpt (and gofumports) be added as an entirely new linter, or options for gofmt/goimports ?

About new linter vs gofmt option is see pros and cons:

- new linter pros: more clean to add/remove the linter if it gets deprecated
- cons: does not make sense to run gofmt/goimports if gofumpt/gofumports are enabled since they are a superset of gofmt/goimports, so how to handle this?

**Comment by ernado** [comment]
Hey, sorry for long responses, we are currently trying to deal with bugs and preparing to go1.14, so very low of capacity.

I'm also not sure how to deal with linters that superset other linters, e.g. we can't just auto-ignore them.

**Comment by gonzaloserrano** [comment]
Maybe we can just start adding it as a new linter and disable gofmt/goimports manually.

**Comment by teivah** [comment]
I created a PR for it: https://github.com/golangci/golangci-lint/pull/1177

**Comment by dnwe** [comment]
@teivah thanks for working on the PR, pleased to see that it was merged

A quick scan of the PR suggests it doesn't currently map the golangci-lint "Autofix" functionality to a `gofumpt -s -w` equivalent, like it does for the `gofmt` linter. It would be good if that could be added, as then we could switch our .golanci-lint.yml to disable the fmt linter and switch to gofumpt wholesale

cc @mvdan as he'd probably be interested in knowing that this work is taking place to add gofumpt to golangci-lint

**Comment by SVilgelm** [comment]
Since gofump returns already formatted file instead of diff, so we need to use something like this https://github.com/sergi/go-diff library to create a diff then use `extractIssuesFromPatch` function

**Comment by SVilgelm** [comment]
@dnwe Could you please test the #1239 ?

**Comment by invidian** [comment]
This has been added in #1177.

**Comment by SVilgelm** [comment]
@invidian you are right, the `gofumpt` linter was added in that PR, but it doesn't support autofixing, I'm adding it in the #1239

**Comment by Antonboom** [comment]
@SVilgelm, hello!

Could you tell me something about this?
https://github.com/mvdan/gofumpt/issues/79

**Comment by SVilgelm** [comment]
@Antonboom latest master has an updated version of `gofumpt` and it works correctly for the example you provided.
The PR with the update: #1228

**Comment by Antonboom** [comment]
Then I have to wait v1.28.4
Thanks!
