### ISSUE TITLE
Under go 1.23, golangci-lint uses all available memory

### ISSUE THREAD

**Issue by jaevans** [golangci/golangci-lint#4909]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

Updating the toolchain line to `1.23.0` in `go.mod` causes the linter to run out of memory. I've duplicated this on both linux x86_64 and darwin arm64. I haven't yet identified which linter is causing the problem, but it's one of the default set

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.59.1 built with go1.22.4 from 1a55854 on 2024-06-08T22:05:49Z
```

</details>

### Configuration

<details>

No configuration file or command line arguments passed.

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.23.0 darwin/arm64
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jaevans/Library/Caches/go-build'
GOENV='/Users/jaevans/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jaevans/go/pkg/mod'
GONOPROXY='gitlab.sicura.dev/*'
GONOSUMDB='gitlab.sicura.dev/*'
GOOS='darwin'
GOPATH='/Users/jaevans/go'
GOPRIVATE='gitlab.sicura.dev/*'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/jaevans/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/jaevans/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/jaevans/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/jaevans/git/test-app/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/f3/1lg41dsx5cqc1vnt1x37x6_40000gn/T/go-build785670845=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO golangci-lint has version 1.59.1 built with go1.22.4 from 1a55854 on 2024-06-08T22:05:49Z
INFO [config_reader] Config search paths: [./ /Users/jaevans/git/test-appller /Users/jaevans/git/saas /Users/jaevans/git /Users/jaevans /Users /]
INFO [lintersdb] Active 6 linters: [errcheck gosimple govet ineffassign staticcheck unused]
INFO [loader] Go packages loading at mode 575 (imports|name|types_sizes|compiled_files|deps|exports_file|files) took 428.207ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 1.086542ms
^C (after memory usage grew above 32Gig
```

</details>

### A minimal reproducible example or link to a public repository

<details>

[semvertool](https://github.com/jaevans/semvertool/tree/golangci-lint-issue) (golangci-lint-issue branch)

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
You are using golangci-lint built with go1.22.5 to analyze go1.23 code, this cannot work.

You should use golangci-lint v1.60.0 (built with go1.23)

Related to #4837

**Comment by scvna** [comment]
@ldez FYI you're likely to continue to see reports like this come in from homebrew users.  golangci-lint v1.60.1 on homebrew was built with go1.22.6
```
golangci-lint has version 1.60.1 built with go1.22.6 from 3298c10 on 2024-08-14T01:09:25Z
```

Building from source on go 1.23.0 works as expected.

**Comment by ldez** [comment]
I know, it's always the same thing when a new version of Go is released: homebrew uses the previous version of Go.

**Comment by skaji** [comment]
How about upgrading the Go version to 1.23.0 in the go.mod file?
https://github.com/golangci/golangci-lint/blob/master/go.mod#L3

Then homebrew cannot build golangci-lint on go 1.22, I think.

**Comment by skaji** [comment]
> The users that use the "tools pattern" need to compile with go1.22.

I see.

**Comment by ldez** [comment]
> is it the same thing with nix?

It depends on your system, and how you build golangci-lint.

If golangci-lint v1.60.1 is compiled by go1.23, there is no problem.

**Comment by mskonovalov** [comment]
Yeah, I see.
I guess golangci-lint v1.60.1 for nix may be built with go 1.22.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/golangci-lint/default.nix
Although I'm not sure how to approach this.
@ldez do you think it might be beneficial to have 2 binaries: 1.60.1-go122 and 1.60.1-go123?

**Comment by ldez** [comment]
We don't need 2 binaries because a binary built with go1.23 works with go1.22.
We officially only build with go1.23 to support the both.

**Comment by mskonovalov** [comment]
thanks for the explanation 👍 
nix definitely has the wrong one :(

**Comment by pugnascotia** [comment]
Is there a regression here? I downloaded a fresh binary on Mac ARM and I see:

`golangci-lint has version v1.60.3 built with go1.22.7 from (unknown, modified: ?, mod sum: "h1:l38A5de24ZeDlcFF+EB7m3W5joPD99/hS5SIHJPyZa0=") on (unknown)`

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/issues/4909#issuecomment-2297924465

**Comment by pugnascotia** [comment]
Huh. So I was installing with `go install ...`, but despite using 1.23.0 to do this, it still fetched a binary for 1.22.*. Weird.

**Comment by ldez** [comment]
`go install` doesn't fetch binaries, it builds the binary from sources, so you are using go1.22 to compile.

**Comment by ingwarsw** [comment]
> You are using golangci-lint v1.59.1 (built with go1.22.4) to analyze go1.23 code, this cannot work.
> 
> You should use golangci-lint v1.60.0 (built with go1.23)

@ldez while I agree with your answer that it cannot work.
But it should either fail, or do whatever it could, but not eat all the memory on the world.

**Comment by ldez** [comment]
Since v1.60.3, there is a log https://golangci-lint.run/product/changelog/#v1603 

```console
$ ./golangci-lint run
Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23)
Failed executing command with error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23)
```

Related to #4938

**Comment by ingwarsw** [comment]
I didnt know that..
But I think it dont work in all cases..

My tests all using same linter.
```
golangci-lint has version v1.61.0 built with go1.22.1 from (unknown, modified: ?, mod sum: "h1:VvbOLaRVWmyxCnUIMTbf1kDsaJbTzH20FAMXTAlQGu8=") on (unknown)
```

- `go version go1.22.1 darwin/arm64` + go.mod -> `go 1.22.0`/`no toolchain`
works as expected

- `go version go1.23.1 darwin/arm64` + go.mod -> `go 1.22.0`/`no toolchain`
***Eats all the memory and hangs forever***

- `go version go1.22.1 darwin/arm64` + go.mod -> `go 1.23.0`/`no toolchain`
Throws error "_Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.0)_" which is expected

- `go version go1.23.1 darwin/arm64` + go.mod -> `go 1.23.0`/`no toolchain`
Throws error "_Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.0)_" which is expected

- `go version go1.22.1 darwin/arm64` + go.mod -> `go 1.22.0`/`toolchain go1.23.1`
***Eats all the memory and hangs forever***

- `go version go1.23.1 darwin/arm64` + go.mod -> `go 1.22.0`/`toolchain go1.23.1`
***Eats all the memory and hangs forever***


So seems like its not even issue with toolchain but the check only checks the `go version` in the go.mod file and dont check actually used go runtime version.

**Comment by ldez** [comment]
Can you provide your test protocol (how do you build)?

If you are using the tools pattern, remember that, in this context, the `toolchain` is always ignored.

**Comment by ingwarsw** [comment]
I was able to create repro case..
Its not just about the versions but the code itself.

I found its breaking for `github.com/grpc-ecosystem/grpc-gateway/v2` package.

You can found all repro files under https://github.com/kentik/.github/pull/1/files

https://github.com/kentik/.github/actions/runs/11723589591/job/32655587129 <- killed by GH after 2m when toolchain is set
https://github.com/kentik/.github/actions/runs/11723611754/job/32655657846 <- passed without toolchain

The [line](https://github.com/kentik/.github/pull/1/files#diff-7c72539ce7d9fc8e76dd2dc788fa6e98f732d7b6ce253eca538a0e3d8a2f2e41R5) thats makes if fail or pass

**Comment by ldez** [comment]
I have no problem even with toolchain.

<details><summary>OK</summary>

```console
$ docker run --rm -v $(pwd):/app -w /app -it golang:1.22.1-alpine sh  
/app # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
...
/app # golangci-lint version
golangci-lint has version v1.61.0 built with go1.22.1 from (unknown, modified: ?, mod sum: "h1:VvbOLaRVWmyxCnUIMTbf1kDsaJbTzH20FAMXTAlQGu8=") on (unknown)
/app # go version
go version go1.22.1 linux/amd64
/app # golangci-lint run
```

</details>

<details><summary>Details</summary>

```go
module github.com/golangci/sandbox

go 1.22.0

toolchain go1.23.1

require github.com/grpc-ecosystem/grpc-gateway/v2 v2.23.0

require (
	golang.org/x/net v0.28.0 // indirect
	golang.org/x/sys v0.24.0 // indirect
	golang.org/x/text v0.19.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20241021214115-324edc3d5d38 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20241021214115-324edc3d5d38 // indirect
	google.golang.org/grpc v1.67.1 // indirect
	google.golang.org/protobuf v1.35.1 // indirect
)
```

</details>

**Comment by ingwarsw** [comment]
You have the code on GH. and you see its failing on GH..
I cannot do much more..
Try with my code..

**Comment by ldez** [comment]
https://github.com/ldez/cuddly-funicular/actions/runs/11724116720

**Comment by ingwarsw** [comment]
But your not doing actually `golangci-lint run`
And your setting GOTOOLCHAIN to lower than go version and should be opposite.

**Comment by ldez** [comment]
https://github.com/ldez/cuddly-funicular/actions/runs/11724207066

https://github.com/ldez/cuddly-funicular/commit/4a5aced32a2fb230c293d166ea329e3342caab01

**Comment by ingwarsw** [comment]
Yup my bad.. but seems that you have it now.
https://github.com/ldez/cuddly-funicular/actions/runs/11724253936

**Comment by ldez** [comment]
Build with go1.22 + go.mod 1.22 toolchain go1.23.1
- local Go version 1.22 -> fail
- local Go version 1.23 -> fail

https://github.com/ldez/cuddly-funicular/actions/runs/11724207066
https://github.com/ldez/cuddly-funicular/commit/4a5aced32a2fb230c293d166ea329e3342caab01

Build with go1.22 + go.mod 1.22 no toolchain
- local Go version 1.22 -> OK
- local Go version 1.23 -> fail

https://github.com/ldez/cuddly-funicular/actions/runs/11724253936 
https://github.com/ldez/cuddly-funicular/commit/dcbedb3aa6d76ec775137acd6a228b26be1bda7f

**Comment by ingwarsw** [comment]
So you have your case?

**Comment by ldez** [comment]
Something that is not reproducible locally is complex to diagnose.
I need to understand what is the exact context inside GitHub Action.

**Comment by ingwarsw** [comment]
why its not reproducible locally?
Just do the same thats on GH and its 100% reproducible..

**Comment by ldez** [comment]
> why its not reproducible locally?

This is the question.

**Comment by ldez** [comment]
Build with go1.22 + go.mod 1.22 toolchain go1.23.1 + global `GOTOOLCHAIN: local`

- local Go version 1.22 -> OK
- local Go version 1.23 -> fail

So I'm staring to understand.

**Comment by ldez** [comment]
The only case (A) that really fails is: build with go1.22 + go.mod 1.22 toolchain go1.23.1 + local Go version 1.23 (global `GOTOOLCHAIN: local`).

The other case (B) is: build with go1.22 + go.mod 1.22 toolchain go1.23.1 + local Go version 1.22 (with `GOTOOLCHAIN: auto` [the default])

The case (B) is the same as the case (A) because `actions/setup-go` downloads go1.23 (because of `toolchain go1.23.1`)

**Comment by ldez** [comment]
So now I can reproduce the problem inside a container:

```console
$ docker run --rm -v $(pwd):/app -w /app -it golang:1.23.2-alpine sh  
/app # GOTOOLCHAIN=go1.22.1 go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
...
/app # golangci-lint version
golangci-lint has version v1.61.0 built with go1.22.1 from (unknown, modified: ?, mod sum: "h1:VvbOLaRVWmyxCnUIMTbf1kDsaJbTzH20FAMXTAlQGu8=") on (unknown)

/app # rm -rf /go/pkg/mod/golang.org/toolchain@*

/app # go version
go version go1.23.2 linux/amd64

/app # golangci-lint run
###### High memory consumption and kill
```

**Comment by ldez** [comment]
I have a fix.

**Comment by ldez** [comment]
The fix: https://github.com/golangci/golangci-lint/pull/5112
