### ISSUE TITLE
Provide pre-built binary for ARM arch

### ISSUE THREAD

**Issue by bmuschko** [golangci/golangci-lint#491]
Currently, the [list of releases](https://github.com/golangci/golangci-lint/releases) only supports binaries for Windows, Linux and MacOSX. It would like to use the tool with ARM architecture (e.g. Raspberry Pi). Does anything speak against creating a binary for it with new releases going forward. The script at https://install.goreleaser.com/github.com/golangci/golangci-lint.sh should also support this type of architecture.

**Comment by jirfag** [comment]
Hi, I'm ok with it. I don't have ARM device to test built release. Can you add `arm` support to [`.goreleaser.yml`](https://github.com/golangci/golangci-lint/blob/master/.goreleaser.yml), test it locally by `goreleaser` and make a pull request?

**Comment by techknowlogick** [comment]
I've provided a PR for this at #607

**Comment by bmuschko** [comment]
@techknowlogick Thanks for providing the PR!
