### ISSUE TITLE
Version the config schemas so that users can specify version in their config file for automatic IDE schema validations

### ISSUE THREAD

**Issue by dakojohn** [golangci/golangci-lint#4928]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

Dependency updating takes time on large teams, especially if it's not currently broken.  

IDEs automatically use the config schema that was recently created to provide schema validation in the editor, but because the only schema available is for the current version of golangci-lint, the validation in IDEs may not reflect the version a user is running, causing confusion.

### Describe the solution you'd like

Find a way to version the schemas you are hosting so that users that are on an older version of golangci-lint can select the correct version of the schema, and are not confused by the IDEs automatic schema validation.

### Describe alternatives you've considered

Not really any viable alternatives...  I guess I could disable schema validation in my IDE for every repo I touch with golangci-lint?  But that defeats the purpose of schema validation.

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

the JSON Schema is already versioned:
- https://golangci-lint.run/jsonschema/golangci.jsonschema.json
- https://golangci-lint.run/jsonschema/golangci.v1.59.jsonschema.json
- https://golangci-lint.run/jsonschema/golangci.v1.58.jsonschema.json

**Comment by dakojohn** [comment]
That was not clear from the documentation or from the url.  With this, I can at least put a comment directive in the file to direct my IDE to an older schema.

Currently the schema store entry links to the most recent schema only.  In the Contributing doc in schema store's github, in the section about [hosting your own schema](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-add-a-json-schema-thats-self-hostedremoteexternal), they link to the an [example PR](https://github.com/SchemaStore/schemastore/pull/1211/files).  Following any of the url links in this example ([like the first one for ORY Hydra](https://raw.githubusercontent.com/ory/hydra/master/.schema/version.schema.json)) to their self hosted schema, they are using a combination of oneOf and allOf to switch the schema validations off of a version field.  I was expecting something more akin to this solution, which would be more automatic for users of golangci-lint.

**Comment by ldez** [comment]
We only maintain one version of golangci-lint (the latest), and the current versioned schemas are just a convenience for the CLI command `golangci-lint config verify`.

Based on the fact we only maintain one version of golangci-lint, I don't think creating an extra step to handle multiple versions of the schema is worth the cost.

**Comment by dakojohn** [comment]
The teams I'm on make use of a large number of the linters available in golangci-lint.  A while back, we were keeping up with bleeding edge, but were required to pin the version we were using after repeated breaking changes to linter config options started blocking feature development.  We now review and update the version we use every ~6 months, in line with established team policy.  This kind of problem and solution are not unusual in larger enterprise environments.

While I understand, and respect, that you only really support the most recent version, the recent addition of the schema validation that IDEs automatically implement has caused teammates to put up PRs with bad linter config changes because the current version of the schema is different from the version we are using.

I am not proposing a change to your supported versions, only proposing IDE version awareness for schema validation purposes.

**Comment by ldez** [comment]
> I am not proposing a change to your supported versions, only proposing schema version awareness for IDE schema validation purposes.

To have schema version awareness we should have a version inside the configuration, and as I explained we don't plan to do that for now.

> This kind of problem and solution are not unusual in larger enterprise environments.

Larger enterprises don't seem to care a lot about golangci-lint sustainability.
The total amount of money that golangci-lint gets monthly from funding/sponsoring is $2 (to be precise $1.80), if you want to check that https://opencollective.com/golangci-lint.

It requires a lot of work and time to maintain golangci-lint, I think we can say that golangci-lint is enterprise-grade software, at least we try to create high-quality software and documentation.

So we have to use our time as best as we can.
It's not against you, it's just pragmatic.
