### ISSUE TITLE
Golangci v1.60.1 opposed to v1.60.2

### ISSUE THREAD

**Issue by youssefhassan** [golangci/golangci-lint#4934]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

Golangci v.1.60.1 was working fine, but after the update to v1.60.2 which came as I use the GitHub actions version 
https://github.com/sc-actions-forks/golangci-lint-action/tree/master

```
Error: ../../../go/pkg/mod/github.com/newrelic/go-agent/v3@v3.33.1/newrelic/sql_driver.go:47:37: predeclared any requires go1.18 or later (typecheck)
  func sendSecureEventSQL(query, args any) any {
                                      ^
  Error: ../../../go/pkg/mod/github.com/newrelic/go-agent/v3@v3.33.1/newrelic/sql_driver.go:51:43: predeclared any requires go1.18 or later (typecheck)
  func sendSecureEventSQLPrepare(query, obj any) {
                                            ^
  Error: ../../../go/pkg/mod/github.com/newrelic/go-agent/v3@v3.[33](https://github.com/soundcloud/gateway/actions/runs/10475562539/job/29012503998#step:6:35).1/newrelic/sql_driver.go:55:46: predeclared any requires go1.18 or later (typecheck)
  func sendSecureEventSQLPrepareArgs(args, obj any) any {
```

while using Go 1.21

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration

<details>

```console
# paste configuration file or CLI flags here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

To be able to process your issue as quickly as possible,
can you edit your issue to add missing elements, fix the invalid elements, and complete the sections?

| Section                                                       | Status |
|---------------------------------------------------------------|--------|
| Welcome                                                       | 🟢🟠🔴 |
| Description of the problem                                    | 🟢🟠🔴 |
| Version of golangci-lint                                      | 🟢🟠🔴 |
| Configuration                                                 | 🟢🟠🔴 |
| Go environment                                                | 🟢🟠🔴 |
| Verbose output of running                                     | 🟢🟠🔴 |
| A minimal reproducible example or link to a public repository | 🟢🟠🔴 |
| Validation                                                    | 🟢🟠🔴 |
| Supporter                                                     | 🟢🟠🔴 |

Legend:
- 🟢: The section is complete and valid.
- 🟠: The section is incomplete.
- 🔴: The section is missing or invalid.

---

> Golangci v.1.60.1 was working fine, but after the update to v1.60.2 which came as I use the GitHub actions version
> https://github.com/sc-actions-forks/golangci-lint-action/tree/master

You are not using the official GitHub Action and this fork is not up-to-date.

**Comment by amyjbaer** [comment]
I am having similar issues. Additionally having these
```
Error: gen/routes.go:27:3: missing type in composite literal (typecheck)
```
This is occuring for custom types it seems
```
type CustomType []otherType
```



and unable to see inherited fields 
```
type Example struct {
  otherStruct
} 

type otherStruct struct {
  SomeField string
}

// linter complains
Example.SomeField
```

**Comment by ldez** [comment]
If you are facing the same problem, the best way to contribute is to provide the following information:

A code example or link to a public repository.

```
golangci-lint --version
```

```
cat .golangci.yml
```

```
go version && go env
```

```
golangci-lint cache clean
golangci-lint run -v
```
