### ISSUE TITLE
v1.60.2 reports integer overflow conversion int -> int32 for conversion like int32(group) with group is an int

### ISSUE THREAD

**Issue by houshengbo** [golangci/golangci-lint#4935]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

v1.60.2 starts to report "integer overflow conversion int -> int32 for conversion like int32(group) with group is an int", but v1.60.1 does not report this error.

### Version of golangci-lint

v1.60.2

### Configuration

Using v1.60.2

v1.60.1 is fine.

### Go environment

1.22.4

### Verbose output of running

G115: integer overflow conversion int -> int32 (gosec)
	drqsGroup := int32(group)

group is an int defined.

### A minimal reproducible example or link to a public repository

internal project. no link.

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/pull/4927#issuecomment-2299823220
