### ISSUE TITLE
License Woes

### ISSUE THREAD

**Issue by crxpandion** [golangci/golangci-lint#495]
Thanks for this awesome project. 

Unfortunately, using `golangci-lint` here at Twitch in our build pipelines is a slow, involved process due to the usage of GPLv3. Would you consider changing the license to something like MPL 2.0?

**Comment by jirfag** [comment]
Hi! I would like to change the license to MIT but I'm not sure I can do it because some of my dependencies are GPL v3. I'm not a license expert and need time to investigate it.

**Comment by mellis** [comment]
It looks like the problem is with a couple of the linters, could they perhaps be distributed separately?

**Comment by lopezator** [comment]
The most common LICENSE in Go/Cloud is Apache 2.0. 

I think it's pretty similar to MPL.

**Comment by ernado** [comment]
I'm not sure that we can easily change the license of existing GPLv3 project :/
