### ISSUE TITLE
go-diff dependency

### ISSUE THREAD

**Issue by godofdream** [golangci/golangci-lint#497]
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
de1d1ad903cdfdfc577ecb08d5027576e70ed2f0

sourcegraph.com/sourcegraph/go-diff@v0.5.1 moved to github.com/sourcegraph/go-diff/diff
This needs to be updated

**Comment by godofdream** [comment]
https://github.com/golangci/golangci-lint/pull/487

**Comment by jirfag** [comment]
thank you, closing as https://github.com/golangci/golangci-lint/pull/487 was merged
