### ISSUE TITLE
Golang version regression when running with pre-commit

### ISSUE THREAD

**Issue by DanGM96** [golangci/golangci-lint#4989]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [ ] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

We updated our project's golang version to 1.23.0 recently, and with it, most of our pre-commits, specifically version 1.60.3, stopped working with go above 1.22

I say it's a regression because it works on both previous versions, 1.60.1 and 1.60.2.

I'm sorry I couldn't test on a standalone linter, but 1.60.2 will now suffice. I'm just reporting to help you guys.

### Version of golangci-lint

<details>

I don't use golangci-lint directly, but the version used with pre-commit is:

- v1.60.3

</details>

### Configuration

<details>

`.pre-commit-config.yaml`
```yaml
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.60.3
    hooks:
    -   id: golangci-lint
        stages: [commit]
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.23.1 linux/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/myuser/.cache/go-build'
GOENV='/home/myuser/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/myuser/go/pkg/mod'
GONOPROXY='github.com/myorganization'
GONOSUMDB='github.com/myorganization'
GOOS='linux'
GOPATH='/home/myuser/go'
GOPRIVATE='github.com/myorganization'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.1'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/myuser/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/home/myuser/myproject/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2009260257=/tmp/go-build -gno-record-gcc-switches'
```

</details>

### Verbose output of running

pre-commit output:

```console
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 3

Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.0)
Failed executing command with error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.0)
```

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

> Failed executing command with error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.0)

This is not related to the pre-commit and is not a regression but the expected behavior.

You are trying to use a golangci-lint binary compiled with go1.22 to analyze go1.23 code.
This cannot work, it's like if you are trying to compile go1.23 code with go1.22.

You should use a golangci-lint binary compiled with go1.23 to analyze go1.23 code.
