### ISSUE TITLE
Implement LSP server

### ISSUE THREAD

**Issue by bersace** [golangci/golangci-lint#5004]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

golangci-lint is great. I miss a faster feedback so that I catch some errors before pushing to CI.

### Describe the solution you'd like

Juste like ruff server, I suggest to implement LSP protocole.

### Describe alternatives you've considered

None.

### Additional context

I'm running Zed.

Thank you,
Étienne

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by bombsimon** [comment]
A language server already exist: https://github.com/nametake/golangci-lint-langserver

**Comment by komidore64** [comment]
While I understand that `golangci-lint-langserver` already exists, it would be really nice if that functionality was integrated directly into `golangci-lint`. That would decrease the number of tools needing installation to get a functioning LSP.

Is there a reason that functionality is separate? Thanks for considering! <3

**Comment by ldez** [comment]
This is in my plan to have an integrated LSP.

- Donate :heart:: 2€ /_$2 / 2£ / 350円 / 15元 / 100₴ / 200₽ / 1500원 / 12 B$ per month is important
    - [golangci-lint](https://donate.golangci.org)
    - [ldez](https://donate.ldez.dev)
- Ask your company to donate (if needed, we can exchange by email: info at golangci dot com)
    - [golangci-lint](https://donate.golangci.org)
    - [ldez](https://donate.ldez.dev)

OSS are free to use but not free of work.
