### ISSUE TITLE
feature request: warn on `//nolint:typecheck`

### ISSUE THREAD

**Issue by vegerot** [golangci/golangci-lint#5005]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

I spent twenty minutes today trying to figure out why `//nolint:typecheck` was being ignored in my project.  I was about to report an issue for `//nolint:typecheck` being ignored, when I read the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors) and saw that this was the intended behavior.

I wish I hadn't wasted twenty minutes figuring out what was wrong.

### Describe the solution you'd like

When encountering a `//nolint:typecheck` golangci-lint should emit a warning saying this directive will be ignored and link to the FAQ.

### Describe alternatives you've considered

We could also emit an error when using `//nolint:typecheck`, but that sounds too extreme

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by vegerot** [comment]
extra credit:

When reporting a `typecheck` error, if the line has `//nolint:all`, we should provide an extra warning saying "I see you put `//nolint:all` here, but this is ignored because of <FAQ link>"

**Comment by ldez** [comment]
Hello,

To be able to detect the directives, we need to analyze the code, but as `typecheck` errors block the analysis, it's impossible to detect the directives.

So I understand the issue but there is no solution.
