### ISSUE TITLE
golangci-lint shows "killed" immediately 

### ISSUE THREAD

**Issue by tzookb** [golangci/golangci-lint#5042]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

when I try to run any command for "golangci-lint"
like:
```
golangci-lint
golangci-lint run .
golangci-lint version
etc...
```

it shows:
```
[1]    18319 killed     golangci-lint --version
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
1.61.0
```
</details>

I cant dump the full content, I just know its the version.

### Configuration

<details>

```console
# paste configuration file or CLI flags here
```

</details>

### Go environment

<details>

```console
$ go version && go env

go version go1.21.0 darwin/arm64
GO111MODULE='on'
GOARCH='arm64'
GOBIN='/xxxxxxx/build-support/go/bin'
GOCACHE='/Users/tzookb/Library/Caches/go-build'
GOENV='/Users/tzookb/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS='-modcacherw'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/xxxxxxx/build-support/go/pkg/mod'
GONOPROXY=''
GONOSUMDB='*'
GOOS='darwin'
GOPATH='/xxxxxxx/build-support/go'
GOPRIVATE=''
GOPROXY='https://xxxxxxxx@artifacts.zzzzzz.net/repository/go'
GOROOT='/xxxxxxx/build-support/go/sdk'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/xxxxxxx/build-support/go/sdk/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/4c/xxxxxx/T/go-build2617350968=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v

[1]    29434 killed     golangci-lint cache clean

```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
/not even checking the code
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by tzookb** [comment]
I did try to run the code directly and it gave me a response.
So I built it directly from code with:

`GOOS=darwin GOARCH=arm64 go build cmd/golangci-lint/main.go`

but then running the executable gave the same "killed" error again

**Comment by ldez** [comment]
Hello,

You should use, at least, go1.22 to compile golangci-lint.

**Comment by tzookb** [comment]
ended up using this to solve the issue:

https://stackoverflow.com/questions/51833310/what-is-killed9-and-how-to-fix-in-macos-terminal

```
codesign --sign - --force --preserve-metadata=entitlements,requirements,flags,runtime /path-to/golangci-lint
```

**Comment by jmoody** [comment]
This is also happening to me.  It started two weeks ago. It hasn't happened yet for any of my colleagues.

macOS 14.7
Xcode 16.0

The process is killed because of an invalid code signature.

This is the only go binary where I've observed this problem.


```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

/Users/moody/go/1.22.5/bin/golangci-lint --version
zsh: killed     /Users/moody/go/1.22.5/bin/golangci-lint --version

codesign -vvvv /Users/moody/go/1.22.5/bin/golangci-lint
/Users/moody/go/1.22.5/bin/golangci-lint: invalid signature (code or signature have been modified)
In architecture: arm64
```

[sample crash report](https://gist.github.com/jmoody/67de7b7508355fb4c2932efa63d14699)

Like the original poster, resigning worked for me.

```
codesign --force --deep --sign - _tools/bin/golangci-lin
```

**Comment by ldez** [comment]
Based on issues on Go: https://github.com/golang/go/issues?q=is%3Aissue+%22Code+Signature+Invalid%22+is%3Aclosed

The problem seems to be related to tooling inside MacOS.
