### ISSUE TITLE
Not able to query version 1.16.0

### ISSUE THREAD

**Issue by Truja** [golangci/golangci-lint#508]
I am trying to install golangci-lint according to installation description, but I am getting following error:

00:20 $ GO111MODULE=on  go get  github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0
go: finding github.com/golangci/golangci-lint/cmd/golangci-lint v1.16.0
go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0: can't query specific version ("v1.16.0") for package github.com/golangci/golangci-lint/cmd/golangci-lint in the main module (github.com/golangci/golangci-lint)

My Go environment: `go version && go env`

> 00:23 $ go version && go env
> go version go1.12.3 darwin/amd64
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/rtrujillo/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/rtrujillo/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/Cellar/go/1.12.3/libexec"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/Cellar/go/1.12.3/libexec/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/Users/rtrujillo/go/src/github.com/golangci/golangci-lint/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9p/163kyyjd59777m8wlnrfny8c0000gn/T/go-build761649214=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by aofei** [comment]
This problem has been solved in #487, you just have to wait for the new version.

CC @jirfag

**Comment by jirfag** [comment]
a next release is planned in 5 days

**Comment by Nivl** [comment]
@jirfag any news on the next version?

**Comment by jirfag** [comment]
sorry for the delay, I've released [v1.17.0](https://github.com/golangci/golangci-lint/releases/tag/v1.17.0)
