### ISSUE TITLE
After the Mac is installed locally, the scanning results are inconsistent with those obtained by running commands from official images

### ISSUE THREAD

**Issue by fjzcxs** [golangci/golangci-lint#5084]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

After the Mac is installed locally, the scanning results are inconsistent with those obtained by running commands from official images, And for both I am using the latest version 1.61.0. 
After installing the scan with mac local brew, I think it contains the correct scan results, and the plugin contains errcheck, gosimple, govet, etc., which are turned on by default6, but the result rules of scanning after using the official image in the local docker run only contain typecheck, why do you scan the same project but have different results

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# 1.61.0
```

</details>

### Configuration

<details>

```console
# paste configuration file or CLI flags here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# go1.21.5
```

</details>

### Verbose output of running

<details>

```console

none
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// add your code here
none
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

To be able to process your issue as quickly as possible,
can you edit your issue to add missing elements, fix the invalid elements, and complete the sections?

| Section                                                       | Status |
|---------------------------------------------------------------|--------|
| Welcome                                                       | 🟠 |
| Description of the problem                                    | 🟢 |
| Version of golangci-lint                                      | 🔴 |
| Configuration                                                 | 🔴 |
| Go environment                                                | 🟠 |
| Verbose output of running                                     | 🔴 |
| A minimal reproducible example or link to a public repository | 🔴 |
| Validation                                                    | 🔴 |
| Supporter                                                     | 🟢 |

Legend:
- 🟢: The section is complete and valid.
- 🟠: The section is incomplete.
- 🔴: The section is missing or invalid.

**Comment by corrosive4354** [comment]
I guess it's a compatibility issue between docker and mac.
Try redeploying your development environment using the [servbay](https://servbay.com) tool.

**Comment by ldez** [comment]
The issue has not been edited to add missing information, so I closed the issue.
