### ISSUE TITLE
Using golangci-lint with neomake

### ISSUE THREAD

**Issue by natemurthy** [golangci/golangci-lint#512]
Hello, I'm using

* Version of golangci-lint: `1.16.0 built from 97ea1cb on 2019-03-31T19:48:46Z`
* Go environment: `go version go1.11.2 darwin/amd64`

And would like to integrate this linter aggregation tool with my [neomake](https://github.com/neomake/neomake) plugin installed for `nvim`. My current setup relies on `gometalinter` as follows:

```vim
autocmd! BufWritePost * Neomake
let g:neomake_error_sign   = {'text': '✖', 'texthl': 'NeomakeErrorSign'}
let g:neomake_warning_sign = {'text': '∆', 'texthl': 'NeomakeWarningSign'}
let g:neomake_message_sign = {'text': '➤', 'texthl': 'NeomakeMessageSign'}
let g:neomake_info_sign    = {'text': 'ℹ', 'texthl': 'NeomakeInfoSign'}
let g:neomake_go_enabled_makers = [ 'go', 'gometalinter' ]
let g:neomake_go_gometalinter_maker = {
  \ 'args': [
  \   '--tests',
  \   '--enable-gc',
  \   '--concurrency=3',
  \   '--fast',
  \   '-D', 'aligncheck',
  \   '-D', 'dupl',
  \   '-D', 'gocyclo',
  \   '-D', 'gotype',
  \   '-E', 'errcheck',
  \   '-E', 'misspell',
  \   '-E', 'unused',
  \   '%:p:h',
  \ ],
  \ 'append_file': 0,
  \ 'errorformat':
  \   '%E%f:%l:%c:%trror: %m,' .
  \   '%W%f:%l:%c:%tarning: %m,' .
  \   '%E%f:%l::%trror: %m,' .
  \   '%W%f:%l::%tarning: %m'
  \ }
```

I'd like to replace `gometalinter` with `golangci-lint` but cannot get any of the neomake signs to appear on any of the lint warnings to appear on lines of code in my text editor. I've tried out [this reference vimrc file](https://github.com/Phantas0s/.dotfiles/blob/master/nvim/pluggedconf/neomake.nvimrc#L104-L136), but this didn't work for me either.

Any help would be appreciated!

**Comment by dmlyons** [comment]
Not sure if this will help you, but I got it mostly working using `golangci_lint` instead of `golangci-lint` (underscore instead of dash).

Looking at the code for https://github.com/neomake/neomake/pull/2333 it seems like that is the way to make it happy.  I am not sure if there is a need to use the underscore instead of the dash, or if this was just a mistake.

**Comment by natemurthy** [comment]
Thanks! I pulled the latest changes of neomake into my plugins and used the `golangci_lint` maker and that got things working. The default golangci_lint maker function _feels_ a bit slower than my gometalinter maker function, but I'll play with a few args that make sense for me.

Closing this out :)
