### ISSUE TITLE
Unknown architecture wasm - Regression

### ISSUE THREAD

**Issue by dallbee** [golangci/golangci-lint#514]
After updating golangci-lint to master, I noticed a new error:

`2019/04/24 11:34:44 unknown architecture wasm`

Produced using: `$ golangci-lint --help`

I bisected the regression to 8c1237b667721304bf597ad3458f116bbbe86377

2. Config file: none
3. Go environment:
`go1.10.3 linux/amd64 `
```
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="~/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS=""
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS=""
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build249139759=/tmp/go-build -gno-record-gcc-switches"
```
4. The error happens before verbose output appears to be respected, so I've not included it.

My guess is that the commit broke 1.10 compatibility, which you might not be supporting anyways.

**Comment by PilotConway** [comment]
We just ran into this in our project as well. The following error mentions unsupported version of go, so I'm guessing we just need to stay on the release just before it broke for now until we can get the time to upgrade to newer go versions.

**Comment by dallbee** [comment]
Interesting. I did _not_ get an error about unsupported version of go.

**Comment by jirfag** [comment]
Hi!
`go vet`'s analyzer `asmdecl` prints this log line. You are compiling golangci-lint with go < 1.11, it's the reason. Please, use binary releases: they are compiled with go 1.12.
