### ISSUE TITLE
Linter sugesting intrange

### ISSUE THREAD

**Issue by Hugoreal2** [golangci/golangci-lint#5142]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

My linter is accusing "for loop can be changed to use an integer range (Go 1.22+) (intrange)"

But you cant use the range keyword for an int since NumField() just returns an int?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version

golangci-lint has version v1.62.0 built with go1.22.9 from (unknown, modified: ?, mod sum: "h1:/G0g+bi1BhmGJqLdNQkKBWjcim8HjOPc4tsKuHDOhcI=") on (unknown)
```

</details>

### Configuration

<details>

```console
None
```

</details>

### Go environment

<details>

```
go version
go version go1.22.0 windows/amd64

go env
go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Hugo Araujo\AppData\Local\go-build
set GOENV=C:\Users\Hugo Araujo\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Hugo Araujo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Hugo Araujo\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\HUGOAR~1\AppData\Local\Temp\go-build981693489=/tmp/go-build -gno-record-gcc-switches
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
func objectToMap(obj interface{}) (map[string]interface{}, error) {
	v := reflect.ValueOf(obj)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	if v.Kind() != reflect.Struct {
		return nil, fmt.Errorf("objectToMap: expected a struct, got %v", v.Kind())
	}

	m := make(map[string]interface{})
	t := v.Type()
	for i := 0; i < v.NumField(); i++ { // QUESTION HERE
		field := t.Field(i)
		value := v.Field(i).Interface()
		m[field.Name] = value
	}

	return m, nil
}
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

> But you cant use the range keyword for an int since NumField() just returns an int?

You can because it's just an int.

```go
func objectToMap(obj interface{}) (map[string]interface{}, error) {
	v := reflect.ValueOf(obj)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	if v.Kind() != reflect.Struct {
		return nil, fmt.Errorf("objectToMap: expected a struct, got %v", v.Kind())
	}

	m := make(map[string]interface{})

	t := v.Type()

	for i := range v.NumField() {
		fmt.Println(i)
		field := t.Field(i)
		value := v.Field(i).Interface()
		m[field.Name] = value
	}

	return m, nil
}
```

https://tip.golang.org/doc/go1.22
