### ISSUE TITLE
Some unused functions are not be detected

### ISSUE THREAD

**Issue by hayato8059** [golangci/golangci-lint#518]
Hello, 
when I use UNUSED to detect unused function in my project, only one  function was detected, but at least four functions are not used.  I also check some other project, but in other project no function was detected.
Is there a mistake in my way of using it?
Any help would be appreciated!

Information is as follows:
1. go version is go1.9.2 linux/amd64
2. golangci-lint has version 1.10.2 built from dbfcf63 on 2018-09-02T12:30:29Z
3. Config file is 
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec

4. Verbose output of running is 
/golangci-lint/bin/golangci-lint run --disable-all -E unused ./...
service/acl_service.go:406:22: func `(*AclService).getFullPath` is unused (unused)
func (s *AclService) getFullPath(op Operation) (string, error) {
                     ^
utils/client/config.go:4:2: const `pcs_api_version_1_0_0` is unused (unused)
	pcs_api_version_1_0_0      = "1.0.0"
	^
utils/client/config.go:5:2: const `pcs_api_version_1_0_1` is unused (unused)
	pcs_api_version_1_0_1      = "1.0.1"
	^

**Comment by hayato8059** [comment]
I know what the problem is. Sorry to disturb you.

**Comment by muly** [comment]
@hayato8059 what was the scenario, can you please elaborate how you resolved it. I'm also seeing unused linter not reporting some functions, even though they are not used anywere else. I also tried with `check-exported: true` option.

**Comment by victory460** [comment]
@hayato8059 @muly   Can you please elaborate how you resolved it. I'm also seeing unused linter not reporting some functions too. Thanks.

**Comment by oscar-soo** [comment]
I'm also seeing unused linter not reporting some exported methods. Just wondering if you guys have figured a workaround? I also tried with check-exported: true option as well.
