### ISSUE TITLE
Exclude unstaged files

### ISSUE THREAD

**Issue by clafoutis42** [golangci/golangci-lint#519]
I think it would be a good idea to exclude unstaged files.

Sometimes I create a commit without staging all the files, it happens to me a lot when I have to fix a bug, and I find my self checked out on another branch, with new files that could not be stashed.

When I run `golangci-lint` manually I can easily exclude them, but in the case of a pre-commit-hook, it would be a lot easier to have them ignored automatically.

Another improvement would be to exclude unstaged changes, however most linters would not be able support it.

**Comment by mamyn0va** [comment]
I totally agree with your suggestion. As many linters need all the codebase to be able to work properly, we can't just provide the staged files as an argument because it will fail. This has to be done internally by `golangci-lint`.
