### ISSUE TITLE
structcheck should probably have `-t` set

### ISSUE THREAD

**Issue by cflewis** [golangci/golangci-lint#52]
By default, `structcheck` does not load test files, so structs with fields that are only used for testing will fail. I'm not sure that's a great default as it leads to more false positives. As you can't modify arguments for specific linters using `golangci-lint` (that I can see at least) it seems like it might be a good idea to run structcheck with `t` so it brings in the test files too.

**Comment by jirfag** [comment]
Hello, thank you for the issue! I've enabled tests linting (`--tests` option)  by default in https://github.com/golangci/golangci-lint/pull/59
