### ISSUE TITLE
File-wide ignore specific linter rules

### ISSUE THREAD

**Issue by temoto** [golangci/golangci-lint#521]
Hello. Thanks for great linter tool.

Is it possible to specify file-wide ignore of specific linter (or specific rules) in that file comment, as opposed to in config?

```
golangci-lint --version
Error: unknown flag: --version
```
I like to think it's version v1.16.0 because installed with module-enabled go get.

**Comment by jirfag** [comment]
Hi! Yes, it's possible. I've improved README about `//nolint` in the https://github.com/golangci/golangci-lint/pull/560.

**Comment by Harkishen-Singh** [comment]
This does not work for me at least. I added `//nolint:govet` and it still shows up in `golangci-lint run`.
