### ISSUE TITLE
unexpected module path when using go modules

### ISSUE THREAD

**Issue by lukatendai** [golangci/golangci-lint#523]
When run go get -u github.com/golangci/golangci-lint/cmd/golangci-lint with go 1.12
I get thise error:

go: sourcegraph.com/sourcegraph/go-diff@v0.5.1: parsing go.mod: unexpected module path "github.com/sourcegraph/go-diff"

**Comment by scraly** [comment]
Same error with go 1.12

**Comment by fgm** [comment]
Workaround for now: just disable them while installing, like this:

`GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`

**Comment by aofei** [comment]
This problem has been solved in #487, you just have to wait for the new version.

Hi @jirfag, I think it's time to release the next version, isn't it? The #508 has been open for almost half a month. :-)

**Comment by rhnvrm** [comment]
Another workaround is to use `go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@master`

**Comment by tpounds** [comment]
Resolving. All `go get` issues should be fixed in newer releases.

**Comment by tpounds** [comment]
see: https://github.com/golangci/golangci-lint/issues/539
