### ISSUE TITLE
[Feature] Add go-mod-outdated

### ISSUE THREAD

**Issue by hazcod** [golangci/golangci-lint#526]
go-mod-outdated checks whether a newer version of a dependency in the `go.mod` / `go.sum` is available.

https://github.com/psampaz/go-mod-outdated

Edit: We might want to wait for https://github.com/psampaz/go-mod-outdated/pull/9 to be implemented.

**Comment by HazCod** [comment]
Version v0.3.0 has been released, which makes it possible to use programmatically.

**Comment by jirfag** [comment]
Hi! I'm not sure it's a good idea because it's not the Go linter.

**Comment by matoous** [comment]
I am with @jirfag on this. Dependency management shouldn't mix with linting in my opinion.

**Comment by psampaz** [comment]
Main author and maintainer of go-mod-outdated here.

I also believe that it should not be part of golangci-lint for the reasons mentioned above.

@hazcod there is a dockerized version out now (https://github.com/psampaz/go-mod-outdated#docker) so using it in CI should be as simple as adding one more line.

**Comment by matoous** [comment]
I am closing this issue. If more people request this feature we can reopen it for discussion again in the future.
