### ISSUE TITLE
Reduce Docker image size by switching to alpine

### ISSUE THREAD

**Issue by JensRantil** [golangci/golangci-lint#528]
I notice that the [Docker image uses `golang:1.12`](https://github.com/golangci/golangci-lint/blob/master/Dockerfile#L1). It is based on Debian Stretch and [is ~296 MB](https://hub.docker.com/_/golang?tab=tags). How about switching to use `1.12-alpine` which [is 128 MB](https://hub.docker.com/_/golang?tab=tags)? There would be a 168 MB saving which would be a nice improvement to those of use who are using the Docker image for CI (less to download => faster CI step execution).

**Comment by volmedo** [comment]
I agree with @JensRantil 

Aside from that, what about using `ENTRYPOINT` in the `Dockerfile` instead of `CMD`? The usual convention for this kind of docker images is to call the tool passing the usual set of params to `docker run` without having to write the name of the command again.
