### ISSUE TITLE
Improve debug logs

### ISSUE THREAD

**Issue by antonmedv** [golangci/golangci-lint#531]
Please, make better logs for users. Now it is just debug mess.

**Comment by tpounds** [comment]
@antonmedv Can you provide some specific examples where we can improve the output and/or messaging?

**Comment by antonmedv** [comment]
Simple run your tool. ALL logs are not useful for users. 
For better DX consider something like this:
1. Progress (should be easy to read, not too over complicated. Maybe some ascii graphics)
2. Results(ok, error)
3. Pinpoint error file, line and show code snippet.

**Comment by jirfag** [comment]
1. Why do you think that these logs should be user-friendly? Their typically used by developers of golangci-lint.
2. Why do you need these logs?

**Comment by antonmedv** [comment]
1. Users run this tool in terminal & looking at the output (for dev there can be special flag).
2. To see there errors are.

**Comment by jirfag** [comment]
1. if you run with `-v` - you see debug logs. If you run without it you see no logs.
