### ISSUE TITLE
Not working with binary literals in Go 1.13

### ISSUE THREAD

**Issue by tanordheim** [golangci/golangci-lint#535]
The upcoming Go 1.13 adds support for binary literals (see https://github.com/golang/go/issues/19308). I'm working on some code using a master-build of Go here and I'm seeing some linter errors on standard library code that got modified to use these new binary literals; primarily in the `utf8` package ([relevant code](https://github.com/golang/go/blob/master/src/unicode/utf8/utf8.go#L28)).

I'm sure golangci-lint isn't meant to support a not yet released version of Go, I just thought it might be useful to flag this in case it's not something you guys were aware of.

golangci-lint version:

`golangci-lint has version 1.16.0 built from 97ea1cb on 2019-03-31T19:48:46Z`

config file:

```
bash-4.4# cat .golangci.yml 
linters:
  enable:
    - govet
```

Go environment: 

```
bash-4.4# go version
go version go1.13-pre linux/amd64
bash-4.4# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS="-mod=readonly"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/code/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build995329976=/tmp/go-build -gno-record-gcc-switches"
```

verbose output:

[golangci-lint-verbose.txt](https://github.com/golangci/golangci-lint/files/3173503/golangci-lint-verbose.txt)

**Comment by tanordheim** [comment]
Is there anything quick and dirty I could to in a custom golangci-lint build to work around this in order to get this passing while waiting for an official Go 1.13 release and a matching golangci-lint update?

**Comment by tanordheim** [comment]
It seems a source build of golangci-lint with an upgrade of golang.org/x/tools to the latest `master` version made stuff working again - so I'll do that as a workaround for now :)

**Comment by tpounds** [comment]
@tanordheim Is this still an issue with the latest release?

**Comment by tanordheim** [comment]
Seems like it, yeah - I switched to 1.19.1 in some of our pipelines here where we previously used a custom build of golangci-lint and it went through without problems. Thanks!
