### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by tamalsaha** [golangci/golangci-lint#538]
I tried to run `go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0` and got the following error:

```
go: extracting golang.org/x/text v0.3.2
# github.com/golangci/golangci-lint/pkg/lint
../../../pkg/mod/github.com/golangci/golangci-lint@v1.16.0/pkg/lint/load.go:171:2: duplicate case "golang.org/x/tools/go/packages".LoadAllSyntax (value 991) in switch
	previous case at /home/tamal/go/pkg/mod/golang.org/x/tools@v0.0.0-20190328211700-ab21143f2384/go/packages/packages.go:98
```

I see that this was fixed in master https://github.com/golangci/golangci-lint/blob/692dacb773b703162c091c2d8c59f9cd2d6801db/pkg/lint/load.go#L171

Can you please release a new version?

**Comment by jc21** [comment]
I'm getting this with 1.15 too..

```
/go/pkg/mod/github.com/golangci/golangci-lint@v1.15.0/pkg/lint/load.go:171:2: duplicate case "golang.org/x/tools/go/packages".LoadAllSyntax (value 991) in switch
        previous case at /go/pkg/mod/golang.org/x/tools@v0.0.0-20190517183331-d88f79806bbd/go/packages/packages.go:98
```

**Comment by ian-howell** [comment]
Any update on this? It's quite the blocker

**Comment by MichaelUrman** [comment]
I had some luck after explicitly running `go get golang.org/x/tools@4892ae6` to use the golang.org/x/tools 1.12 release, but it also downgraded me to `golangci-lint v1.15.0` (I don't understand why). I'll probably just use master or wait for a release.

**Comment by tamalsaha** [comment]
I am using 
`go get github.com/golangci/golangci-lint/cmd/golangci-lint@692dacb773b703162c091c2d8c59f9cd2d6801db` .

This works fine.

**Comment by jirfag** [comment]
I've fixed it in the latest release. `go get -v -u github.com/golangci/golangci-lint@v1.17.1` works ok now.
