### ISSUE TITLE
license clarification ("free for open source")

### ISSUE THREAD

**Issue by novas0x2a** [golangci/golangci-lint#543]
Could you clarify the intended license? Right now, it's licensed GPLv3 but the readme has "Free for Open Source" which makes it seem like this is intended as an additional restriction. Thanks!

**Comment by Stebalien** [comment]
> Sponsored by GolangCI.com: SaaS service for running linters on Github pull requests. Free for Open Source.

That line? I assume that means that the golangci.com linting service is free for open source.

**Comment by novas0x2a** [comment]
Oh. Yeah, I totally mis-read that. Thanks!
