### ISSUE TITLE
[Feature] TODO/FIXME linter

### ISSUE THREAD

**Issue by matoous** [golangci/golangci-lint#547]
Add https://github.com/matoous/godox to linters (I wanted to create an issue for adding https://github.com/766b/godox but I didn't like the code so I hope this fork is ok). I will gladly create PR if this is approved.

**Comment by matoous** [comment]
@jirfag may I please request your opinion on this?

**Comment by Sean-Der** [comment]
@matoous 
Have you tried adding it to golangci-lint? It might get accepted quicker/easier if the code is ready to merge!

I would love to have this! I have built up a fair amount of tech debt from people adding TODOs to [pion/webrtc](https://github.com/pion/webrtc) so anything I can do to help get this merged please tell me :)

**Comment by Sean-Der** [comment]
@matoous I am not able to open issues against your repo because it is a fork.

But would you be ok accepting a PR that sets a non-zero error code when there are results? It would be much easier for me to use in travis if I can just throw an error on non-zero.

thanks

**Comment by matoous** [comment]
Sure! Merged it. I am now away for 3 weeks but when I am back I will try to submit PR for this.

**Comment by matoous** [comment]
Had some time, so here's the PR https://github.com/golangci/golangci-lint/pull/621

**Comment by jirfag** [comment]
Hi, it's merged, thank you

**Comment by douglarek** [comment]
New linters should be not enabled by default, since it is a incompatible upgrade.

**Comment by jirfag** [comment]
@douglarek what are you talking about? godox isn't enabled by default
