### ISSUE TITLE
False positive from go vet due to using x/tools master branch

### ISSUE THREAD

**Issue by dstrelau** [golangci/golangci-lint#552]
Hi folks! I tracked down an issue with golangci-lint reporting false positives on shadowed struct fields that is ultimately caused by the fact that golangci-lint is vendoring x/tools master branch whereas a fix has been pushed to the x/tools 1.12 release branch. 

https://github.com/golang/go/issues/30846

Just wondering if there's a reason to pull master specifically, as @mvdan over there seemed to indicate that pulling the most recent release branch might be better:

> Is there a particular reason for that, other than getting the latest features? I think that's confusing, as most developers will run vet from the latest Go version, not x/tools master.

**Comment by brodin** [comment]
I am also experiencing this issue – did you find a solution @dstrelau? 

I am considering to add a exclude rule for `repeats json tag`.
