### ISSUE TITLE
Add nargs as a supported linter

### ISSUE THREAD

**Issue by palash25** [golangci/golangci-lint#553]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
2. Config file: `cat .golangci.yml`
3. Go environment: `go version && go env`
4. Verbose output of running: `golangci-lint run -v`

https://github.com/alexkohler/nargs

**Comment by jirfag** [comment]
hi,
why isn't `unparam` sufficient for you? it looks like a much less efficient version of `unparam`

**Comment by FdeFabricio** [comment]
There are some cases that are skipped by `unparam`

**Comment by FdeFabricio** [comment]
There are some cases that unused parameters are ignored by `unparam`, called  as "dummy implementation", which are not ignored by `nargs`.  https://github.com/mvdan/unparam/issues/49

In terms of efficiency, I don't know much...
