### ISSUE TITLE
what should i do when code in sub directory

### ISSUE THREAD

**Issue by jinxiao** [golangci/golangci-lint#570]
Thank you for creating the issue!

my code is in a subdirectory which called src, when i run `golangci-lint run` in this directory , it worked all right. however, i want to run `golangci-lint run --new-from-rev=HEAD~`, whether the `golangci-lint` command need to read .git directory or not ? what should i do when i need to run with option `--new-from-rev=HEAD~` and recognize the package correctly

Please include the following information:
1. Version of golangci-lint: `golangci-lint has version 1.16.0 built from 97ea1cb on 2019-03-31T19:48:46Z`
2. Config file: i didnt use yaml file , i use this command `golangci-lint run -j 1 --new-from-rev=HEAD~ --no-config --disable-all -E typecheck -E deadcode -E unused -E errcheck --tests=false`
3. Go environment: `go version && go env`, i use this docker image `golangci/golangci-lint`
4. Verbose output of running: 

> INFO [lintersdb] Active 4 linters: [deadcode errcheck typecheck unused] 
INFO [loader] Go packages loading at mode load deps types and syntax took 90.741628ms 
INFO [loader] SSA repr building timing: packages building 5.577µs, total 7.797µs 
INFO [loader] Packages that do not compile: [_/Users/jinxiao/meishi/src] 
INFO [runner] worker.1 took 282.994µs with stages: unused: 249.777µs, errcheck: 15.245µs, typecheck: 7.464µs, deadcode: 3.731µs 
INFO [runner] Workers idle times:                 
INFO [runner] processing took 553.224µs with stages: cgo: 199.761µs, exclude: 102.472µs, source_code: 91.29µs, identifier_marker: 47.691µs, skip_dirs: 44.082µs, nolint: 28.997µs, path_prettifier: 26.287µs, max_same_issues: 3.351µs, autogenerated_exclude: 3.174µs, uniq_by_line: 1.428µs, path_shortener: 1.237µs, max_per_file_from_linter: 1.167µs, max_from_linter: 875ns, exclude-rules: 443ns, replacement_builder: 443ns, diff: 276ns, skip_files: 250ns 
src/main.go:3:8: could not import baibao/meishi/cmd (invalid package name: "") (typecheck)
import "baibao/meishi/cmd"
       ^
INFO File cache stats: 1 entries of total size 74B 
INFO Memory: 4 samples, avg is 68.9MB, max is 68.9MB 
INFO Execution took 209.967654ms

**Comment by jirfag** [comment]
hi,
`golangci-lint` just runs `git`. `git` can work from nested directories.
