### ISSUE TITLE
bodyclose ignores body closed in util method

### ISSUE THREAD

**Issue by antonkhabaiev** [golangci/golangci-lint#574]
It seems that `bodyclose` linter doesn't see that response body is being closed in a method below.
version: `golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z`
config file: doesn't exist
go env: `go version go1.12.5 darwin/amd64`
verbose output: `INFO [config_reader] Config search paths: [./ /Users/antonkhabaiev/Go/src/github.com/fubotv/services-user /Users/antonkhabaiev/Go/src/github.com/fubotv /Users/antonkhabaiev/Go/src/github.com /Users/antonkhabaiev/Go/src /Users/antonkhabaiev/Go /Users/antonkhabaiev /Users /] 
INFO [lintersdb] Active 31 linters: [bodyclose deadcode depguard dupl errcheck gochecknoglobals gochecknoinits goconst gocritic gocyclo gofmt goimports gosec gosimple govet ineffassign interfacer lll maligned misspell nakedret prealloc scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck] 
INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused stylecheck] into metalinter megacheck 
INFO [loader] Go packages loading at mode load types and syntax took 2.556094653s 
INFO [loader] SSA repr building timing: packages building 27.066483ms, total 616.302327ms 
app/service/email/email.go:143:32: bodyclose: response body must be closed (bodyclose)
        resp, err := s.client.Call(ctx, req, cb.NewOption("services-user:email-send", nil))
                                      ^
INFO [runner] worker.4 took 1.743389077s with stages: dupl: 1.719996879s, deadcode: 14.015039ms, structcheck: 6.364563ms, nakedret: 2.915996ms, gochecknoinits: 67.073µs, typecheck: 4.472µs 
INFO [runner] worker.6 took 1.753123089s with stages: govet: 1.305390623s, misspell: 447.719874ms 
INFO [runner] worker.7 took 1.763668024s with stages: unparam: 1.558361933s, lll: 136.554098ms, errcheck: 36.61697ms, varcheck: 16.621277ms, unconvert: 11.581157ms, maligned: 3.817857ms, gochecknoglobals: 79.585µs 
INFO [runner] worker.8 took 1.777364297s with stages: bodyclose: 1.320061895s, gosec: 445.873928ms, prealloc: 3.946841ms, scopelint: 3.940909ms, gocyclo: 3.513307ms 
INFO [runner] worker.3 took 1.809848168s with stages: interfacer: 1.533144735s, ineffassign: 272.858986ms, goconst: 3.804893ms, depguard: 19.621µs 
INFO [runner] worker.1 took 1.823684647s with stages: gofmt: 1.555285463s, gocritic: 268.384559ms 
INFO [runner] worker.2 took 2.012742399s with stages: goimports: 2.012728175s 
INFO [runner] worker.5 took 3.5285773s with stages: megacheck: 3.528565302s 
INFO [runner] Workers idle times: #1: 1.704757058s, #2: 1.515724788s, #3: 1.71858937s, #4: 1.784908834s, #6: 1.775379073s, #7: 1.764775154s, #8: 1.751019273s 
INFO [runner/max_same_issues] 2/5 issues with text "bodyclose: response body must be closed" were hidden, use --max-same-issues 
INFO [runner] Issues before processing: 79, after processing: 3 
INFO [runner] processing took 1.070814842s with stages: skip_dirs: 489.765056ms, nolint: 310.184627ms, autogenerated_exclude: 224.663654ms, identifier_marker: 32.809691ms, exclude: 9.363051ms, source_code: 3.308326ms, path_prettifier: 239.56µs, cgo: 193.814µs, filename_unadjuster: 89.951µs, max_per_file_from_linter: 65.807µs, max_from_linter: 38.429µs, max_same_issues: 32.437µs, uniq_by_line: 29.595µs, path_shortener: 14.767µs, diff: 8.45µs, exclude-rules: 4.079µs, skip_files: 3.548µs 
INFO File cache stats: 108 entries of total size 347.4KiB 
INFO Memory: 50 samples, avg is 1293.7MB, max is 3030.7MB 
INFO Execution took 6.836766391s`

**Comment by davidnewhall** [comment]
My code looks like this:
```go
	resp, err := u.Do(req)
	if err != nil {
		return errors.Wrap(err, "authReq.Do(req)")
	}
	defer func() {
		_, _ = io.Copy(ioutil.Discard, resp.Body) // avoid leaking.
		_ = resp.Body.Close()
	}()
```
and I get this:
```
github.com/golift/unifi$ golangci-lint run --enable-all -e G402
unifi.go:49:19: bodyclose: response body must be closed (bodyclose)
	resp, err := u.Do(req)
	                 ^
```

maybe I'm doing it wrong? not sure..
```
$ golangci-lint --version
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z
```

**Comment by jirfag** [comment]
Please make an issue in bodyclose repo

**Comment by davidnewhall** [comment]
Yeah I'm over it. Thanks though.
