### ISSUE TITLE
Unable to install using script from goreleaser.com

### ISSUE THREAD

**Issue by subosito** [golangci/golangci-lint#575]
Installing `golangci-lint` using script from goreleaser.com, failed:

```
•|• curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.17.1 for v1.17.1/darwin/amd64
•/• echo $?
1
```

While using fallback script, it works fine:

```
•|• curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.17.1 for v1.17.1/darwin/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
•|• echo $?
0
•|• ./bin/golangci-lint --version
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z
```

**Comment by ivantedja** [comment]
<img width="1111" alt="Screen Shot 2019-06-13 at 11 05 58 AM" src="https://user-images.githubusercontent.com/1907854/59404259-1b2a9400-8dd0-11e9-9e30-d55f6c7a72d2.png">

Somehow the script from goreleaser doesn't have `BINARY` variable

**Comment by flimzy** [comment]
A temporary work-around, to get your CI pipline working again immediately, is to update your install command:

    curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint sh -s -- -d -b $(go env GOPATH)/bin v1.17.1

Note the addition of the `BINARY=golang-ci` variable after the pipe (`|`) character.

**Comment by iliapolo** [comment]
@flimzy 

> A temporary work-around, to get your CI pipline working again immediately, is to update your install command:
> 
> ```
> curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint sh -s -- -b $(go env GOPATH)/bin v1.17.1
> ```
> 
> Note the addition of the `BINARY=golang-ci` variable after the pipe (`|`) character.

While this does the trick, I wonder if a different approach is better.

I noticed that the [`install.sh`](https://github.com/golangci/golangci-lint/blob/master/install.sh#L352) in github does contain the variable, which means that the script in `goreleaser.com` somehow diverged from the one here.

To avoid these things, and actually use a static version of the script for reproducible builds, I changed the URL to simply point to a specific tag in this repo.

i.e `https://raw.githubusercontent.com/golangci/golangci-lint/v1.16.0/install.sh` 

What do you think?

I'd appreciate one of the maintainers to confirm this is a valid approach, just to make sure I can rely on this tag to be frozen and contain all the necessary installation features as the script in `goreleaser.com` does.

**Comment by pierrre** [comment]
@iliapolo I like this approach.
It would allow reproducible build.
It could be great if goreleaser could support that too.

**Comment by flimzy** [comment]
@iliapolo I'm not the one to comment on your proposal. I offered a simple, temporary workaround. Emphasis on *temporary* and *work-around*.

I leave it to the project maintainers to come up with a better permanent solution.

**Comment by iliapolo** [comment]
@flimzy I know, didn't mean to imply otherwise. Still waiting on one of the maintainers to reply.

**Comment by LarsOL** [comment]
FYI this is fixed from goreleaser

**Comment by subosito** [comment]
Just checked, the issue is fixed, as @LarsOL said:

```
•|• curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.17.1 for v1.17.1/darwin/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
•|• echo $?
0
•|• ./bin/golangci-lint --version
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z
```
