### ISSUE TITLE
Missing support for freebsd/amd64

### ISSUE THREAD

**Issue by amiramix** [golangci/golangci-lint#588]
This target is missing in [install.sh](https://github.com/golangci/golangci-lint/blob/v1.17.1/install.sh#L65) and in [releases](https://github.com/golangci/golangci-lint/releases). golang 1.12 is available on FreeBSD and the tooling is similar to Darwin so it should be easy to add it unless Docker is a strict requirement.

I can do the porting and test on FreeBSD but would need some pointers how to go about adding the target.

**Comment by tpounds** [comment]
@amiramix FreeBSD support was added in https://github.com/golangci/golangci-lint/pull/613 and is not available since v1.18.0.
