### ISSUE TITLE
no error detected if the project is a v2 module with the pre-compiled binaries and Go 1.13beta1

### ISSUE THREAD

**Issue by pierrre** [golangci/golangci-lint#604]
golangci-lint version: 1.17.1
Go version: 1.13beta1

I just noticed that no error are detected in my project if:
- I'm using the pre-build binary
- my project is using module and is a "v2"
- Go version is 1.13beta1

It's working if (select one):
- I'm using the version installed by vscode-go (I guess it's using `go get`)
- my project is using module and is a "v1"
- Go version is 1.12.7

In my "v2 module" projects, my packages import paths contain a "/v2".
That's probably why it's not working anymore.

**Comment by pierrre** [comment]
Currently, my solution is to install golangci-lint with `go get`.

Sadly I can't use the "go module" syntax to select a stable tag version du to #581 / #595 .
I attempted to fix it in #605 .

So I'm now installing the latest version without Go module support.
`GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`
The downside is that it's not necessarily a stable version, and the build is not reproducible.

**Comment by pierrre** [comment]
Actually I have this issue only with Go 1.13beta1, not 1.12.7.

**Comment by pierrre** [comment]
I think that this error is blocking for Go 1.13.
The pre-build binary is broken.

**Comment by pierrre** [comment]
I guess this is fixed now.
v1.18.0 has been released, and I think it's using Go 1.13.

Thank you @jirfag :+1:

**Comment by jirfag** [comment]
hi,
yes, `v1.18.0` is built by `go1.13`

**Comment by pierrre** [comment]
Perfect !
I don't see this issue anymore in my project.
Thank you very much.
