### ISSUE TITLE
Feature: New out-format gometalinter

### ISSUE THREAD

**Issue by ct-23** [golangci/golangci-lint#638]
Hi,
thanks for your awesome work on golangci-lint.

For using golangci-lint in ci/cd pipelines together with our well established Sonarqube, it would be helpful, if golangci-lint could print a gometalinter compatible format.

The gometalinter-format is one of Sonarqubes supported formats when importing external issues. See https://docs.sonarqube.org/latest/analysis/external-issues/

Today I'm using a perl regular expression to reformat golangci's output to the gometalinter format, which sonarqube understands.
`golangci-lint run --deadline=30m --out-format=line-number | perl -pe 's/(?<file>[^:]+):(?<line>\d+):(?<col>\d*): (?<message>.*)\((?<linter>[^\(]*)\)/$+{file}:$+{line}:$+{col}:error:$+{message}($+{linter})/g'`
This is far from optimal, but works. 

I could provide a pull request.
What do you think?

**Comment by ryancurrah** [comment]
Sonarqbue addressed this issue in July they have not updated the documentation to reflect it. Basically use the `checkstyle` out-format and the configuration syntax below for `sonar-scanner`.

```
sonar.go.golangci-lint.reportPaths=golangci-lint-report.xml
```

See: https://github.com/SonarSource/slang/blob/master/sonar-go-plugin/src/main/java/org/sonar/go/externalreport/GolangCILintReportSensor.java

**Comment by jirfag** [comment]
hi, if you can use checkstyle output - it's not needed

**Comment by tpounds** [comment]
A similar request was made in #228. As @jirfag mentioned several additional output formats have been added that should fulfill the requirements of this request.

* Checkstyle (#95)
* JUnit (#557)
* Code Climate (#386)
