### ISSUE TITLE
Not parsing "invisible" packages when linting an entire package tree

### ISSUE THREAD

**Issue by Helcaraxan** [golangci/golangci-lint#645]
System / version information
1. Version of golangci-lint: `v1.17.1`
2. Config file: none
3. Go environment: N.A.
4. Verbose output of running: N.A

I have recently noticed that when running `golangci-lint run` over a sub-tree of packages, any `internal` sub-directories are skipped.

```text
/foo/project $ golangci run
<no lint errors shown that are part of /foo/project/internal/... packages>

/foo/project $ golangci run ./...
<no lint errors shown that are part of /foo/project/internal/... packages>

/foo/project $ golangci run ./internal/...
<lint errors shown that are part of /foo/project/internal/... packages>

/foo/project/internal $ golangci-lint run
<lint errors shown that are part of /foo/project/internal/... packages>
```

My best guess is that the way how package listing is done before the result is being fed to the linters uses some public Go functionality that does not list `internal/` packages when these are not importable (i.e you are not in their sub-tree).

**Comment by nezorflame** [comment]
This is a pretty serious issue. Would like to hear more about this and when it can be fixed.

**Comment by oxdef** [comment]
+1 It can lead, e.g. to miss security issues in these directories

**Comment by domgreen** [comment]
+1 would be great to see a fix for this issue.

**Comment by Helcaraxan** [comment]
I've done some extra research on this topic given this is actually a wider, more fundamental, problem then it initially appears.

As suspected the core of the issue can be subscribed to the use of `golang.org/x/tools/go/packages` to load the files to lint. This does not necessarily mean it is a bad thing that we use it, more that it's use implies some limitations of which this issue is one of the outcomes.

The listing of the files targeted by a given invocation of `golangci-lint run` are determined via the `ContextLoader` struct defined in [this file](https://github.com/golangci/golangci-lint/blob/fd997edeeb4ac277823750d746394d80f03d7ec1/pkg/lint/load.go). More specifically the path arguments that are passed to `go/packages` are determined [here](https://github.com/golangci/golangci-lint/blob/fd997edeeb4ac277823750d746394d80f03d7ec1/pkg/lint/load.go#L76-L93), meaning that the paths specified via the command-line are used mostly "as is" without taking into account the specific cases of `internal` subtrees... nor the presence of nested modules.

As a result if we had a hypothetical repo with the following structure:
```text
project
 |- cmd
    |- go.mod
    |- main.go
 |- .golangci.yaml
```
running `golangci-lint run ./cmd/main.go` from the root would result in an error being thrown for lack of the root being inside a Go module.

Similarly:
```text
project
 |- cmd
    |- go.mod
    |- main.go
 |- go.mod
 |- lib.go
 |- .golangci.yaml
```
would also fail with `golangci-lint run ./cmd/main.go`, not because of the lack of Go module but because the targeted file is not part of the same module as from which the file is trying to be loaded.

There is one potential solution here but I have not yet thought through / analysed potential unintended consequences of each:

> We can try to load files while having the current directory set to the path at which they reside (this would ensure the file is always "visible" to `go/packages` regardless of `internal` subtrees or nested modules. These does still leave the edge-case where a targeted file is excluded by the current build flags (like trying to load `pkg_windows.go` or a file starting with `// -build linux` on a Linux machine), but that issue already exist today AFAIK, hence the partial fix would be a step forward anyway.

**Comment by Helcaraxan** [comment]
Further analysis actually showed that the `internal` issue reported here is actually no longer valid and I can no longer reproduce it. The "nested module" issue is an entirely different one.
