### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by lopezator** [golangci/golangci-lint#647]
This been quiet for over a month (the last commit is from 14th of July at time of writing):

https://github.com/golangci/golangci-lint/commit/d2b1eea2c6171a1a1141a448a745335ce2e928a1

Issues & PR's seem to be stacking.

Is @jirfag on a long vacation maybe? :)

Any news?

**Comment by pierrre** [comment]
Are there other maintainers ?

**Comment by lopezator** [comment]
AFAIK there aren't, and looking to the https://github.com/golangci/golangci-lint/graphs/contributors dosn't look there is another major contributor other than @jirfag

**Comment by ernado** [comment]
No worries, **jirfag** is on vacation and will be available in couple of weeks.

**Comment by Helcaraxan** [comment]
Thank you very much for the update @ernado. It is much appreciated. 🙂 

Given that there are a few relatively critical issues for which PRs have been opened is there any way how another maintainer / contributor could have a look, merge the fixes and do a `1.17.2` patch release?

I am mostly thinking about the following PRs:
- #625 to unblock / fix CI for other PRs.
- #605 (which overlaps with and replaces #629, #614 and #583).

and the patch release would also include #594 and #610 that have already been merged.

**Comment by pierrre** [comment]
I think that #604 is blocking for Go 1.13.
But if we merge #605, I will be able to install from source, with a tagged version.

**Comment by laverya** [comment]
I think a lot more people are going to start hitting #605 soon, now that Go 1.13 has been officially released. Is there any chance that things could be expedited @ernado?

**Comment by jirfag** [comment]
Guys, I'm so sorry that all processed stopped because of me being the sole maintainer :( I was on a vacation (thank you @ernado).

To fix it, I'm [looking for co-maintainers](https://github.com/golangci/golangci-lint/issues/669). Also, I've taken another vacation for the next 3 days to merge all accumulated pull requests, I hope I have time to merge them all.

**Comment by lopezator** [comment]
Now that @jirfag is back and opened the co-mantainers issue. I'll close this. Thanks for the feedback.
