### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by LucaPaterlini** [golangci/golangci-lint#648]
hello,

I have executed this command as explained in the readme.

go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

got no error but then 

golangci-lint: command not found

I ma guessing why I do not have the binary ready installed in the bin folder and ready accessible as command line

**Comment by lopezator** [comment]
do you have GO111MODULE set to on/auto?

try this for non-modules install.

`GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`

or a modules installation.

**Comment by LucaPaterlini** [comment]
hello,
I found out the issue, 
the go/bin folder was not in the path

https://askubuntu.com/questions/500775/permanent-path-variable

@lopezator thanks anyway for your response.

**Comment by sajir-dev** [comment]
https://golangci-lint.run/usage/install/

Installation says go get is not guaranteed to work, please follow other methods
