### ISSUE TITLE
--deadline is a misnomer

### ISSUE THREAD

**Issue by variadico** [golangci/golangci-lint#655]
`--deadline` should be called `--timeout`. A timeout is a relative time like what we're supposed to pass to the `--deadline` flag. An actual deadline is an absolute time.

> Timeout: finish in 10 seconds.
> Deadline: finish at 7:15:35PM.

https://news.ycombinator.com/item?id=9948203
https://golang.org/pkg/context/#WithDeadline

This was confusing to me when I was reading the docs.

**Comment by titusjaka** [comment]
I would like to grab this one :)
