### ISSUE TITLE
Looking for co-maintainers

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#669]
Hi everyone and thank you again for using `golangci-lint`. Thank you to [all contributors](https://github.com/golangci/golangci-lint/graphs/contributors) of `golangci-lint` (65 contributors!).

My vacation showed to me that I can't be the sole maintainer of this project. It's was my fault that all processes [stopped on me](https://github.com/golangci/golangci-lint/issues/647) and a lot of users were waiting for me during my vacation.

The project will be more stable and fast-iterating if we will have a few maintainers, not only me. Also, it will be helpful if there will be a co-maintainer in another timezone: my timezone is UTC+3 (Moscow) and it's difficult for me to quickly chat with users from USA (e.g. UTC-7 timezone).

So, I'm looking for co-maintainers. It's my first experience looking for co-maintainers for an open-source project and I'm not sure how to choose developers for this role, so any help is appreciated.

I won't be mentioning all contributors here just not to spam too many people, but I will mention all contributors having >= 2 commits here: @a8m @amenzhinsky @aneeshusa @be-b10g @benpaxton-hf @beono @cezarsa @diegs @gsora @jfrabaute @vovapi @lopezator @tpounds @zchee @ernado @LukeShu @barthr @dixonwille.

Also, I think it may be interesting for @alecthomas and @dominikh.

Anyway, even if you don't have contributions here and you would like to be a co-maintainer - please, don't afraid to suggest yourself in comments here.

Please, if you would like to be a co-maintainer - comment about it here. Thank you!

**Comment by ernado** [comment]
Hey @jirfag, welcome back from vacation :tada: 

First of all, I want to express appreciation for your hard work, golangci is amazing!

I would gladly help with maintaining, with focus on bug fixes (for now).

**Comment by tpounds** [comment]
@jirfag I'd be willing to help out in some capacity. Do you have any contributor guidelines/patch acceptance criteria you are using and would want additional maintainers to use?

**Comment by matoous** [comment]
I could help out too if needed/wanted (UTC+1 though...)

**Comment by lopezator** [comment]
Hello @jirfag and welcome back! As the folks above already said, thank you for your hard work here.

Although I am not sure if I could commit to a fixed time commitment for week or something like that I would be happy to help also.

I'm based on Spain though, UTC+2.

**Comment by sladyn98** [comment]
@jirfag Although I have not contributed to this project, but I do have some golang experience, I would like to help if possible.Thanks.

**Comment by jirfag** [comment]
thank you!
@ernado @tpounds @matoous @lopezator I've made you maintainers and added to a private slack channel (except @matoous - can't find you on slack, please send your login on https://gophers.slack.com)

**Comment by matoous** [comment]
Thanks! Try again please with my full name. I have not been member, so that's why you didn't find me.
