### ISSUE TITLE
Another configuration of linters for tests

### ISSUE THREAD

**Issue by jakubtomany** [golangci/golangci-lint#67]
Some linters have no sense for tests so I would like to be able to set which linters run on tests (or on specific files)

**Comment by jakubtomany** [comment]
eg. errcheck have no sense in most of unit tests

I didn't notice the `—test=false` option - it may help

**Comment by rekby** [comment]
May be some/full linter disable for file level - for example in comment before package line

**Comment by jirfag** [comment]
1. if you use `errcheck` I don't understand why it can't be ignored in tests: errors should be checked even in tests, and especially in tests
2. file level disabling looks too bad for users of golangci-lint: one need to add such comments on each test file.

**Comment by jirfag** [comment]
reopen if you will find another ideas how to do it

**Comment by jirfag** [comment]
we've implemented `exclude-rules` config option for it
