### ISSUE TITLE
please surpport ignore someOne fuction's igored error

### ISSUE THREAD

**Issue by ZedHao** [golangci/golangci-lint#678]
Thank you for creating the issue!

Please include the following information:
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
2. Config file: `cat .golangci.yml`
3. Go environment: `go version && go env`
4. Verbose output of running: `golangci-lint run -v`

**Comment by ZedHao** [comment]
321:136: (*Service).packCheckInRelation - result 1 (error) is always nil (unparam)
forexple： i  think this fuction's check can be ignore,  can you surpport?

**Comment by Depado** [comment]
Please add the following comment on the same line as your function declaration:

```
func (*Service) packCheckInRelation(...) error { // nolint: unparam
}
```

See [this section of the README file](https://github.com/golangci/golangci-lint#nolint)

**Comment by jirfag** [comment]
@Depado thank you, closing
