### ISSUE TITLE
Docker image with Go 1.13

### ISSUE THREAD

**Issue by troyronda** [golangci/golangci-lint#682]
Version of golangci-lint: 1.18

The docker image for golangci-lint is on Go 1.12 (https://github.com/golangci/golangci-lint/blob/cad10b2a358dfa7d2f3cead14ab0b9b4157bdc74/Dockerfile#L1)

This can result in some errors when running this docker image against code developed for Go 1.13. In particular:
`Is not declared by package errors (typecheck)`

**Comment by tpounds** [comment]
@jirfag, @troyronda This is fixed by 6ec8ff2271fd2dda310fb9812fa6c1e907bca6d0 but didn't auto-close since I accidentally annotated the commit with the discarded pull request #683 instead of this issue.

**Comment by troyronda** [comment]
Thanks!
