### ISSUE TITLE
Support "gopls check" linter

### ISSUE THREAD

**Issue by fho** [golangci/golangci-lint#686]
Add support for running `gopls check` via golangci-lint.

`gopls check` can find issues that cause compilation problems without having to compile the code.

**Comment by silverwind** [comment]
This would be very useful. Currently I'm running `gopls check` in addition to `golangci-lint` and it discovers a number of issues that no existing linter can find like impossible conditions and such.

**Comment by silverwind** [comment]
@ldez any chance for re-open?

Currently I'm using [this script](https://github.com/go-gitea/gitea/blob/main/tools/lint-go-gopls.sh) to lint with gopls. Would appreciate having `gopls` as a full-fledged linter.

**Comment by ngotchac** [comment]
@ldez Any reason why this go declined?

**Comment by ldez** [comment]
gopls is a binary not designed to be used as a library: all the analyzers are inside an internal package and those analyzers use internal packages outside of the gopls module (yes it is possible in some cases).
We can easily say that it is an intentional design to strongly limit the usage of those analyzers outside gopls.

So for now, we will not try to overcome those limitations even if I have an idea to "fix" the problem.

rule n°1 of open-source: no is temporary, yes is forever.

**Comment by ngotchac** [comment]
Gotcha, thanks for the prompt response! Too bad they made it that way..

**Comment by silverwind** [comment]
> all the analyzers are inside an internal package and those analyzers use internal packages outside of the gopls module

Even though the analyzers are folder called "internal", they could be imported normally. But I guess gopls makes no stability guarantees regarding these pseudo-public modules. Maybe a issue should be raised so that gopls exposes a documented public API for linters.

**Comment by ngotchac** [comment]
> Even though the analyzers are in folder called "internal", they can be imported normally and also be ran as a CLI, for example https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

They cannot be imported, that's why they are in `internal`: https://pkg.go.dev/cmd/go#hdr-Internal_Directories ; I guess they want to not have a stable API so they can change things easily.

**Comment by adonovan** [comment]
I have no objection to publishing most of the analyzers that are currently internal to gopls in x/tools/go/analysis/passes. Some of them should even be added to cmd/vet, though that requires extra diligence.  A few of them are currently tied to gopls internals, either because they compute edits lazily, or because they make assumptions that they always analyze the "widest" package (i.e. the test) for a given package path.

**Comment by leonklingele** [comment]
@adonovan that'd be awesome! Can I somehow assist here?

**Comment by ldez** [comment]
https://github.com/golang/go/issues/75266

**Comment by adonovan** [comment]
See also https://github.com/golang/go/issues/75267.  (There are still a number of others that there are no immediate plans to publish; file an issue if there are particular ones you need.)

**Comment by silverwind** [comment]
Now that we have a `modernize` linter, I wonder if a `gopls check` linter is also planned. It would be a great to have these checks available in `golangci-lint`.

**Comment by ldez** [comment]
Not planned.

**Comment by silverwind** [comment]
These should be are all the analyzers `gopls check` provides: https://go.dev/gopls/analyzers. Many of these seem to be covered by the `staticcheck` suite, but I think some of them are currently uncovered by golangci-lint, meaning editors using gopls will highlight issues that golangci-lint won't catch, right?

Notable, I find this check to be valuable: https://go.dev/gopls/analyzers#nilness-check-for-redundant-or-impossible-nil-comparisons.

**Comment by ldez** [comment]
gopls imports staticcheck; most of those rules are from [staticcheck](https://golangci-lint.run/docs/linters/configuration/#staticcheck).

The other are mainly related to [govet](https://golangci-lint.run/docs/linters/configuration/#govet) (like nilness) or [modernize](https://golangci-lint.run/docs/linters/configuration/#modernize).

**Comment by silverwind** [comment]
Thanks, I will probably go through all those rules and see if they are already in `govet` or elsewhere, and if they are, then yes it's redundant to add `gopls check` as a separate linter.

**Comment by AlekSi** [comment]
I found this issue when I noticed gopls complained with https://go.dev/gopls/analyzers#recursiveiter-check-for-inefficient-recursive-iterators. Hopefully, it will be moved out of the internal one day.
