### ISSUE TITLE
Config keys with dots in them are parsed incorrectly

### ISSUE THREAD

**Issue by codyleyhan** [golangci/golangci-lint#692]
_golangci-lint: v1.18.0_

I made a merged PR that added the ability to have users provide error messages for depguard, I had made and tested a similar PR for depguard, but did not do the same checks in this repo.  I made a trivial use case of `log` in the test at https://github.com/golangci/golangci-lint/blob/master/test/testdata/depguard.go#L7.

After upgrading to this version, I noticed that when there are "." in a key in the config, the config is parsing incorrectly.  This provides a bad experience as something like `github.com/foo/bar` will fail to parse. This was recently corrected in an unreleased PR in viper https://github.com/spf13/viper/pull/673  that I believe will fix this issue when it is released.  

I plan to make a PR to fix this as soon as a new release of viper is cut so that this bug will be fixed.

**Comment by sagikazarmark** [comment]
Please note that the change in Viper introduced a regression, so it will either be reverted or fixed (if that's possible at all).
