### ISSUE TITLE
ppc64le platform support?

### ISSUE THREAD

**Issue by wzhanw** [golangci/golangci-lint#700]
When I running install.sh on ppc64le platform, I got below error message:
golangci/golangci-lint crit platform linux/ppc64le is not supported.  Make sure this script is up-to-date and file request at https://github.com/golangci/golangci-lint/issues/new

There are a lot of customers of IBM using ppc64le platforms,  we may lost a lot of customers if we don't support that platform.

**Comment by jirfag** [comment]
hi, thank you, pull requests to https://github.com/golangci/golangci-lint/blob/master/.goreleaser.yml are welcome

**Comment by jirfag** [comment]
a next release will be with `ppc64le` platform
