### ISSUE TITLE
How to not check third party libraries?

### ISSUE THREAD

**Issue by bweston92** [golangci/golangci-lint#702]
I just want to check my code and not my third party code (in an environment where they're not possible to obtain) is there a way to do this?

So currently I get the following error:

```
Running error: context loading failed: package github.com/TV4/logrus-stackdriver-formatter: no go files to analyze 
```

**Comment by jirfag** [comment]
Hi,
you can run only linters that don't require type information (like `gocyclo`). But at least half of linters does need a type information and it can't be obtained without source code of third party libraries

**Comment by bweston92** [comment]
Oh I was using just “golint” which I assumed was just basic linting, will
check with just gocyclo when back at desk.

**Comment by bweston92** [comment]
Ok still having issues where it is trying to find packages, do you know of an alternative that isn't this strict? The problem with the error below is the code is generated at build time.

```
ERRO Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled=true -test=true -export=false -deps=false -find=false -- ./...]: exit status 1: build lwebco.de/cosmic/api/identities/cmd/identities-api-server: cannot load lwebco.de/cosmic/spec/identities/v1: cannot find module providing package lwebco.de/cosmic/spec/identities/v1
```
