### ISSUE TITLE
Junit report displayed very silly in the Bitbucket Pipelines Test reporting 

### ISSUE THREAD

**Issue by Trane9991** [golangci/golangci-lint#748]
Hello, I'm trying to display linter results in the [Bitbucket Pipelines Test reporting](https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html) and it looks pretty useless with the current junit-report format.

Found following problems there:
- Bitbucket pipelines skip the report if `testsuite` doesn't mention the number of tests and failures, for example: `<testsuite tests="2" failures="2" time="0" name="name">`
- Currently provided the format of testsuite and testcase displayed by BitBucket pipelines pretty silly:
       <img width="680" alt="Screen Shot 2019-09-25 at 4 59 26 PM" src="https://user-images.githubusercontent.com/9948629/65607891-f7bdda80-dfb5-11e9-8c66-4aa66ffe27e9.png">
      This is because Bitbucket trying to split the `classname` by the `.` as separator and join it with `name` property 🤷‍♂, maybe that makes sense for Java classes, however, this is completely useless for Go.

In order to fix the Test Reporting appearance in Bitbucket the junit report format has to be modified not in the best way :(
I understand that this is more problem of Bitbucket, not `golangci-lint` but I doubt they gonna change it (or if they will it could take years).

I can create a PR with a new format `bitbucket-test-report`, which will be same as `junit`, but optimized for better rendering by Butbucket. Will you consider it a solution? If so, I will get to work :) 

Thanks

Version: `v1.19.0`
Config file: `N/A`
Go Version: `v1.13.0`

**Comment by jirfag** [comment]
Hi, I do not agree with the new format `bitbucket-test-report`. You can always use `reviewdog`, `golangci.com` or similar.

**Comment by Trane9991** [comment]
@jirfag as far as I know, `golangci.com` doesn't have bitbucket integration 🤷‍♀

However, I didn't know about `reviewdog`. Implementing `reviewdog` integration with Bitbucket might be a better idea. Do you agree with that? :) 

Thanks!

**Comment by Trane9991** [comment]
I even see the issue for that https://github.com/reviewdog/reviewdog/issues/113, thanks.
