### ISSUE TITLE
gocyclo repository seems to be abandoned 

### ISSUE THREAD

**Issue by trajber** [golangci/golangci-lint#753]
The gocyclo upstream seems to abandoned a long time ago. There are open issues and PRs that never get any feedback.
What do you think about create a maintained fork of it ?

**Comment by tpounds** [comment]
@trajber There is already a project fork at https://github.com/golangci/gocyclo. Are you asking to have those prs merged in there?

**Comment by OrBaruk** [comment]
Hi, I work with @trajber and the what we are interested in getting merged is the PR https://github.com/fzipp/gocyclo/pull/27 for the issue https://github.com/fzipp/gocyclo/issues/19 

We weren't aware of the the fork used by golangci-lint if there is interest I can open this PR on https://github.com/golangci/gocyclo

**Comment by tpounds** [comment]
@trajber, @OrBaruk That would be fantastic! The first preference is always to upstream changes as much as possible but when that isn't possible the changes can be forked by the project or included directly which is the case for some linters like `dogsled`, `lll`, `nakedret`, etc. If you take a look at the [go.mod](https://github.com/golangci/golangci-lint/blob/master/go.mod) file you can see which linters have been forked to include additions.

**Comment by OrBaruk** [comment]
@tpounds Created https://github.com/golangci/gocyclo/pull/3
