### ISSUE TITLE
Support partitioning for large repositories

### ISSUE THREAD

**Issue by alecthomas** [golangci/golangci-lint#76]
I get this on my work repo:

```
$ golangci-lint run
WARN[0000] Gofmt: got too much paths (2072), analyze first 1000
```

gometalinter supports arbitrarily large repos by partitioning linter invocations into manageable sizes.

**Comment by jirfag** [comment]
hi, thank you, it was a useless code,
fixed it in [this](https://github.com/golangci/golangci-lint/pull/81/commits/2b587b63d6ae9c86f68fbcf27471a335469adfc5) commit, it's in master

**Comment by alecthomas** [comment]
Thanks!
