### ISSUE TITLE
feature: configurable version

### ISSUE THREAD

**Issue by carnott-snap** [golangci/golangci-lint#780]
Currently `.golangci.yml` supports `service.golangci-lint-version` a field that allows one to specify the version of golangci that should be run against their repo using the golangci tool. This functionality would also be useful client side via the binary, either using the same field, or by deprecating the old field and creating a new top level section:
```yaml
version: 1.17.x
```

**Comment by jirfag** [comment]
Hi,
1. why it's better than explicitly change the version where you install binary release?
2. It's the too non-standard and non-obvious solution

**Comment by carnott-snap** [comment]
> 1. why it's better than explicitly change the version where you install binary release?

Different repos have different version requirements, so I would need to reinstall different binaries per repo.

> 2. It's the too non-standard and non-obvious solution

Would it be easier to make  linter groups that work in the enable/disable blocks:
```yaml
linters:
  enable:
    - 1.17.x
```

**Comment by jirfag** [comment]
sorry, I think there will be more harm than good because it's too inconvenient and rarely needed.
