### ISSUE TITLE
cache: too much permissions

### ISSUE THREAD

**Issue by jimen0** [golangci/golangci-lint#782]
1. Version of golangci-lint: `golangci-lint --version`: current `HEAD`: `fd997edeeb4ac277823750d746394d80f03d7ec1`
2. Config file: `cat .golangci.yml`: N/A
3. Go environment: `go version && go env`: N/A
4. Verbose output of running: `golangci-lint run -v`: N/A

While reading `golangci-lint` source code I found that the cache initialization method creates the directory using too many permissions: https://github.com/golangci/golangci-lint/blob/6a979fb40d44a5099e8fd8d10c81a1799f4162b3/internal/cache/default.go#L33-L50

Are world executable and world-writable really needed? If not, I'd be open to creating a PR.

Thanks!

**Comment by jirfag** [comment]
Hi, good points, thank you
