### ISSUE TITLE
go 1.13 DecodeRuneInString not declared by package utf8 (typecheck)

### ISSUE THREAD

**Issue by LucaPaterlini** [golangci/golangci-lint#785]
env linux go 1.13 on elementary os(based on ubuntu 18.4)

> INFO [config_reader] Config search paths: [./ /home/lucasportable/Documents/STUDYFUN/go_study/refresh/go/tournament /home/lucasportable/Documents/STUDYFUN/go_study/refresh/go /home/lucasportable/Documents/STUDYFUN/go_study/refresh /home/lucasportable/Documents/STUDYFUN/go_study /home/lucasportable/Documents/STUDYFUN /home/lucasportable/Documents /home/lucasportable /home /] 
> INFO [lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck] 
> INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused] into metalinter megacheck 
> INFO [loader] Go packages loading at mode load types and syntax took 919.148412ms 
> INFO [loader] SSA repr building timing: packages building 4.648663ms, total 35.38491ms 
> INFO [loader] Packages that do not compile: [_/home/lucasportable/Documents/STUDYFUN/go_study/refresh/go/tournament [_/home/lucasportable/Documents/STUDYFUN/go_study/refresh/go/tournament.test]] 
> INFO [runner] worker.2 took 1.411µs               
> INFO [runner] worker.3 took 1.88µs                
> INFO [runner] worker.8 took 1.078µs               
> INFO [runner] worker.4 took 514ns                 
> INFO [runner] worker.7 took 55.764µs with stages: errcheck: 52.057µs 
> INFO [runner] worker.5 took 527ns                 
> INFO [runner] worker.6 took 516.861µs with stages: typecheck: 493.452µs, ineffassign: 8.953µs, deadcode: 1.961µs, structcheck: 1.595µs, varcheck: 1.358µs 
> INFO [runner] worker.1 took 5.182933ms with stages: govet: 5.168508ms, megacheck: 10.69µs 
> INFO [runner] Workers idle times: #2: 5.072956ms, #3: 5.068035ms, #4: 5.033096ms, #5: 5.010808ms, #6: 4.633811ms, #7: 5.025505ms, #8: 5.052614ms 
> INFO [runner] Issues before processing: 101, after processing: 1 
> tournament.go:1: /usr/lib/go-1.13/src/strconv/quote.go:405:12: ValidString not declared by package utf8 (typecheck)
> package tournament
> INFO [runner] processing took 7.788448ms with stages: identifier_marker: 3.601064ms, exclude: 3.482736ms, skip_dirs: 408.217µs, path_prettifier: 122.391µs, cgo: 32.68µs, source_code: 30.29µs, nolint: 30.006µs, autogenerated_exclude: 23.878µs, uniq_by_line: 20.011µs, filename_unadjuster: 19.669µs, max_same_issues: 13.739µs, path_shortener: 1.304µs, max_per_file_from_linter: 988ns, max_from_linter: 615ns, diff: 424ns, exclude-rules: 241ns, skip_files: 195ns 
> INFO File cache stats: 1 entries of total size 1.8KiB 
> INFO Memory: 11 samples, avg is 130.5MB, max is 203.7MB 
> INFO Execution took 994.017641ms

**Comment by jirfag** [comment]
You've ignored issue template, we can't help, sorry
