### ISSUE TITLE
rb

### ISSUE THREAD

**Issue by elordahl** [golangci/golangci-lint#833]
Thank you for creating the issue!

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
# paste output here
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
# paste output here
```

</details>

**Comment by jirfag** [comment]
is it testing? =)
