### ISSUE TITLE
multirepo can share the same configuration file?

### ISSUE THREAD

**Issue by adibrastegarnia** [golangci/golangci-lint#836]
Hi,

What is the best approach to use golangci-lint for multirepo projects to avoid duplicating config file in each repo? Is there any mechanism in github integration that we can define a config file for all of the repos?

**Comment by adibrastegarnia** [comment]
Any ideas about this

**Comment by tpounds** [comment]
@adibrastegarnia You can share a config file across multiple repos by specifying `--config` flag that points to a file in a common location.

Per the README:
```
  -c, --config PATH                    Read config from file path PATH
```
