### ISSUE TITLE
The "latest" release points at 1.20.1 rather than newer 1.21

### ISSUE THREAD

**Issue by dnwe** [golangci/golangci-lint#838]
- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:11:27Z
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m
linters:
  # enable some additional (non-default) linters
  enable:
    - gofmt
    - gosec
    - govet
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - whitespace
issues:
  exclude-rules:
    # exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
  # maximum count of issues with the same text. set to 0 to disable. default is 3.
  max-same-issues: 0

```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
go version go1.13 darwin/amd64
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
N/A
```

</details>

--

In our builds we run a specific tagged version of golangci-lint per repository build for reproducability. Whilst writing some internal automation to submit PRs that test bumping golangci-lint up to the latest release version I noticed that the "latest" release tag is currently pointing at 1.20.1 rather than 1.21 as both had the same release date. I just wanted to confirm if this was an explicit choice on your side, or whether it was accidental that it wasn't pointing at the most recent?

**Comment by zx8** [comment]
The Homebrew tap also points to 1.20.1 – https://github.com/golangci/homebrew-tap/blob/9a3cca19958509f0e6165cba298ec7a99410f09e/Formula/golangci-lint.rb#L5

**Comment by alex-slynko** [comment]
Additionally, the version that is consumed by golangci.com is also 1.20.1. There is no easy way to automatically bump to the latest version.

**Comment by dnwe** [comment]
@jirfag any thoughts? it would be good to get this fixed

**Comment by tpounds** [comment]
@dnwe, @zx8, @alex-slynko A new release [v1.22.0](https://github.com/golangci/golangci-lint/releases/tag/v1.22.0) was just published which should fix this issue. Please give that a try and report back if you are still seeing issues.

see:
https://github.com/golangci/golangci-lint/releases/tag/v1.22.0
https://github.com/golangci/homebrew-tap/commit/f3ff010a4bd0f794a8e276057404608e5c010863
