### ISSUE TITLE
Stylecheck doesn't ignore ignored files

### ISSUE THREAD

**Issue by ferhatelmas** [golangci/golangci-lint#846]
Method receiver naming convention rule from `stylecheck` still consider ignored files.

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version 1.21.0 built from 645e794 on 2019-10-15T18:16:56Z
```

</details>

<details><summary>Config file</summary>

https://github.com/GetStream/stream-chat-go/blob/master/.golangci.yml

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/ferhat/go/bin"
GOCACHE="/home/ferhat/.cache/go-build"
GOENV="/home/ferhat/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ferhat/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ferhat/.gimme/versions/go1.13.3.linux.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ferhat/.gimme/versions/go1.13.3.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ferhat/Stream/stream-chat-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build186360300=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
device.go:43:18: ST1016: methods on the same type should have the same receiver name (seen 45x "c", 4x "v") (stylecheck)
func (c *Client) AddDevice(device *Device) error {
                 ^
channel.go:140:20: ST1016: methods on the same type should have the same receiver name (seen 27x "ch", 4x "v") (stylecheck)
func (ch *Channel) AddMembers(userIDs ...string) error {
```

</details>

**Comment by to6ka** [comment]
sorry, if you are talking about *_easyjon.go,
stylecheck should ignore all generated files now
and this was fixed here
https://github.com/dominikh/go-tools/commit/27a660a4b58b40c032f1dd332053c0e4c537496c

it's just needed to update dependency in golangci-lint

**Comment by jirfag** [comment]
hi,
what do you mean by "ignored files"? Are you talking about auto-generated files?

**Comment by ferhatelmas** [comment]
`ignored files`: any files should be ignored according to the config.
