### ISSUE TITLE
Skipping maligned check on a struct

### ISSUE THREAD

**Issue by BentCoder** [golangci/golangci-lint#860]
Hi,

I am wondering if I can explicitly skip running `maligned` check on any given struct rather than globally checking either all or none?

Regards

**This is how I wish to return JSON response**

```json
{
   "id": 1,
   "name": "hello",
   "is_active": true,
   "created_at": "2019-01-01"
}
```
```go
struct{
	ID       	uint16
	Name     	string
	IsActive 	bool
	CreatedAt	string
}
```

**However, it is not possible because struct is not maligned and I have to malign it and the response looks odd.**

```go
struct{
	Name     	string
	CreatedAt	string
	ID       	uint16
	IsActive 	bool
}
```

```json
{
   "name": "hello",
   "created_at": "2019-01-01",
   "id": 1,
   "is_active": true
}
```

**Some annotation solution like this, maybe!**

```go
// @skip: maligned
struct{
	ID       	uint16
	Name     	string
	IsActive 	bool
	CreatedAt	string
}
```

**Comment by vearutop** [comment]
@BentCoder you can use `// nolint` suppressor:
```go
// nolint: maligned
struct{
	ID       	uint16
	Name     	string
	IsActive 	bool
	CreatedAt	string
}
```
