### ISSUE TITLE
zsh completion

### ISSUE THREAD

**Issue by Sherlock-Holo** [golangci/golangci-lint#862]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>
golangci-lint has version 1.21.0 built from 645e794 on 2019-10-17T10:33:40Z

</details>

<details><summary>Config file</summary>
no config file

</details>

<details><summary>Go environment</summary>

> go version go1.13.4 linux/amd64
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/sherlock/.cache/go-build"
> GOENV="/home/sherlock/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/sherlock/go"
> GOPRIVATE=""
> GOPROXY="https://goproxy.cn,direct"
> GOROOT="/usr/lib/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD="/tmp/build/coredns/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build017096446=/tmp/go-build -gno-record-gcc-switches"

</details>

<details><summary>Verbose output of running</summary>
nothing about it

</details>

my zsh version is 5.7.1, and enable bash-completion for zsh, but `golangci-lint completaion bash` cause a problem

> /proc/self/fd/12:type:894: bad option: -t

If you enable cobra zsh completion, zsh users will be happy

**Comment by tpounds** [comment]
@Sherlock-Holo This should now be supported in [v1.22.1](https://github.com/golangci/golangci-lint/releases/tag/v1.22.1).
