### ISSUE TITLE
add erris linter

### ISSUE THREAD

**Issue by arnottcr** [golangci/golangci-lint#872]
Since this is unlikely to be added to `vet`, it would be nice to add the `github.com/romanyx/erris` linter; happy to assist.

**Comment by romanyx** [comment]
It will be awesome to have this tool integrated, I volunteer to help too.

**Comment by arnottcr** [comment]
slick, it looks like err13 is a superset of erris, happy to use the more inclusive of the two

**Comment by arnottcr** [comment]
closing in favour of err13
