### ISSUE TITLE
Feature request: Allow concurrent invocations of golangci-lint on separate codebases

### ISSUE THREAD

**Issue by robertlamarre** [golangci/golangci-lint#879]
Hello,

Pull https://github.com/golangci/golangci-lint/pull/812 addressed issue https://github.com/golangci/golangci-lint/issues/108, preventing multiple invocations of golangci-lint in parallel. However, we would like to be able to concurrently run multiple instances of golangci-lint validating separate applications. Is there any reason that this couldn't be done by this tool, perhaps by parameterizing the lock file used by the source tree being linted?

Thanks!

**Comment by ernado** [comment]
Current workaround is to set `GOLANGCI_LINT_CACHE` (which is path to cache dir) for each application.

**Comment by 4m3ndy** [comment]
> Current workaround is to set `GOLANGCI_LINT_CACHE` (which is path to cache dir) for each application.

Unfortunately this workaround didn't work for us, changing `$TMPDIR` for each application did the trick

`cd $APP_PATH && env -i PATH="$PATH" TMPDIR="$PWD/tmp" golangci-lint -v run ./...`

**Comment by SteelPhase** [comment]
I'm running into this as well, and it would appear that `GOLANGCI_LINT_CACHE` does not bypass the lock file check to allow multiple instances

**Comment by jirfag** [comment]
Hi,
we've implemented the `--allow-parallel-runners` option in #1070. Cache in one dir should work for multiple runners but I'm not 100% sure, we don't have specific test cases for that.
