### ISSUE TITLE
Gitlab CI  ERROR

### ISSUE THREAD

**Issue by zuotw32** [golangci/golangci-lint#884]
Thank you for creating the issue!

- [x]  Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x]   Yes, I've searched similar issues on GitHub and didn't find any.
- [x]   Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
# $ golangci-lint --version
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:12:01Z
```

</details>

<details><summary>Using Default</summary>

```bash
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
$ golangci-lint --version
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:12:01Z
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/project/repo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build005188697=/tmp/go-build -gno-record-gcc-switches"```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
# paste output here
```

</details>
level=error msg="Running error: context loading failed: failed to load program with go/packages: could not determine GOARCH and Go compiler"

**Comment by zaynetro** [comment]
For me upgrading to v1.22.2 resolved this issue.

**Comment by Dominik-K** [comment]
@zuotw32: What's the output when adding the environment variables `GL_DEBUG=linters_output GOPACKAGESPRINTGOLISTERRORS=1`?

**Comment by cstevandy** [comment]
I got a similar issue. I have .golang-ci.yaml with run setting modules-download-mode: vendor, but when I ran it, the golangci-lint still tried to download some dependencies and I got the same error.

It was solved by explicitly type the modules-download-mode setting. 
`golangci-lint --modules-download-mode=vendor`
