### ISSUE TITLE
Feature request: allow //nolint only on certain linters

### ISSUE THREAD

**Issue by benjaminjkraft** [golangci/golangci-lint#889]
We'd like to be able to say, in our configuration: you may `//nolint` these linters, but not those.  Currently, there's no way to do this, as far as I know.

A few examples of why this could be useful:
- linters which are necessary to ensure correctness/security, and which should not be bypassed as easily as stylistic linters
- customizing the rules for `//nolint` directives themselves (in the style of #740 or #832)

Ideally, one could enable this behavior for arbitrary files, regexp-matches, etc., just like excludes, but simply opting in/out on a per-linter basis is probably good enough for us.

**Comment by SVilgelm** [comment]
We solved such problem by using a custom config in CI, just only those required linters are enabled and run golangci-lint with that config for all repos.  The project owners can have their own config with any linters they want, but the code must pass the with the CI's config
