### ISSUE TITLE
Feature request: a way to nolint a file without it ending up in godoc

### ISSUE THREAD

**Issue by benjaminjkraft** [golangci/golangci-lint#892]
To nolint an entire file, we can do
```go
//nolint:linter-name
package something

...
```
But godoc wants us to do something different there: it uses that space for a package doc-comment.  This means that the nolint ends up in the package's godoc, which is undesirable as it's irrelevant to users.  (And, depending on lint settings, it may cause further lint errors as it's not exactly a style-compliant package doc-comment.)

So it seems to me like there would be a use in a different way to nolint the entire file.  (Of course you can do so in `.golangci.yml`, but that's not right next to you when reading the file; it means you have to update it if you move the file; etc.)  Sadly, I don't see an ideal alternative, but maybe one could say it can go after the package line, or anywhere near the top and use some other mechanism to make it clear that it applies to the whole file (`//nolint-file:linter-name`, say).

**Comment by PotatoesFall** [comment]
I ran into this due to another weird feature. I am using go:generate enumer to get string values from comments - and I get a misspell linter warning on the comment. Since I can't // nolint:misspell the comment itself, I want to add it for the whole file.

**Comment by ldez** [comment]
Instead of using the directive, you can use `issues.exclude-rules` or `run.skip-files`:

https://golangci-lint.run/usage/configuration/

**Comment by ldez** [comment]
The directives `//nolint` are excluded from the godoc.

https://github.com/golang/go/commit/5a550b695117f07a4f2454039a4871250cd3ed09#diff-f56160fd9fcea272966a8a1d692ad9f49206fdd8dbcbfe384865a98cd9bc2749R158

https://github.com/golang/go/issues/37974

**Comment by bullgare** [comment]
This comment works fine for me:
//nolint:<linter-name>,revive
package <...>
