### ISSUE TITLE
Add 1.22.X to golangci.com

### ISSUE THREAD

**Issue by hanzei** [golangci/golangci-lint#910]
https://github.com/golangci/golangci-lint/releases/tag/v1.22.0 was release 7 days ago. It should be available on https://golangci.com/. E.g. https://golangci.com/r/github.com/mattermost/mattermost-server/pulls/13568 failed because of this.

**Comment by tpounds** [comment]
Should be fixed by golangci/golangci-api#161 once it's merged.

cc @jirfag

**Comment by hanzei** [comment]
Fixed with https://github.com/golangci/golangci-api/pull/161
