### ISSUE TITLE
Linter request: go-ruleguard

### ISSUE THREAD

**Issue by benjaminjkraft** [golangci/golangci-lint#912]
[Ruleguard](https://github.com/quasilyte/go-ruleguard) linter is a rules language for writing linters, based on [gogrep](https://github.com/mvdan/gogrep).  It looks very useful!  But to make it maximally useful to us, we'd love to see it as a golangci-lint linter.  (The idea would presumably be in your `.golangci.yml` config you specify the rules-file.)  This could also be a nice lighter-weight complement to the fully customizable plugin-based linters from #473/#841 (cc @dbraley).

**Comment by quasilyte** [comment]
I can help if there will be any kinds of intergration issues.

**Comment by Eun** [comment]
Is anyone working on this? @quasilyte or @tpounds? Would be nice to get some status.

**Comment by quasilyte** [comment]
I think we need to get maintainers approval before working on this.

**Comment by quasilyte** [comment]
Meanwhile, go-critic may have ruleguard integrated pretty soon:
https://github.com/go-critic/go-critic/pull/907

When `golangci-lint` updates the `go-critic` version it will be possible to use ruleguard through it.

**Comment by tooolbox** [comment]
I just tried to use `ruleguard` in `golangci-lint` via `go-critic` and found it's not in the list :(

Can we update?

**Comment by tooolbox** [comment]
Wow, new version with ruleguard was released 3 hours ago.  🎉   This ticket can be closed.

**Comment by iwankgb** [comment]
It was release of get was long overdue ;)

**Comment by tooolbox** [comment]
I am curious if anyone has actually tried this and used it successfully.  Setting up a `rules.go` file and trying to use ruleguard via golang-ci was extremely hit-or-miss for me yesterday to the point where I abandoned the attempt.

For example, at first I couldn't seem to get it to do anything, and then I put a really basic `err != nil` pattern in the matcher and it ran, and then I couldn't get it to stop even by commenting out the matcher.  Obviously this is not necessarily a golang-ci problem, it could be ruleguard, but the problem is complicated by the fact that it's a few layers in and I have to try to understand where on the stack it's caching and/or borking.

**Comment by quasilyte** [comment]
@tooolbox, I'm sorry if the experience was frustrating. Let's try to fix it.

0. Make sure you have the latest golangci-lint. You need `ruleguard` checker to be included into the distribution.

1. Prepare a test directory:

```
mkdir ruleguard_test
cd ruleguard_test
```

2. Create a `rules.go` file in that test directory:
```go
// +build ignore

package gorules

import "github.com/quasilyte/go-ruleguard/dsl/fluent"

func _(m fluent.Matcher) {
	m.Match(`!($x != $y)`).Report(`can rewrite as $x == $y`)
}
```

3. Now create a Go file that we're going to check with our rule:

```
// file example.go
package example

// Foo is our example function.
func Foo(xs, ys []int) bool {
	return !(xs[0] != ys[0])
}
```

4. The next thing we need is `.golangci.yml` in that directory:
```yaml
linters:
  enable:
    - gocritic
linters-settings:
        gocritic:
                enabled-checks:
                        - ruleguard
                settings:
                        ruleguard:
                                rules: "rules.go"
```

Note that:
* gocritic must be enabled
* ruleguard checker must be enabled
* ruleguard expects a "rules" parameter

Also, keep in mind that you won't get any warnings if rules file is not found.

5. Run golangci-lint on `example.go`:

```
$ golangci-lint run example.go 
example.go:5:9: ruleguard: can rewrite as xs[0] == ys[0] (gocritic)
	return !(xs[0] != ys[0])
	       ^
```

Success!

To see more rules examples, see [rules.go](https://github.com/quasilyte/go-ruleguard/blob/master/rules.go).

More info on ruleguard: https://quasilyte.dev/blog/post/ruleguard/

**Comment by tooolbox** [comment]
Thanks @quasilyte for the detailed example, that's really helpful.  I'll give another shot at it soon.  The cache was the main thing I couldn't figure out, it's good to know that's a golang-ci thing.
