### ISSUE TITLE
Configure linters via command line

### ISSUE THREAD

**Issue by TudorHulban** [golangci/golangci-lint#918]
Hi, Thank you very much for the wonderful functionality provided.
Please advise if it would be possible to pass in command a threshold to be used by a linter. 
Example:
```console
golangci-lint run --disable-all -E gocyclo
```
Runs gocyclo with 30 as threshold. What if I would like to run gocyclo with a smaller value?
How could I pass this to the linter in the command line?
Thank you again.

**Comment by ernado** [comment]
Seems like there is no 1:1 mapping from configuration file to command line arguments, so currently there is no way.

Please use configuration file until we implement this feature.
