### ISSUE TITLE
Make incremental program loading

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#92]
Currently, it's the slowest part of `golangci-lint` in "slow" (without `--fast`) mode.
Need to cache loaded packages and reload only changed packages.

**Comment by tpounds** [comment]
@jirfag Is this still valid after all the recent work in #337?

**Comment by jirfag** [comment]
yes, it's valid, I'm currently doing that

**Comment by tpounds** [comment]
Sounds good! I'll remove the `stale` label.

**Comment by jirfag** [comment]
done in #768
