### ISSUE TITLE
crit unable to find '1.22.2' - use 'latest'

### ISSUE THREAD

**Issue by jakubtomany** [golangci/golangci-lint#923]
- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>It is not possible to install specific version (e.g. 1.22.2)</summary>

```console
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 1.22.2
golangci/golangci-lint info checking GitHub for tag '1.22.2'
golangci/golangci-lint crit unable to find '1.22.2' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```

```console
$ curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /bin 1.22.2
golangci/golangci-lint info checking GitHub for tag '1.22.2'
golangci/golangci-lint crit unable to find '1.22.2' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```

</details>

**Comment by ernado** [comment]
Please use `v1.22.2` instead of `1.22.2`.

**Comment by jakubtomany** [comment]
Closing, as it was just my wrong usage.
