### ISSUE TITLE
Add `prefix-current-module` to goimports

### ISSUE THREAD

**Issue by sagikazarmark** [golangci/golangci-lint#931]
I'd like to add a bool option `prefix-current-module` to the goimports config.

It would basically check if the linted package is a module, and slap the module path (based on `go.mod` if exists) to the list of local prefixes. It would make the configuration more portable.

WDYT?

**Comment by ernado** [comment]
Thank you for idea, seems reasonable.

**Comment by sagikazarmark** [comment]
@ernado are you aware of any tools that detect module paths in GolangCI?

If not, I would pull in https://github.com/gobuffalo/here as a dependency. It doesn't have any additional dependencies that's not already a dependency in GolangCI.

**Comment by ernado** [comment]
I think that package name should be already in analysis context, but I'm not sure.

**Comment by sagikazarmark** [comment]
The package name is not enough, I need the root module path and as far as I can tell, it's not available in the context.

**Comment by sagikazarmark** [comment]
Sadly, I haven't beeb able to work on it, but it'd still be a good feature.

**Comment by ldez** [comment]
The problem can be solved with `gci` instead of `goimports`:

```yml
linters:
  enable:
    - gci

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
```

https://golangci-lint.run/usage/linters/#gci
