### ISSUE TITLE
README: invalid repository link to rowserrcheck lnter

### ISSUE THREAD

**Issue by ifraixedes** [golangci/golangci-lint#932]
README links the `rowserrcheck` linter to a wrong URL repository.

Actual: https://github.com/jingyugao/rowserr
Correct: https://github.com/jingyugao/rowserrcheck

I tried to find where I have to update this for sending a PR, but I haven't been able to find it.

**Comment by tpounds** [comment]
@ifraixedes Thanks for the report! I've fixed this in #933.
