### ISSUE TITLE
Maintaining minor versions on Homebrew

### ISSUE THREAD

**Issue by pauwlsky** [golangci/golangci-lint#940]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint:</summary>
1.23.1
</details>

<details><summary>Config file</summary>
Not relevant for issue
</details>

<details><summary>Go environment</summary>

go version go1.13.3 darwin/amd64

</details>

<details><summary>Verbose output of running</summary>
not relevant for issue
</details>

### Issue:

The lack of older-than-latest golangci-lint versions in Homebrew is making it difficult for our team to smoothly integrate the tool into our dev and CI process due to the prospect of forced upgrades. Because we have learned that minor version upgrades sometimes introduce new linting failures (e.g. when updating from 1.21.0 to 1.23.1; gocyclo and gocognit became stricter between these versions, causing our builds to break; this disagrees with our expectations for semver), we wish to be insulated from a forced update schedule that requires us to suddenly dive in and make code changes or weaken our linter config.

We pin the version we use for our CI server so that it isn't prone to such disruption, but team members rely on Homebrew (when possible) to manage tools for local development. Any time someone doesn't have the current pinned version installed (because they're new, haven't touched the Go code in a while, etc.) and needs to do so, they're out of luck with Homebrew unless it's the latest version, since older versions are apparently being aggressively pruned (other Homebrew packages don't seem to do this so aggressively, so we wonder if it's necessary). While other means are available, this creates tool friction and complexity we'd rather avoid levying on team members diving into areas of code they touch infrequently.

We understand that the recommended means of acquiring a specific version is to use `curl` or `wget` to get and run the install script, however for security concerns our team prefers to avoid this practice if possible.

Would it be possible to keep older versions available for longer, so that we don't get cornered into making sudden adjustments like this? Is there a better option we're missing?

Thanks for the great work, hope to hear a response soon.

**Comment by aneeshusa** [comment]
FYI, at my company we use https://pre-commit.com for this - you have a `.pre-commit-config.yaml` config file checked into the repo which specifies the golangci-lint version, and the tool handles installing the right version for you. I contributed [pre-commit support to golangci-lint](https://github.com/golangci/golangci-lint/pull/311) a while back.

**Comment by ernado** [comment]
cc: @jirfag 

I'm using linux exclusively so can't help here

**Comment by bombsimon** [comment]
The [brew formulae](https://github.com/golangci/homebrew-tap/blob/master/Formula/golangci-lint.rb) is created with goreleaser according to [this](https://github.com/golangci/golangci-lint/blob/master/.goreleaser.yml#L82-L97) spec. You can support multiple versions according to [docs.brew.sh/Versions](https://docs.brew.sh/Versions) by creating tagged files with class names following a specific format ([more details](https://discourse.brew.sh/t/how-do-i-add-multiple-versions-to-a-formula-on-github/910/10)). However, I cannot find in the [goreleaser documentation](https://goreleaser.com/intro/) how one would achieve this.

I found [this issue](https://github.com/goreleaser/goreleaser/issues/1058) in the goreleaser repository requesting the same feature but according to the answer this is not possible or supported

Maybe look into anther way to update the homebrew formulae?

**Comment by ChrisSargent** [comment]
Is there any chance this can be re-opened? We have a pinned version in CI but not locally, it can cause some headaches. If it is not possible, could you please at least provide detailed docs with how to install a specific version?

**Comment by bombsimon** [comment]
The way to install a given version is the way listed in the [docs](https://golangci-lint.run/usage/install/#other-ci). You can just add the versionyou want to install at the end. This actually used to be a part of the docs, not sure when it was removd. F.ex. to install `v1.42.0` you would do:

```sh
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.42.0
```

I also wrote a tool for this use case where you might want to switch between versions or have the version defined in your `.golangic.yml`; [gclv](https://github.com/bombsimon/gclv).
