### ISSUE TITLE
wiki: "How to add a custom linter" page is outdated

### ISSUE THREAD

**Issue by Rikkuru** [golangci/golangci-lint#949]
on wiki page https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter in step 3 there is an old link that returns 404 now - pkg/lint/lintersdb/lintersdb.go

It needs to be changed to pkg/lint/lintersdb/manager.go

**Comment by Rikkuru** [comment]
also in step 5 `make readme` command is wrong 
`make README.md` works

**Comment by jonathon-l** [comment]
Could this information instead be added to the README or some sort of other doc inside the repo?

The primary advantages of this method:
- PRs can be made by community to update the process as needed.
- The instructions on how to add a linter (or any other instructions added in future) wil be tied to that specific version of the code.

**Comment by ldez** [comment]
Fixed by e3227ec340b1d5a29dd6d47fa97c90ea4e2fbddc
