### ISSUE TITLE
Update errcheck to latest version

### ISSUE THREAD

**Issue by zendern** [golangci/golangci-lint#959]
This maybe the wrong place for it so close it if it is but https://github.com/golangci/errcheck does not have the ability to create an issue.

But I wanted to open it up and get feedback on thoughts regarding updating that forked repo to have the latest version of what the forked repo has https://github.com/kisielk/errcheck. 

The thing that golangci version is currently missing is the embedded interface walker stuff found here. 

https://github.com/kisielk/errcheck/blob/master/internal/errcheck/embedded_walker.go

I believe updating that would resolve issue #656 and hopefully #657

**Comment by divoxx** [comment]
What needs to be done for this to be merged?

**Comment by zendern** [comment]
> What needs to be done for this to be merged?

Nothing to merge yet.... basically need to merge the original repo with the fork and resolve all the merge conflicts. I attempted and never finished. But had difficulties in trying to resolve those merge conflicts.

**Comment by danielcooperxyz** [comment]
@zendern Looks like https://github.com/golangci/errcheck/pull/4 may have synced up what you mentioned?
