### ISSUE TITLE
ERRO Running error: can't combine options --enable-all and --enable megacheck

### ISSUE THREAD

**Issue by tegk** [golangci/golangci-lint#968]
Thank you for creating the issue!

- [ x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ x] Yes, I've searched similar issues on GitHub and didn't find any.
- [ x] Yes, I've included all information below (version, config, etc).

Please include the following information:

I get this error "ERRO Running error: can't combine options --enable-all and --enable megacheck"
but I just have this command: "golangci-lint run --enable-all"
```console
$ golangci-lint --version
golangci-lint has version 1.23.3 built from 2241adf on 2020-02-04T05:01:09Z

```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# paste output here
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.13.7 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/till/.cache/go-build"
GOENV="/home/till/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/till/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5243"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5243/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/till/Desktop/lint/go-micro/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build350376426=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by ldez** [comment]
With the latest, I don't reproduce so I think that the problem has been fixed
