### ISSUE TITLE
[RFC] Remove comparison with gometalinter, as it is archived

### ISSUE THREAD

**Issue by thaJeztah** [golangci/golangci-lint#986]
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

(not relevant)

</details>

<details><summary>Config file</summary>

(not relevant)

</details>

<details><summary>Go environment</summary>

(not relevant)

</details>

<details><summary>Verbose output of running</summary>

(not relevant)

</details>

The documentation and description of this repository contains a substantial amount of information to compare performance with Gometalinter. 

Now that Gometalinter was deprecated, [archived](https://github.com/alecthomas/gometalinter), and is recommending GolangCI-lint as alternative, I think the comparison  (and comparing benchmarks) is no longer relevant, so might as well be removed.

**Comment by ernado** [comment]
Agree, PR is welcome.
